force-app/main/default/objects/Campaign/fields/City__c.field-meta.xml
<CustomField>
    <fullName>City__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>City</label>
    <length>25</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Campaign/fields/Country__c.field-meta.xml
<CustomField>
    <fullName>Country__c</fullName>
    <label>Country</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>AT</fullName>
            </value>
            <value>
                <fullName>AU</fullName>
            </value>
            <value>
                <fullName>Australia</fullName>
            </value>
            <value>
                <fullName>Austria</fullName>
            </value>
            <value>
                <fullName>BE</fullName>
            </value>
            <value>
                <fullName>Belgium</fullName>
            </value>
            <value>
                <fullName>BR</fullName>
            </value>
            <value>
                <fullName>Brazil</fullName>
            </value>
            <value>
                <fullName>CA</fullName>
            </value>
            <value>
                <fullName>Canada</fullName>
            </value>
            <value>
                <fullName>CH</fullName>
            </value>
            <value>
                <fullName>Chile</fullName>
            </value>
            <value>
                <fullName>China</fullName>
            </value>
            <value>
                <fullName>CL</fullName>
            </value>
            <value>
                <fullName>CN</fullName>
            </value>
            <value>
                <fullName>CZ</fullName>
            </value>
            <value>
                <fullName>Czech Republic</fullName>
            </value>
            <value>
                <fullName>DE</fullName>
            </value>
            <value>
                <fullName>Denmark</fullName>
            </value>
            <value>
                <fullName>DK</fullName>
            </value>
            <value>
                <fullName>ES</fullName>
            </value>
            <value>
                <fullName>FI</fullName>
            </value>
            <value>
                <fullName>Finland</fullName>
            </value>
            <value>
                <fullName>FR</fullName>
            </value>
            <value>
                <fullName>France</fullName>
            </value>
            <value>
                <fullName>GB</fullName>
            </value>
            <value>
                <fullName>Germany</fullName>
            </value>
            <value>
                <fullName>GR</fullName>
            </value>
            <value>
                <fullName>Greece</fullName>
            </value>
            <value>
                <fullName>Iceland</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Campaign/fields/Event_Website__c.field-meta.xml
<CustomField>
    <fullName>Event_Website__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Event Website</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/Campaign/fields/Segment__c.field-meta.xml
<CustomField>
    <fullName>Segment__c</fullName>
    <label>Segment</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Alle</fullName>
            </value>
            <value>
                <fullName>ASC Solutions</fullName>
            </value>
            <value>
                <fullName>Biologics</fullName>
            </value>
            <value>
                <fullName>Bone Healing</fullName>
            </value>
            <value>
                <fullName>Cement</fullName>
            </value>
            <value>
                <fullName>CMF &amp; Thoracic</fullName>
            </value>
            <value>
                <fullName>Dental</fullName>
            </value>
            <value>
                <fullName>Etex</fullName>
            </value>
            <value>
                <fullName>Extremities</fullName>
            </value>
            <value>
                <fullName>Foot &amp; Ankle</fullName>
            </value>
            <value>
                <fullName>Hip</fullName>
            </value>
            <value>
                <fullName>Knee</fullName>
            </value>
            <value>
                <fullName>Knee Creations</fullName>
            </value>
            <value>
                <fullName>mymobility</fullName>
            </value>
            <value>
                <fullName>OSP</fullName>
            </value>
            <value>
                <fullName>ROSA</fullName>
            </value>
            <value>
                <fullName>Spine</fullName>
            </value>
            <value>
                <fullName>Sports Medicine</fullName>
            </value>
            <value>
                <fullName>Surgical</fullName>
            </value>
            <value>
                <fullName>Trauma</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Campaign/fields/State__c.field-meta.xml
<CustomField>
    <fullName>State__c</fullName>
    <label>State/Province</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Country__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>AK</fullName>
            </value>
            <value>
                <fullName>AL</fullName>
            </value>
            <value>
                <fullName>AR</fullName>
            </value>
            <value>
                <fullName>AS</fullName>
            </value>
            <value>
                <fullName>AZ</fullName>
            </value>
            <value>
                <fullName>CA</fullName>
            </value>
            <value>
                <fullName>CO</fullName>
            </value>
            <value>
                <fullName>CT</fullName>
            </value>
            <value>
                <fullName>DC</fullName>
            </value>
            <value>
                <fullName>DE</fullName>
            </value>
            <value>
                <fullName>FL</fullName>
            </value>
            <value>
                <fullName>FM</fullName>
            </value>
            <value>
                <fullName>GA</fullName>
            </value>
            <value>
                <fullName>GU</fullName>
            </value>
            <value>
                <fullName>HI</fullName>
            </value>
            <value>
                <fullName>IA</fullName>
            </value>
            <value>
                <fullName>ID</fullName>
            </value>
            <value>
                <fullName>IL</fullName>
            </value>
            <value>
                <fullName>IN</fullName>
            </value>
            <value>
                <fullName>KS</fullName>
            </value>
            <value>
                <fullName>KY</fullName>
            </value>
            <value>
                <fullName>LA</fullName>
            </value>
            <value>
                <fullName>MA</fullName>
            </value>
            <value>
                <fullName>MD</fullName>
            </value>
            <value>
                <fullName>ME</fullName>
            </value>
            <value>
                <fullName>MH</fullName>
            </value>
            <value>
                <fullName>MI</fullName>
            </value>
            <value>
                <fullName>MN</fullName>
            </value>
            <value>
                <fullName>MO</fullName>
            </value>
            <value>
                <fullName>MP</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/Event_Calendar_APILogicWrapper.cls
public with sharing class Event_Calendar_APILogicWrapper {   

    public static String ERROR_MSG = 'Please input a search string.';
    private static String CORRECT_MSG = 'Correct request';

    public static Event_Calendar_ResponseWrappers getAttachments(String parentId) {
        List<Event_Calendar_ResponseWrappers.AttachmentWrapper> results = new List<Event_Calendar_ResponseWrappers.AttachmentWrapper>();
        String query = 'SELECT Id, Name FROM Attachment WHERE ParentId = :parentId';
        try {
            for (Attachment attach : Database.query(query)) {
                results.add(new Event_Calendar_ResponseWrappers.AttachmentWrapper(attach.Name, attach.Id));
            }
            return new Event_Calendar_ResponseWrappers(true, CORRECT_MSG, results);
        } catch (Exception e) {
            return new Event_Calendar_ResponseWrappers(false, e.getMessage());
        }
    }

    public static Event_Calendar_ResponseWrappers getCampaignDetail(String campaignId) {
        String query = 'SELECT Id, Name, StartDate, Event_Website__c, EndDate, Segment__c, City__c, State__c, Country__c '
                       + 'FROM Campaign WHERE Id =: campaignId LIMIT 1';
        try {
            Campaign camp = Database.query(query);
            return new Event_Calendar_ResponseWrappers(true, CORRECT_MSG,
                    new Event_Calendar_ResponseWrappers.CampaignDetailWrapper(camp));
        } catch (Exception e) {
            return new Event_Calendar_ResponseWrappers(false, e.getMessage());
        }
    }

    public static Event_Calendar_ResponseWrappers getCampaigns(Integer month, Integer year) {
        List<Event_Calendar_ResponseWrappers.CampaignWrapper> results = new List<Event_Calendar_ResponseWrappers.CampaignWrapper>();
        Integer daysInMonth = Date.daysInMonth(year, month);
        Date startOfMonth = Date.newInstance(year, month, 2).toStartOfMonth();
        Date endOfMonth = startOfMonth.addDays(daysInMonth);
        String query = 'SELECT '
                       + 'Id, Name, StartDate, EndDate, Segment__c, Event_Website__c, Status, Type, Country__c, State__c, City__c '
                       + 'FROM Campaign '
                       + 'WHERE IsActive = true '
                       + 'AND Event_Website__c <> null '
                       + 'AND ((StartDate >= :startOfMonth AND StartDate < :endOfMonth) OR (EndDate >= :startOfMonth AND EndDate < :endOfMonth))';
        try {
            for (Campaign camp : Database.query(query)) {
                results.add(new Event_Calendar_ResponseWrappers.CampaignWrapper(camp));
            }
            return new Event_Calendar_ResponseWrappers(true, CORRECT_MSG, results);
        } catch (Exception e) {
            return new Event_Calendar_ResponseWrappers(false, e.getMessage());
        }
    }

    public static Event_Calendar_ResponseWrappers getCampaignsSearch(String searchParameter) {
        List<Event_Calendar_ResponseWrappers.CampaignWrapper> results = new List<Event_Calendar_ResponseWrappers.CampaignWrapper>();
        String searchParamString = '\'' + searchParameter + '%\'';
        String searchParamList = '\'' + searchParameter + '\'';
        Id recordTypeId = Schema.SObjectType.Campaign.getRecordTypeInfosByName().get('Cvent Campaign').getRecordTypeId();
        Date today = Date.today();
        String query = 'SELECT Id, Name, StartDate, EndDate, Segment__c, Event_Website__c, Status, Type, Country__c, State__c, City__c'
                       + ' FROM Campaign'
                       + ' WHERE IsActive = true AND StartDate >= :today'
                       + ' AND Event_Website__c <> null AND RecordTypeId = :recordTypeId'
                       + ' AND (Name LIKE ' + searchParamString + ' OR Type = ' + searchParamList
                       + ' OR City__c LIKE ' + searchParamString + ' OR State__c = ' + searchParamList
                       + ' OR Segment__c = ' + searchParamList + ')'
                       + ' ORDER BY Name';
        try {
            for (Campaign camp : Database.query(query)) {
                results.add(new Event_Calendar_ResponseWrappers.CampaignWrapper(camp));
            }
            return new Event_Calendar_ResponseWrappers(true, CORRECT_MSG, results, true);
        } catch (Exception e) {
            return new Event_Calendar_ResponseWrappers(false, e.getMessage());
        }
    }
}