force-app/main/default/objects/Campaign/fields/City__c.field-meta.xml
<CustomField>
    <fullName>City__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>City</label>
    <length>25</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Campaign/fields/Country__c.field-meta.xml
<CustomField>
    <fullName>Country__c</fullName>
    <label>Country</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>AT</fullName>
            </value>
            <value>
                <fullName>AU</fullName>
            </value>
            <value>
                <fullName>Australia</fullName>
            </value>
            <value>
                <fullName>Austria</fullName>
            </value>
            <value>
                <fullName>BE</fullName>
            </value>
            <value>
                <fullName>Belgium</fullName>
            </value>
            <value>
                <fullName>BR</fullName>
            </value>
            <value>
                <fullName>Brazil</fullName>
            </value>
            <value>
                <fullName>CA</fullName>
            </value>
            <value>
                <fullName>Canada</fullName>
            </value>
            <value>
                <fullName>CH</fullName>
            </value>
            <value>
                <fullName>Chile</fullName>
            </value>
            <value>
                <fullName>China</fullName>
            </value>
            <value>
                <fullName>CL</fullName>
            </value>
            <value>
                <fullName>CN</fullName>
            </value>
            <value>
                <fullName>CZ</fullName>
            </value>
            <value>
                <fullName>Czech Republic</fullName>
            </value>
            <value>
                <fullName>DE</fullName>
            </value>
            <value>
                <fullName>Denmark</fullName>
            </value>
            <value>
                <fullName>DK</fullName>
            </value>
            <value>
                <fullName>ES</fullName>
            </value>
            <value>
                <fullName>FI</fullName>
            </value>
            <value>
                <fullName>Finland</fullName>
            </value>
            <value>
                <fullName>FR</fullName>
            </value>
            <value>
                <fullName>France</fullName>
            </value>
            <value>
                <fullName>GB</fullName>
            </value>
            <value>
                <fullName>Germany</fullName>
            </value>
            <value>
                <fullName>GR</fullName>
            </value>
            <value>
                <fullName>Greece</fullName>
            </value>
            <value>
                <fullName>Iceland</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Campaign/fields/Event_Website__c.field-meta.xml
<CustomField>
    <fullName>Event_Website__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Event Website</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/Campaign/fields/Segment__c.field-meta.xml
<CustomField>
    <fullName>Segment__c</fullName>
    <label>Segment</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Alle</fullName>
            </value>
            <value>
                <fullName>ASC Solutions</fullName>
            </value>
            <value>
                <fullName>Biologics</fullName>
            </value>
            <value>
                <fullName>Bone Healing</fullName>
            </value>
            <value>
                <fullName>Cement</fullName>
            </value>
            <value>
                <fullName>CMF &amp; Thoracic</fullName>
            </value>
            <value>
                <fullName>Dental</fullName>
            </value>
            <value>
                <fullName>Etex</fullName>
            </value>
            <value>
                <fullName>Extremities</fullName>
            </value>
            <value>
                <fullName>Foot &amp; Ankle</fullName>
            </value>
            <value>
                <fullName>Hip</fullName>
            </value>
            <value>
                <fullName>Knee</fullName>
            </value>
            <value>
                <fullName>Knee Creations</fullName>
            </value>
            <value>
                <fullName>mymobility</fullName>
            </value>
            <value>
                <fullName>OSP</fullName>
            </value>
            <value>
                <fullName>ROSA</fullName>
            </value>
            <value>
                <fullName>Spine</fullName>
            </value>
            <value>
                <fullName>Sports Medicine</fullName>
            </value>
            <value>
                <fullName>Surgical</fullName>
            </value>
            <value>
                <fullName>Trauma</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Campaign/fields/State__c.field-meta.xml
<CustomField>
    <fullName>State__c</fullName>
    <label>State/Province</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Country__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>AK</fullName>
            </value>
            <value>
                <fullName>AL</fullName>
            </value>
            <value>
                <fullName>AR</fullName>
            </value>
            <value>
                <fullName>AS</fullName>
            </value>
            <value>
                <fullName>AZ</fullName>
            </value>
            <value>
                <fullName>CA</fullName>
            </value>
            <value>
                <fullName>CO</fullName>
            </value>
            <value>
                <fullName>CT</fullName>
            </value>
            <value>
                <fullName>DC</fullName>
            </value>
            <value>
                <fullName>DE</fullName>
            </value>
            <value>
                <fullName>FL</fullName>
            </value>
            <value>
                <fullName>FM</fullName>
            </value>
            <value>
                <fullName>GA</fullName>
            </value>
            <value>
                <fullName>GU</fullName>
            </value>
            <value>
                <fullName>HI</fullName>
            </value>
            <value>
                <fullName>IA</fullName>
            </value>
            <value>
                <fullName>ID</fullName>
            </value>
            <value>
                <fullName>IL</fullName>
            </value>
            <value>
                <fullName>IN</fullName>
            </value>
            <value>
                <fullName>KS</fullName>
            </value>
            <value>
                <fullName>KY</fullName>
            </value>
            <value>
                <fullName>LA</fullName>
            </value>
            <value>
                <fullName>MA</fullName>
            </value>
            <value>
                <fullName>MD</fullName>
            </value>
            <value>
                <fullName>ME</fullName>
            </value>
            <value>
                <fullName>MH</fullName>
            </value>
            <value>
                <fullName>MI</fullName>
            </value>
            <value>
                <fullName>MN</fullName>
            </value>
            <value>
                <fullName>MO</fullName>
            </value>
            <value>
                <fullName>MP</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/Event_Calendar_ResponseWrappers.cls
global with sharing class Event_Calendar_ResponseWrappers { 

    public String message;
    public Boolean success;
    public List<BasicWrapper> dataList;
    public BasicWrapper data;
    public Integer numberOfRecords;

    public Event_Calendar_ResponseWrappers(Boolean success, String message,
                                           List<BasicWrapper> dataList, Boolean isSearch) {
        this.message = message;
        this.success = success;
        this.dataList = dataList;
        if (isSearch) this.numberOfRecords = this.dataList.size();
    }

    public Event_Calendar_ResponseWrappers(Boolean success, String message, List<BasicWrapper> dataList) {
        this.message = message;
        this.success = success;
        this.dataList = dataList;
    }

    public Event_Calendar_ResponseWrappers(Boolean success, String message, BasicWrapper data) {
        this.message = message;
        this.success = success;
        this.data = data;
    }

    public Event_Calendar_ResponseWrappers(Boolean success, String message) {
        this.message = message;
        this.success = success;
    }

    public abstract class BasicWrapper {}

    global class AttachmentWrapper extends BasicWrapper {

        public String name;
        public String attachmentId;

        public AttachmentWrapper(String name, String attachmentId) {
            this.name = name;
            this.attachmentId = attachmentId;
        }
    }

    global class CampaignDetailWrapper extends BasicWrapper {

        public String id;
        public String name;
        public Date startDate;
        public Date endDate;
        public String eventWebsite;
        public String segment;
        public String country;
        public String state;
        public String city;

        public CampaignDetailWrapper(Campaign camp) {
            this.id = camp.Id;
            this.name = camp.Name;
            this.startDate = camp.StartDate;
            this.endDate = camp.EndDate;
            this.segment = camp.Segment__c;
            this.country = camp.Country__c;
            this.state = camp.State__c;
            this.city = camp.City__c;
            this.eventWebsite = camp.Event_Website__c;
        }
    }

    global class CampaignWrapper extends BasicWrapper {

        public String id;
        public String name;
        public Date startDate;
        public Date endDate;
        public String segment;
        public String eventWebsite;
        public String status;
        public String type;
        public String country;
        public String state;
        public String city;

        public CampaignWrapper(Campaign camp) {
            this.id = camp.Id;
            this.name = camp.Name;
            this.startDate = camp.StartDate;
            this.endDate = camp.EndDate;
            this.segment = camp.Segment__c;
            this.eventWebsite = camp.Event_Website__c;
            this.status = camp.Status;
            this.type = camp.Type;
            this.country = camp.Country__c;
            this.state = camp.State__c;
            this.city = camp.City__c;
        }
    }

    global class CampaignsSearchWrapper extends BasicWrapper {

        public String id;
        public String name;
        public String city;
        public String segment;

        public CampaignsSearchWrapper(Campaign camp) {
            this.id = camp.Id;
            this.name = camp.Name;
            this.city = camp.City__c;
            this.segment = camp.Segment__c;
        }
    }
}