force-app/main/default/objects/Campaign/fields/City__c.field-meta.xml
<CustomField>
    <fullName>City__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>City</label>
    <length>25</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Campaign/fields/Event_Website__c.field-meta.xml
<CustomField>
    <fullName>Event_Website__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Event Website</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/Campaign/fields/Segment__c.field-meta.xml
<CustomField>
    <fullName>Segment__c</fullName>
    <label>Segment</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Alle</fullName>
            </value>
            <value>
                <fullName>ASC Solutions</fullName>
            </value>
            <value>
                <fullName>Biologics</fullName>
            </value>
            <value>
                <fullName>Bone Healing</fullName>
            </value>
            <value>
                <fullName>Cement</fullName>
            </value>
            <value>
                <fullName>CMF &amp; Thoracic</fullName>
            </value>
            <value>
                <fullName>Dental</fullName>
            </value>
            <value>
                <fullName>Etex</fullName>
            </value>
            <value>
                <fullName>Extremities</fullName>
            </value>
            <value>
                <fullName>Foot &amp; Ankle</fullName>
            </value>
            <value>
                <fullName>Hip</fullName>
            </value>
            <value>
                <fullName>Knee</fullName>
            </value>
            <value>
                <fullName>Knee Creations</fullName>
            </value>
            <value>
                <fullName>mymobility</fullName>
            </value>
            <value>
                <fullName>OSP</fullName>
            </value>
            <value>
                <fullName>ROSA</fullName>
            </value>
            <value>
                <fullName>Spine</fullName>
            </value>
            <value>
                <fullName>Sports Medicine</fullName>
            </value>
            <value>
                <fullName>Surgical</fullName>
            </value>
            <value>
                <fullName>Trauma</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/Event_Calendar_TestHelper.cls
public with sharing class Event_Calendar_TestHelper {

    public static  Campaign createCampaign(String name) {
        Campaign camp = new Campaign();
        camp.Name = name;
        camp.StartDate = Date.today();
        camp.EndDate = Date.today().addDays(14);
        camp.Segment__c = 'test';
        camp.Event_Website__c = 'test.test.com';
        camp.IsActive = true;
        camp.City__c = 'test city';
        camp.RecordTypeId = Schema.SObjectType.Campaign.getRecordTypeInfosByName().get('Cvent Campaign').getRecordTypeId();
        return camp;
    }

    public static Campaign createCampaign() {
        Campaign camp = new Campaign();
        camp.Name = 'test campaign';
        camp.StartDate = Date.today();
        camp.EndDate = Date.today().addDays(14);
        camp.Segment__c = 'test';
        camp.Event_Website__c = 'test.test.com';
        camp.IsActive = true;
        camp.City__c = 'test city';
        camp.RecordTypeId = Schema.SObjectType.Campaign.getRecordTypeInfosByName().get('Cvent Campaign').getRecordTypeId();
        return camp;
    }

    public static void setupRestSettings(String httpMethod, String requestURI) {
        RestRequest req = new RestRequest();
        RestResponse res = new RestResponse();
        req.requestURI = requestURI;
        req.httpMethod = httpMethod;
        RestContext.request = req;
        RestContext.response = res;
    }

    public static Attachment createAttachment(Id parentId, Integer num) {
        Attachment attach = new Attachment();
        attach.Body = Blob.toPdf('test');
        attach.Name = 'test attach' + String.valueOf(num);
        attach.ParentId = parentId;
        return attach;
    }
}