force-app/main/default/objects/Campaign/fields/Segment__c.field-meta.xml
<CustomField>
    <fullName>Segment__c</fullName>
    <label>Segment</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Alle</fullName>
            </value>
            <value>
                <fullName>ASC Solutions</fullName>
            </value>
            <value>
                <fullName>Biologics</fullName>
            </value>
            <value>
                <fullName>Bone Healing</fullName>
            </value>
            <value>
                <fullName>Cement</fullName>
            </value>
            <value>
                <fullName>CMF &amp; Thoracic</fullName>
            </value>
            <value>
                <fullName>Dental</fullName>
            </value>
            <value>
                <fullName>Etex</fullName>
            </value>
            <value>
                <fullName>Extremities</fullName>
            </value>
            <value>
                <fullName>Foot &amp; Ankle</fullName>
            </value>
            <value>
                <fullName>Hip</fullName>
            </value>
            <value>
                <fullName>Knee</fullName>
            </value>
            <value>
                <fullName>Knee Creations</fullName>
            </value>
            <value>
                <fullName>mymobility</fullName>
            </value>
            <value>
                <fullName>OSP</fullName>
            </value>
            <value>
                <fullName>ROSA</fullName>
            </value>
            <value>
                <fullName>Spine</fullName>
            </value>
            <value>
                <fullName>Sports Medicine</fullName>
            </value>
            <value>
                <fullName>Surgical</fullName>
            </value>
            <value>
                <fullName>Trauma</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lead/fields/Campaign_Segment__c.field-meta.xml
<CustomField>
    <fullName>Campaign_Segment__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Campaign Segment</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/SegmentUpdateOnLeadData.cls
//***************************//
        // Developer  : Hardeep Brar
        // Version    : 1.0
        // Object     : Campaign Member
        // Trigger    : SegmentUpdateOnLead
        //***************************//

        public class SegmentUpdateOnLeadData {
            public static void campaignMemberData(List<CampaignMember> campMemberList ){ 
            System.debug('Camp Memeber List Size ' + campMemberList.size());
      
                    List<Lead> ldlist = new List<Lead>();
                    set<id> campaignIDs = new set<id>();
                    set<id> leadIDs = new set<id>();                    
                    for(CampaignMember cmm : campMemberList)
                    {                        
                    campaignIDs.add(cmm.CampaignID);                                            
                    }               
                    
                    Map<ID,Campaign> campaignMap = new Map<ID,Campaign>([Select id, Segment__c from Campaign Where id IN :campaignIDs]);
                                        
                    for(CampaignMember cmm : campMemberList){
                      if((cmm.CampaignId <>NULL) && (cmm.LeadId<>NULL)) {
                        if (campaignMap.get(cmm.CampaignID).Segment__c <>'NULL'){
                            Lead L =new Lead(id=cmm.LeadID, Campaign_Segment__c = campaignMap.get(cmm.CampaignID).Segment__c);      
                            ldlist.add(L);
                           }
                        }  
                    }
                    if(ldlist.size()>0){
                        update ldlist;
                    } 
                }                  
            }