force-app/main/default/objects/Ortho_Mobile_Setting__mdt/Ortho_Mobile_Setting__mdt.object-meta.xml
<CustomObject>
    <label>Ortho Mobile Setting</label>
    <pluralLabel>Ortho Mobile Settings</pluralLabel>
</CustomObject>

force-app/main/default/objects/Ortho_Mobile_Setting__mdt/fields/Value__c.field-meta.xml
<CustomField>
    <fullName>Value__c</fullName>
    <description>Setting Value</description>
    <label>Value</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/Ortho_GroupsService.cls
public with sharing class Ortho_GroupsService {


    public static List<CollaborationGroup> communicationGroups { get {
        if(communicationGroups == null){
            communicationGroups = [Select Id, Name from CollaborationGroup where Name in: (groupNames)];
        }
        return communicationGroups;
    }set;}

    public static Set<String> groupNames { get{ 
        if(groupNames == null){
            groupNames = new Set<String>();
            Ortho_Mobile_Setting__mdt[] orthoMobileSettings = Ortho_SettingsService.getSettingByType('Communication Group');
            for(Ortho_Mobile_Setting__mdt oms : orthoMobileSettings){
                groupNames.add(oms.Value__c);
            }
            System.debug('groupNames--------'+groupNames);
        }
        return groupNames;
    }set;}
}