force-app/main/default/objects/Ortho_Mobile_Setting__mdt/Ortho_Mobile_Setting__mdt.object-meta.xml
<CustomObject>
    <label>Ortho Mobile Setting</label>
    <pluralLabel>Ortho Mobile Settings</pluralLabel>
</CustomObject>

force-app/main/default/objects/Ortho_Mobile_Setting__mdt/fields/Setting_Type__c.field-meta.xml
<CustomField>
    <fullName>Setting_Type__c</fullName>
    <label>Setting Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Communication Group</fullName>
                <default>true</default>
                <label>Communication Group</label>
            </value>
            <value>
                <fullName>App</fullName>
            </value>
            <value>
                <fullName>Trigger</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Ortho_Mobile_Setting__mdt/fields/Test_Context__c.field-meta.xml
<CustomField>
    <fullName>Test_Context__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Test Context</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Ortho_Mobile_Setting__mdt/fields/Value__c.field-meta.xml
<CustomField>
    <fullName>Value__c</fullName>
    <description>Setting Value</description>
    <label>Value</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/Ortho_TriggerSettingsTest.cls
@isTest
public class Ortho_TriggerSettingsTest {   
    @isTest
    public static void isTriggerDisabledTest()
    {
       Ortho_Mobile_Setting__mdt[] triggerSetting = [SELECT MasterLabel, Value__c, Setting_Type__c 
                                                      FROM Ortho_Mobile_Setting__mdt WHERE
                                                      Test_Context__c = True];
        
        
        String triggerName =  'Test Trigger All';
        Ortho_TriggerSettings.isTriggerDisabled(triggerName);
        
        triggerName =  'Test Trigger Profile';
        Ortho_TriggerSettings.isTriggerDisabled(triggerName);
        
        triggerName =  'Test Trigger User';
        Ortho_TriggerSettings.isTriggerDisabled(triggerName);
    }   
    
}