force-app/main/default/objects/GPL_Location__c/GPL_Location__c.object-meta.xml
<CustomObject>
    <label>GPL Location</label>
    <nameField>
        <displayFormat>GPL_L-{0000}</displayFormat>
        <label>GPL Location ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>GPL Locations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/GPL_Location__c/fields/City__c.field-meta.xml
<CustomField>
    <fullName>City__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>City</label>
    <length>80</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/GPL_Location__c/fields/Country__c.field-meta.xml
<CustomField>
    <fullName>Country__c</fullName>
    <label>Country</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>AU</fullName>
            </value>
            <value>
                <fullName>CA</fullName>
            </value>
            <value>
                <fullName>GB</fullName>
            </value>
            <value>
                <fullName>US</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/GPL_Location__c/fields/GPL_Profile__c.field-meta.xml
<CustomField>
    <fullName>GPL_Profile__c</fullName>
    <label>GPL Profile</label>
    <referenceTo>GPL_Profile__c</referenceTo>
    <relationshipLabel>GPL Locations</relationshipLabel>
    <relationshipName>Locations</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/GPL_Location__c/fields/Latitude__c.field-meta.xml
<CustomField>
    <fullName>Latitude__c</fullName>
    <label>Latitude</label>
    <precision>11</precision>
    <scale>8</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/GPL_Location__c/fields/Location_Type__c.field-meta.xml
<CustomField>
    <fullName>Location_Type__c</fullName>
    <label>Location Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Hospital</fullName>
            </value>
            <value>
                <fullName>Practice</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/GPL_Location__c/fields/Longitude__c.field-meta.xml
<CustomField>
    <fullName>Longitude__c</fullName>
    <label>Longitude</label>
    <precision>11</precision>
    <scale>8</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/GPL_Location__c/fields/Name__c.field-meta.xml
<CustomField>
    <fullName>Name__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Name</label>
    <required>true</required>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/GPL_Location__c/fields/PostalCode__c.field-meta.xml
<CustomField>
    <fullName>PostalCode__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Postal Code</label>
    <length>10</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/GPL_Location__c/fields/Services__c.field-meta.xml
<CustomField>
    <fullName>Services__c</fullName>
    <label>Services</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Chaplaincy Services</fullName>
            </value>
            <value>
                <fullName>Pickup Services</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/GPL_Location__c/fields/State__c.field-meta.xml
<CustomField>
    <fullName>State__c</fullName>
    <label>State</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Country__c</controllingField>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>AB</fullName>
            </value>
            <value>
                <fullName>ACT</fullName>
            </value>
            <value>
                <fullName>AK</fullName>
            </value>
            <value>
                <fullName>AL</fullName>
            </value>
            <value>
                <fullName>AR</fullName>
            </value>
            <value>
                <fullName>AZ</fullName>
            </value>
            <value>
                <fullName>BC</fullName>
            </value>
            <value>
                <fullName>CA</fullName>
            </value>
            <value>
                <fullName>CO</fullName>
            </value>
            <value>
                <fullName>CT</fullName>
            </value>
            <value>
                <fullName>DC</fullName>
            </value>
            <value>
                <fullName>DE</fullName>
            </value>
            <value>
                <fullName>FL</fullName>
            </value>
            <value>
                <fullName>GA</fullName>
            </value>
            <value>
                <fullName>HI</fullName>
            </value>
            <value>
                <fullName>IA</fullName>
            </value>
            <value>
                <fullName>ID</fullName>
            </value>
            <value>
                <fullName>IL</fullName>
            </value>
            <value>
                <fullName>IN</fullName>
            </value>
            <value>
                <fullName>KS</fullName>
            </value>
            <value>
                <fullName>KY</fullName>
            </value>
            <value>
                <fullName>LA</fullName>
            </value>
            <value>
                <fullName>MA</fullName>
            </value>
            <value>
                <fullName>MB</fullName>
            </value>
            <value>
                <fullName>MD</fullName>
            </value>
            <value>
                <fullName>ME</fullName>
            </value>
            <value>
                <fullName>MI</fullName>
            </value>
            <value>
                <fullName>MN</fullName>
            </value>
            <value>
                <fullName>MO</fullName>
            </value>
            <value>
                <fullName>MS</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/GPL_Location__c/fields/Street__c.field-meta.xml
<CustomField>
    <fullName>Street__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Street</label>
    <required>true</required>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/GPL_Profile__c/GPL_Profile__c.object-meta.xml
<CustomObject>
    <label>GPL Profile</label>
    <nameField>
        <displayFormat>GPL_P-{0000}</displayFormat>
        <label>GPL Profile ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>GPL Profiles</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/GPL_Profile__c/fields/Devices__c.field-meta.xml
<CustomField>
    <fullName>Devices__c</fullName>
    <label>Devices</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Adkins Strut</fullName>
            </value>
            <value>
                <fullName>Chondrofix</fullName>
            </value>
            <value>
                <fullName>Early Intervention</fullName>
            </value>
            <value>
                <fullName>Gel-One</fullName>
            </value>
            <value>
                <fullName>Oxford Partial Knee</fullName>
            </value>
            <value>
                <fullName>Patient Specific Instruments</fullName>
            </value>
            <value>
                <fullName>Pectus Bar</fullName>
            </value>
            <value>
                <fullName>Persona Knee System</fullName>
            </value>
            <value>
                <fullName>PFJ</fullName>
            </value>
            <value>
                <fullName>RibFix Blu</fullName>
            </value>
            <value>
                <fullName>SternaLock 360</fullName>
            </value>
            <value>
                <fullName>SternaLock Blu</fullName>
            </value>
            <value>
                <fullName>Trabecular Metal Total Ankle</fullName>
            </value>
            <value>
                <fullName>Vanguard</fullName>
            </value>
            <value>
                <fullName>VitaminE</fullName>
            </value>
            <value>
                <fullName>Vivacit-E-Hip Construct</fullName>
            </value>
            <value>
                <fullName>XP</fullName>
            </value>
            <value>
                <fullName>Zimmer Biomet Signature Solutions</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/GPL_Profile__c/fields/Facebook__c.field-meta.xml
<CustomField>
    <fullName>Facebook__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Facebook</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/GPL_Profile__c/fields/Fellowship__c.field-meta.xml
<CustomField>
    <fullName>Fellowship__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Fellowship</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/GPL_Profile__c/fields/FirstName__c.field-meta.xml
<CustomField>
    <fullName>FirstName__c</fullName>
    <formula>IF (Account__c != null, Account__r.FirstName,
    IF (Contact__c != null, Contact__r.FirstName,&apos;&apos;)
)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>First Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/GPL_Profile__c/fields/Languages__c.field-meta.xml
<CustomField>
    <fullName>Languages__c</fullName>
    <label>Languages</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>English</fullName>
            </value>
            <value>
                <fullName>Spanish</fullName>
            </value>
            <value>
                <fullName>French</fullName>
            </value>
            <value>
                <fullName>German</fullName>
            </value>
            <value>
                <fullName>Mandarin</fullName>
            </value>
            <value>
                <fullName>Hebrew</fullName>
            </value>
            <value>
                <fullName>Japanese</fullName>
            </value>
            <value>
                <fullName>Hindi</fullName>
            </value>
            <value>
                <fullName>Arabic</fullName>
            </value>
            <value>
                <fullName>Portuguese</fullName>
            </value>
            <value>
                <fullName>Bengali</fullName>
            </value>
            <value>
                <fullName>Russian</fullName>
            </value>
            <value>
                <fullName>Korean</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/GPL_Profile__c/fields/LastName__c.field-meta.xml
<CustomField>
    <fullName>LastName__c</fullName>
    <formula>IF (Account__c != null, Account__r.LastName,
    IF (Contact__c != null, Contact__r.LastName,&apos;&apos;)
)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Last Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/GPL_Profile__c/fields/LinkedIn__c.field-meta.xml
<CustomField>
    <fullName>LinkedIn__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>LinkedIn</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/GPL_Profile__c/fields/MasterId__c.field-meta.xml
<CustomField>
    <fullName>MasterId__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <externalId>true</externalId>
    <label>Master ID</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/GPL_Profile__c/fields/MedicalSchool__c.field-meta.xml
<CustomField>
    <fullName>MedicalSchool__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Medical School</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/GPL_Profile__c/fields/Name__c.field-meta.xml
<CustomField>
    <fullName>Name__c</fullName>
    <formula>IF (!ISBLANK(Account__c), 
IF (Account__r.IsPersonAccount, 
IF (!ISNULL(TEXT(Account__r.Salutation)),TEXT(Account__r.Salutation) &amp; &quot; &quot;,null) &amp; Account__r.FirstName &amp; &quot; &quot; &amp; Account__r.LastName, 
Account__r.Name), 
IF (!ISNULL(TEXT(Contact__r.Salutation)),TEXT(Contact__r.Salutation) &amp; &quot; &quot;,null) &amp; Contact__r.FirstName &amp; &quot; &quot; &amp; Contact__r.LastName)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/GPL_Profile__c/fields/Procedures__c.field-meta.xml
<CustomField>
    <fullName>Procedures__c</fullName>
    <label>Procedures</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Anterior Hip Replacement</fullName>
            </value>
            <value>
                <fullName>Anterior Supine</fullName>
            </value>
            <value>
                <fullName>MIS</fullName>
            </value>
            <value>
                <fullName>Mobi-C Cervical Disc Replacement</fullName>
            </value>
            <value>
                <fullName>mymobility® Mobile App</fullName>
            </value>
            <value>
                <fullName>Partial Knee Replacement</fullName>
            </value>
            <value>
                <fullName>ROSA® Knee</fullName>
            </value>
            <value>
                <fullName>ROSA® Spine</fullName>
            </value>
            <value>
                <fullName>ROSA ONE® Brain</fullName>
            </value>
            <value>
                <fullName>Subchondroplasty</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/GPL_Profile__c/fields/Residency__c.field-meta.xml
<CustomField>
    <fullName>Residency__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Residency</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/GPL_Profile__c/recordTypes/GPL_ClinicProfile.recordType-meta.xml
<RecordType>
    <fullName>GPL_ClinicProfile</fullName>
    <active>true</active>
    <label>GPL Clinic Profile</label>
</RecordType>

force-app/main/default/objects/GPL_Profile__c/recordTypes/GPL_DentistProfile.recordType-meta.xml
<RecordType>
    <fullName>GPL_DentistProfile</fullName>
    <active>true</active>
    <label>GPL Dentist Profile</label>
</RecordType>

force-app/main/default/objects/GPL_Profile__c/recordTypes/GPL_PhysicianProfile.recordType-meta.xml
<RecordType>
    <fullName>GPL_PhysicianProfile</fullName>
    <active>true</active>
    <label>GPL Physician Profile</label>
</RecordType>

force-app/main/default/classes/GplRestDataManager.cls
public with sharing class GplRestDataManager {
    
    private static Id CLINIC_RECORD_TYPE_ID = RecordTypeHelper.getRecordTypeId('GPL_Profile__c', 'GPL_ClinicProfile');
    private static Id PHYSICIAN_RECORD_TYPE_ID = RecordTypeHelper.getRecordTypeId('GPL_Profile__c', 'GPL_PhysicianProfile');
    private static Id DENTIST_RECORD_TYPE_ID = RecordTypeHelper.getRecordTypeId('GPL_Profile__c', 'GPL_DentistProfile');
    
    
    public list<GplRestDataModel.Profile> searchPhysicians(GplRestDataModel.Criteria criteria){
        list<GPL_Location__c> matches = Database.query(buildQuery(criteria, PHYSICIAN_RECORD_TYPE_ID));
        map<Id, GplRestDataModel.Profile> results = new map<Id, GplRestDataModel.Profile>();
        set<String> ids = new set<String>();
        for(GPL_Location__c location : matches){
            GplRestDataModel.Profile profile = results.get(location.GPL_Profile__c);
            if(profile == null){
                profile = createPhysician(location.GPL_Profile__r);
                ids.add(location.GPL_Profile__r.MasterId__c);
            }
            results.put(location.GPL_Profile__c, profile);
        }
        
        list<GPl_Location__c> locations = findLocations(results.keySet());
        for(GPL_Location__c location : locations){
            GplRestDataModel.Profile profile = results.get(location.GPL_Profile__c);
            profile.locations.add(createLocation(location));
            results.put(location.GPL_Profile__c, profile);
        }
        
        return results.values();
    }
    
    public list<GplRestDataModel.Profile> searchClinics(GplRestDataModel.Criteria criteria){
        list<GPL_Location__c> matches = Database.query(buildQuery(criteria, CLINIC_RECORD_TYPE_ID));
        map<Id, GplRestDataModel.Profile> results = new map<Id, GplRestDataModel.Profile>();
        set<String> ids = new set<String>();
        for(GPL_Location__c location : matches){
            GplRestDataModel.Profile profile = results.get(location.GPL_Profile__c);
            if(profile == null){
                profile = createClinic(location.GPL_Profile__r);
            }
            results.put(location.GPL_Profile__c, profile);
        }
        
        list<GPl_Location__c> locations = findLocations(results.keySet());
        for(GPL_Location__c location : locations){
            GplRestDataModel.Profile profile = results.get(location.GPL_Profile__c);
            profile.locations.add(createLocation(location));
            results.put(location.GPL_Profile__c, profile);
        }
        
        return results.values();
    }
    
    public list<GplRestDataModel.Profile> searchDentists(GplRestDataModel.Criteria criteria){
        list<GPL_Location__c> matches = Database.query(buildQuery(criteria, DENTIST_RECORD_TYPE_ID));
        map<Id, GplRestDataModel.Profile> results = new map<Id, GplRestDataModel.Profile>();
        set<String> ids = new set<String>();
        for(GPL_Location__c location : matches){
            GplRestDataModel.Profile profile = results.get(location.GPL_Profile__c);
            if(profile == null){
                profile = createDentist(location.GPL_Profile__r);
                ids.add(location.GPL_Profile__r.MasterId__c);
            }
            results.put(location.GPL_Profile__c, profile);
        }
        
        list<GPl_Location__c> locations = findLocations(results.keySet());
        for(GPL_Location__c location : locations){
            GplRestDataModel.Profile profile = results.get(location.GPL_Profile__c);
            profile.locations.add(createLocation(location));
            results.put(location.GPL_Profile__c, profile);
        }
        
        return results.values();
    }
    
    
    public GplRestDataModel.Photo retrievePhoto(String id){
        GplRestDataModel.Photo photo = null;
        Attachment a = [select Body, ContentType, BodyLength from Attachment where Id = :id];
        if (a != null){
            photo = new GplRestDataModel.Photo();
            photo.body = a.Body;
            photo.bodyLength = a.BodyLength;
            photo.contentType = a.ContentType;
        }
        return photo;
    }
    
    private String buildQuery(GplRestDataModel.Criteria criteria, Id recordType){
        String query = 'SELECT Id, Name__c, City__c, Country__c, Fax__c, Latitude__c, Longitude__c, Geolocation__c, ' + 
                       'Geolocation__Latitude__s, Geolocation__Longitude__s, Phone__c, ' +
                       'PostalCode__c, Services__c, State__c, Street__c, Website__c, Location_Type__c, GPL_Profile__c, ' + 
                       'GPL_Profile__r.Devices__c, GPL_Profile__r.Facebook__c, GPL_Profile__r.Name, ' +
                        'GPL_Profile__r.Fellowship__c, GPL_Profile__r.FirstName__c, ' +
                        'GPL_Profile__r.Languages__c, GPL_Profile__r.LastName__c, ' + 
                        'GPL_Profile__r.LinkedIn__c, GPL_Profile__r.MedicalSchool__c, ' +
                        'GPL_Profile__r.Procedures__c, ' + // GPL_Profile__r.JobTitle__c, ' +
                        'GPL_Profile__r.Residency__c, GPL_Profile__r.Salutation__c, ' +
                        'GPL_Profile__r.Specialties__c, GPL_Profile__r.Twitter__c, ' +
                        'GPL_Profile__r.Username__c, GPL_Profile__r.YouTube__c, ' +
                        'GPL_Profile__r.MasterId__c, GPL_Profile__r.Groups__c, GPL_Profile__r.ParentId__c, ' +
                        'GPL_Profile__r.Honors__c, GPL_Profile__r.Publications__c, ' +
                        'GPL_Profile__r.PhotoId__c, GPL_Profile__r.Name__c, GPL_Profile__r.PreferredFirstName__c, ' +
                        'GPL_Profile__r.PreferredName__c, GPL_Profile__r.Specialty_Type__c, '+
                        'GPL_Profile__r.Contact_Title__c '+
                        'FROM GPL_Location__c ' +                           
                        'WHERE GPL_Profile__r.RecordTypeId = \'' + recordType + '\'';
        if (criteria.id == null || criteria.id.trim().length() == 0){
            query += ' AND GPL_Profile__r.Inactive__c = false ';
            query += ' AND Location_Type__c != \'Hospital\'';
        }
        
        if (criteria.postalCode != null && criteria.postalCode.trim().length() > 0){
            query += ' and PostalCode__c = \'' + String.escapeSingleQuotes(criteria.postalCode) + '\'';
        }   
        if (criteria.city != null && criteria.city.trim().length() > 0) {
            query += ' and City__c = \'' + String.escapeSingleQuotes(criteria.city) + '\'';
        }                  
        if (criteria.state != null && criteria.state.trim().length() > 0) {
            query += ' and State__c = \'' + String.escapeSingleQuotes(criteria.state) + '\'';
        }
        if(criteria.coordinate != null && criteria.coordinate.latitude != null && criteria.coordinate.longitude != null){
            if (criteria.radius == null || criteria.radius > 100) {
                criteria.radius = 25;
            }
            if (criteria.radiusUom != 'mi' || criteria.radiusUom != 'km') {
                criteria.radiusUom = 'mi';
            }
            query += ' and DISTANCE(Geolocation__c, GEOLOCATION(' + criteria.coordinate.latitude + ',' + criteria.coordinate.longitude + '), \'' + String.escapeSingleQuotes(criteria.radiusUom) + '\') < ' + criteria.radius;
        }
        if (criteria.country != null && criteria.country.trim().length() > 0){
            query += ' and Country__c = \'' +  String.escapeSingleQuotes(criteria.country) + '\'';
        }
        if (criteria.firstName != null && criteria.firstName.trim().length() > 0) {
            query += ' and (GPL_Profile__r.FirstName__c like \'%' + String.escapeSingleQuotes(criteria.firstName) + '%\' ' + 
                        'or GPL_Profile__r.PreferredFirstName__c like \'&' + String.escapeSingleQuotes(criteria.firstName) + '%\')';
        }
        if (criteria.lastName != null && criteria.lastName.trim().length() > 0) {
            query += ' and GPL_Profile__r.LastName__c like \'%' + String.escapeSingleQuotes(criteria.lastName) + '%\'';
        }
        if (criteria.name != null && criteria.name.trim().length() > 0) {
            query += ' and (GPL_Profile__r.Name__c like \'%' + String.escapeSingleQuotes(criteria.name) + '%\' ' + 
                        'or GPL_Profile__r.PreferredName__c like \'&' + String.escapeSingleQuotes(criteria.name) + '%\')';
        }
        if (criteria.specialty != null && criteria.specialty.trim().length() > 0){
            query += ' and (GPL_Profile__r.Specialties__c includes (\'' + String.escapeSingleQuotes(criteria.specialty) + '\') or GPL_Profile__r.Specialty_Type__c includes (\'' + String.escapeSingleQuotes(criteria.specialty) + '\'))';
        }
        if (criteria.medicalDevice != null && criteria.medicalDevice.trim().length() > 0){
            query += ' and GPL_Profile__r.Devices__c includes (\'' + String.escapeSingleQuotes(criteria.medicalDevice) + '\')';
        }
        if (criteria.procedure != null && criteria.procedure.trim().length() > 0){
            query += ' and GPL_Profile__r.Procedures__c includes (\'' + String.escapeSingleQuotes(criteria.procedure) + '\')';
        }       
        if (criteria.name != null && criteria.name.trim().length() > 0){
            query += ' and Name__c like \'%' + String.escapeSingleQuotes(criteria.name) + '%\'';
        }
        if (criteria.id != null && criteria.id.trim().length() > 0){
            query += ' and GPL_Profile__c = \'' + String.escapeSingleQuotes(criteria.id) + '\'';
        }
        System.debug('-----------------------------------------' + query);
        return query;
    }
    
    private GplRestDataModel.Profile createPhysician(GPL_Profile__c x){
        GplRestDataModel.Profile p = new GplRestDataModel.Profile();
        p.id = x.Id;
        p.masterId = x.ParentId__c;
        p.salutation = x.Salutation__c;
        if(x.PreferredFirstName__c == null || x.PreferredFirstName__c.trim().length() == 0){
            p.name = x.FirstName__c + ' ' + x.LastName__c;
        } else{
            p.name = x.PreferredFirstName__c + ' ' + x.LastName__c;
        }
        p.firstName = x.FirstName__c;
        p.lastName = x.LastName__c;
        p.preferredName = x.PreferredFirstName__c;
        p.medicalSchool = x.MedicalSchool__c;
        p.residency = x.Residency__c;
        p.fellowship = x.Fellowship__c;
        p.procedures = x.Procedures__c;
        p.specialties = x.Specialties__c;
        p.devices = x.Devices__c;
        p.honors = x.Honors__c;
        p.groups = x.Groups__c;
        p.publications = x.Publications__c;
        p.languages = x.Languages__c;
        p.pictureId = x.PhotoId__c;
        p.facebook = x.Facebook__c;
        p.twitter = x.Twitter__c;
        p.linkedIn = x.LinkedIn__c;
        p.youtube = x.YouTube__c;
        p.locations = new list<GplRestDataModel.Location>();
        return p;
    }
    
    private GplRestDataModel.Profile createClinic(GPL_Profile__c x){
        GplRestDataModel.Profile p = new GplRestDataModel.Profile();
        p.id = x.Id;
        p.masterId = x.ParentId__c;
        p.name = x.Name__c;
        p.preferredName = x.PreferredName__c;
        p.devices = x.Devices__c;
        p.specialties = x.Specialties__c;
        p.procedures = x.Procedures__c;
        p.languages = x.Languages__c;
        p.facebook = x.Facebook__c;
        p.twitter = x.Twitter__c;
        p.linkedIn = x.LinkedIn__c;
        p.pictureId = x.PhotoId__c;
        p.locations = new list<GplRestDataModel.Location>();
        return p;
    }
    
    private GplRestDataModel.Profile createDentist(GPL_Profile__c x){
        GplRestDataModel.Profile p = new GplRestDataModel.Profile();
        p.id = x.Id;
        p.masterId = x.ParentId__c;
        p.salutation = x.Salutation__c;
        if(x.PreferredFirstName__c == null || x.PreferredFirstName__c.trim().length() == 0){
            p.name = x.FirstName__c + ' ' + x.LastName__c;
        } else{
            p.name = x.PreferredFirstName__c + ' ' + x.LastName__c;
        }
        p.firstName = x.FirstName__c;
        p.lastName = x.LastName__c;
        p.preferredName = x.PreferredFirstName__c;
        p.medicalSchool = x.MedicalSchool__c;
        p.residency = x.Residency__c;
        p.fellowship = x.Fellowship__c;
        p.honors = x.Honors__c;
        p.groups = x.Groups__c;
        p.publications = x.Publications__c;
        p.languages = x.Languages__c;
        p.pictureId = x.PhotoId__c;
        p.facebook = x.Facebook__c;
        p.twitter = x.Twitter__c;
        p.linkedIn = x.LinkedIn__c;
        p.youtube = x.YouTube__c;
        p.specialties = x.Specialty_Type__c;
        p.locations = new list<GplRestDataModel.Location>();
        return p;
    }
    
     private list<GPL_Location__c> findLocations(set<Id> physicianIds){
        return [SELECT Id, City__c, Country__c, Fax__c, Geolocation__Latitude__s, Geolocation__Longitude__s, Name__c, 
                       Phone__c, PostalCode__c, Services__c, State__c, Street__c, Website__c,
                       Location_Type__c, GPL_Profile__c 
                FROM GPL_Location__c
                WHERE GPL_Profile__c in :physicianIds];
                //WHERE GPL_Profile__r.Inactive__c = false
                //AND GPL_Profile__c in :physicianIds ];
    }
    
    private GplRestDataModel.Location createLocation(GPL_Location__c x){
        GplRestDataModel.Location l = new GplRestDataModel.Location();
        l.id = x.Id;
        l.locationType = x.Location_Type__c;
        l.name = x.Name__c;
        l.street = x.Street__c;
        l.city = x.City__c;
        l.state = x.State__c;
        l.country = x.Country__c;
        l.postalCode = x.PostalCode__c;
        l.phone = x.Phone__c;
        l.fax = x.Fax__c;
        l.website = x.Website__c;
        l.services = x.Services__c;
        l.latitude = x.Geolocation__Latitude__s;//x.Latitude__c;
        l.longitude = x.Geolocation__Longitude__s;//x.Longitude__c;
        return l;
    }

}