force-app/main/default/objects/GPL_Location__c/GPL_Location__c.object-meta.xml
<CustomObject>
    <label>GPL Location</label>
    <nameField>
        <displayFormat>GPL_L-{0000}</displayFormat>
        <label>GPL Location ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>GPL Locations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/GPL_Location__c/fields/Latitude__c.field-meta.xml
<CustomField>
    <fullName>Latitude__c</fullName>
    <label>Latitude</label>
    <precision>11</precision>
    <scale>8</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/GPL_Location__c/fields/Longitude__c.field-meta.xml
<CustomField>
    <fullName>Longitude__c</fullName>
    <label>Longitude</label>
    <precision>11</precision>
    <scale>8</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/GplConvertGplLocationsToGeolocation.cls
global class GplConvertGplLocationsToGeolocation implements Database.Batchable<sObject> {
     global String query;
    
    public Database.QueryLocator start(Database.BatchableContext context) {
        //return Database.getQueryLocator('select Id, Latitude__c, Longitude__c, Geolocation__Latitude__s, Geolocation__Longitude__s from GPL_Location__c') ;
        return Database.getQueryLocator(query);
    }
    
    public void execute (Database.BatchableContext context, List<sObject> scope) {
        for (sObject s : scope) {
            GPL_Location__c loc = (GPL_Location__c)s;
            loc.Geolocation__Latitude__s = loc.Latitude__c;
            loc.Geolocation__Longitude__s = loc.Longitude__c;
        }
        update scope;
    }
    
    public void finish(Database.BatchableContext bc) {
        
    }
    
}