force-app/main/default/objects/GPL_Location__c/GPL_Location__c.object-meta.xml
<CustomObject>
    <label>GPL Location</label>
    <nameField>
        <displayFormat>GPL_L-{0000}</displayFormat>
        <label>GPL Location ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>GPL Locations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/GPL_Location__c/fields/City__c.field-meta.xml
<CustomField>
    <fullName>City__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>City</label>
    <length>80</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/GPL_Location__c/fields/Country__c.field-meta.xml
<CustomField>
    <fullName>Country__c</fullName>
    <label>Country</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>AU</fullName>
            </value>
            <value>
                <fullName>CA</fullName>
            </value>
            <value>
                <fullName>GB</fullName>
            </value>
            <value>
                <fullName>US</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/GPL_Location__c/fields/GPL_Profile__c.field-meta.xml
<CustomField>
    <fullName>GPL_Profile__c</fullName>
    <label>GPL Profile</label>
    <referenceTo>GPL_Profile__c</referenceTo>
    <relationshipLabel>GPL Locations</relationshipLabel>
    <relationshipName>Locations</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/GPL_Location__c/fields/Name__c.field-meta.xml
<CustomField>
    <fullName>Name__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Name</label>
    <required>true</required>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/GPL_Location__c/fields/PostalCode__c.field-meta.xml
<CustomField>
    <fullName>PostalCode__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Postal Code</label>
    <length>10</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/GPL_Location__c/fields/Services__c.field-meta.xml
<CustomField>
    <fullName>Services__c</fullName>
    <label>Services</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Chaplaincy Services</fullName>
            </value>
            <value>
                <fullName>Pickup Services</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/GPL_Location__c/fields/State__c.field-meta.xml
<CustomField>
    <fullName>State__c</fullName>
    <label>State</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Country__c</controllingField>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>AB</fullName>
            </value>
            <value>
                <fullName>ACT</fullName>
            </value>
            <value>
                <fullName>AK</fullName>
            </value>
            <value>
                <fullName>AL</fullName>
            </value>
            <value>
                <fullName>AR</fullName>
            </value>
            <value>
                <fullName>AZ</fullName>
            </value>
            <value>
                <fullName>BC</fullName>
            </value>
            <value>
                <fullName>CA</fullName>
            </value>
            <value>
                <fullName>CO</fullName>
            </value>
            <value>
                <fullName>CT</fullName>
            </value>
            <value>
                <fullName>DC</fullName>
            </value>
            <value>
                <fullName>DE</fullName>
            </value>
            <value>
                <fullName>FL</fullName>
            </value>
            <value>
                <fullName>GA</fullName>
            </value>
            <value>
                <fullName>HI</fullName>
            </value>
            <value>
                <fullName>IA</fullName>
            </value>
            <value>
                <fullName>ID</fullName>
            </value>
            <value>
                <fullName>IL</fullName>
            </value>
            <value>
                <fullName>IN</fullName>
            </value>
            <value>
                <fullName>KS</fullName>
            </value>
            <value>
                <fullName>KY</fullName>
            </value>
            <value>
                <fullName>LA</fullName>
            </value>
            <value>
                <fullName>MA</fullName>
            </value>
            <value>
                <fullName>MB</fullName>
            </value>
            <value>
                <fullName>MD</fullName>
            </value>
            <value>
                <fullName>ME</fullName>
            </value>
            <value>
                <fullName>MI</fullName>
            </value>
            <value>
                <fullName>MN</fullName>
            </value>
            <value>
                <fullName>MO</fullName>
            </value>
            <value>
                <fullName>MS</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/GPL_Location__c/fields/Street__c.field-meta.xml
<CustomField>
    <fullName>Street__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Street</label>
    <required>true</required>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/GPL_Profile__c/GPL_Profile__c.object-meta.xml
<CustomObject>
    <label>GPL Profile</label>
    <nameField>
        <displayFormat>GPL_P-{0000}</displayFormat>
        <label>GPL Profile ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>GPL Profiles</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/GPL_Profile__c/fields/Devices__c.field-meta.xml
<CustomField>
    <fullName>Devices__c</fullName>
    <label>Devices</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Adkins Strut</fullName>
            </value>
            <value>
                <fullName>Chondrofix</fullName>
            </value>
            <value>
                <fullName>Early Intervention</fullName>
            </value>
            <value>
                <fullName>Gel-One</fullName>
            </value>
            <value>
                <fullName>Oxford Partial Knee</fullName>
            </value>
            <value>
                <fullName>Patient Specific Instruments</fullName>
            </value>
            <value>
                <fullName>Pectus Bar</fullName>
            </value>
            <value>
                <fullName>Persona Knee System</fullName>
            </value>
            <value>
                <fullName>PFJ</fullName>
            </value>
            <value>
                <fullName>RibFix Blu</fullName>
            </value>
            <value>
                <fullName>SternaLock 360</fullName>
            </value>
            <value>
                <fullName>SternaLock Blu</fullName>
            </value>
            <value>
                <fullName>Trabecular Metal Total Ankle</fullName>
            </value>
            <value>
                <fullName>Vanguard</fullName>
            </value>
            <value>
                <fullName>VitaminE</fullName>
            </value>
            <value>
                <fullName>Vivacit-E-Hip Construct</fullName>
            </value>
            <value>
                <fullName>XP</fullName>
            </value>
            <value>
                <fullName>Zimmer Biomet Signature Solutions</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/GPL_Profile__c/fields/Facebook__c.field-meta.xml
<CustomField>
    <fullName>Facebook__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Facebook</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/GPL_Profile__c/fields/Groups__c.field-meta.xml
<CustomField>
    <fullName>Groups__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Groups</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/GPL_Profile__c/fields/Honors__c.field-meta.xml
<CustomField>
    <fullName>Honors__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Honors</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/GPL_Profile__c/fields/Languages__c.field-meta.xml
<CustomField>
    <fullName>Languages__c</fullName>
    <label>Languages</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>English</fullName>
            </value>
            <value>
                <fullName>Spanish</fullName>
            </value>
            <value>
                <fullName>French</fullName>
            </value>
            <value>
                <fullName>German</fullName>
            </value>
            <value>
                <fullName>Mandarin</fullName>
            </value>
            <value>
                <fullName>Hebrew</fullName>
            </value>
            <value>
                <fullName>Japanese</fullName>
            </value>
            <value>
                <fullName>Hindi</fullName>
            </value>
            <value>
                <fullName>Arabic</fullName>
            </value>
            <value>
                <fullName>Portuguese</fullName>
            </value>
            <value>
                <fullName>Bengali</fullName>
            </value>
            <value>
                <fullName>Russian</fullName>
            </value>
            <value>
                <fullName>Korean</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/GPL_Profile__c/fields/LinkedIn__c.field-meta.xml
<CustomField>
    <fullName>LinkedIn__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>LinkedIn</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/GPL_Profile__c/fields/Name__c.field-meta.xml
<CustomField>
    <fullName>Name__c</fullName>
    <formula>IF (!ISBLANK(Account__c), 
IF (Account__r.IsPersonAccount, 
IF (!ISNULL(TEXT(Account__r.Salutation)),TEXT(Account__r.Salutation) &amp; &quot; &quot;,null) &amp; Account__r.FirstName &amp; &quot; &quot; &amp; Account__r.LastName, 
Account__r.Name), 
IF (!ISNULL(TEXT(Contact__r.Salutation)),TEXT(Contact__r.Salutation) &amp; &quot; &quot;,null) &amp; Contact__r.FirstName &amp; &quot; &quot; &amp; Contact__r.LastName)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/GPL_Profile__c/fields/Procedures__c.field-meta.xml
<CustomField>
    <fullName>Procedures__c</fullName>
    <label>Procedures</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Anterior Hip Replacement</fullName>
            </value>
            <value>
                <fullName>Anterior Supine</fullName>
            </value>
            <value>
                <fullName>MIS</fullName>
            </value>
            <value>
                <fullName>Mobi-C Cervical Disc Replacement</fullName>
            </value>
            <value>
                <fullName>mymobility® Mobile App</fullName>
            </value>
            <value>
                <fullName>Partial Knee Replacement</fullName>
            </value>
            <value>
                <fullName>ROSA® Knee</fullName>
            </value>
            <value>
                <fullName>ROSA® Spine</fullName>
            </value>
            <value>
                <fullName>ROSA ONE® Brain</fullName>
            </value>
            <value>
                <fullName>Subchondroplasty</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/GPL_Profile__c/fields/Publications__c.field-meta.xml
<CustomField>
    <fullName>Publications__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Publications</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/GPL_Profile__c/fields/Specialties__c.field-meta.xml
<CustomField>
    <fullName>Specialties__c</fullName>
    <label>Specialties</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Cardiothoracic</fullName>
            </value>
            <value>
                <fullName>Dental</fullName>
            </value>
            <value>
                <fullName>Elbow</fullName>
            </value>
            <value>
                <fullName>Foot and Ankle</fullName>
            </value>
            <value>
                <fullName>General Surgery/Trauma</fullName>
            </value>
            <value>
                <fullName>Hand and Wrist</fullName>
            </value>
            <value>
                <fullName>Heart Surgery</fullName>
            </value>
            <value>
                <fullName>Hips</fullName>
            </value>
            <value>
                <fullName>Knee</fullName>
            </value>
            <value>
                <fullName>Knee Pain Injection</fullName>
            </value>
            <value>
                <fullName>Orthopedic Trauma</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
            <value>
                <fullName>Pectus Surgery</fullName>
            </value>
            <value>
                <fullName>Pediatric</fullName>
            </value>
            <value>
                <fullName>Plastic</fullName>
            </value>
            <value>
                <fullName>ROSA Knee Robotics</fullName>
            </value>
            <value>
                <fullName>Shoulder</fullName>
            </value>
            <value>
                <fullName>Spine</fullName>
            </value>
            <value>
                <fullName>Spine/Back</fullName>
            </value>
            <value>
                <fullName>Sports Medicine</fullName>
            </value>
            <value>
                <fullName>Thoracic</fullName>
            </value>
            <value>
                <fullName>Trauma</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/GPL_Profile__c/fields/Twitter__c.field-meta.xml
<CustomField>
    <fullName>Twitter__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Twitter</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/GPL_Profile__c/fields/YouTube__c.field-meta.xml
<CustomField>
    <fullName>YouTube__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>YouTube</label>
    <type>Url</type>
</CustomField>

force-app/main/default/classes/GplGeocodeLocationsBatchJob.cls
global class GplGeocodeLocationsBatchJob implements Database.Batchable<sObject>, Database.AllowsCallouts {
	global String query {get;set;}
	global Database.QueryLocator start (Database.BatchableContext bc){
		return Database.getQueryLocator(query);
	}
	global void execute(Database.BatchableContext bc, list<sObject> scope){
		list<list<String>> batches = new list<list<String>>();
		list<String> batch = new list<String>();
		Integer count = 0;
		for (sObject so : scope){
			if (count == 10){
				count = 0;
				batches.add(batch);
				batch = new list<String>();
			}
			batch.add(so.Id);
			count = count + 1;
		}
		if (batch.size() > 0){
			batches.add(batch);
		}
		if (batches.size() > 0){
			for (list<String> ids : batches){
				GplGeocodeService.geocodeLocations(ids); 
			}	
		}
		
	}
	global void finish(Database.BatchableContext bc){
	}
	static testMethod void testGplGeocodeLocationsBatchJob(){
		GPL_Profile__c profile = new GPL_Profile__c(
			Devices__c = 'Kinectiv',
			Groups__c = 'AAOS',
			Honors__c = 'Man of the Year (2011)',
			Publications__c = 'How to replace a knee (Doctor Review - May 2011)',
			Specialties__c = 'Knee',
			Procedures__c = 'MIS',
			Languages__c = 'English',
			Facebook__c = 'http://www.facebook.com',
			Twitter__c = 'http://www.twitter.com',
			LinkedIn__c = 'http://www.linkedin.com',
			YouTube__c = 'http://www.youtube.com'
		);
		insert(profile);
		list<GPL_Location__c> locations = new list<GPL_Location__c>();
		for (integer i=0;i<25;i++){
			GPL_Location__c l1 = new GPL_Location__c(
				GPL_Profile__c = profile.Id,
				Name__c = 'TEST Practice ' + i,
				Street__c = 'TEST Mataveri International Airport',
				City__c = 'Easter Island',
				State__c = 'CL',
				PostalCode__c = 'CL012001',
				Country__c = 'CL',
			   	Phone__c = '574-372-4068',
			   	Fax__c = '574-372-4068',
			   	Website__c = 'http://www.google.com',
			   	Services__c = 'Pickup Services'
			);
			locations.add(l1);
		}
		insert locations;
		String q = 'SELECT Id FROM GPL_Location__c where Id IN (';
		boolean f = true;
		for (GPL_Location__c l : locations){
			if (!f){
				q = q + ', ';
			}
			q = q + '\'' + l.Id + '\'';
			f = false;
		}
		q = q + ')';		
		GplGeocodeLocationsBatchJob job = new GplGeocodeLocationsBatchJob();
		job.query = q;
		test.startTest();
		Database.executeBatch(job,200);
		Test.stopTest();
	}
	

}