force-app/main/default/objects/Ortho_KPI__c/Ortho_KPI__c.object-meta.xml
<CustomObject>
    <label>Ortho KPI</label>
    <nameField>
        <displayFormat>OKPI-{00000}</displayFormat>
        <label>Ortho KPI</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Ortho KPIs</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Ortho_KPI__c/fields/KPI_Current__c.field-meta.xml
<CustomField>
    <fullName>KPI_Current__c</fullName>
    <description>Value of the current KPI measure</description>
    <label>KPI Current</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Ortho_KPI__c/fields/KPI_Label__c.field-meta.xml
<CustomField>
    <fullName>KPI_Label__c</fullName>
    <description>Label for the KPI value (e.g. &quot;January&quot; for a Monthly KPI</description>
    <encryptionScheme>None</encryptionScheme>
    <label>KPI Label</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Ortho_KPI__c/fields/KPI_Previous__c.field-meta.xml
<CustomField>
    <fullName>KPI_Previous__c</fullName>
    <description>Previous KPI value</description>
    <label>KPI Previous</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Ortho_KPI__c/fields/KPI_Target__c.field-meta.xml
<CustomField>
    <fullName>KPI_Target__c</fullName>
    <description>Target KPI value</description>
    <label>KPI Target</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Ortho_KPI__c/fields/KPI_Type__c.field-meta.xml
<CustomField>
    <fullName>KPI_Type__c</fullName>
    <description>KPI type (Target, Year-Over-Year)</description>
    <label>KPI Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Target</fullName>
            </value>
            <value>
                <fullName>Year-Over-Year</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Ortho_KPI__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <description>Product related to the KPI measure</description>
    <label>Product</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Cement</fullName>
            </value>
            <value>
                <fullName>Early Intervention</fullName>
            </value>
            <value>
                <fullName>Extremities</fullName>
            </value>
            <value>
                <fullName>Foot &amp; Ankle</fullName>
            </value>
            <value>
                <fullName>Hips</fullName>
            </value>
            <value>
                <fullName>Knees</fullName>
            </value>
            <value>
                <fullName>LARGE JOINT</fullName>
            </value>
            <value>
                <fullName>Non-Recon</fullName>
            </value>
            <value>
                <fullName>Recon</fullName>
            </value>
            <value>
                <fullName>Sports Medicine</fullName>
            </value>
            <value>
                <fullName>Trauma</fullName>
            </value>
            <value>
                <fullName>UPPER EXTREMITIES</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Ortho_KPI__c/fields/Timeframe__c.field-meta.xml
<CustomField>
    <fullName>Timeframe__c</fullName>
    <description>Timeframe for KPI value</description>
    <label>Timeframe</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Quarterly</fullName>
            </value>
            <value>
                <fullName>Monthly</fullName>
            </value>
            <value>
                <fullName>Yearly</fullName>
            </value>
            <value>
                <fullName>Yearly - Without Quarter</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/Ortho_KPIControllerTest.cls
/**
* @author Appirio Inc.
* @date March, 2020
*
* @description Test Class for Ortho_KPI Controller
*/
@isTest
public class Ortho_KPIControllerTest {
    @testSetup
    public static void CreateCustomSetting(){
        
        TestUtilsLocal.createCustomSetting('AddUsersToPSQueues Trigger',true);
    }
    public Static Ortho_KPI__c CreateTestData(User usr){
        
        system.runAs(usr){
            //Create Ortho KPI 
            Ortho_KPI__c oKPI = new Ortho_KPI__c(KPI_Type__c = 'Target',
                                                 Timeframe__c = 'Monthly',
                                                 Product__c = 'F&A',
                                                 KPI_Current__c = 63000,
                                                 KPI_Previous__c = 56700,
                                                 KPI_Label__c = '2020-07');
            INSERT oKPI;
        }
        Ortho_KPI__c oKPI = [SELECT Id, KPI_Current__c, KPI_Previous__c, KPI_Target__c, KPI_Type__c, LastModifiedById, 
                             Name, OwnerId, Product__c, Timeframe__c, 
                             KPI_Label__c FROM Ortho_KPI__c WHERE Product__c = 'F&A'];
        return oKPI;
    }
    //Check when Time Frame is Monthly
    @isTest
    public Static void MonthlyTimeFrame()
    {
        //Create Test User
        User usr = TestUtilsLocal.createTestUser('Test@2', True); 
        Test.startTest();
        System.runAs(usr){
            Ortho_KPI__c oKPI = CreateTestData(usr);
            System.assertNotEquals(oKPI, NULL);
            Ortho_KPIController.getProductData(oKPI.Product__c);
            Test.stopTest();
        }
    }
    
    //Check When Time Frame is Quarterly
    @isTest
    public static void QuarterlyTimeFrame()
    {
        //Create Test User
        User usr = TestUtilsLocal.createTestUser('Test@2', True); 
        Test.startTest();
        System.runAs(usr){
            Ortho_KPI__c oKPI = CreateTestData(usr);            
            System.assertNotEquals(oKPI, NULL);
            oKPI.Timeframe__c = 'Quarterly';
            UPDATE oKPI;
            Ortho_KPIController.getProductData(oKPI.Product__c);
            Test.stopTest();
        }
    }
    
}