force-app/main/default/objects/Ortho_KPI__c/Ortho_KPI__c.object-meta.xml
<CustomObject>
    <label>Ortho KPI</label>
    <nameField>
        <displayFormat>OKPI-{00000}</displayFormat>
        <label>Ortho KPI</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Ortho KPIs</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Ortho_KPI__c/fields/Timeframe__c.field-meta.xml
<CustomField>
    <fullName>Timeframe__c</fullName>
    <description>Timeframe for KPI value</description>
    <label>Timeframe</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Quarterly</fullName>
            </value>
            <value>
                <fullName>Monthly</fullName>
            </value>
            <value>
                <fullName>Yearly</fullName>
            </value>
            <value>
                <fullName>Yearly - Without Quarter</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/Ortho_KPIController.cls
public with sharing class Ortho_KPIController {
    @AuraEnabled(cacheable = true)
    public static Ortho_KPI getProductData(String product){

        List<Ortho_KPI__c> orthoKPIs = Ortho_KPISelector.getKPIByUserAndTypeAndProduct(new Set<Id>{UserInfo.getUserId()}, new Set<String>{'Target'}, new Set<String>{product});
        Ortho_KPI oKPI = new Ortho_KPI();
        for(Ortho_KPI__c kpi : orthoKPIs){
            if(kpi.Timeframe__c == 'Monthly'){
                oKPI.monthly = kpi;
            }
            if(kpi.Timeframe__c == 'Quarterly'){
                oKPI.quarterly = kpi;
            }
            if(kpi.Timeframe__c == 'Yearly'){
                oKPI.yearly = kpi;
            }
            if(kpi.Timeframe__c == 'Yearly - Without Quarter'){
                oKPI.yearlyWithoutQtr = kpi;
            }
        }
        return oKPI;
    }

    public class Ortho_KPI {
        @AuraEnabled
        public Ortho_KPI__c monthly {get;set;}
        @AuraEnabled
        public Ortho_KPI__c quarterly {get;set;}
        @AuraEnabled
        public Ortho_KPI__c yearly {get;set;}
        @AuraEnabled
        public Ortho_KPI__c yearlyWithoutQtr {get;set;}
    }
}