force-app/main/default/objects/Ortho_KPI__c/Ortho_KPI__c.object-meta.xml
<CustomObject>
    <label>Ortho KPI</label>
    <nameField>
        <displayFormat>OKPI-{00000}</displayFormat>
        <label>Ortho KPI</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Ortho KPIs</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Ortho_KPI__c/fields/KPI_Current__c.field-meta.xml
<CustomField>
    <fullName>KPI_Current__c</fullName>
    <description>Value of the current KPI measure</description>
    <label>KPI Current</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Ortho_KPI__c/fields/KPI_Target__c.field-meta.xml
<CustomField>
    <fullName>KPI_Target__c</fullName>
    <description>Target KPI value</description>
    <label>KPI Target</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Ortho_KPI__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <description>Product related to the KPI measure</description>
    <label>Product</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Cement</fullName>
            </value>
            <value>
                <fullName>Early Intervention</fullName>
            </value>
            <value>
                <fullName>Extremities</fullName>
            </value>
            <value>
                <fullName>Foot &amp; Ankle</fullName>
            </value>
            <value>
                <fullName>Hips</fullName>
            </value>
            <value>
                <fullName>Knees</fullName>
            </value>
            <value>
                <fullName>LARGE JOINT</fullName>
            </value>
            <value>
                <fullName>Non-Recon</fullName>
            </value>
            <value>
                <fullName>Recon</fullName>
            </value>
            <value>
                <fullName>Sports Medicine</fullName>
            </value>
            <value>
                <fullName>Trauma</fullName>
            </value>
            <value>
                <fullName>UPPER EXTREMITIES</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Ortho_KPI__c/fields/Timeframe__c.field-meta.xml
<CustomField>
    <fullName>Timeframe__c</fullName>
    <description>Timeframe for KPI value</description>
    <label>Timeframe</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Quarterly</fullName>
            </value>
            <value>
                <fullName>Monthly</fullName>
            </value>
            <value>
                <fullName>Yearly</fullName>
            </value>
            <value>
                <fullName>Yearly - Without Quarter</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/Ortho_ChartDataP2T.cls
public with sharing class Ortho_ChartDataP2T implements Ortho_IChart {

    public Ortho_ChartFilter [] filters = new List<Ortho_ChartFilter>{
        new Ortho_ChartFilter('Timeframe__c', 'Timeframe', new List<String>{'Monthly', 'Quarterly'}, 'Monthly', null),
        new Ortho_ChartFilter('Product__c', 'Product', new List<String>{
            'All',
            'Early Intervention',
            'Extremeties',
            'Cement',
            'F&A',
            'Hips',
            'Knees'
        }, 'All', 'All')
    };

    public String getName(){
        return System.Label.Ortho_Mobile_Chart_Performance_to_Target_Title;
    }


    public Ortho_ChartData getData(){
        return getData(new List<Ortho_ChartFilter>());

    }

    public Ortho_ChartData getData(Ortho_ChartFilter[] filters){
        if(filters == null || filters.size() == 0){
            filters = this.filters;
        }

        List<Ortho_KPI__c> kpis = Ortho_KPISelector.getKPIByUserAndType(new Set<Id>{UserInfo.getUserId()}, new Set<String>{'Target'});
        Ortho_ChartData chartData = new Ortho_ChartData();

        Ortho_KPI__c currentKPI;

        List<Ortho_KPI__c> matchingKPIs = new List<Ortho_KPI__c>();
        for(Ortho_KPI__c kpi : kpis){
            if(Ortho_ChartFilter.matches(kpi, filters)){
                matchingKPIs.add(kpi);
            }
        }
        
        Decimal current = 0;
        Decimal target = 0;

        for(Ortho_KPI__c kpi : matchingKpis){
            current+= kpi.KPI_Current__c;
            target+= kpi.KPI_Target__c;
        }

        Ortho_ChartDataset performance = new Ortho_ChartDataset();
        
        Decimal targetRemaining = target - current;
        performance.data = new List<Decimal>{current, targetRemaining};

        chartData.addDataset(performance);
        chartData.labels = System.Label.Ortho_Mobile_Chart_Performance_to_Target_Labels.split(',');

        chartData.chartTitle = System.Label.Ortho_Mobile_Chart_Performance_to_Target_Title;
    


        chartData.filters = this.filters;

        return chartData;
    }

   


}