force-app/main/default/objects/Ortho_KPI__c/Ortho_KPI__c.object-meta.xml
<CustomObject>
    <label>Ortho KPI</label>
    <nameField>
        <displayFormat>OKPI-{00000}</displayFormat>
        <label>Ortho KPI</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Ortho KPIs</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Ortho_KPI__c/fields/KPI_Current__c.field-meta.xml
<CustomField>
    <fullName>KPI_Current__c</fullName>
    <description>Value of the current KPI measure</description>
    <label>KPI Current</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Ortho_KPI__c/fields/KPI_Previous__c.field-meta.xml
<CustomField>
    <fullName>KPI_Previous__c</fullName>
    <description>Previous KPI value</description>
    <label>KPI Previous</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Ortho_KPI__c/fields/KPI_Target__c.field-meta.xml
<CustomField>
    <fullName>KPI_Target__c</fullName>
    <description>Target KPI value</description>
    <label>KPI Target</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Ortho_KPI__c/fields/KPI_Type__c.field-meta.xml
<CustomField>
    <fullName>KPI_Type__c</fullName>
    <description>KPI type (Target, Year-Over-Year)</description>
    <label>KPI Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Target</fullName>
            </value>
            <value>
                <fullName>Year-Over-Year</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Ortho_KPI__c/fields/Timeframe__c.field-meta.xml
<CustomField>
    <fullName>Timeframe__c</fullName>
    <description>Timeframe for KPI value</description>
    <label>Timeframe</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Quarterly</fullName>
            </value>
            <value>
                <fullName>Monthly</fullName>
            </value>
            <value>
                <fullName>Yearly</fullName>
            </value>
            <value>
                <fullName>Yearly - Without Quarter</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/Ortho_ChartDataYOYTableTest.cls
/**
* @author Appirio Inc.
* @date March, 2020
*
* @group Opportunity
*
* @description Test Class for Ortho_ChartDataYOYTable Controller
*/
@isTest
public class Ortho_ChartDataYOYTableTest {
    
    @testSetup
    public static void createTestData(){
        TestUtilsLocal.createCustomSetting('AddUsersToPSQueues Trigger',true);
        Ortho_KPI__c objKPI = new Ortho_KPI__c();
        objKPI.KPI_Type__c='Year-Over-Year';
        objKPI.Timeframe__c='Yearly';
        //objKPI.OwnerId = appUser.id;
        objKPI.KPI_Current__c = 12000.00;
        objKPI.KPI_Previous__c = 1000.00;
        objKpi.KPI_Target__c = 12.00;
        insert objKPI;
    }
    
    @istest
    static void testDataYOYTable(){
        Ortho_KPI__c objKPI = [Select Id,OwnerId from Ortho_KPI__c LIMIT 1];
        User appUser = TestUtilsLocal.createTestSalesUser('appUser',true);
        Test.startTest();
        System.runAs(appUser) {
            objKPI.OwnerId = appUser.id;
            update objKPI;
            System.assertEquals(appUser.id, objKPI.OwnerId);
            Ortho_ChartDataYOYTable objOrtho = new Ortho_ChartDataYOYTable();
            objOrtho.getName();
            objOrtho.getData();
        }
        Test.stopTest();
    }
}