force-app/main/default/objects/Ortho_KPI__c/Ortho_KPI__c.object-meta.xml
<CustomObject>
    <label>Ortho KPI</label>
    <nameField>
        <displayFormat>OKPI-{00000}</displayFormat>
        <label>Ortho KPI</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Ortho KPIs</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Ortho_KPI__c/fields/KPI_Current__c.field-meta.xml
<CustomField>
    <fullName>KPI_Current__c</fullName>
    <description>Value of the current KPI measure</description>
    <label>KPI Current</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Ortho_KPI__c/fields/KPI_Label__c.field-meta.xml
<CustomField>
    <fullName>KPI_Label__c</fullName>
    <description>Label for the KPI value (e.g. &quot;January&quot; for a Monthly KPI</description>
    <encryptionScheme>None</encryptionScheme>
    <label>KPI Label</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Ortho_KPI__c/fields/KPI_Previous__c.field-meta.xml
<CustomField>
    <fullName>KPI_Previous__c</fullName>
    <description>Previous KPI value</description>
    <label>KPI Previous</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Ortho_KPI__c/fields/KPI_Type__c.field-meta.xml
<CustomField>
    <fullName>KPI_Type__c</fullName>
    <description>KPI type (Target, Year-Over-Year)</description>
    <label>KPI Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Target</fullName>
            </value>
            <value>
                <fullName>Year-Over-Year</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Ortho_KPI__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <description>Product related to the KPI measure</description>
    <label>Product</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Cement</fullName>
            </value>
            <value>
                <fullName>Early Intervention</fullName>
            </value>
            <value>
                <fullName>Extremities</fullName>
            </value>
            <value>
                <fullName>Foot &amp; Ankle</fullName>
            </value>
            <value>
                <fullName>Hips</fullName>
            </value>
            <value>
                <fullName>Knees</fullName>
            </value>
            <value>
                <fullName>LARGE JOINT</fullName>
            </value>
            <value>
                <fullName>Non-Recon</fullName>
            </value>
            <value>
                <fullName>Recon</fullName>
            </value>
            <value>
                <fullName>Sports Medicine</fullName>
            </value>
            <value>
                <fullName>Trauma</fullName>
            </value>
            <value>
                <fullName>UPPER EXTREMITIES</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Ortho_KPI__c/fields/Timeframe__c.field-meta.xml
<CustomField>
    <fullName>Timeframe__c</fullName>
    <description>Timeframe for KPI value</description>
    <label>Timeframe</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Quarterly</fullName>
            </value>
            <value>
                <fullName>Monthly</fullName>
            </value>
            <value>
                <fullName>Yearly</fullName>
            </value>
            <value>
                <fullName>Yearly - Without Quarter</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/Ortho_ChartDataYOYPerformanceTest.cls
/**
* @author Appirio Inc.
* @date March, 2020
*
* @group Opportunity
*
* @description Test Class for Ortho_ChartDataYOYPerformance Controller
*/
@isTest
public class Ortho_ChartDataYOYPerformanceTest {
    
    @testSetup
    public static void createTestData(){
        TestUtilsLocal.createCustomSetting('AddUsersToPSQueues Trigger',true);
        Product2 objProduct = TestUtilsLocal.createProduct();
        Ortho_KPI__c objKPI = new Ortho_KPI__c();
        objKPI.KPI_Type__c='Year-Over-Year';
        objKPI.Timeframe__c='Yearly';
        objKPI.Product__c = objProduct.id;
        objKPI.KPI_Current__c = 12000.00;
        objKPI.KPI_Previous__c = 1000.00;
        objKPI.KPI_Label__c = 'KPI_Label__c';
        insert objKPI;
    }
    @istest
    static void testDataYOYPerf(){
        Ortho_KPI__c objKPI = [Select Id,OwnerId from Ortho_KPI__c LIMIT 1];
        User appUser = TestUtilsLocal.createTestSalesUser('appUser',true);
        Ortho_ChartFilter [] filters=new List<Ortho_ChartFilter>{
            new Ortho_ChartFilter('Product__c', 'Product', new List<String>{
                'All'})
                };
               Test.startTest();
        System.runAs(appUser) {
            objKPI.OwnerId = appUser.id;
            update objKPI;
            System.assertEquals(appUser.id, objKPI.OwnerId);
            Ortho_ChartDataYOYPerformance objOrtho = new Ortho_ChartDataYOYPerformance();
            objOrtho.getName();
            objOrtho.getData();
            objOrtho.getData(filters);
        }
        Test.stopTest();
    }
}