force-app/main/default/objects/Certification__c/Certification__c.object-meta.xml
<CustomObject>
    <label>Certification</label>
    <nameField>
        <displayFormat>CID-{000000}</displayFormat>
        <label>Certification Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Certifications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Certification__c/fields/Certification__c.field-meta.xml
<CustomField>
    <fullName>Certification__c</fullName>
    <description>Names of applicable certifications available to a particular record type</description>
    <label>Certification</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>ROSA Knee</fullName>
            </value>
            <value>
                <fullName>ROSA Partial Knee</fullName>
            </value>
            <value>
                <fullName>ROSA Hip</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Certification__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Contact the Certification Record is related to</description>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Certifications</relationshipLabel>
    <relationshipName>Certifications</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/HCF_Surgeon_Certification__c/HCF_Surgeon_Certification__c.object-meta.xml
<CustomObject>
    <description>Junction object informing HCF Accounts of which Certifications exist against Surgeon Records</description>
    <label>HCF Surgeon Certification</label>
    <nameField>
        <displayFormat>HSC-{0000000}</displayFormat>
        <label>HCF Surgeon Certification Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>HCF Surgeon Certification</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/HCF_Surgeon_Certification__c/fields/Certification__c.field-meta.xml
<CustomField>
    <fullName>Certification__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Certification assigned against a Surgeon</description>
    <label>Certification</label>
    <referenceTo>Certification__c</referenceTo>
    <relationshipLabel>Surgeon Certification Certifications</relationshipLabel>
    <relationshipName>HCF_Surgeon_Certification</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/HCF_Surgeon_Certification__c/fields/Health_Care_Facility__c.field-meta.xml
<CustomField>
    <fullName>Health_Care_Facility__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Health Care Facility Account Id</description>
    <label>Health Care Facility</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Surgeon Certifications</relationshipLabel>
    <relationshipName>HCF_Surgeon_Certification</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/HCF_Surgeon_Certification__c/fields/Surgeon__c.field-meta.xml
<CustomField>
    <fullName>Surgeon__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Surgeon Mapping who has Certification records and exists against a Health Care Facility</description>
    <label>Surgeon</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>HCF Surgeon Certification (Surgeon)</relationshipLabel>
    <relationshipName>HCF_Surgeon_Certification1</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Healthcare_Surgeon_Relationship__c/Healthcare_Surgeon_Relationship__c.object-meta.xml
<CustomObject>
    <label>Account Relationship</label>
    <nameField>
        <displayFormat>{0000}</displayFormat>
        <label>Relationship Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Accounts Relationships</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Healthcare_Surgeon_Relationship__c/fields/Surgeon__c.field-meta.xml
<CustomField>
    <fullName>Surgeon__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Surgeon</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Healthcare Facility Relationship</relationshipLabel>
    <relationshipName>Healthcare_Facility_Surgeon</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/MedCertDailySyncJob.cls
/**
* @author Manish Vashistha - Zimmer Biomet.
* @date December, 2020
*
* @group HCF_Surgeon_Certification__c
*
* @description The batch job will keep records in sync with Healthcare_Surgeon_Relationship__c
*/
global class MedCertDailySyncJob  implements Database.Batchable<sObject> {
    public MedCertDailySyncJob() {

    }

    private String query;
    private List<Id> lstSrgn;
    global Database.QueryLocator start(Database.BatchableContext bc) {  
        Datetime d = Datetime.now();
        d = d.addHours(-24);
        //query = 'SELECT Id,Surgeon__c, Certification__c, Health_Care_Facility__c FROM HCF_Surgeon_Certification__c order by LastModifiedDate desc';
        query = 'SELECT Contact__r.AccountId, Id FROM Certification__c';
        return Database.getQueryLocator(query);
    }
    

    global void execute(Database.BatchableContext bc, List<Certification__c> lstSrgnCerts){
        // process each batch of records
        System.debug('Synchronizing ... Med Certifications : '+lstSrgnCerts.size());
        /*
        Set<Id> setUnqSrgns = new Set<Id>();    
        
        for (Certification__c i : lstSrgnCerts)
            setUnqSrgns.add(i.Contact__r.AccountId);

        //Create the List Variable
        List<Id> unqSrgns  = new List<Id>();
        unqSrgns.addAll(setUnqSrgns);
        */
        if(!lstSrgnCerts.isEmpty()) 
        {            
            MedCert_Util.syncMedCertifications(lstSrgnCerts);            
        }        
    }
        

    global void finish(Database.BatchableContext bc){
        System.debug('Med Cert Synchronization Job Completed.');

        // Get the ID of the AsyncApexJob representing this batch job
        // from Database.BatchableContext.
        // Query the AsyncApexJob object to retrieve the current job's information.
        AsyncApexJob a = [SELECT Id, Status, NumberOfErrors, JobItemsProcessed,
        TotalJobItems, CreatedBy.Email
        FROM AsyncApexJob WHERE Id =
        :BC.getJobId()];
        // Send an email to the Apex job's submitter notifying of job completion.
        Messaging.SingleEmailMessage mail = new Messaging.SingleEmailMessage();
        System.debug('The Job Id :'+ BC.getJobId() + ' is created by '+a.CreatedBy.Email);
        String[] toAddresses = new String[] {a.CreatedBy.Email};
        mail.setToAddresses(toAddresses);
        mail.setSubject('Apex Med Cert Synchronization ' + a.Status);
        mail.setPlainTextBody
        ('The batch Apex job processed ' + a.TotalJobItems +
        ' batches with '+ a.NumberOfErrors + ' failures.');
        Messaging.sendEmail(new Messaging.SingleEmailMessage[] { mail });
    }
}