force-app/main/default/objects/Certification__c/Certification__c.object-meta.xml
<CustomObject>
    <label>Certification</label>
    <nameField>
        <displayFormat>CID-{000000}</displayFormat>
        <label>Certification Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Certifications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Certification__c/fields/Certification__c.field-meta.xml
<CustomField>
    <fullName>Certification__c</fullName>
    <description>Names of applicable certifications available to a particular record type</description>
    <label>Certification</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>ROSA Knee</fullName>
            </value>
            <value>
                <fullName>ROSA Partial Knee</fullName>
            </value>
            <value>
                <fullName>ROSA Hip</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Certification__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Contact the Certification Record is related to</description>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Certifications</relationshipLabel>
    <relationshipName>Certifications</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/HCF_Surgeon_Certification__c/HCF_Surgeon_Certification__c.object-meta.xml
<CustomObject>
    <description>Junction object informing HCF Accounts of which Certifications exist against Surgeon Records</description>
    <label>HCF Surgeon Certification</label>
    <nameField>
        <displayFormat>HSC-{0000000}</displayFormat>
        <label>HCF Surgeon Certification Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>HCF Surgeon Certification</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/HCF_Surgeon_Certification__c/fields/Certification__c.field-meta.xml
<CustomField>
    <fullName>Certification__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Certification assigned against a Surgeon</description>
    <label>Certification</label>
    <referenceTo>Certification__c</referenceTo>
    <relationshipLabel>Surgeon Certification Certifications</relationshipLabel>
    <relationshipName>HCF_Surgeon_Certification</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/HCF_Surgeon_Certification__c/fields/Health_Care_Facility__c.field-meta.xml
<CustomField>
    <fullName>Health_Care_Facility__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Health Care Facility Account Id</description>
    <label>Health Care Facility</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Surgeon Certifications</relationshipLabel>
    <relationshipName>HCF_Surgeon_Certification</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/HCF_Surgeon_Certification__c/fields/Surgeon__c.field-meta.xml
<CustomField>
    <fullName>Surgeon__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Surgeon Mapping who has Certification records and exists against a Health Care Facility</description>
    <label>Surgeon</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>HCF Surgeon Certification (Surgeon)</relationshipLabel>
    <relationshipName>HCF_Surgeon_Certification1</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Healthcare_Surgeon_Relationship__c/Healthcare_Surgeon_Relationship__c.object-meta.xml
<CustomObject>
    <label>Account Relationship</label>
    <nameField>
        <displayFormat>{0000}</displayFormat>
        <label>Relationship Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Accounts Relationships</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Healthcare_Surgeon_Relationship__c/fields/Healthcare_Facility__c.field-meta.xml
<CustomField>
    <fullName>Healthcare_Facility__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Healthcare Facility</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Healthcare Facility</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Surgeon Relationship</relationshipLabel>
    <relationshipName>R00N80000002hSSQEA2</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Healthcare_Surgeon_Relationship__c/fields/Surgeon__c.field-meta.xml
<CustomField>
    <fullName>Surgeon__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Surgeon</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Healthcare Facility Relationship</relationshipLabel>
    <relationshipName>Healthcare_Facility_Surgeon</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/MedCert_Util.cls
public with sharing class MedCert_Util {
    public MedCert_Util() {
    }
    /*
    * @description This method creates Surgeon Med Certifications Records
    */
    public static void syncMedCertifications(List<Certification__c> lstCerts) {
        List<HCF_Surgeon_Certification__c> lstExistingCerts = new List<HCF_Surgeon_Certification__c>();
        List<Healthcare_Surgeon_Relationship__c> lstHCFs = new List<Healthcare_Surgeon_Relationship__c>();

        Set<Id> lstUnqSrgns = new Set<Id>();        
        
        Map<Id, Set<Id>> srgnCertMapNeeded = new Map<id, Set<Id>>();

        System.debug(lstCerts.size() + ' certifications');
        for (Certification__c c : lstCerts) {

            if (c.Contact__r.AccountId != null) {
                if(!srgnCertMapNeeded.containsKey(c.Contact__r.AccountId)){
                    srgnCertMapNeeded.put(c.Contact__r.AccountId, new Set<Id>());
                }
                
                srgnCertMapNeeded.get(c.Contact__r.AccountId).add(c.Id);

                lstUnqSrgns.add(c.Contact__r.AccountId);
            }
        }
        
        lstExistingCerts = [Select Id, Certification__c, Health_Care_Facility__c, Surgeon__c from HCF_Surgeon_Certification__c where Surgeon__c in :lstUnqSrgns];

        lstHCFs = [Select Id, Healthcare_Facility__c, Surgeon__c from Healthcare_Surgeon_Relationship__c where Surgeon__c in :lstUnqSrgns];

        Map<Id, Set<Id>> srgnCertMap = new Map<id, Set<Id>>();
        Map<Id, Set<Id>> srgnHCFMap = new Map<id, Set<Id>>();
        // We will create a Set of Srgn + '-' + Cert + '-' + HCF
        Set<String> currCertSet = new Set<String>(); 

        // Get All Current Cerifications
        for (HCF_Surgeon_Certification__c c : lstExistingCerts) {
            if(!srgnCertMap.containsKey(c.Surgeon__c)){
                srgnCertMap.put(c.Surgeon__c, new Set<Id>());
            }
            
            srgnCertMap.get(c.Surgeon__c).add(c.Certification__c);

            currCertSet.add(c.Surgeon__c + '-' + c.Certification__c + '-' + c.Health_Care_Facility__c);
        }

        // Get All Current Surgeon Relationships
        for (Healthcare_Surgeon_Relationship__c hcf : lstHCFs) {
            if(!srgnHCFMap.containsKey(hcf.Surgeon__c)){
                srgnHCFMap.put(hcf.Surgeon__c, new Set<Id>());
            }
            
            srgnHCFMap.get(hcf.Surgeon__c).add(hcf.Healthcare_Facility__c);
        }

        
        System.debug('There are '+lstUnqSrgns.size() + ' unique surgeons');
        
        System.debug(currCertSet);
        //List<SrgnCertHCF> lstToAdd = new List<SrgnCertHCF>();
        List<HCF_Surgeon_Certification__c> lstToAdd = new List<HCF_Surgeon_Certification__c>();
        List<HCF_Surgeon_Certification__c> lstToDelete = new List<HCF_Surgeon_Certification__c>();

        // Identify List of Certification Records to be created/deleted
        for (String s : lstUnqSrgns) {
            Set<Id> certs = srgnCertMapNeeded.get(s);
            Set<Id> hcfs = srgnHCFMap.get(s);

            if (certs != null) {
                for (String c : certs) {
                    if (hcfs != null) {
                        for (String h : hcfs) {
                            if (!currCertSet.contains(s + '-' + c + '-' + h))
                                lstToAdd.add(new HCF_Surgeon_Certification__c(Surgeon__c=s, Certification__c = c, Health_Care_Facility__c = h));
                        }
                    }
                }
            }
        }

        // Now find the list to delete
        for (HCF_Surgeon_Certification__c c : lstExistingCerts) {
            if (c.Health_Care_Facility__c != null) {
                Set<Id> srgnHCF = srgnHCFMap.get(c.Surgeon__c);

                if(srgnHCF == null || !srgnHCF.contains(c.Health_Care_Facility__c)){
                    System.debug('Did not find Surgeon '+c.Surgeon__c + ' with HCF Facility : '+c.Health_Care_Facility__c+'. It will be deleted');
                    lstToDelete.add(new HCF_Surgeon_Certification__c(Id=c.Id));
                }
            }
        }

        System.debug('Surgeon Certification Records Added : '+lstToAdd.size());
        System.debug('Surgeon Certification Records Deleted : '+lstToDelete.size());

        System.debug(lstToAdd);
        System.debug(lstToDelete);

        if(!lstToAdd.isEmpty()){
            insert lstToAdd;
        }

        if(!lstToDelete.isEmpty()){
            delete lstToDelete;
        }
    }
}