force-app/main/default/objects/iPad_Content_Views__c/iPad_Content_Views__c.object-meta.xml
<CustomObject>
    <label>iPad Content View</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>iPad Content Views Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>iPad Content Views</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/iPad_Content_Views__c/fields/ContentId__c.field-meta.xml
<CustomField>
    <fullName>ContentId__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <externalId>true</externalId>
    <label>ContentId</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/iPad_Content_Views__c/fields/howMuch__c.field-meta.xml
<CustomField>
    <fullName>howMuch__c</fullName>
    <label>howMuch</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/iPadContentViewsBatchScheduler.cls
global class  iPadContentViewsBatchScheduler  implements Schedulable {
	global void execute(SchedulableContext sc) {
      String query='select '
			            + 'Id, ' 
			            + 'ContentId__c, '
			            + 'howMuch__c ' 
			            +  'from iPad_Content_Views__c where howMuch__c >0';  
	  iPadContentViewsBatch ipcvBatch = new iPadContentViewsBatch(query);
      Id batchprocessid = Database.executeBatch(ipcvBatch);	
   }
   
   static testmethod void testSchedule() {
   Test.startTest();
      String jobId = System.schedule('test',
      '0 0 0 3 9 ? 2022', 
         new iPadContentViewsBatchScheduler());

      CronTrigger ct = [SELECT id, CronExpression, TimesTriggered, 
         NextFireTime
         FROM CronTrigger WHERE id = :jobId];
    
      System.assertEquals('0 0 0 3 9 ? 2022', 
         ct.CronExpression);
      System.assertEquals(0, ct.TimesTriggered);
      
      System.assertEquals('2022-09-03 00:00:00', 
         String.valueOf(ct.NextFireTime));

   	 Test.stopTest();
   }
}