force-app/main/default/objects/Data_Extract__c/Data_Extract__c.object-meta.xml
<CustomObject>
    <description>This object will be used for scheduling data extract via Report or SOQL</description>
    <label>Data Extract</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Extract Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Data Extracts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Data_Extract__c/fields/Batch_Job_Id__c.field-meta.xml
<CustomField>
    <fullName>Batch_Job_Id__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Batch Job Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/ScheduleTrendingSnapshotsBatch.cls
global class ScheduleTrendingSnapshotsBatch implements Schedulable { 
    
    global void execute(SchedulableContext sc) {     

        ID dataExtractId;
        Datetime dateNow = Datetime.now();
        String currDateString = dateNow.format(UploadTrendingSnapshotsBatch.DATE_FORMAT_STRING);        
        
        if(!Test.isRunningTest()) {
            for(Data_Extract__c dataExtract : [SELECT Id FROM Data_Extract__c WHERE Batch_Job_Id__c =: sc.getTriggerId()]) {
                updateTimestamp(dataExtract.Id);        
                database.executebatch(new UploadTrendingSnapshotsBatch(null, null, null, 1, null, dataExtract.Id, currDateString), 2000);       
            }
         } else {
            for(Data_Extract__c dataExtract : [SELECT Id FROM Data_Extract__c limit 1]) {
                updateTimestamp(dataExtract.Id);        
                database.executebatch(new UploadTrendingSnapshotsBatch(null, null, null, 1, null, dataExtract.Id, currDateString), 2000);       
            }
        }
    } 
    
    @future 
    public static void updateTimestamp(Id dataExtractId) {  
        Data_Extract__c dataExtract = new Data_Extract__c(Id = dataExtractId, Timestamp__c = Datetime.now());
        update dataExtract;
    }
}