force-app/main/default/objects/ContentVersion/fields/iPad_Content_Views__c.field-meta.xml
<CustomField>
    <fullName>iPad_Content_Views__c</fullName>
    <label>iPad Content Views</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/iPad_Content_Views__c/iPad_Content_Views__c.object-meta.xml
<CustomObject>
    <label>iPad Content View</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>iPad Content Views Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>iPad Content Views</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/iPad_Content_Views__c/fields/ContentId__c.field-meta.xml
<CustomField>
    <fullName>ContentId__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <externalId>true</externalId>
    <label>ContentId</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/iPad_Content_Views__c/fields/howMuch__c.field-meta.xml
<CustomField>
    <fullName>howMuch__c</fullName>
    <label>howMuch</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/iPadContentViewsBatch.cls
/**   
*     iPadContentViewsBatch
*    
*     author:  Shuji Iida
*     date:    Jan 4 2011
*     version: 1.0 
*     
*     speccification:  Defect 2436099 - Content View Counter is not updating if a user has read-only access to the content record
*     author:          Tom G 
*     date:             Jan 4 2011
*     version:          1.0
* 
*     Description: 
*     create a Scheduled Batch Apex job that runs every night at 1:00AM 
*     that reads through each record on the custom object, 
*      and updates the Content records with those values. 
*      These iPad_Content_Views__c records should then be deleted.
**/

global class iPadContentViewsBatch  implements Database.Batchable<sObject>,Database.Stateful
{
    
 
  global final String Query;
   
   global iPadContentViewsBatch(String q){
          Query = q;
   } 

   global Database.QueryLocator start(Database.BatchableContext BC){
   
      return Database.getQueryLocator(Query);
       
   }
  
   global void execute(Database.BatchableContext BC, List<iPad_Content_Views__c> ipadContViewsList)
   {
   /*
         Set<Id> contentIdSet = new Set<Id>(); 
         
         for(iPad_Content_Views__c ipadCon: ipadContViewsList){
            if(ipadCon.ContentId__c!=null){
                contentIdSet.add(ipadCon.ContentId__c);
            }
         } 
         
     List<ContentVersion> contentVersions = [select Id, iPad_Content_Views__c from ContentVersion where Id in :contentIdSet];
     Map<String,ContentVersion> mapOfContentVersions = new Map<String,ContentVersion>();
     for (ContentVersion cv : contentVersions){
         mapOfContentVersions.put(cv.Id,cv);
     }
     
     for(iPad_Content_Views__c ipadConViews: ipadContViewsList){
            ContentVersion conV = mapOfContentVersions.get(ipadConViews.ContentId__c);
            if(conV.iPad_Content_Views__c==null){
               conV.iPad_Content_Views__c=0;
            }
            conV.iPad_Content_Views__c += ipadConViews.howMuch__c;
     }
     List<ContentVersion> listOfContentVersion = mapOfContentVersions.values();
     if(listOfContentVersion.size()>0){
         System.Debug('iPadContentViewsBatch:listOfContentVersion.size()='+listOfContentVersion.size()+'-------------');
         update listOfContentVersion;
     }
      for(iPad_Content_Views__c ipv: ipadContViewsList){
        ipv.howMuch__c=0;
      }
      if(ipadContViewsList.size()>0){
         System.Debug('iPadContentViewsBatch:ipadContViewsList.size()='+ipadContViewsList.size()+'-------------');
         update ipadContViewsList;
      }
    */
    }

   global void finish(Database.BatchableContext BC){
   
   
   }

}