force-app/main/default/objects/Account/recordTypes/Distributor.recordType-meta.xml
<RecordType>
    <fullName>Distributor</fullName>
    <active>true</active>
    <description>A record to keep information about Zimmer Distributors</description>
    <label>Distributor</label>
</RecordType>

force-app/main/default/objects/Contact/fields/AD_Username__c.field-meta.xml
<CustomField>
    <fullName>AD_Username__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>AD Username</label>
    <length>12</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Hire_Date__c.field-meta.xml
<CustomField>
    <fullName>Hire_Date__c</fullName>
    <description>First Day of Employment</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Hire Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Role_Classification__c.field-meta.xml
<CustomField>
    <fullName>Role_Classification__c</fullName>
    <description>This field is used to identify distributor personnel for manpower reporting purposes.</description>
    <label>Role Classification</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>CMF&amp;T</fullName>
            </value>
            <value>
                <fullName>Distributor</fullName>
            </value>
            <value>
                <fullName>Office - Admin</fullName>
            </value>
            <value>
                <fullName>Office - Customer Service Leader</fullName>
            </value>
            <value>
                <fullName>Office - Customer Service Representative</fullName>
            </value>
            <value>
                <fullName>Office - Driver</fullName>
            </value>
            <value>
                <fullName>Office - HR/Compliance</fullName>
            </value>
            <value>
                <fullName>Office - Inventory  Coordinator</fullName>
            </value>
            <value>
                <fullName>Office - Inventory Leader</fullName>
            </value>
            <value>
                <fullName>Office - Operations Leader</fullName>
            </value>
            <value>
                <fullName>Office - Pricing/Contracts</fullName>
            </value>
            <value>
                <fullName>Office - Sourcing/Logistics Coordinator</fullName>
            </value>
            <value>
                <fullName>Office - Sourcing/Logistics Leader</fullName>
            </value>
            <value>
                <fullName>Sales Associate</fullName>
            </value>
            <value>
                <fullName>Sales Manager with accounts</fullName>
            </value>
            <value>
                <fullName>Sales Manager without accounts</fullName>
            </value>
            <value>
                <fullName>Surgery Case Specialist</fullName>
            </value>
            <value>
                <fullName>Zimmer Biomet Canada Office</fullName>
            </value>
            <value>
                <fullName>Zimmer Biomet Canada Recon</fullName>
            </value>
            <value>
                <fullName>Zimmer Biomet Canada Spine</fullName>
            </value>
            <value>
                <fullName>Zimmer Biomet OBT</fullName>
            </value>
            <value>
                <fullName>Zimmer Biomet Spine</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/US_CA_Ivan_Report_Recipient__c/US_CA_Ivan_Report_Recipient__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>US &amp; CA Ivan Report Recipient</description>
    <label>US &amp; CA Ivan Report Recipient</label>
</CustomObject>

force-app/main/default/classes/USReconAndCAIvanSch_Test.cls
@isTest
public class USReconAndCAIvanSch_Test 
{    

     @testSetup static void setup() {
        
        US_CA_Ivan_Report_Recipient__c recp1 = new US_CA_Ivan_Report_Recipient__c();
        recp1.Name = 'Recipient 1';
        recp1.Email__c = 'mohit.gulati@zimmerbiomet.com';
        insert recp1;
    }
    
    public static testMethod void UnitTest01() {
        
        Date dt = date.today().addDays(-7);
        
        list<Contact>contList = new list<Contact>();
        
        //get sales contact record type Id
        Id salescontactrecordtypeId = Schema.SObjectType.Contact.getRecordTypeInfosByName().get('Sales Contact').getRecordTypeId();
        
        Account acc= new Account();
        acc.RecordTypeId = '012800000002ByT';//Distributor Account Rec Type
        acc.Name = 'Test Account';
        insert acc;
        
        for(integer i=0;i<10;i++)
        {
            Contact con = new contact();
            con.FirstName = 'Test';
            con.LastName = 'Record-0'+i;
            con.RecordTypeId = salescontactrecordtypeId;
            con.Role_Classification__c = 'Sales Associate';
            con.AD_Username__c = 'Record-0'+i;
            con.AccountId = acc.Id;
            con.Hire_Date__c = date.today().addDays(-7);
            
            contList.add(con);
        }
        
        insert contList;
        
        Account acct = [select Id,Name from Account where Name=:'Test Account'];
        for(Contact c : [select Id,LastName from Contact where AccountId=:acct.Id])
        {
            system.debug('--c--'+c.LastName);
            Test.setCreatedDate(c.Id, DateTime.newInstance(dt.year(),dt.month(),dt.day()));
        }   
        
        Test.startTest();
        
        USReconAndCAIvan_Scheduler emailSch = new USReconAndCAIvan_Scheduler();
        String sch = '0 0 7 * * ?'; 
        System.schedule('Test USReconAndCAIvan Report', sch, emailSch);
        
        Test.stopTest(); 
        
    }
    
    public static testMethod void UnitTest02() {
        
        Date dt = date.today().addDays(-15);
        
        list<Contact>contList = new list<Contact>();
        
        //get sales contact record type Id
        Id salescontactrecordtypeId = Schema.SObjectType.Contact.getRecordTypeInfosByName().get('Sales Contact').getRecordTypeId();
        
        Account acc= new Account();
        acc.RecordTypeId = '012800000002ByT';//Distributor Account Rec Type
        acc.Name = 'Test Account';
        insert acc;
        
        for(integer i=0;i<10;i++)
        {
            Contact con = new contact();
            con.FirstName = 'Test';
            con.LastName = 'Record-0'+i;
            con.RecordTypeId = salescontactrecordtypeId;
            con.Role_Classification__c = 'Sales Associate';
            con.AD_Username__c = 'Record-0'+i;
            con.AccountId = acc.Id;
            con.Hire_Date__c = date.today().addDays(-15);
            
            contList.add(con);
        }
        
        insert contList;
        
        Account acct = [select Id,Name from Account where Name=:'Test Account'];
        for(Contact c : [select Id,LastName from Contact where AccountId=:acct.Id])
        {
            system.debug('--c--'+c.LastName);
            Test.setCreatedDate(c.Id, DateTime.newInstance(dt.year(),dt.month(),dt.day()));
        }   
        
        Test.startTest();
        
        USReconAndCAIvan_Scheduler emailSch = new USReconAndCAIvan_Scheduler();
        String sch = '0 0 7 * * ?'; 
        System.schedule('Test USReconAndCAIvan Report', sch, emailSch);
        
        Test.stopTest(); 
        
    }
}