force-app/main/default/objects/Discussion_Board__c/Discussion_Board__c.object-meta.xml
<CustomObject>
    <label>Discussion Board</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Discussion Board Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Discussion Boards</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Discussion_Board__c/fields/Discussion_Intro__c.field-meta.xml
<CustomField>
    <fullName>Discussion_Intro__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Discussion Intro</label>
    <length>32000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Discussion_Board__c/fields/Full_Content__c.field-meta.xml
<CustomField>
    <fullName>Full_Content__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Full Content</label>
    <length>32000</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/Discussion_Board__c/fields/Region__c.field-meta.xml
<CustomField>
    <fullName>Region__c</fullName>
    <label>Region</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Americas</fullName>
            </value>
            <value>
                <fullName>EMEA</fullName>
            </value>
            <value>
                <fullName>APAC</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/User/fields/Region__c.field-meta.xml
<CustomField>
    <fullName>Region__c</fullName>
    <description>This field is required-There are workflow and validation rules that uses this field to determine processing path based on the Geography, Business Division and/or Region field(s) setting of the user.</description>
    <inlineHelpText>This field is required-There are workflow and validation rules that uses this field to determine processing path based on the Geography, Business Division and/or Region field(s) setting of the user.</inlineHelpText>
    <label>Region</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>AM</fullName>
            </value>
            <value>
                <fullName>AP</fullName>
            </value>
            <value>
                <fullName>EU</fullName>
            </value>
            <value>
                <fullName>GL</fullName>
            </value>
            <value>
                <fullName>LA</fullName>
            </value>
            <value>
                <fullName>N/A</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/Discussion_Board.cls
public class Discussion_Board
{
/*
Discussion_Board__c[] MyDiscussion;
    //Method to get the Discussion Board from  Discussion_Board__c with respect to user LOB
    
     public List<Discussion_Board__c> getdiscussionDetail() 
     {
     //Checking the provided ID parameter in current page 
     User LOBLIST = [select id,Name,ProfileId from User where Id = :UserInfo.getUserId() Limit 1];

        Profile[] ProfileName = [Select Id, Name from Profile where id =:LOBLIST.ProfileId  ];

        if (ProfileName.size() > 0)
            {
            if (ProfileName [0].Name ==  null)
                {
                ProfileName[0].Name = 'Standard User';
                }
            }
        else 
            {
            ProfileName[0].Name = 'Standard User';
            }
         System.debug('Profile.Name##########' +   ProfileName[0].Name);
        
        Discussion_Board__c[] MultiSelectBull;
          
    string tregion = 'Americas';
    //string tregion;

    if (ProfileName[0].Name.contains('EU'))
    {
      tregion  = 'EMEA';
    }     
    else if (ProfileName[0].Name.contains('ANZ') || ProfileName[0].Name.contains('JPN'))
    {
      tregion  = 'APAC';
    }
    else
    {
      tregion  = 'Americas';
    } 

   MyDiscussion= [select id,Discussion_Intro__c,Full_Content__c ,Name from Discussion_Board__c where Active__c= true and  region__c INCLUDES (:tregion) Order By LastModifiedDate DESC Limit 1];
      
      
        if (MyDiscussion.size() <= 0)
            {
            Discussion_Board__c test = new Discussion_Board__c();
            test.Discussion_Intro__c ='Not Available';
            test.Full_Content__c ='Not Available';
            MyDiscussion.add(test);
            } 
       
   return MyDiscussion;
        //retun the value to the calling page 
   }
   */
}