force-app/main/default/objects/Discussion_Board__c/Discussion_Board__c.object-meta.xml
<CustomObject>
    <label>Discussion Board</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Discussion Board Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Discussion Boards</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Discussion_Board__c/fields/Bulletin_Board_Date__c.field-meta.xml
<CustomField>
    <fullName>Bulletin_Board_Date__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Bulletin Board Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Discussion_Board__c/fields/Full_Content__c.field-meta.xml
<CustomField>
    <fullName>Full_Content__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Full Content</label>
    <length>32000</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/User/fields/Bulletin_Board__c.field-meta.xml
<CustomField>
    <fullName>Bulletin_Board__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Bulletin Board</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/User/fields/Bulletin_Board_Date__c.field-meta.xml
<CustomField>
    <fullName>Bulletin_Board_Date__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Bulletin Board Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/classes/NewDiscussionBoardAvailableTest.cls
@isTest
private class NewDiscussionBoardAvailableTest { 
/*

public static User user_admin{


get{
if(user_admin == null){
Profile p = [SELECT Id FROM profile WHERE name='System Administrator'];
user_admin = new User(alias = 'dB1', email='testUserDB1@testorg.com',
emailencodingkey='UTF-8', lastname='Testing', 
languagelocalekey='en_US',IsActive=true,
localesidkey='en_US', profileid = p.Id,Bulletin_Board__c=true,
timezonesidkey='America/Los_Angeles',username='dB1@testorg.com');
insert user_admin;

}

return user_admin;
}
set;
}


static testMethod void testNewDiscussionBoardAvailableTrigger() {
System.assertEquals(User_admin.Bulletin_Board__c, true);

Discussion_Board__c  NewD = new Discussion_Board__c();
NewD.Name = 'TestDB';
//NewD.CurrencyIsoCode = 'USD - U.S.Dollar';
//NewD.Bulletin_Board_Date__c = Now();
NewD.Full_Content__c='Test';
NewD.Active__c = true;
insert NewD;
System.assertNotEquals(User_admin.Bulletin_Board__c, false);
}
*/
}