force-app/main/default/objects/Account/fields/Account_Picture_Id__c.field-meta.xml
<CustomField>
    <fullName>Account_Picture_Id__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Account Picture Id</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Expertise_Integration_purpose__c.field-meta.xml
<CustomField>
    <fullName>Expertise_Integration_purpose__c</fullName>
    <label>Enterprise Integration purpose</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Anterior Supine</fullName>
            </value>
            <value>
                <fullName>Partial Knee</fullName>
            </value>
            <value>
                <fullName>Patient Specific Instruments</fullName>
            </value>
            <value>
                <fullName>Vanguard</fullName>
            </value>
            <value>
                <fullName>VitaminE</fullName>
            </value>
            <value>
                <fullName>Vivacit-E Hip Construct</fullName>
            </value>
            <value>
                <fullName>XP</fullName>
            </value>
            <value>
                <fullName>Chondrofix</fullName>
            </value>
            <value>
                <fullName>Early Intervention</fullName>
            </value>
            <value>
                <fullName>Gel-One</fullName>
            </value>
            <value>
                <fullName>Persona Knee System</fullName>
            </value>
            <value>
                <fullName>PFJ</fullName>
            </value>
            <value>
                <fullName>Trabecular Metal Total Ankle</fullName>
            </value>
            <value>
                <fullName>Zimmer Unicompartmental Knee</fullName>
            </value>
            <value>
                <fullName>Oxford Partial Knee</fullName>
            </value>
            <value>
                <fullName>Zimmer Biomet Signature Solutions</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Fellowship__c.field-meta.xml
<CustomField>
    <fullName>Fellowship__c</fullName>
    <description>Name of the healthcare facility where surgeon did his/her Fellowship</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>Enter the name of healthcare facility where the surgeon completed their Fellowship</inlineHelpText>
    <label>Fellowship</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/MDM_SAP_ID__c.field-meta.xml
<CustomField>
    <fullName>MDM_SAP_ID__c</fullName>
    <description>The identification number assigned from the DCS/SAP/DPS systems</description>
    <encryptionScheme>None</encryptionScheme>
    <externalId>true</externalId>
    <inlineHelpText>This field identifies the DCS/SAP/DPS ID</inlineHelpText>
    <label>Zimmer Account Number</label>
    <length>12</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Account/fields/Medical_Degree__c.field-meta.xml
<CustomField>
    <fullName>Medical_Degree__c</fullName>
    <description>The listing of a surgeon&apos;s medical degree(s)</description>
    <inlineHelpText>Select the surgeon&apos;s medical degree</inlineHelpText>
    <label>Medical Degree</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>A.U.D.</fullName>
            </value>
            <value>
                <fullName>C.R.P.</fullName>
            </value>
            <value>
                <fullName>D.D.M</fullName>
            </value>
            <value>
                <fullName>D.D.S.</fullName>
            </value>
            <value>
                <fullName>D.M.D.</fullName>
            </value>
            <value>
                <fullName>D.M.D., M.D.</fullName>
            </value>
            <value>
                <fullName>D.O.</fullName>
            </value>
            <value>
                <fullName>D.P.M.</fullName>
            </value>
            <value>
                <fullName>D.V.M</fullName>
            </value>
            <value>
                <fullName>FRACS</fullName>
            </value>
            <value>
                <fullName>FRCS</fullName>
            </value>
            <value>
                <fullName>M.D.</fullName>
            </value>
            <value>
                <fullName>M.D., Ph.D.</fullName>
            </value>
            <value>
                <fullName>MB BS</fullName>
            </value>
            <value>
                <fullName>MSc</fullName>
            </value>
            <value>
                <fullName>N.P.</fullName>
            </value>
            <value>
                <fullName>O.D.</fullName>
            </value>
            <value>
                <fullName>P.A.</fullName>
            </value>
            <value>
                <fullName>P.H.R.</fullName>
            </value>
            <value>
                <fullName>P.S.Y.</fullName>
            </value>
            <value>
                <fullName>Ph.D.</fullName>
            </value>
            <value>
                <fullName>S.W.</fullName>
            </value>
            <value>
                <fullName>VM.D.</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Medical_School__c.field-meta.xml
<CustomField>
    <fullName>Medical_School__c</fullName>
    <description>Name of the medical school where the surgeon did his/her medical studies</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>Enter the surgeon&apos;s medical school name</inlineHelpText>
    <label>Medical School</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Middle_Name__c.field-meta.xml
<CustomField>
    <fullName>Middle_Name__c</fullName>
    <description>Middle initial of surgeon</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Middle Name(Custom)</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Physicians_Locator__c.field-meta.xml
<CustomField>
    <fullName>Physicians_Locator__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Indicates where we recieved the list information</description>
    <inlineHelpText>Check this box if you want to select this list for your mailng</inlineHelpText>
    <label>Physicians Locator</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/fields/Publications_Presentations__c.field-meta.xml
<CustomField>
    <fullName>Publications_Presentations__c</fullName>
    <description>The publications and presentations to which this surgeon was the author or contributor</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>Enter the publications and presentations this surgeon wrote or contributed (max 255 characters)</inlineHelpText>
    <label>Publications and Presentations</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Account/fields/Residency__c.field-meta.xml
<CustomField>
    <fullName>Residency__c</fullName>
    <description>Name of the health care facility where this surgeon did his/her residency</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>Enter the name of the healthcare facility where this surgeon did their residency</inlineHelpText>
    <label>Residency</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Specialty_integration__c.field-meta.xml
<CustomField>
    <fullName>Specialty_integration__c</fullName>
    <label>Specialty integration</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Dental</fullName>
            </value>
            <value>
                <fullName>Elbow</fullName>
            </value>
            <value>
                <fullName>Foot and Ankle</fullName>
            </value>
            <value>
                <fullName>Hand and Wrist</fullName>
            </value>
            <value>
                <fullName>Hip</fullName>
            </value>
            <value>
                <fullName>Knee</fullName>
            </value>
            <value>
                <fullName>Orthopedic</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
            <value>
                <fullName>Pain Medicine</fullName>
            </value>
            <value>
                <fullName>Plastics</fullName>
            </value>
            <value>
                <fullName>Podiatry</fullName>
            </value>
            <value>
                <fullName>Primary Care</fullName>
            </value>
            <value>
                <fullName>Rheumetology</fullName>
            </value>
            <value>
                <fullName>Shoulder</fullName>
            </value>
            <value>
                <fullName>Spine</fullName>
            </value>
            <value>
                <fullName>Sports Medicine</fullName>
            </value>
            <value>
                <fullName>Trauma</fullName>
            </value>
            <value>
                <fullName>Wound Care</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Suffix__c.field-meta.xml
<CustomField>
    <fullName>Suffix__c</fullName>
    <description>A surgeon&apos;s name suffix</description>
    <label>Suffix(Custom)</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Jr.</fullName>
            </value>
            <value>
                <fullName>Sr.</fullName>
            </value>
            <value>
                <fullName>II</fullName>
            </value>
            <value>
                <fullName>III</fullName>
            </value>
            <value>
                <fullName>IV</fullName>
            </value>
            <value>
                <fullName>V</fullName>
            </value>
            <value>
                <fullName>VI</fullName>
            </value>
            <value>
                <fullName>VII</fullName>
            </value>
            <value>
                <fullName>VIII</fullName>
            </value>
            <value>
                <fullName>IX</fullName>
            </value>
            <value>
                <fullName>X</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Technique__c.field-meta.xml
<CustomField>
    <fullName>Technique__c</fullName>
    <description>The techniques commonly used by this surgeon</description>
    <inlineHelpText>Enter the surgery techniques commonly used by this surgeon (max 255 characters)</inlineHelpText>
    <label>Technique</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>MIS</fullName>
            </value>
            <value>
                <fullName>MIS II</fullName>
            </value>
            <value>
                <fullName>MIS Mini</fullName>
            </value>
            <value>
                <fullName>Quad Sparing</fullName>
            </value>
            <value>
                <fullName>PSI</fullName>
            </value>
            <value>
                <fullName>PSI Uni Knee</fullName>
            </value>
            <value>
                <fullName>Anterior Supine Hip</fullName>
            </value>
            <value>
                <fullName>Smart Tools – Knee</fullName>
            </value>
            <value>
                <fullName>Smart Tools – Hip</fullName>
            </value>
            <value>
                <fullName>Mini Hip – Posteriolateral</fullName>
            </value>
            <value>
                <fullName>Mini Hip –Anteriorlateral</fullName>
            </value>
            <value>
                <fullName>Subchondroplasty</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/recordTypes/Practice.recordType-meta.xml
<RecordType>
    <fullName>Practice</fullName>
    <active>true</active>
    <description>A record to keep information about the medical practice(s) to which a surgeon is a member</description>
    <label>Medical Practice</label>
</RecordType>

force-app/main/default/objects/Healthcare_Surgeon_Relationship__c/Healthcare_Surgeon_Relationship__c.object-meta.xml
<CustomObject>
    <label>Account Relationship</label>
    <nameField>
        <displayFormat>{0000}</displayFormat>
        <label>Relationship Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Accounts Relationships</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Healthcare_Surgeon_Relationship__c/fields/Healthcare_Facility__c.field-meta.xml
<CustomField>
    <fullName>Healthcare_Facility__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Healthcare Facility</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Healthcare Facility</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Surgeon Relationship</relationshipLabel>
    <relationshipName>R00N80000002hSSQEA2</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Healthcare_Surgeon_Relationship__c/fields/Surgeon__c.field-meta.xml
<CustomField>
    <fullName>Surgeon__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Surgeon</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Healthcare Facility Relationship</relationshipLabel>
    <relationshipName>Healthcare_Facility_Surgeon</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Practice_Surgeon_Link__c/Practice_Surgeon_Link__c.object-meta.xml
<CustomObject>
    <label>Practice &amp; Surgeon Relationship</label>
    <nameField>
        <displayFormat>{0000}</displayFormat>
        <label>Practice Link Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Practice &amp; Surgeon Relationships</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Practice_Surgeon_Link__c/fields/Practice__c.field-meta.xml
<CustomField>
    <fullName>Practice__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Practice</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Surgeon Relationships</relationshipLabel>
    <relationshipName>R00N80000002Up33EAC</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Practice_Surgeon_Link__c/fields/Surgeon__c.field-meta.xml
<CustomField>
    <fullName>Surgeon__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Surgeon</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Practice Relationships</relationshipLabel>
    <relationshipName>R00N80000002hQEjEAM</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/PhysicianLocatorService.cls
global class PhysicianLocatorService{

    global class Physician {
        WebService String PhysicianId;
        WebService String Salutation;
        WebService String FirstName;
        WebService String MiddleName;
        WebService String LastName;
        WebService String Suffix;
        WebService String Email;
        WebService String OfficeStreet;
        WebService String OfficeCity;
        WebService String OfficeStateOrProvince;
        WebService String OfficePostalCode;
        WebService String OfficeCountry;
        WebService String Graduate;
        WebService Date GraduationDate;
        WebService String Residency;
        WebService Date ResidencyDate;
        WebService String Fellowship;  
        WebService Date FellowshipDate;
        WebService String MIS; 
        WebService String SpecialInterest;
        WebService String MedicalDegree; 
        WebService String Specialties;
        WebService String SubSpecialties;
        WebService String Publications;
        WebService String Awards;
        WebService Decimal YearsPracticing;
        WebService String Languages;
        WebService String OfficeLocations;
        WebService String Gender;
        WebService String PictureID;        
        WebService String FacebookUrl;
        WebService String TwitterId;
        WebService String LinkedInUrl;
        WebService String JobTitle;
        WebService list<Hospital> HospitalAffiliations;
        WebService list<MedicalPractice> MedicalPractices;
    }
    
    global class PhysicianLocatorSearchCriteria {
        WebService list<String> ZipCodes;
        WebService String City;
        WebService String State;
        WebService String FirstName;
        WebService String LastName;
        WebService String Specialty;
        WebService String MedicalPracticeName;
        WebService String PhysicianId;
        WebService String MedicalPracticeId;
    }
    
    global class MedicalPractice {
        WebService String Id;
        WebService String Name;
        WebService String Street;
        WebService String City;
        WebService String State;
        WebService string Country;
        WebService String PostalCode; 
        WebService String Phone;
        WebService String Fax;
        WebService String WebSite;
    }
    
    global class Hospital {
        WebService String Id;
        WebService String Name;
        WebService String City;
        WebService String State;
        WebService String Country;
    }
    global class Photo {
        WebService Blob Body;
        WebService Integer BodyLength;
        WebService String ContentType;
    }
    
    WebService static list<Physician> searchByZipCode(list<String> zipCodes){
        String query = buildQuery(zipCodes, null, null, null, null, null, null, null, null);
        return performSearch(query);
    }
    
    WebService static list<Physician> searchByCityState(String city, String state){
        String query = buildQuery(null, city, state, null, null, null, null, null, null);
        return performSearch(query);
    }
    
    WebService static Physician searchById(String medicalPracticeId, String physicianId){
        String query = buildQuery(null, null, null, null, null, null, null, physicianId, medicalPracticeId);
        list<Physician> results = performSearch(query);
        if (results.isEmpty()){
            return null;
        }else{
            return results.get(0);
        }
    }
    
    WebService static list<Physician> search(PhysicianLocatorSearchCriteria criteria){
        String query = buildQuery(criteria);
        return performSearch(query);
    }
    
    WebService static Photo getPhysicianPhoto(String id){
        Photo photo = null;
        try {
            Attachment a = [select Body, ContentType, BodyLength from Attachment where Id = :id];
            if (a != null){
                photo = new Photo();
                photo.Body = a.Body;
                photo.BodyLength = a.BodyLength;
                photo.ContentType = a.ContentType;
            }
        } catch (System.Queryexception ex){
            
        }
        return photo;
        
    }
    
    private static list<Physician> performSearch(String query){
        list<Practice_Surgeon_Link__c> surgeons = Database.query(query);
        list<String> surgeonIds = new list<String>();
        for (Practice_Surgeon_Link__c surgeon : surgeons){
            surgeonIds.add(surgeon.Surgeon__c);
        }
        //list<Healthcare_Surgeon_Relationship__c> surgeonHealthcareFacilities = listHealthcareFacilitiesBySurgeon(surgeons);
        map<ID, list<MedicalPractice>> practicesBySurgeon = listMedicalPracticesBySurgeon(surgeonIds);
        map<ID, list<Hospital>> hospitalsBySurgeon = listHealthcareFacilitiesBySurgeon(surgeonIds);
        map<ID,Physician> physicians = new map<ID,Physician>();
        for (Practice_Surgeon_Link__c surgeon : surgeons){
            Physician physician = physicians.get(surgeon.Surgeon__c);
            if (physician == null){
                physician = createPhysician(surgeon); 
                physician.MedicalPractices = practicesBySurgeon.get(surgeon.Surgeon__c);
                physician.HospitalAffiliations = hospitalsBySurgeon.get(surgeon.Surgeon__c);
                physicians.put(surgeon.Surgeon__c, physician);
            }
        }
        return physicians.values();
    }
    
    private static map<ID, list<MedicalPractice>> listMedicalPracticesBySurgeon(list<String> surgeonIds){
        map<ID, list<MedicalPractice>> output = new map<ID, list<MedicalPractice>>();
        list<Practice_Surgeon_Link__c> relationships = new list<Practice_Surgeon_Link__c>();
        relationships = [ select id, Practice__c, Practice__r.Name, Practice__r.ShippingCity,
                      Practice__r.ShippingCountry, Practice__r.ShippingPostalCode,
                      Practice__r.ShippingState, Practice__r.ShippingStreet, Practice__r.Website,
                      Practice__r.Phone, Practice__r.Fax, Surgeon__c
                 from Practice_Surgeon_Link__c
                 where Surgeon__c IN :surgeonIds
                 limit 2000]; 
        for (Practice_Surgeon_Link__c relationship : relationships){
            list<MedicalPractice> practices = output.get(relationship.Surgeon__c);
            if (practices == null){
                practices = new list<MedicalPractice>();
            }  
            practices.add(createMedicalPractice(relationship));
            output.put(relationship.Surgeon__c, practices);
        }     
        return output;
    }
    
    private static map<ID, list<Hospital>> listHealthcareFacilitiesBySurgeon(list<String> surgeons){
        map<ID, list<Hospital>> output = new map<ID, list<Hospital>>();
        list<Healthcare_Surgeon_Relationship__c> relationships = new list<Healthcare_Surgeon_Relationship__c>();
        relationships = [ select id,Healthcare_Facility__c,Healthcare_Facility__r.Name,
                        Healthcare_Facility__r.ShippingCity,Healthcare_Facility__r.ShippingCountry,                                                           
                        Healthcare_Facility__r.ShippingState,Surgeon__c
                 from Healthcare_Surgeon_Relationship__c
                 where Surgeon__c IN :surgeons
                 limit 2000];      
        for (Healthcare_Surgeon_Relationship__c relationship : relationships){
            list<Hospital> hospitals = output.get(relationship.Surgeon__c);
            if (hospitals == null){
                hospitals = new list<Hospital>();
            }
            Hospital hospital = new Hospital();
            hospital.Name = relationship.Healthcare_Facility__r.Name;
            hospital.City = relationship.Healthcare_Facility__r.ShippingCity;
            hospital.State = relationship.Healthcare_Facility__r.ShippingState;
            hospital.Country = relationship.Healthcare_Facility__r.ShippingCountry;    
            hospitals.add(hospital);
            output.put(relationship.Surgeon__c, hospitals);
        }     
        return output;
    }
    
    private static String buildQuery(PhysicianLocatorSearchCriteria criteria){
        return buildQuery(criteria.ZipCodes, criteria.City, criteria.State, criteria.FirstName, criteria.LastName,
                          criteria.Specialty, criteria.MedicalPracticeName, criteria.PhysicianId, criteria.MedicalPracticeId);
    }
    
    private static String buildQuery(list<String> zipCodes, String city, String state, String firstName, 
                                     String lastName, String specialty, String practiceName, String physicianId,
                                     String medicalPracticeId ) {
        String query = 'select id, Surgeon__c, Surgeon__r.FirstName, ' +
                       'Surgeon__r.Middle_Name__c, Surgeon__r.LastName, Surgeon__r.Suffix__c, ' +
                       'Surgeon__r.Technique__c, Surgeon__r.Expertise_integration_purpose__c, ' +
                       'Surgeon__r.Medical_School__c, Surgeon__r.Residency__c, Surgeon__r.Fellowship__c,' +
                       'Surgeon__r.Medical_Degree__c, Surgeon__r.Specialty_Integration__c, ' +
                       'Surgeon__r.PersonMailingCity, Surgeon__r.PersonMailingCountry, ' +
                       'Surgeon__r.PersonMailingPostalCode, Surgeon__r.PersonMailingState, ' +
                       'Surgeon__r.PersonMailingStreet, Surgeon__r.MDM_SAP_ID__c, ' + 
                       'Surgeon__r.Physicians_Locator__c, Surgeon__r.Account_Picture_Id__c, ' +
                       'Surgeon__r.Publications_Presentations__c, Surgeon__r.Awards_Honors_Patents__c, ' +
                       'Surgeon__r.Years_experienced__c, Surgeon__r.Languages__c, Surgeon__r.Gender__c, ' +
                       'Surgeon__r.PersonEmail, Surgeon__r.Med_Grad_Date__c, Surgeon__r.Residency_Completion_Date__c, ' +
                       'Surgeon__r.Fellowship_Completion_Date__c, Surgeon__r.Salutation, Surgeon__r.Facebook_URL__c, ' +
                       'Surgeon__r.Twitter_ID__c, Surgeon__r.LinkedInURL__c, Surgeon__r.PersonTitle,  ' +
                       'Surgeon__r.Surgical_Interests__c ' +
                       'from Practice_Surgeon_Link__c ' + 
                       'where Surgeon__r.Physicians_Locator__c = true ';
        if ((zipCodes != null) && !(zipCodes.isEmpty())){
            boolean first = true;
            String values = '';
            for (String zipCode : zipCodes){
                if (zipCode != null && zipCode.trim().length() > 0){
                    if (!first){
                        values += ', ';
                    }           
                    values += '\''+ zipCode +'\'';
                    first = false;
                }
            }
            if (values.length() > 0){
                query += ' and Practice__r.ShippingPostalCode in (' + values + ')';
            }
        }   
        if (city != null && city.trim().length() > 0) {
            query += ' and Practice__r.ShippingCity = \'' + String.escapeSingleQuotes(city) + '\'';
        }                  
        if (state != null && state.trim().length() > 0) {
            query += ' and Practice__r.ShippingState = \'' + String.escapeSingleQuotes(state) + '\'';
        }
        if (firstName != null && firstName.trim().length() > 0) {
            query += ' and Surgeon__r.FirstName like \'%' + String.escapeSingleQuotes(firstName) + '%\'';
        }
        if (lastName != null && lastName.trim().length() > 0) {
            query += ' and Surgeon__r.LastName like \'%' + String.escapeSingleQuotes(lastName) + '%\'';
        }
        if (specialty != null && specialty.trim().length() > 0){
            query += ' and Surgeon__r.Specialty_Integration__c includes (\'' + String.escapeSingleQuotes(specialty) + '\')';
        }
        if (practiceName != null && practiceName.trim().length() > 0){
            query += ' and Practice__r.Name like \'%' + String.escapeSingleQuotes(practiceName) + '%\'';
        }
        if (physicianId != null && physicianId.trim().length() > 0){
            query += ' and Surgeon__c = \'' + String.escapeSingleQuotes(physicianId) + '\'';
        }
        if (medicalPracticeId != null && medicalPracticeId.trim().length() > 0){
            query += ' and Practice__c = \'' + String.escapeSingleQuotes(medicalPracticeId) + '\'';
        }
        query += ' limit 999';
        return query;
    }       
    
    private static Physician createPhysician(Practice_Surgeon_Link__c surgeon){
        Physician physician = new Physician();
        physician.PhysicianId = surgeon.Surgeon__c;
        physician.Salutation = surgeon.Surgeon__r.Salutation;
        physician.FirstName = surgeon.Surgeon__r.FirstName;
        physician.MiddleName = surgeon.Surgeon__r.Middle_Name__c;
        physician.LastName = surgeon.Surgeon__r.LastName;
        physician.Suffix = surgeon.Surgeon__r.Suffix__c;
        physician.Email = surgeon.Surgeon__r.PersonEmail;
        physician.OfficeStreet = surgeon.Surgeon__r.PersonMailingStreet;
        physician.OfficeCity = surgeon.Surgeon__r.PersonMailingCity;
        physician.OfficeStateOrProvince = surgeon.Surgeon__r.PersonMailingState;
        physician.OfficePostalCode = surgeon.Surgeon__r.PersonMailingPostalCode;
        physician.OfficeCountry = surgeon.Surgeon__r.PersonMailingCountry;
        physician.Graduate = surgeon.Surgeon__r.Medical_School__c;
        physician.GraduationDate = surgeon.Surgeon__r.Med_Grad_Date__c;
        physician.Residency = surgeon.Surgeon__r.Residency__c;
        physician.ResidencyDate = surgeon.Surgeon__r.Residency_Completion_Date__c;
        physician.Fellowship = surgeon.Surgeon__r.Fellowship__c;
        physician.FellowshipDate = surgeon.Surgeon__r.Fellowship_Completion_Date__c;  
        physician.MIS = surgeon.Surgeon__r.Technique__c; 
        physician.SpecialInterest = surgeon.Surgeon__r.Expertise_integration_purpose__c;
        physician.MedicalDegree = surgeon.Surgeon__r.Medical_Degree__c; 
        physician.Specialties = surgeon.Surgeon__r.Specialty_Integration__c;
        physician.SubSpecialties = surgeon.Surgeon__r.Surgical_Interests__c;
        physician.Publications = surgeon.Surgeon__r.Publications_Presentations__c;
        physician.Awards = surgeon.Surgeon__r.Awards_Honors_Patents__c;
        physician.YearsPracticing = surgeon.Surgeon__r.Years_experienced__c;
        physician.Languages = surgeon.Surgeon__r.Languages__c;
        physician.OfficeLocations = '';
        physician.Gender = surgeon.Surgeon__r.Gender__c;
        physician.PictureID = surgeon.Surgeon__r.Account_Picture_Id__c;
        physician.FacebookUrl = surgeon.Surgeon__r.Facebook_URL__c;
        physician.TwitterId = surgeon.Surgeon__r.Twitter_ID__c;
        physician.LinkedInUrl = surgeon.Surgeon__r.LinkedInURL__c;
        physician.JobTitle = surgeon.Surgeon__r.PersonTitle;
        return physician;
    }
    
    private static MedicalPractice createMedicalPractice(Practice_Surgeon_Link__c surgeon){
        MedicalPractice practice = new MedicalPractice();
        practice.Id = surgeon.Practice__c;
        practice.Name = surgeon.Practice__r.Name;
        practice.Street = surgeon.Practice__r.ShippingStreet;
        practice.City = surgeon.Practice__r.ShippingCity;
        practice.State = surgeon.Practice__r.ShippingState;
        practice.Country = surgeon.Practice__r.ShippingCountry;
        practice.PostalCode = surgeon.Practice__r.ShippingPostalCode; 
        practice.Phone = surgeon.Practice__r.Phone;
        practice.Fax = surgeon.Practice__r.Fax;
        practice.WebSite = surgeon.Practice__r.Website;
        return practice;
    }
    
    static testMethod void testAll(){
        list<String> zipCodes = new list<String>();
        zipCodes.add('19107');
        zipCodes.add('19145');
        zipCodes.add('08080');
        test.startTest();
        Boolean result = false;
        list<Physician> zipPhysicians = searchByZipCode(zipCodes);
        if (zipPhysicians.size() > 0){
            Physician p = zipPhysicians.get(0);
            MedicalPractice mp = p.MedicalPractices.get(0);
            list<Physician> csPhysicians = searchByCityState(mp.City, mp.State);
            Physician pById = searchById(mp.Id, p.PhysicianId);
            PhysicianLocatorSearchCriteria criteria = new PhysicianLocatorSearchCriteria();
            //criteria.FirstName = p.FirstName;
            //criteria.LastName = p.LastName;
            //citeria.City = mp.City;
            criteria.State = mp.State;
            //criteria.Specialty = p.Specialties;
            list<Physician> freePs = search(criteria);  
            String names = '';
            for (Physician x : zipPhysicians){
                names += x.FirstName + ' ' + x.LastName + '\n';
            }
            system.debug('--------ZIP CODE RESULTS--------------');
            system.debug(names);
            names = '';
            for (Physician x : csPhysicians){
                names += x.FirstName + ' ' + x.LastName + '\n';
            }
            system.debug('--------CITY STATE RESULTS------------');
            system.debug(names);
            
            system.debug('--------BY ID RESULTS------------------');
            system.debug(pById.FirstName + ' ' + pById.LastName);
            
            names = '';
            for (Physician x : freePs){
                names += x.FirstName + ' ' + x.LastName + '\n';
            }
            System.debug('---------------------------------------------->>>' + freePs.size());
            System.debug('---------------FREE SEARCH RESULTS----------------');
            system.debug(names);
            
            result = ((csPhysicians.size() > 0) && (pById != null));     
        }
        test.stopTest();
        System.assert(result);
    }
}