force-app/main/default/objects/Account/fields/Account_Picture_Id__c.field-meta.xml
<CustomField>
    <fullName>Account_Picture_Id__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Account Picture Id</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Awards_Honors_Patents__c.field-meta.xml
<CustomField>
    <fullName>Awards_Honors_Patents__c</fullName>
    <description>The awards, honors and patents given to this surgeon</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>Enter the earned awards, honors and patents received by  this surgeon</inlineHelpText>
    <label>Awards, Honors, Patents</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Account/fields/Expertise_Integration_purpose__c.field-meta.xml
<CustomField>
    <fullName>Expertise_Integration_purpose__c</fullName>
    <label>Enterprise Integration purpose</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Anterior Supine</fullName>
            </value>
            <value>
                <fullName>Partial Knee</fullName>
            </value>
            <value>
                <fullName>Patient Specific Instruments</fullName>
            </value>
            <value>
                <fullName>Vanguard</fullName>
            </value>
            <value>
                <fullName>VitaminE</fullName>
            </value>
            <value>
                <fullName>Vivacit-E Hip Construct</fullName>
            </value>
            <value>
                <fullName>XP</fullName>
            </value>
            <value>
                <fullName>Chondrofix</fullName>
            </value>
            <value>
                <fullName>Early Intervention</fullName>
            </value>
            <value>
                <fullName>Gel-One</fullName>
            </value>
            <value>
                <fullName>Persona Knee System</fullName>
            </value>
            <value>
                <fullName>PFJ</fullName>
            </value>
            <value>
                <fullName>Trabecular Metal Total Ankle</fullName>
            </value>
            <value>
                <fullName>Zimmer Unicompartmental Knee</fullName>
            </value>
            <value>
                <fullName>Oxford Partial Knee</fullName>
            </value>
            <value>
                <fullName>Zimmer Biomet Signature Solutions</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Fellowship__c.field-meta.xml
<CustomField>
    <fullName>Fellowship__c</fullName>
    <description>Name of the healthcare facility where surgeon did his/her Fellowship</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>Enter the name of healthcare facility where the surgeon completed their Fellowship</inlineHelpText>
    <label>Fellowship</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Gender__c.field-meta.xml
<CustomField>
    <fullName>Gender__c</fullName>
    <description>The gender of the surgeon or consumer</description>
    <label>Gender</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Female</fullName>
            </value>
            <value>
                <fullName>Male</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Languages__c.field-meta.xml
<CustomField>
    <fullName>Languages__c</fullName>
    <description>The languages a surgeon speaks</description>
    <inlineHelpText>Select the languages a surgeon speaks proficiently</inlineHelpText>
    <label>Languages</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>English</fullName>
                <default>true</default>
                <label>English</label>
            </value>
            <value>
                <fullName>French</fullName>
            </value>
            <value>
                <fullName>German</fullName>
            </value>
            <value>
                <fullName>Spanish</fullName>
            </value>
            <value>
                <fullName>Chinese</fullName>
            </value>
            <value>
                <fullName>Hebrew</fullName>
            </value>
            <value>
                <fullName>Russian</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Medical_Degree__c.field-meta.xml
<CustomField>
    <fullName>Medical_Degree__c</fullName>
    <description>The listing of a surgeon&apos;s medical degree(s)</description>
    <inlineHelpText>Select the surgeon&apos;s medical degree</inlineHelpText>
    <label>Medical Degree</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>A.U.D.</fullName>
            </value>
            <value>
                <fullName>C.R.P.</fullName>
            </value>
            <value>
                <fullName>D.D.M</fullName>
            </value>
            <value>
                <fullName>D.D.S.</fullName>
            </value>
            <value>
                <fullName>D.M.D.</fullName>
            </value>
            <value>
                <fullName>D.M.D., M.D.</fullName>
            </value>
            <value>
                <fullName>D.O.</fullName>
            </value>
            <value>
                <fullName>D.P.M.</fullName>
            </value>
            <value>
                <fullName>D.V.M</fullName>
            </value>
            <value>
                <fullName>FRACS</fullName>
            </value>
            <value>
                <fullName>FRCS</fullName>
            </value>
            <value>
                <fullName>M.D.</fullName>
            </value>
            <value>
                <fullName>M.D., Ph.D.</fullName>
            </value>
            <value>
                <fullName>MB BS</fullName>
            </value>
            <value>
                <fullName>MSc</fullName>
            </value>
            <value>
                <fullName>N.P.</fullName>
            </value>
            <value>
                <fullName>O.D.</fullName>
            </value>
            <value>
                <fullName>P.A.</fullName>
            </value>
            <value>
                <fullName>P.H.R.</fullName>
            </value>
            <value>
                <fullName>P.S.Y.</fullName>
            </value>
            <value>
                <fullName>Ph.D.</fullName>
            </value>
            <value>
                <fullName>S.W.</fullName>
            </value>
            <value>
                <fullName>VM.D.</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Medical_School__c.field-meta.xml
<CustomField>
    <fullName>Medical_School__c</fullName>
    <description>Name of the medical school where the surgeon did his/her medical studies</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>Enter the surgeon&apos;s medical school name</inlineHelpText>
    <label>Medical School</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Middle_Name__c.field-meta.xml
<CustomField>
    <fullName>Middle_Name__c</fullName>
    <description>Middle initial of surgeon</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Middle Name(Custom)</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Physicians_Locator__c.field-meta.xml
<CustomField>
    <fullName>Physicians_Locator__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Indicates where we recieved the list information</description>
    <inlineHelpText>Check this box if you want to select this list for your mailng</inlineHelpText>
    <label>Physicians Locator</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/fields/Publications_Presentations__c.field-meta.xml
<CustomField>
    <fullName>Publications_Presentations__c</fullName>
    <description>The publications and presentations to which this surgeon was the author or contributor</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>Enter the publications and presentations this surgeon wrote or contributed (max 255 characters)</inlineHelpText>
    <label>Publications and Presentations</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Account/fields/Residency__c.field-meta.xml
<CustomField>
    <fullName>Residency__c</fullName>
    <description>Name of the health care facility where this surgeon did his/her residency</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>Enter the name of the healthcare facility where this surgeon did their residency</inlineHelpText>
    <label>Residency</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Specialty_integration__c.field-meta.xml
<CustomField>
    <fullName>Specialty_integration__c</fullName>
    <label>Specialty integration</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Dental</fullName>
            </value>
            <value>
                <fullName>Elbow</fullName>
            </value>
            <value>
                <fullName>Foot and Ankle</fullName>
            </value>
            <value>
                <fullName>Hand and Wrist</fullName>
            </value>
            <value>
                <fullName>Hip</fullName>
            </value>
            <value>
                <fullName>Knee</fullName>
            </value>
            <value>
                <fullName>Orthopedic</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
            <value>
                <fullName>Pain Medicine</fullName>
            </value>
            <value>
                <fullName>Plastics</fullName>
            </value>
            <value>
                <fullName>Podiatry</fullName>
            </value>
            <value>
                <fullName>Primary Care</fullName>
            </value>
            <value>
                <fullName>Rheumetology</fullName>
            </value>
            <value>
                <fullName>Shoulder</fullName>
            </value>
            <value>
                <fullName>Spine</fullName>
            </value>
            <value>
                <fullName>Sports Medicine</fullName>
            </value>
            <value>
                <fullName>Trauma</fullName>
            </value>
            <value>
                <fullName>Wound Care</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Suffix__c.field-meta.xml
<CustomField>
    <fullName>Suffix__c</fullName>
    <description>A surgeon&apos;s name suffix</description>
    <label>Suffix(Custom)</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Jr.</fullName>
            </value>
            <value>
                <fullName>Sr.</fullName>
            </value>
            <value>
                <fullName>II</fullName>
            </value>
            <value>
                <fullName>III</fullName>
            </value>
            <value>
                <fullName>IV</fullName>
            </value>
            <value>
                <fullName>V</fullName>
            </value>
            <value>
                <fullName>VI</fullName>
            </value>
            <value>
                <fullName>VII</fullName>
            </value>
            <value>
                <fullName>VIII</fullName>
            </value>
            <value>
                <fullName>IX</fullName>
            </value>
            <value>
                <fullName>X</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Technique__c.field-meta.xml
<CustomField>
    <fullName>Technique__c</fullName>
    <description>The techniques commonly used by this surgeon</description>
    <inlineHelpText>Enter the surgery techniques commonly used by this surgeon (max 255 characters)</inlineHelpText>
    <label>Technique</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>MIS</fullName>
            </value>
            <value>
                <fullName>MIS II</fullName>
            </value>
            <value>
                <fullName>MIS Mini</fullName>
            </value>
            <value>
                <fullName>Quad Sparing</fullName>
            </value>
            <value>
                <fullName>PSI</fullName>
            </value>
            <value>
                <fullName>PSI Uni Knee</fullName>
            </value>
            <value>
                <fullName>Anterior Supine Hip</fullName>
            </value>
            <value>
                <fullName>Smart Tools – Knee</fullName>
            </value>
            <value>
                <fullName>Smart Tools – Hip</fullName>
            </value>
            <value>
                <fullName>Mini Hip – Posteriolateral</fullName>
            </value>
            <value>
                <fullName>Mini Hip –Anteriorlateral</fullName>
            </value>
            <value>
                <fullName>Subchondroplasty</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Years_experienced__c.field-meta.xml
<CustomField>
    <fullName>Years_experienced__c</fullName>
    <description>The number of years of experience of a surgeon from his/her date of medical school graduation</description>
    <formula>YEAR( TODAY()) -YEAR( Med_Grad_Date__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>The number of years of experience a surgeon has since their medical school graduation</inlineHelpText>
    <label>Years of experience</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Practice_Surgeon_Link__c/Practice_Surgeon_Link__c.object-meta.xml
<CustomObject>
    <label>Practice &amp; Surgeon Relationship</label>
    <nameField>
        <displayFormat>{0000}</displayFormat>
        <label>Practice Link Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Practice &amp; Surgeon Relationships</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Practice_Surgeon_Link__c/fields/Surgeon__c.field-meta.xml
<CustomField>
    <fullName>Surgeon__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Surgeon</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Practice Relationships</relationshipLabel>
    <relationshipName>R00N80000002hQEjEAM</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/GplConvertAccountsBatchJobScheduler.cls
global class GplConvertAccountsBatchJobScheduler implements Schedulable {
	global void execute(SchedulableContext sc){
		String query = 'select id, Surgeon__c, Surgeon__r.FirstName, ' +
					   'Surgeon__r.Middle_Name__c, Surgeon__r.LastName, Surgeon__r.Suffix__c, ' +
					   'Surgeon__r.Technique__c, Surgeon__r.Expertise_integration_purpose__c, ' +
					   'Surgeon__r.Medical_School__c, Surgeon__r.Residency__c, Surgeon__r.Fellowship__c,' +
					   'Surgeon__r.Medical_Degree__c, Surgeon__r.Specialty_Integration__c, ' +
					   'Surgeon__r.Physicians_Locator__c, Surgeon__r.Account_Picture_Id__c, ' +
					   'Surgeon__r.Publications_Presentations__c, Surgeon__r.Awards_Honors_Patents__c, ' +
					   'Surgeon__r.Years_experienced__c, Surgeon__r.Languages__c, Surgeon__r.Gender__c, ' +
					   'Surgeon__r.Med_Grad_Date__c, Surgeon__r.Residency_Completion_Date__c, ' +
					   'Surgeon__r.Fellowship_Completion_Date__c, Surgeon__r.Salutation, Surgeon__r.PersonTitle, Practice__r.Name, ' +
					   'Surgeon__r.Surgical_Interests__c, Practice__r.ShippingState, Practice__r.ShippingPostalCode, ' +
					   'Surgeon__r.Memberships_Associations_Conferences__c, ' +
				   	   'Practice__r.ShippingCountry, Practice__r.Phone, Practice__r.Fax, Practice__r.Website, ' +
				   	   'Practice__r.ShippingStreet, Practice__r.ShippingCity, Practice__r.RecordTypeId, Surgeon__r.IsPersonAccount ' +
					   'from Practice_Surgeon_Link__c ' + 
					   'where Surgeon__r.Physicians_Locator__c = true ';
	   	GplConvertAccountsBatchJob job = new GplConvertAccountsBatchJob();
	   	job.query = query;
	   	Database.executeBatch(job,1);
	}
	
	static testmethod void testGplGeocodeAccountsBatchJobScheduler1(){
		Test.startTest();
		GplConvertAccountsBatchJobScheduler job = new GplConvertAccountsBatchJobScheduler();
        Datetime dt = Datetime.now().addMinutes(1);
        String cron = '0 ' + dt.minute() + ' * ' + dt.day() + ' ' + dt.month() + ' ' + ' ? ' + dt.year();
        System.schedule('Schedule', cron, job);
		Test.stopTest();
	}
}