force-app/main/default/objects/Account/fields/AcctInactive__c.field-meta.xml
<CustomField>
    <fullName>AcctInactive__c</fullName>
    <defaultValue>false</defaultValue>
    <description>This field indicates if the Account is Active or Inactive</description>
    <label>AcctInactive</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/fields/MDM_SAP_ID__c.field-meta.xml
<CustomField>
    <fullName>MDM_SAP_ID__c</fullName>
    <description>The identification number assigned from the DCS/SAP/DPS systems</description>
    <encryptionScheme>None</encryptionScheme>
    <externalId>true</externalId>
    <inlineHelpText>This field identifies the DCS/SAP/DPS ID</inlineHelpText>
    <label>Zimmer Account Number</label>
    <length>12</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Insurance_Verification__c/Insurance_Verification__c.object-meta.xml
<CustomObject>
    <description>For use with the Reimbursement Hotline Project.</description>
    <label>Insurance Verification/Access to Care</label>
    <nameField>
        <displayFormat>IV/ATC-{000000}</displayFormat>
        <label>IV/ATC Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Insurance Verification/Access to Care</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Insurance_Verification__c/fields/Date_Initiated__c.field-meta.xml
<CustomField>
    <fullName>Date_Initiated__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Date Initiated</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Insurance_Verification__c/fields/Patient__c.field-meta.xml
<CustomField>
    <fullName>Patient__c</fullName>
    <label>Patient</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Consumer</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipName>Insurance_Verifications1</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/insuranceVerificationTestSuite.cls
@isTest
private class insuranceVerificationTestSuite{

     public Static ApexPages.StandardController insuranceController;
     public Static insuranceVerificationPDFAttacher2 insuranceVerification;
     public static Insurance_Verification__c insurance;
     public Static Account patient;
     
     public Static void createSampleData(){
     
        patient= new Account();
        //ID recordTypeId3 = [select id from RecordType where SObjectType = 'Account' and IsActive = true and Name = 'Consumer'].id;
        ID recordTypeId3 = [select id from RecordType where SObjectType = 'Account' and IsActive = true and DeveloperName = 'Consumer'].id;
        patient.LastName='Account Attendee 1 Test';
        patient.AcctInactive__c= false;
        patient.FirstName='Test';
        patient.RecordTypeId=recordTypeId3;
        patient.MDM_SAP_ID__c='7865';
        patient.PersonMailingCountry='US';
        patient.PersonMailingState='CA';
        patient.PersonMailingStreet='Test1 Line1'+'\n'+'Mailing line2'+'\n'+'Mailing line3';
        patient.PersonMailingCity='LA';
        patient.PersonMailingPostalCode='10106';
        
        insert patient;
        
        insurance = new Insurance_Verification__c();
        //insurance.Name = 'Test Insurance';
        insurance.Patient__c = patient.id;
         insurance.Date_Initiated__c =Date.newInstance(2018, 05, 9);
        insert insurance;
     
     } 

      private Static Void initInsuranceVerification(){
      
       createSampleData();
       //insuranceController = new ApexPages.StandardController(insurance);
       
      
      }
      
      public Static testmethod void insuranceVerificationEmailTest(){
      initInsuranceVerification();
      test.StartTest();
      
          insuranceVerificationPDFAttacher2 insuranceVerification1 = new insuranceVerificationPDFAttacher2(); 
          insuranceVerification1.toEmail = 'naveen.chugh@zimmer.com';
          insuranceVerification1.ccEmail = 'naveen.chugh@zimmer.com';
          Apexpages.currentPage().getParameters().put('id',insurance.id);
          insuranceVerification1.sendEmail();
          insuranceVerification1.ccEmail = 'naveen.chugh@zimme';
          insuranceVerification1.toEmail = 'naveen.chugh@zimom';
          insuranceVerification1.checkRequiredFieldsSave();
          insuranceVerification1.toEmail = '';
          insuranceVerification1.checkRequiredFieldsSave();
      
      test.StopTest();
      
      }


}