force-app/main/default/objects/Account/fields/AcctInactive__c.field-meta.xml
<CustomField>
    <fullName>AcctInactive__c</fullName>
    <defaultValue>false</defaultValue>
    <description>This field indicates if the Account is Active or Inactive</description>
    <label>AcctInactive</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/fields/Deactive_Date__c.field-meta.xml
<CustomField>
    <fullName>Deactive_Date__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>Date this account was inactivated as a customer</inlineHelpText>
    <label>Deactive Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Account/fields/External_ID__c.field-meta.xml
<CustomField>
    <fullName>External_ID__c</fullName>
    <description>Used to house external customer reference ID in the US for AMA Surgeon ME#</description>
    <encryptionScheme>None</encryptionScheme>
    <externalId>true</externalId>
    <label>External ID</label>
    <length>50</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Account/fields/MDM_SAP_ID__c.field-meta.xml
<CustomField>
    <fullName>MDM_SAP_ID__c</fullName>
    <description>The identification number assigned from the DCS/SAP/DPS systems</description>
    <encryptionScheme>None</encryptionScheme>
    <externalId>true</externalId>
    <inlineHelpText>This field identifies the DCS/SAP/DPS ID</inlineHelpText>
    <label>Zimmer Account Number</label>
    <length>12</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Account/fields/Refer_To__c.field-meta.xml
<CustomField>
    <fullName>Refer_To__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>Refer&apos;s to the active account.</inlineHelpText>
    <label>Refer To</label>
    <length>12</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Refer_To_SFDC_Id__c.field-meta.xml
<CustomField>
    <fullName>Refer_To_SFDC_Id__c</fullName>
    <description>This field gives the uniqe SFDC ID of the Master account to which the Inactive account refers to</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Refer To SFDC Unique Id #</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/aaaSurgeonMergeClass.cls
Public Class aaaSurgeonMergeClass {
  //******************************************************************************************//
  // Author: Saikishore Aengareddy
  // Date of last modification: 10/22/2010
  // Purpose of this class: provides the ability to undelete the account record 
  //******************************************************************************************//
  
    @future
    Public static void undelfunction(List<id> idList, string mid) {
        List<Account> accList = new List<Account>();
        accList = [select id, External_ID__c, Refer_To__c, Deactive_Date__c from account where id in :idList all rows];
        try{
            undelete accList;

        Account Master1 = [select Id, External_ID__c, MDM_SAP_ID__c from account where id = :mid limit 1];
        for(account a : accList) { 
            a.Refer_To__c = Master1.MDM_SAP_ID__c;
            //Code Added by Naveen Chugh for HCP Expense Extension - CUSTOM MERGE FUNCTIONALITY
            a.Refer_To_SFDC_Id__c=Master1.Id;
            //Code Addition Ends Here
            a.Inactive__pc = TRUE;
            a.AcctInactive__c = TRUE;
            
            //system.debug('Refer to:' +a.Refer_To__c);
            //system.debug('Refer to SFDC ID:' +a.Refer_To_SFDC_Id__c);
            //system.debug('Inactive:' +a.AcctInactive__c);
                   
            if(a.Deactive_Date__c == NULL) {
                a.Deactive_Date__c = System.Today();
               }
            }
        update accList;
 
        }
        catch (Exception e) {}
    }
}