force-app/main/default/objects/Account/fields/AcctInactive__c.field-meta.xml
<CustomField>
    <fullName>AcctInactive__c</fullName>
    <defaultValue>false</defaultValue>
    <description>This field indicates if the Account is Active or Inactive</description>
    <label>AcctInactive</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/fields/Awards_Honors_Patents__c.field-meta.xml
<CustomField>
    <fullName>Awards_Honors_Patents__c</fullName>
    <description>The awards, honors and patents given to this surgeon</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>Enter the earned awards, honors and patents received by  this surgeon</inlineHelpText>
    <label>Awards, Honors, Patents</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Account/fields/Distributor_Name__c.field-meta.xml
<CustomField>
    <fullName>Distributor_Name__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Distributor Name(s)</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Expertise_Integration_purpose__c.field-meta.xml
<CustomField>
    <fullName>Expertise_Integration_purpose__c</fullName>
    <label>Enterprise Integration purpose</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Anterior Supine</fullName>
            </value>
            <value>
                <fullName>Partial Knee</fullName>
            </value>
            <value>
                <fullName>Patient Specific Instruments</fullName>
            </value>
            <value>
                <fullName>Vanguard</fullName>
            </value>
            <value>
                <fullName>VitaminE</fullName>
            </value>
            <value>
                <fullName>Vivacit-E Hip Construct</fullName>
            </value>
            <value>
                <fullName>XP</fullName>
            </value>
            <value>
                <fullName>Chondrofix</fullName>
            </value>
            <value>
                <fullName>Early Intervention</fullName>
            </value>
            <value>
                <fullName>Gel-One</fullName>
            </value>
            <value>
                <fullName>Persona Knee System</fullName>
            </value>
            <value>
                <fullName>PFJ</fullName>
            </value>
            <value>
                <fullName>Trabecular Metal Total Ankle</fullName>
            </value>
            <value>
                <fullName>Zimmer Unicompartmental Knee</fullName>
            </value>
            <value>
                <fullName>Oxford Partial Knee</fullName>
            </value>
            <value>
                <fullName>Zimmer Biomet Signature Solutions</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/GPL_Profile__c.field-meta.xml
<CustomField>
    <fullName>GPL_Profile__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Zimmer.com Profile</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>$Source.Id</field>
            <operation>equals</operation>
            <valueField>$Source.Id</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>GPL_Profile__c</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/Languages__c.field-meta.xml
<CustomField>
    <fullName>Languages__c</fullName>
    <description>The languages a surgeon speaks</description>
    <inlineHelpText>Select the languages a surgeon speaks proficiently</inlineHelpText>
    <label>Languages</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>English</fullName>
                <default>true</default>
                <label>English</label>
            </value>
            <value>
                <fullName>French</fullName>
            </value>
            <value>
                <fullName>German</fullName>
            </value>
            <value>
                <fullName>Spanish</fullName>
            </value>
            <value>
                <fullName>Chinese</fullName>
            </value>
            <value>
                <fullName>Hebrew</fullName>
            </value>
            <value>
                <fullName>Russian</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/MDM_SAP_ID__c.field-meta.xml
<CustomField>
    <fullName>MDM_SAP_ID__c</fullName>
    <description>The identification number assigned from the DCS/SAP/DPS systems</description>
    <encryptionScheme>None</encryptionScheme>
    <externalId>true</externalId>
    <inlineHelpText>This field identifies the DCS/SAP/DPS ID</inlineHelpText>
    <label>Zimmer Account Number</label>
    <length>12</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Account/fields/Memberships_Associations_Conferences__c.field-meta.xml
<CustomField>
    <fullName>Memberships_Associations_Conferences__c</fullName>
    <description>Memberships, Associations, Conferences to which this surgeon belongs</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>Enter the Memberships, associations and conferences to which this surgeon is a participant (max 255 characters)</inlineHelpText>
    <label>Memberships, Associations, Conferences</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Account/fields/Publications_Presentations__c.field-meta.xml
<CustomField>
    <fullName>Publications_Presentations__c</fullName>
    <description>The publications and presentations to which this surgeon was the author or contributor</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>Enter the publications and presentations this surgeon wrote or contributed (max 255 characters)</inlineHelpText>
    <label>Publications and Presentations</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Account/fields/Specialty_integration__c.field-meta.xml
<CustomField>
    <fullName>Specialty_integration__c</fullName>
    <label>Specialty integration</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Dental</fullName>
            </value>
            <value>
                <fullName>Elbow</fullName>
            </value>
            <value>
                <fullName>Foot and Ankle</fullName>
            </value>
            <value>
                <fullName>Hand and Wrist</fullName>
            </value>
            <value>
                <fullName>Hip</fullName>
            </value>
            <value>
                <fullName>Knee</fullName>
            </value>
            <value>
                <fullName>Orthopedic</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
            <value>
                <fullName>Pain Medicine</fullName>
            </value>
            <value>
                <fullName>Plastics</fullName>
            </value>
            <value>
                <fullName>Podiatry</fullName>
            </value>
            <value>
                <fullName>Primary Care</fullName>
            </value>
            <value>
                <fullName>Rheumetology</fullName>
            </value>
            <value>
                <fullName>Shoulder</fullName>
            </value>
            <value>
                <fullName>Spine</fullName>
            </value>
            <value>
                <fullName>Sports Medicine</fullName>
            </value>
            <value>
                <fullName>Trauma</fullName>
            </value>
            <value>
                <fullName>Wound Care</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Technique__c.field-meta.xml
<CustomField>
    <fullName>Technique__c</fullName>
    <description>The techniques commonly used by this surgeon</description>
    <inlineHelpText>Enter the surgery techniques commonly used by this surgeon (max 255 characters)</inlineHelpText>
    <label>Technique</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>MIS</fullName>
            </value>
            <value>
                <fullName>MIS II</fullName>
            </value>
            <value>
                <fullName>MIS Mini</fullName>
            </value>
            <value>
                <fullName>Quad Sparing</fullName>
            </value>
            <value>
                <fullName>PSI</fullName>
            </value>
            <value>
                <fullName>PSI Uni Knee</fullName>
            </value>
            <value>
                <fullName>Anterior Supine Hip</fullName>
            </value>
            <value>
                <fullName>Smart Tools – Knee</fullName>
            </value>
            <value>
                <fullName>Smart Tools – Hip</fullName>
            </value>
            <value>
                <fullName>Mini Hip – Posteriolateral</fullName>
            </value>
            <value>
                <fullName>Mini Hip –Anteriorlateral</fullName>
            </value>
            <value>
                <fullName>Subchondroplasty</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/recordTypes/Distributor.recordType-meta.xml
<RecordType>
    <fullName>Distributor</fullName>
    <active>true</active>
    <description>A record to keep information about Zimmer Distributors</description>
    <label>Distributor</label>
</RecordType>

force-app/main/default/objects/Contact/fields/GPL_Profile__c.field-meta.xml
<CustomField>
    <fullName>GPL_Profile__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Zimmer.com Profile</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>$Source.Id</field>
            <operation>equals</operation>
            <valueField>GPL_Profile__c.Contact__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>GPL_Profile__c</referenceTo>
    <relationshipLabel>Contacts</relationshipLabel>
    <relationshipName>Contacts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Territory_Number__c.field-meta.xml
<CustomField>
    <fullName>Territory_Number__c</fullName>
    <formula>Account.Territory_Number__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Territory Number(formula)</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/GPL_Location__c/GPL_Location__c.object-meta.xml
<CustomObject>
    <label>GPL Location</label>
    <nameField>
        <displayFormat>GPL_L-{0000}</displayFormat>
        <label>GPL Location ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>GPL Locations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/GPL_Location__c/fields/GPL_Profile__c.field-meta.xml
<CustomField>
    <fullName>GPL_Profile__c</fullName>
    <label>GPL Profile</label>
    <referenceTo>GPL_Profile__c</referenceTo>
    <relationshipLabel>GPL Locations</relationshipLabel>
    <relationshipName>Locations</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/GPL_Location__c/fields/Name__c.field-meta.xml
<CustomField>
    <fullName>Name__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Name</label>
    <required>true</required>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/GPL_Profile__c/GPL_Profile__c.object-meta.xml
<CustomObject>
    <label>GPL Profile</label>
    <nameField>
        <displayFormat>GPL_P-{0000}</displayFormat>
        <label>GPL Profile ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>GPL Profiles</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/GPL_Profile__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>GPL Profiles</relationshipLabel>
    <relationshipName>GPL_Profiles</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/GPL_Profile__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>GPL Profiles</relationshipLabel>
    <relationshipName>GPL_Profiles</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/GPL_Profile__c/fields/Languages__c.field-meta.xml
<CustomField>
    <fullName>Languages__c</fullName>
    <label>Languages</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>English</fullName>
            </value>
            <value>
                <fullName>Spanish</fullName>
            </value>
            <value>
                <fullName>French</fullName>
            </value>
            <value>
                <fullName>German</fullName>
            </value>
            <value>
                <fullName>Mandarin</fullName>
            </value>
            <value>
                <fullName>Hebrew</fullName>
            </value>
            <value>
                <fullName>Japanese</fullName>
            </value>
            <value>
                <fullName>Hindi</fullName>
            </value>
            <value>
                <fullName>Arabic</fullName>
            </value>
            <value>
                <fullName>Portuguese</fullName>
            </value>
            <value>
                <fullName>Bengali</fullName>
            </value>
            <value>
                <fullName>Russian</fullName>
            </value>
            <value>
                <fullName>Korean</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/GPL_Profile__c/fields/Name__c.field-meta.xml
<CustomField>
    <fullName>Name__c</fullName>
    <formula>IF (!ISBLANK(Account__c), 
IF (Account__r.IsPersonAccount, 
IF (!ISNULL(TEXT(Account__r.Salutation)),TEXT(Account__r.Salutation) &amp; &quot; &quot;,null) &amp; Account__r.FirstName &amp; &quot; &quot; &amp; Account__r.LastName, 
Account__r.Name), 
IF (!ISNULL(TEXT(Contact__r.Salutation)),TEXT(Contact__r.Salutation) &amp; &quot; &quot;,null) &amp; Contact__r.FirstName &amp; &quot; &quot; &amp; Contact__r.LastName)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/SurgeonPortalExtensionTest.cls
@isTest

Private Class SurgeonPortalExtensionTest{

    public Static ApexPages.StandardController surgeonController;
    public Static SurgeonPortalExtension surgeon;
    public Static SurgeonPortalDetailExtension surgeonDetail;
    public Static SurgeonPortalDetailExtension surgeonDetail1;
    public Static GPL_Profile__c gpl_Profile;  
    public Static GPL_Location__c gpl_Location;
    public Static GPL_Location__c gpl_Location1;
    public Static Account accountContact;
    public Static Account personAccount;
    public Static Contact contact1;
    public Static Profile adminProfile;
    
    public Static void createSampleData(){
    
    personAccount = new Account();
    ID recordTypeId3 = [select id from RecordType where SObjectType = 'Account' and IsActive = true and Name = 'Physician'].id;
    personAccount.LastName='Account Attendee 1 Test';
    personAccount.AcctInactive__c= false;
    personAccount.FirstName='Test';
    personAccount.RecordTypeId=recordTypeId3;
    personAccount.MDM_SAP_ID__c='7865';
    personAccount.PersonMailingCountry='US';
    personAccount.PersonMailingState='CA';
    personAccount.PersonMailingStreet='Test1 Line1'+'\n'+'Mailing line2'+'\n'+'Mailing line3';
    personAccount.PersonMailingCity='LA';
    personAccount.PersonMailingPostalCode='10106';
    personAccount.Specialty_integration__c='Anterior Approach Hip';
    personAccount.Technique__c= 'Kinectiv';
    personAccount.Expertise_Integration_purpose__c='Shoulder';
    personAccount.Languages__c='English';
    personAccount.Memberships_Associations_Conferences__c='qqqq';
    personAccount.Awards_Honors_Patents__c='aaaa';
    personAccount.Publications_Presentations__c='bbbb';
    
    insert personAccount;
    
    accountContact = new Account();
    ID recordTypeId6 = [select id from RecordType where SObjectType='Account' and Name='Distributor'].id;
    accountContact.Name='Test Account'; 
    accountContact.RecordTypeId=recordTypeId6;
    accountContact.BillingCountry='US';
    accountContact.BillingState='CA';
    accountContact.BillingStreet='Test Line1'+'\n'+'Mailing line2'+'\n'+'Mailing line3';
    accountContact.Distributor_Name__c='Test Distributor Name';
    accountContact.Territory_Number__c='9999';
    insert accountContact;
    
    contact1 = new Contact();
    ID recordTypeId2=[select id from RecordType where SObjectType='Contact' and Name='Sales Contact'].id;
    contact1.LastName='Contact Attendee 2';
    contact1.recordtypeid=recordTypeId2;
    contact1.AccountId=accountContact.id;
    insert contact1;
    
    gpl_Profile = new gpl_Profile__c();
    gpl_Profile.Account__c = personAccount.id;
    //gpl_Profile.Contact__c
    gpl_Profile.Specialties__c = 'Anterior Approach Hip';
    gpl_Profile.Procedures__c = 'Shoulder';
    insert gpl_Profile;
    
    gpl_Location = new gpl_Location__c();
    gpl_Location.GPL_Profile__c = gpl_Profile.id;
    gpl_Location.Name__c = 'LA';
    gpl_Location.City__c = 'Warsaw';
    gpl_Location.Country__c = 'US';
    gpl_Location.PostalCode__c = '154785';
    gpl_Location.State__c = 'CA';
    gpl_Location.Street__c = '1800 W A street';
    insert gpl_Location; 
    
    }

    public static User userAdmin1
    
    {
        get{
            if (userAdmin1 == null )
            {
                adminProfile = [Select Id, Name From Profile where name = 'System Admin' limit 1];
                userAdmin1  = new user (Username = ' test@key.net', FirstName = 'FirstTest', LastName ='LastTest', alias = 'FLast', 
                            email='test@key.net', communityNickname='test0101019', TimeZoneSidKey='America/Indianapolis',
                            LocaleSidKey='en_US', EmailEncodingKey='ISO-8859-1', ProfileId=adminProfile.Id ,
                            LanguageLocaleKey='en_US',Region__c='AM', Geography__c='US', Business_Division__c='DN', ContactId=contact1.Id);
                insert userAdmin1;             
             }
             return userAdmin1;
            }
        set;
    }
    
    public static User userAdmin2
    
    {
        get{
            if (userAdmin2 == null )
            {
                adminProfile = [Select Id, Name From Profile where name = 'System Admin' limit 1];
                userAdmin2  = new user (Username = ' test@key.net', FirstName = 'FirstTest', LastName ='LastTest', alias = 'FLast', 
                            email='test@key.net', communityNickname='test0101019', TimeZoneSidKey='America/Indianapolis',
                            LocaleSidKey='en_US', EmailEncodingKey='ISO-8859-1', ProfileId=adminProfile.Id ,
                            LanguageLocaleKey='en_US',Region__c='AM', Geography__c='US', Business_Division__c='DN', ContactId=personAccount.PersonContactId);
                insert userAdmin2;             
             }
             return userAdmin2;
            }
        set;
    }
    
    private Static Void initSurgeonPortalExtension()
    {
        
         createSampleData();         
         surgeonController = new ApexPages.StandardController(gpl_Profile);
         surgeon = new SurgeonPortalExtension(surgeonController); 
         //system.assertEquals(expenseTest1.HCP_Status__c,'Not Submitted');
    }
    
    private Static Void initSurgeonPortalDetailExtension()
    {
        
         createSampleData();         
         surgeonController = new ApexPages.StandardController(gpl_Location);
         surgeonDetail = new SurgeonPortalDetailExtension(surgeonController); 
         //system.assertEquals(expenseTest1.HCP_Status__c,'Not Submitted');
    }
    
    public Static testmethod void surgeonPortalTest(){
    
    test.startTest();
    
    initSurgeonPortalExtension();
    ApexPages.currentPage().getParameters().put('SurgeonId', contact1.Id);
    surgeon.loadSurgeonData(contact1.Id);
    surgeon.doAction();
    ApexPages.currentPage().getParameters().put('returnURL', 'http://apex');
    surgeon.edit();
    surgeon.save();
    surgeon.newLocation();
    
    Id b;
    for(Account a : [select PersonContactId from Account where id=:personAccount.id] )
    {
        b= a.PersonContactId;
    }
    
    system.assertNotEquals(b, Null );
    surgeon.loadSurgeonData(b);
    
    GPLProfileAccountRecordHelper.hasAlreadyUpdatedGPLProfile ();
    
    personAccount.Specialty_integration__c='MIS Mini';
    personAccount.Technique__c= 'Alloclasic';
    personAccount.Expertise_Integration_purpose__c='Knee';
    personAccount.Languages__c='Spanish';
    personAccount.Memberships_Associations_Conferences__c='www';
    personAccount.Awards_Honors_Patents__c='bbbb';
    personAccount.Publications_Presentations__c='ccc';
    update personAccount;
    
    
    gpl_Location__c gpl_Location2= new gpl_Location__c();
    gpl_Location2.GPL_Profile__c = gpl_Profile.id;
    gpl_Location2.Name__c = 'LA';
    gpl_Location2.City__c = 'Warsaw';
    gpl_Location2.Country__c = 'US';
    gpl_Location2.PostalCode__c = '154785';
    gpl_Location2.State__c = 'CA';
    gpl_Location2.Street__c = '1800 W A street';
    insert gpl_Location2; 
        
    //surgeon.deleteLocation();
    
    //ApexPages.currentPage().getParameters().put('locationid', gpl_Location.id);
    //SurgeonPortalExtension sp = new SurgeonPortalExtension(); 
    //Apexclasses.put('SelectedLocationId', gpl_Location.id);
    
    surgeon.deleteLocation();
    surgeon.UploadPhoto();
    surgeon.getLt();
    surgeon.getGt();
    
    test.stopTest();
    
    }
    
     public Static testmethod void surgeonPortalDetailTest()
     {
     
     test.startTest();
     initSurgeonPortalDetailExtension();
     ApexPages.currentPage().getParameters().put('returnURL', 'http://apex');
     surgeonDetail.edit();
     surgeonDetail.save();
     surgeonDetail.doClose();
     
     gpl_Location1 = new gpl_Location__c();
     gpl_Location1.GPL_Profile__c = gpl_Profile.id;
     gpl_Location1.Name__c = 'LA';
     gpl_Location1.City__c = 'Warsaw';
     gpl_Location1.Country__c = 'US';
     gpl_Location1.PostalCode__c = '154785';
     gpl_Location1.State__c = 'CA';
     gpl_Location1.Street__c = '1800 W A street';
     gpl_Location.Fax__c='(111)111-1111';
     gpl_Location.Phone__c='(222)222-2222';
     gpl_Location.PostalCode__c='12as';
     update gpl_Location;
     
     surgeonDetail.save();
     
     surgeonController = new ApexPages.StandardController(gpl_Location1);
     surgeonDetail1 = new SurgeonPortalDetailExtension(surgeonController);
     surgeonDetail1.save();
     test.stoptest();
     
     }        
}