force-app/main/default/objects/Account/fields/Deactive_Date__c.field-meta.xml
<CustomField>
    <fullName>Deactive_Date__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>Date this account was inactivated as a customer</inlineHelpText>
    <label>Deactive Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Account/fields/MDM_SAP_ID__c.field-meta.xml
<CustomField>
    <fullName>MDM_SAP_ID__c</fullName>
    <description>The identification number assigned from the DCS/SAP/DPS systems</description>
    <encryptionScheme>None</encryptionScheme>
    <externalId>true</externalId>
    <inlineHelpText>This field identifies the DCS/SAP/DPS ID</inlineHelpText>
    <label>Zimmer Account Number</label>
    <length>12</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Account/fields/Refer_To__c.field-meta.xml
<CustomField>
    <fullName>Refer_To__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>Refer&apos;s to the active account.</inlineHelpText>
    <label>Refer To</label>
    <length>12</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Refer_To_SFDC_Id__c.field-meta.xml
<CustomField>
    <fullName>Refer_To_SFDC_Id__c</fullName>
    <description>This field gives the uniqe SFDC ID of the Master account to which the Inactive account refers to</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Refer To SFDC Unique Id #</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/User/fields/Business_Division__c.field-meta.xml
<CustomField>
    <fullName>Business_Division__c</fullName>
    <description>This field is required-There are workflow and validation rules that uses this field to determine processing path based on the Geography, Business Division and/or Region field(s) setting of the user.</description>
    <inlineHelpText>This field is required-There are workflow and validation rules that uses this field to determine processing path based on the Geography, Business Division and/or Region field(s) setting of the user.</inlineHelpText>
    <label>Business Division</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>BH</fullName>
            </value>
            <value>
                <fullName>CAS</fullName>
            </value>
            <value>
                <fullName>CO</fullName>
            </value>
            <value>
                <fullName>DN</fullName>
            </value>
            <value>
                <fullName>GE</fullName>
            </value>
            <value>
                <fullName>GO</fullName>
            </value>
            <value>
                <fullName>HL</fullName>
            </value>
            <value>
                <fullName>N/A</fullName>
            </value>
            <value>
                <fullName>RC</fullName>
            </value>
            <value>
                <fullName>SP</fullName>
            </value>
            <value>
                <fullName>TR</fullName>
            </value>
            <value>
                <fullName>ZSP</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/User/fields/Geography__c.field-meta.xml
<CustomField>
    <fullName>Geography__c</fullName>
    <description>This field is required-There are workflow and validation rules that uses this field to determine processing path based on the Geography, Business Division and/or Region field(s) setting of the user.</description>
    <inlineHelpText>This field is required-There are workflow and validation rules that uses this field to determine processing path based on the Geography, Business Division and/or Region field(s) setting of the user.</inlineHelpText>
    <label>Geography</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Argentina</fullName>
            </value>
            <value>
                <fullName>Australia</fullName>
            </value>
            <value>
                <fullName>Austria</fullName>
            </value>
            <value>
                <fullName>Belgium</fullName>
            </value>
            <value>
                <fullName>Bolivia (Plurinational State of)</fullName>
            </value>
            <value>
                <fullName>Brazil</fullName>
            </value>
            <value>
                <fullName>Canada</fullName>
            </value>
            <value>
                <fullName>Chile</fullName>
            </value>
            <value>
                <fullName>China</fullName>
            </value>
            <value>
                <fullName>Colombia</fullName>
            </value>
            <value>
                <fullName>Costa Rica</fullName>
            </value>
            <value>
                <fullName>Czech Republic</fullName>
            </value>
            <value>
                <fullName>Denmark</fullName>
            </value>
            <value>
                <fullName>Ecuador</fullName>
            </value>
            <value>
                <fullName>Finland</fullName>
            </value>
            <value>
                <fullName>France</fullName>
            </value>
            <value>
                <fullName>Germany</fullName>
            </value>
            <value>
                <fullName>Hong Kong</fullName>
            </value>
            <value>
                <fullName>Hungary</fullName>
            </value>
            <value>
                <fullName>India</fullName>
            </value>
            <value>
                <fullName>Ireland</fullName>
            </value>
            <value>
                <fullName>Italy</fullName>
            </value>
            <value>
                <fullName>Japan</fullName>
            </value>
            <value>
                <fullName>Korea (Republic of)</fullName>
            </value>
            <value>
                <fullName>Lebanon</fullName>
            </value>
            <value>
                <fullName>Malaysia</fullName>
            </value>
            <value>
                <fullName>Mexico</fullName>
            </value>
            <value>
                <fullName>N/A</fullName>
            </value>
            <value>
                <fullName>Netherlands</fullName>
            </value>
            <value>
                <fullName>New Zealand</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/User/fields/Region__c.field-meta.xml
<CustomField>
    <fullName>Region__c</fullName>
    <description>This field is required-There are workflow and validation rules that uses this field to determine processing path based on the Geography, Business Division and/or Region field(s) setting of the user.</description>
    <inlineHelpText>This field is required-There are workflow and validation rules that uses this field to determine processing path based on the Geography, Business Division and/or Region field(s) setting of the user.</inlineHelpText>
    <label>Region</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>AM</fullName>
            </value>
            <value>
                <fullName>AP</fullName>
            </value>
            <value>
                <fullName>EU</fullName>
            </value>
            <value>
                <fullName>GL</fullName>
            </value>
            <value>
                <fullName>LA</fullName>
            </value>
            <value>
                <fullName>N/A</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/aaaSurgeonMergeTest.cls
/*****************************************************************************/
/* Class name: aaaSurgeonMergeClass                                             */
/* Author: Saikishore R Aengareddy                                           */
/* Last modified: 09/28/2010                                                 */
/* Purpose: Used to provide unit test coverage for SurgeonmMergeClass        */
/*****************************************************************************/

@istest
private class aaaSurgeonMergeTest{

    public static testMethod void testSurgeon() {    
        profile[] UserProfile1 = [Select Id, Name From Profile where name = 'Custom - Data Administrator' limit 1];
        User u1 = new user (Username = ' test@key.net', FirstName = 'FirstTest', LastName ='LastTest', alias = 'FLast', 
                            email='test@key.net', communityNickname='test0101019', TimeZoneSidKey='America/Indiana/Indianapolis',
                            LocaleSidKey='en_US', EmailEncodingKey='ISO-8859-1', ProfileId=UserProfile1[0].Id ,
                            LanguageLocaleKey='en_US',Region__c='AM', Geography__c='US', Business_Division__c='DN');
        insert u1;
        System.debug('-----SurgeonMergeTest.testSurgeon-u1----- = ' + u1);
        System.RunAs(u1) {
            Account a1 = new Account();
            //String rtId = [select id from RecordType where SObjectType = 'Account' and IsActive = true and Name = 'Physician(processing)'].Id;
            String rtId = [select id from RecordType where SObjectType = 'Account' and IsActive = true and DeveloperName = 'Physician_Processing'].Id;
            a1.RecordTypeId = rtId;
            a1.FirstName='test 1';
            a1.LastName = 'TEST ACCOUNT1';
            a1.PersonMailingCountry = 'US';  
            a1.PersonMailingState='AK';
            a1.PersonMailingStreet ='Test street one dr' + '\n' + 'Mailing line 2' + '\n' + 'Mailing Line 3' ;
            a1.PersonOtherStreet ='Test street one dr' + '\n' + 'Other line 2' + '\n' + 'Other Line 3' ;
            a1.PersonOtherCountry = 'US';  
            a1.PersonOtherState='AK';
            a1.PersonMailingCity='NY';
            a1.PersonMailingPostalCode='12345';
            a1.MDM_SAP_ID__c = '1111100000';
            a1.Refer_To__c = '';
            a1.Refer_To_SFDC_Id__c= '';
            insert a1;
            
            Account a2 = new Account();
            a2.RecordTypeId = rtId;
            a2.FirstName='test 2';
            a2.LastName = 'TEST ACCOUNT2';
            a2.PersonMailingCountry = 'US';  
            a2.PersonMailingState='AK';
            a2.PersonMailingStreet ='Test street two dr'+ '\n' + 'Mailing line 2' + '\n' + 'Mailing Line 3';
            a2.PersonOtherStreet ='Test street one dr' + '\n' + 'Mailing line 2' + '\n' + 'Other Line 3';
            a2.PersonOtherCountry = 'US';  
            a2.PersonOtherState='AK';
            a2.PersonMailingCity='NY';
            a2.PersonMailingPostalCode='12345';
            a2.MDM_SAP_ID__c = '2222200000';
            a2.Refer_To__c = '';
            //Code Change Added By Naveen Chugh For Custom Merge FUnctionality
            a2.Refer_To_SFDC_Id__c= '';
            //Code Change Ends Here
            insert a2;
            
            //Because the merging is asynchronous
            Test.startTest();     
                Merge a1 a2;
            Test.stopTest();
    
    Account[] a =[select id from Account where MDM_SAP_ID__c = '1111100000' all rows];
    
    Account[] unDeletedAcc = [select Refer_To__c,Refer_To_SFDC_Id__c, Deactive_date__c from Account where MDM_SAP_ID__c = '2222200000' all rows];
    //Code Change Added By Naveen Chugh For Custom Merge FUnctionality
    //system.assertequals(a[0].id,unDeletedAcc[0].Refer_To_SFDC_Id__c);
    //Code Change Ends Here
    //system.assertequals('1111100000',unDeletedAcc[0].Refer_To__c);
    //System.assertNotEquals(unDeletedAcc[0].Deactive_date__c,NULL);
    } //end of runAs(u1)
  }
}