force-app/main/default/objects/Account/fields/Deactive_Date__c.field-meta.xml
<CustomField>
    <fullName>Deactive_Date__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>Date this account was inactivated as a customer</inlineHelpText>
    <label>Deactive Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Account/fields/Distributor_Specialties__c.field-meta.xml
<CustomField>
    <fullName>Distributor_Specialties__c</fullName>
    <label>Distributor Specialties</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Reconstructive</fullName>
            </value>
            <value>
                <fullName>Spine</fullName>
            </value>
            <value>
                <fullName>CMF&amp;T</fullName>
            </value>
            <value>
                <fullName>OBT</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Latitude__c.field-meta.xml
<CustomField>
    <fullName>Latitude__c</fullName>
    <label>Latitude</label>
    <precision>11</precision>
    <scale>8</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Account/fields/Longitude__c.field-meta.xml
<CustomField>
    <fullName>Longitude__c</fullName>
    <label>Longitude</label>
    <precision>11</precision>
    <scale>8</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Account/fields/Organization__c.field-meta.xml
<CustomField>
    <fullName>Organization__c</fullName>
    <label>Organization</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Parent</fullName>
            </value>
            <value>
                <fullName>Satellite</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/territory__c.field-meta.xml
<CustomField>
    <fullName>territory__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>territory</label>
    <referenceTo>territory__c</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/Toll_free__c.field-meta.xml
<CustomField>
    <fullName>Toll_free__c</fullName>
    <description>Distributor toll-free number</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Toll-free</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/Account/recordTypes/Distributor.recordType-meta.xml
<RecordType>
    <fullName>Distributor</fullName>
    <active>true</active>
    <description>A record to keep information about Zimmer Distributors</description>
    <label>Distributor</label>
</RecordType>

force-app/main/default/objects/County_Distributor__c/County_Distributor__c.object-meta.xml
<CustomObject>
    <description>Integration</description>
    <label>Territory County</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>County  Distributor Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Territory Counties</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/County_to_Zip_codes__c/County_to_Zip_codes__c.object-meta.xml
<CustomObject>
    <description>Integration</description>
    <label>County to Zip codes</label>
    <nameField>
        <displayFormat>{0000}</displayFormat>
        <label>County Zip code Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>County to Zip Codes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/County_to_Zip_codes__c/fields/County_Distributor__c.field-meta.xml
<CustomField>
    <fullName>County_Distributor__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>County distributor</label>
    <referenceTo>County_Distributor__c</referenceTo>
    <relationshipLabel>County to Zip Codes</relationshipLabel>
    <relationshipName>County_to_Zip_Codes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/County_to_Zip_codes__c/fields/Zip_Codes_Distributor__c.field-meta.xml
<CustomField>
    <fullName>Zip_Codes_Distributor__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Zip Codes distributor</label>
    <referenceTo>Zip_codes_distributor__c</referenceTo>
    <relationshipLabel>County to Zip Codes</relationshipLabel>
    <relationshipName>County_to_Zip_Codes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/GDL_DistributorEvent__c/GDL_DistributorEvent__c.object-meta.xml
<CustomObject>
    <label>Distributor Event</label>
    <nameField>
        <displayFormat>GDL_E-{0000}</displayFormat>
        <label>Distributor Event ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Distributor Events</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/GDL_DistributorEvent__c/fields/DistributorProfile__c.field-meta.xml
<CustomField>
    <fullName>DistributorProfile__c</fullName>
    <label>Distributor Profile</label>
    <referenceTo>GDL_Profile__c</referenceTo>
    <relationshipLabel>Distributor Events</relationshipLabel>
    <relationshipName>DistributorEvents</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/GDL_DistributorEvent__c/fields/EndDate__c.field-meta.xml
<CustomField>
    <fullName>EndDate__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>End Date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/GDL_DistributorEvent__c/fields/Title__c.field-meta.xml
<CustomField>
    <fullName>Title__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Title</label>
    <length>200</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/GDL_DistributorLink__c/GDL_DistributorLink__c.object-meta.xml
<CustomObject>
    <label>Distributor Link</label>
    <nameField>
        <displayFormat>GDL_L-{0000}</displayFormat>
        <label>Distributor Link ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Distributor Links</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/GDL_DistributorLink__c/fields/DistributorProfile__c.field-meta.xml
<CustomField>
    <fullName>DistributorProfile__c</fullName>
    <label>Distributor Profile</label>
    <referenceTo>GDL_Profile__c</referenceTo>
    <relationshipLabel>Distributor Links</relationshipLabel>
    <relationshipName>DistributorLinks</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/GDL_DistributorLink__c/fields/Target__c.field-meta.xml
<CustomField>
    <fullName>Target__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Target</label>
    <required>true</required>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/GDL_DistributorLink__c/fields/Title__c.field-meta.xml
<CustomField>
    <fullName>Title__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Title</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/GDL_Profile__c/GDL_Profile__c.object-meta.xml
<CustomObject>
    <label>Distributor Profile</label>
    <nameField>
        <displayFormat>GDL_P-{0000}</displayFormat>
        <label>Distributor Profile ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Distributor Profiles</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/GDL_Profile__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Account</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Distributor</value>
        </filterItems>
        <filterItems>
            <field>Account.Organization__c</field>
            <operation>equals</operation>
            <value>Parent</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Distributor Profiles</relationshipLabel>
    <relationshipName>Distributor_Profiles</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/GDL_Profile__c/fields/Content__c.field-meta.xml
<CustomField>
    <fullName>Content__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Content</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/GDL_Profile__c/fields/Image__c.field-meta.xml
<CustomField>
    <fullName>Image__c</fullName>
    <label>Image</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>distributor-1.jpg</fullName>
                <default>true</default>
                <label>distributor-1.jpg</label>
            </value>
            <value>
                <fullName>distributor-2.jpg</fullName>
            </value>
            <value>
                <fullName>distributor-3.jpg</fullName>
            </value>
            <value>
                <fullName>distributor-4.jpg</fullName>
            </value>
            <value>
                <fullName>distributor-5.jpg</fullName>
            </value>
            <value>
                <fullName>distributor-6.jpg</fullName>
            </value>
            <value>
                <fullName>distributor-7.jpg</fullName>
            </value>
            <value>
                <fullName>distributor-8.jpg</fullName>
            </value>
            <value>
                <fullName>distributor-9.jpg</fullName>
            </value>
            <value>
                <fullName>distributor-10.jpg</fullName>
            </value>
            <value>
                <fullName>distributor-11.jpg</fullName>
            </value>
            <value>
                <fullName>distributor-12.jpg</fullName>
            </value>
            <value>
                <fullName>distributor-13.jpg</fullName>
            </value>
            <value>
                <fullName>distributor-14.jpg</fullName>
            </value>
            <value>
                <fullName>distributor-15.jpg</fullName>
            </value>
            <value>
                <fullName>distributor-16.jpg</fullName>
            </value>
            <value>
                <fullName>distributor-17.jpg</fullName>
            </value>
            <value>
                <fullName>distributor-18.jpg</fullName>
            </value>
            <value>
                <fullName>distributor-19.jpg</fullName>
            </value>
            <value>
                <fullName>distributor-20.jpg</fullName>
            </value>
            <value>
                <fullName>distributor-21.jpg</fullName>
            </value>
            <value>
                <fullName>distributor-22.jpg</fullName>
            </value>
            <value>
                <fullName>distributor-23.jpg</fullName>
            </value>
            <value>
                <fullName>distributor-24.jpg</fullName>
            </value>
            <value>
                <fullName>distributor-25.jpg</fullName>
            </value>
            <value>
                <fullName>distributor-26.jpg</fullName>
            </value>
            <value>
                <fullName>distributor-27.jpg</fullName>
            </value>
            <value>
                <fullName>distributor-28.jpg</fullName>
            </value>
            <value>
                <fullName>distributor-29.jpg</fullName>
            </value>
            <value>
                <fullName>distributor-30.jpg</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/GDL_Profile__c/fields/Name__c.field-meta.xml
<CustomField>
    <fullName>Name__c</fullName>
    <formula>LEFT(Account__r.Name, FIND(&apos; - &apos; ,Account__r.Name) - 1)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/territory__c/territory__c.object-meta.xml
<CustomObject>
    <description>Integration</description>
    <label>Territory</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Territory Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Territories</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Territory_county__c/Territory_county__c.object-meta.xml
<CustomObject>
    <label>County</label>
    <nameField>
        <displayFormat>{0000}</displayFormat>
        <label>Territory county Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Counties</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Territory_county__c/fields/County_Distributor__c.field-meta.xml
<CustomField>
    <fullName>County_Distributor__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>County distributor</label>
    <referenceTo>County_Distributor__c</referenceTo>
    <relationshipName>Territory_counties2</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Territory_county__c/fields/territory__c.field-meta.xml
<CustomField>
    <fullName>territory__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>territory</label>
    <referenceTo>territory__c</referenceTo>
    <relationshipName>Territory_counties2</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Zip_codes_distributor__c/Zip_codes_distributor__c.object-meta.xml
<CustomObject>
    <description>Integration</description>
    <label>Zip Codes distributor</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Zip Codes Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Zip Codes distributor</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/GdlLocatorService.cls
global class GdlLocatorService {
    private static Id RECORD_TYPE_ID = RecordTypeHelper.getRecordTypeId('Account','Distributor');
    
    webservice static list<GdlDataModel.DistributorLocation> searchLocations(GdlDataModel.SearchCriteria criteria){
        list<Account> matches = Database.query(buildQuery(criteria));
        list<GdlDataModel.DistributorLocation> locations = new list<GdlDataModel.DistributorLocation>();
        map<Id,Id> profiles = new map<Id,Id>();
        for (GDL_Profile__c p : [SELECT Id, Account__c from GDL_Profile__c where Account__c IN :matches]){
            profiles.put(p.Account__c, p.Id);
        } 
        for (Account a : matches){
            GdlDataModel.DistributorLocation l = new GdlDataModel.DistributorLocation();
            l.id = a.Id;
            l.name = a.Name;
            l.street = a.BillingStreet;
            l.city = a.BillingCity;
            l.state = a.BillingState;
            l.postalCode = a.BillingPostalCode;
            l.country = a.BillingCountry;
            l.latitude = a.Latitude__c;
            l.longitude = a.Longitude__c;
            if (a.Toll_free__c != null && a.Toll_free__c.length() > 0){
                l.phone = a.Toll_free__c;   
            } else {
                l.phone = a.Phone;
            }
            l.fax = a.Fax;
            l.website = a.Website;
            l.specialties = a.Distributor_Specialties__c;
            l.parentId = a.ParentId;
            Id profileId = profiles.get(a.Id);
            if (profileId == null){
                profileId = profiles.get(a.ParentId);
            }
            l.hasProfile = (profileId != null);
            locations.add(l);
        }
        
        
        return locations;
    }
    
    webservice static GdlDataModel.DistributorProfile getDistributorProfile(String id){
        GdlDataModel.DistributorProfile profile = null;
        Account acct = [SELECT Id, ParentId FROM Account WHERE id = :id LIMIT 1];
        if (acct != null){
            Id parentId = acct.Id;
            if (acct.ParentId != null){
                parentId = acct.ParentId;
            }
            list<Account> accounts = [SELECT Id, Name, BillingStreet, BillingCity, BillingState, BillingPostalCode, BillingCountry,
                                             Latitude__c, Longitude__c, Phone, Fax, Website, Toll_free__c, Distributor_Specialties__c,parentId
                                      FROM Account
                                      WHERE RecordTypeId = :RECORD_TYPE_ID
                                        AND (Id = :parentId OR ParentId = :parentId)
                                        AND (Deactive_Date__c = null OR Deactive_Date__c > TODAY)];
            
            list<GdlDataModel.DistributorLocation> locations = new list<GdlDataModel.DistributorLocation>();
            for (Account a : accounts){
                GdlDataModel.DistributorLocation l = new GdlDataModel.DistributorLocation();
                l.id = a.Id;
                l.name = a.Name;
                l.street = a.BillingStreet;
                l.city = a.BillingCity;
                l.state = a.BillingState;
                l.postalCode = a.BillingPostalCode;
                l.country = a.BillingCountry;
                l.latitude = a.Latitude__c;
                l.longitude = a.Longitude__c;
                l.parentId = a.ParentId;
                if (a.Toll_free__c != null && a.Toll_free__c.length() > 0){
                    l.phone = a.Toll_free__c;   
                } else {
                    l.phone = a.Phone;
                }
                l.fax = a.Fax;
                l.website = a.Website;
                l.specialties = a.Distributor_Specialties__c;
                locations.add(l);
            }
            profile = new GdlDataModel.DistributorProfile();
            profile.mainOfficeId = parentId; 
            profile.requestedOfficeId = id;
            GDL_Profile__c p = [SELECT Id, Account__c, Name__c, Image__c, Content__c, OwnerId
                                         FROM GDL_Profile__c
                                         WHERE Account__c = :parentId LIMIT 1];
            profile.content = p.Content__c;
            profile.image = p.Image__c;
            profile.name = p.Name__c;
            profile.supportQueueId = p.OwnerId;
            list<GDL_DistributorEvent__c> gdlEvents = [SELECT Id, Name, StartDate__c, EndDate__c, Description__c, DistributorProfile__c, Title__c
                                                       FROM GDL_DistributorEvent__c
                                                       WHERE DistributorProfile__c = :p.Id
                                                         AND (StartDate__c >= TODAY OR EndDate__c >= TODAY)
                                                         ORDER BY StartDate__c];
            list<GdlDataModel.DistributorEvent> events = new list<GdlDataModel.DistributorEvent>();
            for (GDL_DistributorEvent__c gdlEvent : gdlEvents){
                GdlDataModel.DistributorEvent e = new GdlDataModel.DistributorEvent();
                e.startDate = gdlEvent.StartDate__c;
                e.endDate = gdlEvent.EndDate__c;
                e.name = gdlEvent.Title__c;
                e.description = gdlEvent.Description__c;
                events.add(e);
            }
            profile.events = events;
            list<GDL_DistributorLink__c> gdlLinks = [SELECT Id, Name, Target__c, Title__c, DistributorProfile__c
                                                     FROM GDL_DistributorLink__c
                                                     WHERE DistributorProfile__c = :p.Id];
            list<GdlDataModel.DistributorLink> links = new list<GdlDataModel.DistributorLink>();
            for (GDL_DistributorLink__c gdlLink : gdlLinks){
                GdlDataModel.DistributorLink link = new GdlDataModel.DistributorLink();
                link.name = gdlLink.Title__c;
                link.url = gdlLink.Target__c;
                links.add(link);
            }
            profile.links = links;
            profile.locations = locations;
        }
        return profile;
    }
            
    private static String buildQuery(GdlDataModel.SearchCriteria criteria){
        String query = 'SELECT Id, Name, BillingStreet, BillingCity, BillingState, BillingPostalCode, BillingCountry, ' +
                       'Latitude__c, Longitude__c, Phone, Fax, Website, ParentId, Toll_free__c, Distributor_Specialties__c ' +
                       'FROM Account ' +
                       'WHERE RecordTypeId = \'' + RECORD_TYPE_ID + '\'' +  
                       ' AND (Organization__c = \'Parent\' OR Organization__c = \'Satellite\') ' +  
                       ' AND (Deactive_Date__c = null OR Deactive_Date__c > TODAY) ';
        
        
        if ((criteria.id != null) && (criteria.id.length() > 0)){
            query += ' AND Id = \'' + criteria.id + '\'';
        }
        if ((criteria.name != null) && (criteria.name.length() > 0)){
            query += ' AND Name like \'%' + criteria.name + '%\'';
        }
        if ((criteria.specialty != null) && (criteria.specialty.length() > 0)){
            query += ' AND Distributor_Specialties__c includes (\'' + String.escapeSingleQuotes(criteria.specialty) + '\')';
        }
        if ((criteria.postalCode != null) && (criteria.postalCode.length() > 0)){
            if ((criteria.country == null) || (criteria.country == 'US')){
                list<String> tids = lookupTerritories(criteria.postalCode);
                if (tids!= null && !tids.isEmpty()){
                    query += ' AND Territory__c IN (';
                    for (Integer i=0; i<tids.size(); i++){
                        if (i > 0){
                            query += ',';
                        }
                        query += '\'' + tids.get(i)+ '\'';
                    }
                    query += ')';
                }
            } else {
                query += ' AND BillingPostalCode = \'' + criteria.postalCode + '\'';                    
            }       
        }
        if ((criteria.country != null) && (criteria.country.length() > 0)){
            query += ' AND BillingCountry = \'' + criteria.country + '\'';
        }       
        return query;
    }
    
    public static list<String> lookupTerritories(String postalCode){
        list<String> territories = null;
        list<Zip_codes_distributor__c> zcd = [select id,name from Zip_codes_distributor__c where name = :postalCode];
        if(!zcd.isEmpty()) {
            list<County_to_Zip_codes__c> czc = [select id,County_Distributor__c,Zip_Codes_Distributor__c 
                                                from County_to_Zip_codes__c 
                                                where zip_Codes_Distributor__c IN :zcd];
            system.debug('the size of the territory ciountry  list is: ' +czc.size());
            if(!czc.isEmpty()) {
                list<String> CdId = new list<String>();
                for(County_to_Zip_codes__c cc :czc) {
                    CdId.add(cc.County_Distributor__c);
                }
                list<Territory_county__c> tc = [select id,County_Distributor__c,territory__c
                                                from Territory_county__c 
                                                where County_Distributor__c IN :CdId];
                system.debug('the size of the territory ciountry  list is: ' +tc.size());
                if(!tc.isEmpty()) {
                    territories = new list<String>();
                    for(Territory_county__c tt :tc) {
                        
                        if(tt.territory__c != null){
                            territories.add(tt.territory__c);
                        	system.debug('the territory value is:' + tt.territory__c);
                        }
                        
                    }
                }   
            }
        }
        return territories;        
    }
    
// Modified By Rohit Attri : Commented below code because TestMethods should be written in a separate test class 
// and created new Test Class GdlLocatorServiceTest for Code Coverage of GdlLocatorService and GdlDataModel Classes
/*
    static testmethod void testSearchLocations(){
        Account main = new Account(
            RecordTypeID = RECORD_TYPE_ID,
            Name = 'Test Parent Distributor',
            BillingStreet = 'TEST 123 Main Street',
            BillingCity = 'Easter Island',
            BillingState = 'CL',
            BillingPostalCode = 'CL012001',
            BillingCountry = 'CL',
            Latitude__c = -27.128,
            Longitude__c = -109.341,
            Territory_Number__c = '0000',
            Organization__c = 'Parent'
            //Territory__c = '0000' 
        );
        insert(main);
        Account s1 = new Account(
            RecordTypeId = RECORD_TYPE_ID,
            ParentId = main.Id,
            Name = 'Test Parent Distributor',
            BillingStreet = 'TEST 123 Main Street',
            BillingCity = 'Puerto Villamil',
            BillingState = 'EC',
            BillingPostalCode = 'EC012001',
            BillingCountry = 'EC',
            Latitude__c = -0.8292784,
            Longitude__c = -90.9820667999999,
            Territory_Number__c = '0000',
            Organization__c = 'Parent'
            //Territory__c = '0000'
        );
        insert(s1);
        GDL_Profile__c profile = new GDL_Profile__c(
            Account__c = main.Id,
            Content__c = '<h3>About Test Parent Distributor</h3><p>This is the content for this distributor</p>',
            Image__c = 'image1'
        );
        insert(profile);
        GDL_DistributorLink__c link = new GDL_DistributorLink__c(
            Target__c = 'http://www.google.com',
            Title__c = 'Google',
            DistributorProfile__c = profile.Id
        );
        insert(link);
        GDL_DistributorEvent__c event = new GDL_DistributorEvent__c(
            Title__c = 'A Test Event',
            StartDate__c = System.today(),
            EndDate__C = System.today(),
            DistributorProfile__c = profile.Id
        );
        insert(event);
        
        GdlDataModel.SearchCriteria criteria = new GdlDataModel.SearchCriteria();
        criteria.country = 'CL';
        criteria.state = 'CL';
        criteria.postalCode = 'CL012001';
        test.startTest();
            list<GdlDataModel.DistributorLocation> locations = searchLocations(criteria);
            System.assertEquals(1, locations.size());
            GdlDataModel.DistributorProfile prof = getDistributorProfile(locations.get(0).Id);
            System.assertNotEquals(null, prof);
        test.stopTest();
        
    } */
}