force-app/main/default/objects/Account/fields/Deactive_Date__c.field-meta.xml
<CustomField>
    <fullName>Deactive_Date__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>Date this account was inactivated as a customer</inlineHelpText>
    <label>Deactive Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Account/fields/Inactive__c.field-meta.xml
<CustomField>
    <fullName>Inactive__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Account Inactive</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/fields/MDM_SAP_ID__c.field-meta.xml
<CustomField>
    <fullName>MDM_SAP_ID__c</fullName>
    <description>The identification number assigned from the DCS/SAP/DPS systems</description>
    <encryptionScheme>None</encryptionScheme>
    <externalId>true</externalId>
    <inlineHelpText>This field identifies the DCS/SAP/DPS ID</inlineHelpText>
    <label>Zimmer Account Number</label>
    <length>12</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Account/fields/Refer_To__c.field-meta.xml
<CustomField>
    <fullName>Refer_To__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>Refer&apos;s to the active account.</inlineHelpText>
    <label>Refer To</label>
    <length>12</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Refer_To_SFDC_Id__c.field-meta.xml
<CustomField>
    <fullName>Refer_To_SFDC_Id__c</fullName>
    <description>This field gives the uniqe SFDC ID of the Master account to which the Inactive account refers to</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Refer To SFDC Unique Id #</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Deactive_Date__c.field-meta.xml
<CustomField>
    <fullName>Deactive_Date__c</fullName>
    <description>This gives the date on which the contacts was deactivated</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Deactive Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Inactive__c.field-meta.xml
<CustomField>
    <fullName>Inactive__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Indicates whether this contact is inactive</description>
    <inlineHelpText>Check the box to Indicate that this contact is no longer an active contact</inlineHelpText>
    <label>Inactive</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Refer_To_SFDC_Id__c.field-meta.xml
<CustomField>
    <fullName>Refer_To_SFDC_Id__c</fullName>
    <description>This field gives the uniqe SFDC ID of the Master account to which the Inactive account refers to</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Refer To SFDC Unique Id #</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/ContactCustomMergeClass.cls
Public Class ContactCustomMergeClass {
  //******************************************************************************************//
  // Author: Naveen Chugh
  // Date of last modification: 09/02/2011
  // Parameters:None
  // Purpose of this class: provides the ability to undelete the contact record that has just been 
  // deleted by standard merge functionality
  //******************************************************************************************//
  
    @future
    Public static void undelfunction(List<id> idList, string mid) 
    {
        /************************************************************************************************
          Purpose: To undelete the Contact that would have been deleted by standard Merge functionality
                   and to mark it as Inactive and populate its Refer To SFDC Unique ID field with the
                   Master record Id. 
          Parameters:  List containing the Id of the contact that has to be Undeleted denoted by idList
                       and string mid that contains the Id of the Master record to which the undeleted 
                       Contact would refer to.
          Returns: None
          ***********************************************************************************************/  

        List<contact> contactList = new List<contact>();
        
        //getting the list of all the Contacts that need to be undeleted
        contactList = [select id from contact where id in :idList all rows];
        for(contact b : contactList)
        {
        system.debug('the contact record that was undeleted is: ' +b.id);
        }
        try{
            undelete contactList;
        
        //Contact Master1 = [select Id,Contact.Account.MDM_SAP_ID__c from contact where id = :mid limit 1];
        //Selecting the Master Contact Record id
        Contact Master1 = [select Id from contact where id = :mid limit 1];

        for(contact a : ContactList)
         { 
            //a.Refer_To__c = Master1.MDM_SAP_ID__c;
            //Assinging the Refer To SFDC ID field with the Master Record Id
            a.Refer_To_SFDC_Id__c=Master1.Id;
            // Flaggin the Inactive field as true
            a.Inactive__c = TRUE;
                    
           if(a.Deactive_Date__c == NULL) 
               {
                  //Assignimg the De-Activate date to the undeleted Contact.
                  a.Deactive_Date__c = System.Today();
               }
            
            }
        update contactList;
 
        } catch (Exception e) {}
    }
}