force-app/main/default/objects/Account/fields/Distributor_Specialties__c.field-meta.xml
<CustomField>
    <fullName>Distributor_Specialties__c</fullName>
    <label>Distributor Specialties</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Reconstructive</fullName>
            </value>
            <value>
                <fullName>Spine</fullName>
            </value>
            <value>
                <fullName>CMF&amp;T</fullName>
            </value>
            <value>
                <fullName>OBT</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/recordTypes/Distributor.recordType-meta.xml
<RecordType>
    <fullName>Distributor</fullName>
    <active>true</active>
    <description>A record to keep information about Zimmer Distributors</description>
    <label>Distributor</label>
</RecordType>

force-app/main/default/objects/Contact/fields/AD_Username__c.field-meta.xml
<CustomField>
    <fullName>AD_Username__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>AD Username</label>
    <length>12</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Hire_Date__c.field-meta.xml
<CustomField>
    <fullName>Hire_Date__c</fullName>
    <description>First Day of Employment</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Hire Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Role_Classification__c.field-meta.xml
<CustomField>
    <fullName>Role_Classification__c</fullName>
    <description>This field is used to identify distributor personnel for manpower reporting purposes.</description>
    <label>Role Classification</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>CMF&amp;T</fullName>
            </value>
            <value>
                <fullName>Distributor</fullName>
            </value>
            <value>
                <fullName>Office - Admin</fullName>
            </value>
            <value>
                <fullName>Office - Customer Service Leader</fullName>
            </value>
            <value>
                <fullName>Office - Customer Service Representative</fullName>
            </value>
            <value>
                <fullName>Office - Driver</fullName>
            </value>
            <value>
                <fullName>Office - HR/Compliance</fullName>
            </value>
            <value>
                <fullName>Office - Inventory  Coordinator</fullName>
            </value>
            <value>
                <fullName>Office - Inventory Leader</fullName>
            </value>
            <value>
                <fullName>Office - Operations Leader</fullName>
            </value>
            <value>
                <fullName>Office - Pricing/Contracts</fullName>
            </value>
            <value>
                <fullName>Office - Sourcing/Logistics Coordinator</fullName>
            </value>
            <value>
                <fullName>Office - Sourcing/Logistics Leader</fullName>
            </value>
            <value>
                <fullName>Sales Associate</fullName>
            </value>
            <value>
                <fullName>Sales Manager with accounts</fullName>
            </value>
            <value>
                <fullName>Sales Manager without accounts</fullName>
            </value>
            <value>
                <fullName>Surgery Case Specialist</fullName>
            </value>
            <value>
                <fullName>Zimmer Biomet Canada Office</fullName>
            </value>
            <value>
                <fullName>Zimmer Biomet Canada Recon</fullName>
            </value>
            <value>
                <fullName>Zimmer Biomet Canada Spine</fullName>
            </value>
            <value>
                <fullName>Zimmer Biomet OBT</fullName>
            </value>
            <value>
                <fullName>Zimmer Biomet Spine</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/Sales_Assoc_ID__c.field-meta.xml
<CustomField>
    <fullName>Sales_Assoc_ID__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Sales Assoc ID</label>
    <length>5</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Error_Notification_Recipient__c/Error_Notification_Recipient__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Error Notification Recipients</description>
    <label>Error Notification Recipient</label>
</CustomObject>

force-app/main/default/objects/Error_Notification_Recipient__c/fields/Email__c.field-meta.xml
<CustomField>
    <fullName>Email__c</fullName>
    <description>Recipient Email Id</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Email</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Trigger_Settings__c/Trigger_Settings__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Activate/ De-activate SFDC triggers</description>
    <label>Trigger Settings</label>
</CustomObject>

force-app/main/default/objects/Trigger_Settings__c/fields/Active__c.field-meta.xml
<CustomField>
    <fullName>Active__c</fullName>
    <defaultValue>false</defaultValue>
    <description>If Checked, Trigger is Activated and Id Unchecked, trigger is De-Activated</description>
    <label>Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/TestContactTriggerHandler.cls
@isTest
public class TestContactTriggerHandler {
    
    @testSetup static void setup() {
        
        Trigger_Settings__c cs = new Trigger_Settings__c();
        cs.Name = 'AddUsersToPSQueues Trigger';
        cs.Active__c = true;
        insert cs; 
        
        //CreateUserAccountfromContact Trigger
        Trigger_Settings__c cs1 = new Trigger_Settings__c();
        cs1.Name = 'CreateUserAccountfromContact Trigger';
        cs1.Active__c = true;
        insert cs1;         
        
        Error_Notification_Recipient__c enr1 = new Error_Notification_Recipient__c();
        enr1.Name = 'Recipient1';
        enr1.Email__c = 'mohit.gulati@zimmerbiomet.com';
        insert enr1; 
        
        Error_Notification_Recipient__c enr2 = new Error_Notification_Recipient__c();
        enr2.Name = 'Recipient2';
        enr2.Email__c = 'mohitgulati41@gmail.com';
        insert enr2; 
        
        // Create a unique UserName
        String uniqueUserName = 'standarduser' + DateTime.now().getTime() + '@testorg.com';
        
        Profile p = [SELECT Id FROM Profile WHERE Name='System Administrator']; 
        
        User u = new User(Alias = 'standt', Email='standarduser@testorg.com', 
                          EmailEncodingKey='UTF-8', LastName='Testing', LanguageLocaleKey='en_US', 
                          LocaleSidKey='en_US', ProfileId = p.Id, 
                          TimeZoneSidKey='America/Los_Angeles', UserName=uniqueUserName);
        
        system.runAs(u){
            
            String orgId = UserInfo.getOrganizationId();
            String dateString = String.valueof(Datetime.now()).replace(' ','').replace(':','').replace('-','');
            Integer randomInt = Integer.valueOf(math.rint(math.random()*1000000));
            String uniqueName = orgId + dateString + randomInt;
            
            Profile p1 = [SELECT ID FROM profile WHERE name='US Ortho SF Platform User'];
            
            User u1 = new User(Alias ='ZB05', Email='TestContactTriggerHandler@zb3.com', IsActive=FALSE,
                               EmailEncodingKey='UTF-8', LastName='ZBUser', LanguageLocaleKey='en_US', 
                               LocaleSidKey='en_US', ProfileId = p1.Id, 
                               TimeZoneSidKey='America/Los_Angeles', UserName=uniqueName+'@test'+ orgId+'.com');
            insert u1;
        }
        
    }
    
    public static testMethod void TestUserCreationWithContact()
    {
        test.startTest();
        
        Id devRecordTypeId1 = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Distributor').getRecordTypeId();
        Account acc = new Account(Name = 'testAccount',RecordTypeId =devRecordTypeId1,Distributor_Specialties__c = 'Reconstructive');
        insert acc;
        
        
        Id devRecordTypeId = Schema.SObjectType.Contact.getRecordTypeInfosByName().get('Sales Contact').getRecordTypeId();
        list<Contact> conList = new List<contact>();
        
        for(Integer i=1; i<=5; i++){
            Contact cont =  new Contact(FirstName= 'test',LastName='Contact'+i,Email='TestContactTriggerHandler@zimmerbiometrohit.com'+i,
                                        RecordTypeId=devRecordTypeId,
                                        Sales_Assoc_ID__c='ROH09',
                                        AccountID = acc.ID,
                                        Hire_Date__c=System.today(),
                                        AD_Username__c = 'test',
                                        Role_Classification__c ='Distributor'); 
            conList.add(cont);
        }
        
        Contact cont1 =  new Contact(FirstName= 'test',LastName='Contact2',Email='TestContactTriggerHandler@zimmerbiometrohit.com2',
                                     RecordTypeId=devRecordTypeId,
                                     Sales_Assoc_ID__c='ROH09',
                                     AccountID = acc.ID,
                                     Hire_Date__c=System.today(),
                                     AD_Username__c = 'test',
                                     Role_Classification__c ='Sales Manager with accounts'); 
        conList.add(cont1);
        
        Contact cont3 =  new Contact(FirstName= 'test',LastName='Contact3',Email='TestContactTriggerHandler@zb3.com',
                                     RecordTypeId=devRecordTypeId,
                                     Sales_Assoc_ID__c='ZB05',
                                     AccountID = acc.ID,
                                     Hire_Date__c=System.today().addDays(-7),
                                     AD_Username__c = 'ZB',
                                     Role_Classification__c ='Sales Manager with accounts'); 
        conList.add(cont3);
        
        
        insert conList;
        
        
        test.stopTest();                       
    }     
}