force-app/main/default/objects/Account/fields/Distributor_Name__c.field-meta.xml
<CustomField>
    <fullName>Distributor_Name__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Distributor Name(s)</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/recordTypes/Distributor.recordType-meta.xml
<RecordType>
    <fullName>Distributor</fullName>
    <active>true</active>
    <description>A record to keep information about Zimmer Distributors</description>
    <label>Distributor</label>
</RecordType>

force-app/main/default/objects/Contact/fields/Territory_Number__c.field-meta.xml
<CustomField>
    <fullName>Territory_Number__c</fullName>
    <formula>Account.Territory_Number__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Territory Number(formula)</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/recordTypes/DN_Global_Contact_Record_Type.recordType-meta.xml
<RecordType>
    <fullName>DN_Global_Contact_Record_Type</fullName>
    <active>true</active>
    <label>DN-Global-Contact Record Type</label>
</RecordType>

force-app/main/default/classes/DNGlobalContactOwnerDataTest.cls
@isTest (seeAllData=false)
private class DNGlobalContactOwnerDataTest{

            private static testmethod void basic(){
               Test.startTest(); 
                Account accountTest = new Account();
                ID recordTypeIdTemp = [select id from RecordType where SObjectType='Account' and Name='DN-ACCT-RECORD-TYPE'].id;
                accountTest.Name='Test Account'; 
                accountTest.RecordTypeId=recordTypeIdTemp;
                accountTest.BillingCountry='US';
                accountTest.BillingState='CA';
                accountTest.BillingStreet='Test Line1'+'\n'+'Mailing line2'+'\n'+'Mailing line3';
                accountTest.Distributor_Name__c='Test Distributor Name';
                accountTest.Territory_Number__c='9999';
                insert accountTest;
                
                System.debug('Created new Account');
                Contact Con = New Contact();
                Con.LastName = 'TEST CONTACT1';
                RecordType RecType =([ SELECT Id from RecordType where Name = 'DN-Global-Contact Record Type' and SobjectType = 'Contact']);
                Con.RecordTypeId= RecType.Id; 
                //[select id from RecordType where SObjectType='Contact' and Name='DN_Global_Contact_Record_Type'].id;
                Con.AccountId= accountTest.id;
               
                Insert Con;
                System.debug('Created new Contact');
               Test.stoptest();
        
            }
}