force-app/main/default/objects/Account/fields/Distributor_Name__c.field-meta.xml
<CustomField>
    <fullName>Distributor_Name__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Distributor Name(s)</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/recordTypes/Distributor.recordType-meta.xml
<RecordType>
    <fullName>Distributor</fullName>
    <active>true</active>
    <description>A record to keep information about Zimmer Distributors</description>
    <label>Distributor</label>
</RecordType>

force-app/main/default/objects/dental_Deal__c/dental_Deal__c.object-meta.xml
<CustomObject>
    <label>Dental Deal</label>
    <nameField>
        <displayFormat>{00000}</displayFormat>
        <label>Dental Deal Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Dental Deals</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/dental_Deal__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Dental Deals</relationshipLabel>
    <relationshipName>Dental_Deals</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/DN_Account_Sales_Analytics__c/DN_Account_Sales_Analytics__c.object-meta.xml
<CustomObject>
    <label>DN Account Sales Analytics</label>
    <nameField>
        <displayFormat>{0}</displayFormat>
        <label>DN Account Sales Analytics Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>DN Account Sales Analytics</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/DN_Account_Sales_Analytics__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>DN Account Sales Analytics</relationshipLabel>
    <relationshipName>DN_Account_Sales_Analytics</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/DN_Account_Sales_Analytics__c/fields/Biomend_Biomend_Extend_FPY__c.field-meta.xml
<CustomField>
    <fullName>Biomend_Biomend_Extend_FPY__c</fullName>
    <label>Biomend/Biomend Extend FPY</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/DN_Account_Sales_Analytics__c/fields/Biomend_Biomend_Extend_PYTD__c.field-meta.xml
<CustomField>
    <fullName>Biomend_Biomend_Extend_PYTD__c</fullName>
    <label>Biomend/Biomend Extend PYTD</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/DN_Account_Sales_Analytics__c/fields/Biomend_Biomend_Extend_YTD__c.field-meta.xml
<CustomField>
    <fullName>Biomend_Biomend_Extend_YTD__c</fullName>
    <label>Biomend/Biomend Extend YTD</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/DN_Account_Sales_Analytics__c/fields/Colla_All_Products_FPY__c.field-meta.xml
<CustomField>
    <fullName>Colla_All_Products_FPY__c</fullName>
    <label>Colla (All Products) FPY</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/DN_Account_Sales_Analytics__c/fields/Colla_All_Products_PYTD__c.field-meta.xml
<CustomField>
    <fullName>Colla_All_Products_PYTD__c</fullName>
    <label>Colla (All Products) PYTD</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/DN_Account_Sales_Analytics__c/fields/Colla_All_Products_YTD__c.field-meta.xml
<CustomField>
    <fullName>Colla_All_Products_YTD__c</fullName>
    <label>Colla (All Products) YTD</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/DN_Account_Sales_Analytics__c/fields/Puros_Block_FPY__c.field-meta.xml
<CustomField>
    <fullName>Puros_Block_FPY__c</fullName>
    <label>Puros Block FPY</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/DN_Account_Sales_Analytics__c/fields/Puros_Block_PYTD__c.field-meta.xml
<CustomField>
    <fullName>Puros_Block_PYTD__c</fullName>
    <label>Puros Block PYTD</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/DN_Account_Sales_Analytics__c/fields/Puros_Block_YTD__c.field-meta.xml
<CustomField>
    <fullName>Puros_Block_YTD__c</fullName>
    <label>Puros Block YTD</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/DN_Account_Sales_Analytics__c/fields/Puros_Cancellous_FPY__c.field-meta.xml
<CustomField>
    <fullName>Puros_Cancellous_FPY__c</fullName>
    <label>Puros Cancellous FPY</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/DN_Account_Sales_Analytics__c/fields/Puros_Cancellous_PYTD__c.field-meta.xml
<CustomField>
    <fullName>Puros_Cancellous_PYTD__c</fullName>
    <label>Puros Cancellous PYTD</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/DN_Account_Sales_Analytics__c/fields/Puros_Cancellous_YTD__c.field-meta.xml
<CustomField>
    <fullName>Puros_Cancellous_YTD__c</fullName>
    <label>Puros Cancellous YTD</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/DN_Account_Sales_Analytics__c/fields/Puros_CC_Mix_FPY__c.field-meta.xml
<CustomField>
    <fullName>Puros_CC_Mix_FPY__c</fullName>
    <label>Puros CC Mix FPY</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/DN_Account_Sales_Analytics__c/fields/Puros_CC_Mix_PYTD__c.field-meta.xml
<CustomField>
    <fullName>Puros_CC_Mix_PYTD__c</fullName>
    <label>Puros CC Mix PYTD</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/DN_Account_Sales_Analytics__c/fields/Puros_CC_Mix_YTD__c.field-meta.xml
<CustomField>
    <fullName>Puros_CC_Mix_YTD__c</fullName>
    <label>Puros CC Mix YTD</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/DN_Account_Sales_Analytics__c/fields/Puros_Cortical_FPY__c.field-meta.xml
<CustomField>
    <fullName>Puros_Cortical_FPY__c</fullName>
    <label>Puros Cortical FPY</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/DentalTriggersTestClass.cls
@isTest
public with sharing class DentalTriggersTestClass {

private static testMethod void DentalTest(){
                
                Account accountTest = new Account();
                ID recordTypeId6 = [select id from RecordType where SObjectType='Account' and Name='Distributor'].id;
                accountTest.Name='Test Account'; 
                accountTest.RecordTypeId=recordTypeId6;
                accountTest.BillingCountry='US';
                accountTest.BillingState='CA';
                accountTest.BillingStreet='Test Line1'+'\n'+'Mailing line2'+'\n'+'Mailing line3';
                accountTest.Distributor_Name__c='Test Distributor Name';
                accountTest.Territory_Number__c='9999';
                accountTest.OwnerId = '005C0000004JAHl';
                insert accountTest;
                
                dental_Deal__c w = new dental_Deal__c();
                w.account__c = accountTest.id;
                w.Description__c = 'a';
                w.OwnerId = '005C0000004JAHl';           
                insert w;
                
                
                //w.Warranty_Relationship__c = '0015000000LwRkD';     
                DN_Account_Sales_Analytics__c d = new DN_Account_Sales_Analytics__c();
                d.account__c = accountTest.id;
                d.Biomend_Biomend_Extend_YTD__c = 6;
                d.Colla_All_Products_FPY__c = 8;
                d.Colla_All_Products_PYTD__c = 5;
                d.Colla_All_Products_YTD__c = 9;
                d.Puros_Block_FPY__c = 7;
                d.Puros_Block_PYTD__c = 6;
                d.Puros_Block_YTD__c = 5;
                d.Puros_Cancellous_FPY__c =6;
                d.Puros_Cancellous_PYTD__c = 4;
                d.Puros_Cancellous_YTD__c = 5;
                d.Puros_CC_Mix_FPY__c = 5;
                d.Puros_CC_Mix_PYTD__c =7;
                d.Puros_CC_Mix_YTD__c =6;
                d.Puros_Cortical_FPY__c = 6;
                d.Biomend_Biomend_Extend_FPY__c = 5;
                d.Biomend_Biomend_Extend_PYTD__c = 6;
                d.OwnerId = '005C0000004JAHl';           
                insert d;
                 try{
                    //update w;
                    dental_Deal__c a = [select id, Description__c from  dental_Deal__c where id = :w.id];
                    System.assertEquals('a',w.Description__c);
                    
                    DN_Account_Sales_Analytics__c b = [select id, Biomend_Biomend_Extend_YTD__c from  DN_Account_Sales_Analytics__c where id = :d.id];
                    System.assertEquals(6,d.Biomend_Biomend_Extend_YTD__c);
            
        } catch (System.DmlException e){
            System.debug('we caught a dml exception: ' + e.getDmlMessage(0));    
        }
    }  

}