force-app/main/default/objects/Account/fields/Distributor_E_mail__c.field-meta.xml
<CustomField>
    <fullName>Distributor_E_mail__c</fullName>
    <description>This field will provide the email for the distributor</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Distributor E-mail</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Account/fields/Distributor_Specialties__c.field-meta.xml
<CustomField>
    <fullName>Distributor_Specialties__c</fullName>
    <label>Distributor Specialties</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Reconstructive</fullName>
            </value>
            <value>
                <fullName>Spine</fullName>
            </value>
            <value>
                <fullName>CMF&amp;T</fullName>
            </value>
            <value>
                <fullName>OBT</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Organization__c.field-meta.xml
<CustomField>
    <fullName>Organization__c</fullName>
    <label>Organization</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Parent</fullName>
            </value>
            <value>
                <fullName>Satellite</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/territory__c.field-meta.xml
<CustomField>
    <fullName>territory__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>territory</label>
    <referenceTo>territory__c</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/Toll_free__c.field-meta.xml
<CustomField>
    <fullName>Toll_free__c</fullName>
    <description>Distributor toll-free number</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Toll-free</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/Account/recordTypes/Distributor.recordType-meta.xml
<RecordType>
    <fullName>Distributor</fullName>
    <active>true</active>
    <description>A record to keep information about Zimmer Distributors</description>
    <label>Distributor</label>
</RecordType>

force-app/main/default/objects/Contact/fields/Territory_Number__c.field-meta.xml
<CustomField>
    <fullName>Territory_Number__c</fullName>
    <formula>Account.Territory_Number__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Territory Number(formula)</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/County_Distributor__c/County_Distributor__c.object-meta.xml
<CustomObject>
    <description>Integration</description>
    <label>Territory County</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>County  Distributor Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Territory Counties</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/County_to_Zip_codes__c/County_to_Zip_codes__c.object-meta.xml
<CustomObject>
    <description>Integration</description>
    <label>County to Zip codes</label>
    <nameField>
        <displayFormat>{0000}</displayFormat>
        <label>County Zip code Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>County to Zip Codes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/County_to_Zip_codes__c/fields/County_Distributor__c.field-meta.xml
<CustomField>
    <fullName>County_Distributor__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>County distributor</label>
    <referenceTo>County_Distributor__c</referenceTo>
    <relationshipLabel>County to Zip Codes</relationshipLabel>
    <relationshipName>County_to_Zip_Codes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/County_to_Zip_codes__c/fields/Zip_Codes_Distributor__c.field-meta.xml
<CustomField>
    <fullName>Zip_Codes_Distributor__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Zip Codes distributor</label>
    <referenceTo>Zip_codes_distributor__c</referenceTo>
    <relationshipLabel>County to Zip Codes</relationshipLabel>
    <relationshipName>County_to_Zip_Codes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/territory__c/territory__c.object-meta.xml
<CustomObject>
    <description>Integration</description>
    <label>Territory</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Territory Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Territories</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Territory_county__c/Territory_county__c.object-meta.xml
<CustomObject>
    <label>County</label>
    <nameField>
        <displayFormat>{0000}</displayFormat>
        <label>Territory county Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Counties</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Territory_county__c/fields/County_Distributor__c.field-meta.xml
<CustomField>
    <fullName>County_Distributor__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>County distributor</label>
    <referenceTo>County_Distributor__c</referenceTo>
    <relationshipName>Territory_counties2</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Territory_county__c/fields/territory__c.field-meta.xml
<CustomField>
    <fullName>territory__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>territory</label>
    <referenceTo>territory__c</referenceTo>
    <relationshipName>Territory_counties2</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Zip_codes_distributor__c/Zip_codes_distributor__c.object-meta.xml
<CustomObject>
    <description>Integration</description>
    <label>Zip Codes distributor</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Zip Codes Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Zip Codes distributor</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/Distributor_Locater_Updated.cls
global class Distributor_Locater_Updated {


   global class Distributor_Locator_Output{
    
      WebService String DistributorId;
      WebService String Distributor_name;
      WebService String AddressLine1;
      WebService String City;
      WebService String StateOrProvince;
      WebService String ZipCodeOrPostalCode;
      WebService String Country;
      WebService String OfficePhone;
      WebService String SecondaryPhone;
      WebService String FaxNumber;
      WebService String Email;
      WebService String WebsiteUrl;
      WebService String Specialty;
      
   } 
 
     //  System.debug('result------------->' +Distributor_Locater_Updated.zipCodeMethod('23'));
       //System.debug('Result is------------>'  +Distributor_Locater_Udated.zipCodeMethod('1234'));
       Webservice static list<Distributor_Locator_Output> zipCodeMethod(String zipCodeInput){
         
          list<Distributor_Locator_Output> result = 

DistributerResult(zipCodeInput,'','',true,false,false);
          
          return result;
                         
       }
       
       Webservice static list<Distributor_Locator_Output> countryMethod(String Country){
         
          list<Distributor_Locator_Output> result = 

DistributerResult('',Country,'',false,true,false);
          
          return result;
                         
       }
      
       Webservice static Distributor_Locator_Output MySalesAssociate(String DistributorId){
         
          list<Distributor_Locator_Output> result = 

DistributerResult('','',DistributorId,false,false,true);
          
         if(!result.isEmpty())
          return result[0];
          else
          return null;
                         
       }        
              
       
       public static list<Distributor_Locator_Output> DistributerResult(String zipCodeInput,String 

Country,String DistributorId,
                                                                                            Boolean 

isZip,Boolean isCountry,Boolean isMyphy)
       {
                     String DisbTypeId = RecordTypeHelper.getRecordTypeId('Account','Distributor');
         
         list<Distributor_Locator_Output> result = new list<Distributor_Locator_Output>();
         list<Account> MatchSales = new list<Account>();
//Territory Number
//MatchSales[0].Territory_Number__c
        if(isZip){
                   map<id,Zip_codes_distributor__c> zcd = new 

map<id,Zip_codes_distributor__c>([select id,name from 
                                                              Zip_codes_distributor__c where name = 

:zipCodeInput]);
                    if(!zcd.isEmpty())
                    {
                        list<County_to_Zip_codes__c> czc = [select 

id,County_Distributor__c,Zip_Codes_Distributor__c from 
                                                                     County_to_Zip_codes__c where 

Zip_Codes_Distributor__c IN :zcd.keyset()];
                        if(!czc.isEmpty())
                        {
                            list<String> CdId = new list<String>();
                            for(County_to_Zip_codes__c cc :czc)
                            {
                                CdId.add(cc.County_Distributor__c);
                            }
                            list<Territory_county__c> tc = [select 

id,County_Distributor__c,territory__c
                                                              from Territory_county__c where 

County_Distributor__c IN :CdId];
                            if(!tc.isEmpty())
                            {
                                list<String> TrId = new list<String>();
                                for(Territory_county__c tt :tc)
                                {
                                    TrId.add(tt.territory__c);
                                }
                                MatchSales = [Select 

id,name,BillingCity,Website,territory__c,BillingState,BillingPostalCode,Distributor_Specialties__c,
                                                       BillingCountry,phone,Toll_free__c,
                                      fax,Territory_Number__c,BillingStreet,Distributor_E_mail__c 
                                                From Account where territory__c IN :TrId and 

RecordTypeId = :DisbTypeId limit 9999];    
                            }
                        }
                    }                                          
         

                                                                                         
                                             
        }else if(isCountry){
          MatchSales = [Select id,name, 

BillingCity,Website,BillingState,BillingPostalCode,Distributor_Specialties__c,BillingCountry,phone,

Toll_free__c,
                                      fax,Territory_Number__c,BillingStreet,Distributor_E_mail__c 

From 
                                                  Account where BillingCountry = :Country and 

RecordTypeId =:DisbTypeId 
                                                  and Organization__c ='Parent' limit 9999];        

    
        }else if(isMyphy){
          MatchSales = [Select id,name, 

BillingCity,Website,BillingState,BillingPostalCode,Distributor_Specialties__c,BillingCountry,phone,

Toll_free__c,
                                      fax,Territory_Number__c,BillingStreet,Distributor_E_mail__c 
                                              From Account where Id = :DistributorId];           
        }
       //     Contact cc;
        //  cc.
          
     if(!MatchSales.isEmpty()){
          for(Account cc :MatchSales)
          {
            Distributor_Locator_Output dd = new Distributor_Locator_Output();
            dd.DistributorId = cc.Id;
            dd.Distributor_name = cc.Name +' - ' + cc.BillingCity +',' +cc.BillingState;
     //     dd.Sales_Associate_First_Name = cc.FirstName;
     //     dd.Sales_Associate_Last_Name = cc.LastName;
            dd.AddressLine1 = cc.BillingStreet;
            dd.City = cc.BillingCity;
            dd.StateOrProvince = cc.BillingState;
            dd.ZipCodeOrPostalCode = cc.BillingPostalCode;
            dd.Country = cc.BillingCountry;
            dd.OfficePhone = cc.Phone;
            dd.SecondaryPhone = cc.Toll_free__c;
            dd.FaxNumber = cc.Fax;
            dd.Email = cc.Distributor_E_mail__c;
            dd.WebsiteUrl = cc.Website;
            dd.Specialty = cc.Distributor_Specialties__c;
            result.add(dd);     
          }
     }
          return result; 
       }
}