force-app/main/default/objects/Account/fields/Distributor_Specialties__c.field-meta.xml
<CustomField>
    <fullName>Distributor_Specialties__c</fullName>
    <label>Distributor Specialties</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Reconstructive</fullName>
            </value>
            <value>
                <fullName>Spine</fullName>
            </value>
            <value>
                <fullName>CMF&amp;T</fullName>
            </value>
            <value>
                <fullName>OBT</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/recordTypes/Distributor.recordType-meta.xml
<RecordType>
    <fullName>Distributor</fullName>
    <active>true</active>
    <description>A record to keep information about Zimmer Distributors</description>
    <label>Distributor</label>
</RecordType>

force-app/main/default/objects/Contact/fields/AD_Username__c.field-meta.xml
<CustomField>
    <fullName>AD_Username__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>AD Username</label>
    <length>12</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Employee_Non_Employee__c.field-meta.xml
<CustomField>
    <fullName>Employee_Non_Employee__c</fullName>
    <inlineHelpText>This field provides information about an employee status</inlineHelpText>
    <label>In HRIS?</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
            <value>
                <fullName>Employee</fullName>
                <isActive>false</isActive>
                <label>Employee</label>
            </value>
            <value>
                <fullName>Non-Employee</fullName>
                <isActive>false</isActive>
                <label>Non-Employee</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/Hire_Date__c.field-meta.xml
<CustomField>
    <fullName>Hire_Date__c</fullName>
    <description>First Day of Employment</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Hire Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Role_Classification__c.field-meta.xml
<CustomField>
    <fullName>Role_Classification__c</fullName>
    <description>This field is used to identify distributor personnel for manpower reporting purposes.</description>
    <label>Role Classification</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>CMF&amp;T</fullName>
            </value>
            <value>
                <fullName>Distributor</fullName>
            </value>
            <value>
                <fullName>Office - Admin</fullName>
            </value>
            <value>
                <fullName>Office - Customer Service Leader</fullName>
            </value>
            <value>
                <fullName>Office - Customer Service Representative</fullName>
            </value>
            <value>
                <fullName>Office - Driver</fullName>
            </value>
            <value>
                <fullName>Office - HR/Compliance</fullName>
            </value>
            <value>
                <fullName>Office - Inventory  Coordinator</fullName>
            </value>
            <value>
                <fullName>Office - Inventory Leader</fullName>
            </value>
            <value>
                <fullName>Office - Operations Leader</fullName>
            </value>
            <value>
                <fullName>Office - Pricing/Contracts</fullName>
            </value>
            <value>
                <fullName>Office - Sourcing/Logistics Coordinator</fullName>
            </value>
            <value>
                <fullName>Office - Sourcing/Logistics Leader</fullName>
            </value>
            <value>
                <fullName>Sales Associate</fullName>
            </value>
            <value>
                <fullName>Sales Manager with accounts</fullName>
            </value>
            <value>
                <fullName>Sales Manager without accounts</fullName>
            </value>
            <value>
                <fullName>Surgery Case Specialist</fullName>
            </value>
            <value>
                <fullName>Zimmer Biomet Canada Office</fullName>
            </value>
            <value>
                <fullName>Zimmer Biomet Canada Recon</fullName>
            </value>
            <value>
                <fullName>Zimmer Biomet Canada Spine</fullName>
            </value>
            <value>
                <fullName>Zimmer Biomet OBT</fullName>
            </value>
            <value>
                <fullName>Zimmer Biomet Spine</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/Sales_Assoc_ID__c.field-meta.xml
<CustomField>
    <fullName>Sales_Assoc_ID__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Sales Assoc ID</label>
    <length>5</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Sales_Specialty__c.field-meta.xml
<CustomField>
    <fullName>Sales_Specialty__c</fullName>
    <description>Used to assign sales specialty</description>
    <label>Sales Specialty</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Role_Classification__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>Recon (H, K)</fullName>
            </value>
            <value>
                <fullName>Trauma</fullName>
            </value>
            <value>
                <fullName>Sports</fullName>
            </value>
            <value>
                <fullName>Foot &amp; Ankle</fullName>
            </value>
            <value>
                <fullName>Extremities</fullName>
            </value>
            <value>
                <fullName>Surgical</fullName>
            </value>
            <value>
                <fullName>B.E.S.T.</fullName>
            </value>
            <value>
                <fullName>None</fullName>
                <default>true</default>
                <label>None</label>
            </value>
            <value>
                <fullName>Early Intervention</fullName>
            </value>
            <value>
                <fullName>DSFFA</fullName>
            </value>
            <value>
                <fullName>Full Line</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact_To_User_Batch_Recipient__c/Contact_To_User_Batch_Recipient__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Contact To User Batch Recipient</description>
    <label>Contact To User Batch Recipient</label>
</CustomObject>

force-app/main/default/objects/Contact_To_User_Contact_Record_Types__c/Contact_To_User_Contact_Record_Types__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Contact To User Contact Record Types</description>
    <label>Contact To User Contact Record Types</label>
</CustomObject>

force-app/main/default/objects/Contact_To_User_Contact_Record_Types__c/fields/Record_Type_Id__c.field-meta.xml
<CustomField>
    <fullName>Record_Type_Id__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Record Type Id</label>
    <length>50</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact_To_User_Profiles__c/Contact_To_User_Profiles__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Contact To User profiles</description>
    <label>Contact To User Profiles</label>
</CustomObject>

force-app/main/default/objects/Contact_To_User_Profiles__c/fields/Profile_Id__c.field-meta.xml
<CustomField>
    <fullName>Profile_Id__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Profile Id</label>
    <length>20</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Error_Notification_Recipient__c/Error_Notification_Recipient__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Error Notification Recipients</description>
    <label>Error Notification Recipient</label>
</CustomObject>

force-app/main/default/objects/Error_Notification_Recipient__c/fields/Email__c.field-meta.xml
<CustomField>
    <fullName>Email__c</fullName>
    <description>Recipient Email Id</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Email</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Trigger_Settings__c/Trigger_Settings__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Activate/ De-activate SFDC triggers</description>
    <label>Trigger Settings</label>
</CustomObject>

force-app/main/default/objects/Trigger_Settings__c/fields/Active__c.field-meta.xml
<CustomField>
    <fullName>Active__c</fullName>
    <defaultValue>false</defaultValue>
    <description>If Checked, Trigger is Activated and Id Unchecked, trigger is De-Activated</description>
    <label>Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/User/fields/Contact_to_user__c.field-meta.xml
<CustomField>
    <fullName>Contact_to_user__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <externalId>true</externalId>
    <label>Contact to user</label>
    <length>18</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/classes/UpdateSalesContactOnUser_Scheduler_Test.cls
@isTest
public class UpdateSalesContactOnUser_Scheduler_Test {
    
    
    @testSetup static void setup() 
    {
        List<Contact_To_User_Contact_Record_Types__c> CRType_List = new list<Contact_To_User_Contact_Record_Types__c>();
        List<Contact_To_User_Profiles__c> uProfile_List = new list<Contact_To_User_Profiles__c>();
        List<Trigger_Settings__c> tsList = new List<Trigger_Settings__c>();
        
        Contact_To_User_Contact_Record_Types__c cRType = new Contact_To_User_Contact_Record_Types__c();
        cRType.Name = 'Sales Contact';
        cRType.Record_Type_Id__c = '012800000002DoB';
        CRType_List.add(cRType);
        
        Contact_To_User_Contact_Record_Types__c cRType1 = new Contact_To_User_Contact_Record_Types__c();
        cRType1.Name = 'Zimmer Corporate Employees';
        cRType1.Record_Type_Id__c = '012800000003ZTZ';
        CRType_List.add(cRType1);
        
        insert CRType_List;
        
        Contact_To_User_Batch_Recipient__c rec = new Contact_To_User_Batch_Recipient__c();
        rec.Name = 'Recipient 1';
        rec.Email__c = 'mohit.gulati@zimmerbiomet.com';
        insert rec;
        
        Contact_To_User_Profiles__c usrProfile = new Contact_To_User_Profiles__c();
        usrProfile.Name = 'AM-US- Surgeon Maintenance Users';
        usrProfile.Profile_Id__c = '00eC0000001Skq9';
        uProfile_List.add(usrProfile);
        
        Contact_To_User_Profiles__c usrProfile1 = new Contact_To_User_Profiles__c();
        usrProfile1.Name = 'AM-US-Sales Management';
        usrProfile1.Profile_Id__c = '00eC0000001SrVA';
        uProfile_List.add(usrProfile1);
        
        Contact_To_User_Profiles__c usrProfile2 = new Contact_To_User_Profiles__c();
        usrProfile2.Name = 'Custom-Zimmer Sales';
        usrProfile2.Profile_Id__c = '00e80000000tnIn';
        uProfile_List.add(usrProfile2);
        
        Contact_To_User_Profiles__c usrProfile3 = new Contact_To_User_Profiles__c();
        usrProfile3.Name = 'US Ortho SF Platform User';
        usrProfile3.Profile_Id__c = '00e3b000001TRWw';
        uProfile_List.add(usrProfile3);
        
        insert uProfile_List;
        
        Trigger_Settings__c cs = new Trigger_Settings__c();
        cs.Name = 'AddUsersToPSQueues Trigger';
        cs.Active__c = true;
        tsList.add(cs);
        
        //CreateUserAccountfromContact Trigger
        Trigger_Settings__c cs1 = new Trigger_Settings__c();
        cs1.Name = 'CreateUserAccountfromContact Trigger';
        cs1.Active__c = true;
        tsList.add(cs1);
        
        insert tsList;
        
        Error_Notification_Recipient__c errorNotify = new Error_Notification_Recipient__c();
        errorNotify.Name = 'Recp 1';
        errorNotify.Email__c = 'mohit.gulati@zimmerbiomet.com';
        insert errorNotify;
        /*
        // Create a unique UserName
        String uniqueUserName = 'standarduser' + DateTime.now().getTime() + '@testorg.com';
        
        Profile p = [SELECT Id FROM Profile WHERE Name='Standard User']; 
        
        User u = new User(Alias = 'standt', Email='standarduser@testorg.com', 
                          EmailEncodingKey='UTF-8', LastName='Testing', LanguageLocaleKey='en_US', 
                          LocaleSidKey='en_US', ProfileId = p.Id, 
                          TimeZoneSidKey='America/Los_Angeles', UserName=uniqueUserName);
        
        system.runAs(u)
		*/
        {
            
            Date dt = date.today().addDays(-7);
            
            list<Contact>contList = new list<Contact>();
            list<User> insertusers = new list<User>();
            
            //get sales contact record type Id
            Id salescontactrecordtypeId = Schema.SObjectType.Contact.getRecordTypeInfosByName().get('Sales Contact').getRecordTypeId();
            
            Account acc= new Account();
            acc.RecordTypeId = '012800000002ByT';//Distributor Account Rec Type
            acc.Name = 'Test Account';
            acc.Distributor_Specialties__c = 'Reconstructive';
            insert acc;
            
            for(integer i=0;i<5;i++)
            {
                Contact con = new contact();
                con.FirstName = 'Test';
                con.LastName = 'Record-0'+i;
                con.RecordTypeId = salescontactrecordtypeId;
                con.Role_Classification__c = 'Sales Associate';
                con.AD_Username__c = 'Record-0'+i;
                con.AccountId = acc.Id;
                con.Hire_Date__c = date.today().addDays(-7);
                con.Email = 'Test_Trigger'+i+'@gmail.com';
                con.Sales_Assoc_ID__c = '5555'+i;
                con.Sales_Specialty__c = 'Sports';
                con.Employee_Non_Employee__c = 'No';
                
                contList.add(con);
            }
            
            insert contList;
            
        }
    }
    
    public static testMethod void UnitTest01() {
        
        Test.startTest();

        Account a = [Select Id, Name from Account Where Name=:'Test Account' Limit 1];
        
        Contact c = [Select Id, Name, Email, AccountId from Contact Where AccountId=:a.Id Limit 1];
        
        User u1 = [Select Id, Name , Email, Contact_to_user__c,ProfileId,IsActive From User
                   Where Email=:c.Email Limit 1];
        u1.Contact_to_user__c = '';
        update u1;
        
        
        UpdateSalesContactOnUser_Scheduler emailSch = new UpdateSalesContactOnUser_Scheduler();
        String sch = '0 0 7 * * ?'; 
        System.schedule('Test UpdateSalesContactOnUser', sch, emailSch);
        
        Test.stopTest(); 
        
    }
    
     public static testMethod void UnitTest02() {
        
        Test.startTest();
        
        UpdateSalesContactOnUser_Scheduler emailSch = new UpdateSalesContactOnUser_Scheduler();
        String sch = '0 0 7 * * ?'; 
        System.schedule('Test UpdateSalesContactOnUser', sch, emailSch);
        
        Test.stopTest(); 
        
    }
    
    public static testMethod void UnitTest03() {
        
        Test.startTest();
        
        Map<String, Contact_To_User_Profiles__c> csMap = Contact_To_User_Profiles__c.getAll();
        List<Contact_To_User_Profiles__c> csList = csMap.values();
        
        delete csList;
        
        Account a = [Select Id, Name from Account Where Name=:'Test Account' Limit 1];
        
        Contact c = [Select Id, Name, Email, AccountId from Contact Where AccountId=:a.Id Limit 1];
        
        User u1 = [Select Id, Name , Email, Contact_to_user__c,ProfileId,IsActive From User
                   Where Email=:c.Email Limit 1];
        u1.Contact_to_user__c = '';
        update u1;
        
        UpdateSalesContactOnUser_Scheduler emailSch = new UpdateSalesContactOnUser_Scheduler();
        String sch = '0 0 7 * * ?'; 
        System.schedule('Test UpdateSalesContactOnUser', sch, emailSch);
        
        Test.stopTest(); 
        
    }
}