force-app/main/default/objects/Account/fields/Distributor_Name__c.field-meta.xml
<CustomField>
    <fullName>Distributor_Name__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Distributor Name(s)</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/recordTypes/Distributor.recordType-meta.xml
<RecordType>
    <fullName>Distributor</fullName>
    <active>true</active>
    <description>A record to keep information about Zimmer Distributors</description>
    <label>Distributor</label>
</RecordType>

force-app/main/default/classes/UpdateAccountInfoOnDealsDNAnalyticsTest.cls
@isTest (seeAllData=false)
private class UpdateAccountInfoOnDealsDNAnalyticsTest{

            private static testmethod void basic()
            {
               Test.startTest(); 
                Account accountTest = new Account();
                ID recordTypeIdTemp = [select id from RecordType where SObjectType='Account' and Name='DN-ACCT-RECORD-TYPE'].id;
                accountTest.Name='Test Account'; 
                accountTest.RecordTypeId=recordTypeIdTemp;
                accountTest.BillingCountry='US';
                accountTest.BillingState='CA';
                accountTest.BillingStreet='Test Line1'+'\n'+'Mailing line2'+'\n'+'Mailing line3';
                accountTest.Distributor_Name__c='Test Distributor Name';
                accountTest.Territory_Number__c='9999';
                accountTest.Phone='9999-9999-00';
                insert accountTest;
                
                System.debug('Created new DN-ACCT-RECORD-TYPE Account');
                
               Test.stoptest();
        
            }
}