force-app/main/default/objects/Account/fields/Expertise_Integration_purpose__c.field-meta.xml
<CustomField>
    <fullName>Expertise_Integration_purpose__c</fullName>
    <label>Enterprise Integration purpose</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Anterior Supine</fullName>
            </value>
            <value>
                <fullName>Partial Knee</fullName>
            </value>
            <value>
                <fullName>Patient Specific Instruments</fullName>
            </value>
            <value>
                <fullName>Vanguard</fullName>
            </value>
            <value>
                <fullName>VitaminE</fullName>
            </value>
            <value>
                <fullName>Vivacit-E Hip Construct</fullName>
            </value>
            <value>
                <fullName>XP</fullName>
            </value>
            <value>
                <fullName>Chondrofix</fullName>
            </value>
            <value>
                <fullName>Early Intervention</fullName>
            </value>
            <value>
                <fullName>Gel-One</fullName>
            </value>
            <value>
                <fullName>Persona Knee System</fullName>
            </value>
            <value>
                <fullName>PFJ</fullName>
            </value>
            <value>
                <fullName>Trabecular Metal Total Ankle</fullName>
            </value>
            <value>
                <fullName>Zimmer Unicompartmental Knee</fullName>
            </value>
            <value>
                <fullName>Oxford Partial Knee</fullName>
            </value>
            <value>
                <fullName>Zimmer Biomet Signature Solutions</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Fellowship__c.field-meta.xml
<CustomField>
    <fullName>Fellowship__c</fullName>
    <description>Name of the healthcare facility where surgeon did his/her Fellowship</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>Enter the name of healthcare facility where the surgeon completed their Fellowship</inlineHelpText>
    <label>Fellowship</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/MDM_SAP_ID__c.field-meta.xml
<CustomField>
    <fullName>MDM_SAP_ID__c</fullName>
    <description>The identification number assigned from the DCS/SAP/DPS systems</description>
    <encryptionScheme>None</encryptionScheme>
    <externalId>true</externalId>
    <inlineHelpText>This field identifies the DCS/SAP/DPS ID</inlineHelpText>
    <label>Zimmer Account Number</label>
    <length>12</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Account/fields/Medical_Degree__c.field-meta.xml
<CustomField>
    <fullName>Medical_Degree__c</fullName>
    <description>The listing of a surgeon&apos;s medical degree(s)</description>
    <inlineHelpText>Select the surgeon&apos;s medical degree</inlineHelpText>
    <label>Medical Degree</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>A.U.D.</fullName>
            </value>
            <value>
                <fullName>C.R.P.</fullName>
            </value>
            <value>
                <fullName>D.D.M</fullName>
            </value>
            <value>
                <fullName>D.D.S.</fullName>
            </value>
            <value>
                <fullName>D.M.D.</fullName>
            </value>
            <value>
                <fullName>D.M.D., M.D.</fullName>
            </value>
            <value>
                <fullName>D.O.</fullName>
            </value>
            <value>
                <fullName>D.P.M.</fullName>
            </value>
            <value>
                <fullName>D.V.M</fullName>
            </value>
            <value>
                <fullName>FRACS</fullName>
            </value>
            <value>
                <fullName>FRCS</fullName>
            </value>
            <value>
                <fullName>M.D.</fullName>
            </value>
            <value>
                <fullName>M.D., Ph.D.</fullName>
            </value>
            <value>
                <fullName>MB BS</fullName>
            </value>
            <value>
                <fullName>MSc</fullName>
            </value>
            <value>
                <fullName>N.P.</fullName>
            </value>
            <value>
                <fullName>O.D.</fullName>
            </value>
            <value>
                <fullName>P.A.</fullName>
            </value>
            <value>
                <fullName>P.H.R.</fullName>
            </value>
            <value>
                <fullName>P.S.Y.</fullName>
            </value>
            <value>
                <fullName>Ph.D.</fullName>
            </value>
            <value>
                <fullName>S.W.</fullName>
            </value>
            <value>
                <fullName>VM.D.</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Medical_School__c.field-meta.xml
<CustomField>
    <fullName>Medical_School__c</fullName>
    <description>Name of the medical school where the surgeon did his/her medical studies</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>Enter the surgeon&apos;s medical school name</inlineHelpText>
    <label>Medical School</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Middle_Name__c.field-meta.xml
<CustomField>
    <fullName>Middle_Name__c</fullName>
    <description>Middle initial of surgeon</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Middle Name(Custom)</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Physician_Specialty__c.field-meta.xml
<CustomField>
    <fullName>Physician_Specialty__c</fullName>
    <description>The speciality(s) of this surgeon with regard to Zimmer products</description>
    <inlineHelpText>Select Zimmer specialty for this surgeon</inlineHelpText>
    <label>Specialty</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Knee</fullName>
            </value>
            <value>
                <fullName>Hip</fullName>
            </value>
            <value>
                <fullName>Elbow</fullName>
            </value>
            <value>
                <fullName>Shoulder</fullName>
            </value>
            <value>
                <fullName>Spine</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
            <value>
                <fullName>CAS</fullName>
            </value>
            <value>
                <fullName>Dental</fullName>
            </value>
            <value>
                <fullName>Foot &amp; Ankle</fullName>
            </value>
            <value>
                <fullName>Hand &amp; Wrist</fullName>
            </value>
            <value>
                <fullName>Orthobiologics</fullName>
            </value>
            <value>
                <fullName>OSP</fullName>
            </value>
            <value>
                <fullName>Patient Specific</fullName>
            </value>
            <value>
                <fullName>Sports Medicine</fullName>
            </value>
            <value>
                <fullName>Trauma</fullName>
            </value>
            <value>
                <fullName>Neurosurgical</fullName>
            </value>
            <value>
                <fullName>Arthroplasty</fullName>
            </value>
            <value>
                <fullName>Arthroscopy</fullName>
            </value>
            <value>
                <fullName>Paediatric</fullName>
            </value>
            <value>
                <fullName>Oncology</fullName>
            </value>
            <value>
                <fullName>PEDIATRIC ORTHOPEDICS</fullName>
            </value>
            <value>
                <fullName>ORTHOPEDIC SURGERY</fullName>
                <label>Orthopedic Surgery</label>
            </value>
            <value>
                <fullName>NEUROLOGICAL SURGERY</fullName>
            </value>
            <value>
                <fullName>ORTHOPEDIC SURGERY OF THE SPINE</fullName>
            </value>
            <value>
                <fullName>ADULT RECONSTRUCTIVE ORTHOPEDICS</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Physicians_Locator__c.field-meta.xml
<CustomField>
    <fullName>Physicians_Locator__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Indicates where we recieved the list information</description>
    <inlineHelpText>Check this box if you want to select this list for your mailng</inlineHelpText>
    <label>Physicians Locator</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/fields/Residency__c.field-meta.xml
<CustomField>
    <fullName>Residency__c</fullName>
    <description>Name of the health care facility where this surgeon did his/her residency</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>Enter the name of the healthcare facility where this surgeon did their residency</inlineHelpText>
    <label>Residency</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Suffix__c.field-meta.xml
<CustomField>
    <fullName>Suffix__c</fullName>
    <description>A surgeon&apos;s name suffix</description>
    <label>Suffix(Custom)</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Jr.</fullName>
            </value>
            <value>
                <fullName>Sr.</fullName>
            </value>
            <value>
                <fullName>II</fullName>
            </value>
            <value>
                <fullName>III</fullName>
            </value>
            <value>
                <fullName>IV</fullName>
            </value>
            <value>
                <fullName>V</fullName>
            </value>
            <value>
                <fullName>VI</fullName>
            </value>
            <value>
                <fullName>VII</fullName>
            </value>
            <value>
                <fullName>VIII</fullName>
            </value>
            <value>
                <fullName>IX</fullName>
            </value>
            <value>
                <fullName>X</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Technique__c.field-meta.xml
<CustomField>
    <fullName>Technique__c</fullName>
    <description>The techniques commonly used by this surgeon</description>
    <inlineHelpText>Enter the surgery techniques commonly used by this surgeon (max 255 characters)</inlineHelpText>
    <label>Technique</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>MIS</fullName>
            </value>
            <value>
                <fullName>MIS II</fullName>
            </value>
            <value>
                <fullName>MIS Mini</fullName>
            </value>
            <value>
                <fullName>Quad Sparing</fullName>
            </value>
            <value>
                <fullName>PSI</fullName>
            </value>
            <value>
                <fullName>PSI Uni Knee</fullName>
            </value>
            <value>
                <fullName>Anterior Supine Hip</fullName>
            </value>
            <value>
                <fullName>Smart Tools – Knee</fullName>
            </value>
            <value>
                <fullName>Smart Tools – Hip</fullName>
            </value>
            <value>
                <fullName>Mini Hip – Posteriolateral</fullName>
            </value>
            <value>
                <fullName>Mini Hip –Anteriorlateral</fullName>
            </value>
            <value>
                <fullName>Subchondroplasty</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/recordTypes/Practice.recordType-meta.xml
<RecordType>
    <fullName>Practice</fullName>
    <active>true</active>
    <description>A record to keep information about the medical practice(s) to which a surgeon is a member</description>
    <label>Medical Practice</label>
</RecordType>

force-app/main/default/objects/Healthcare_Surgeon_Relationship__c/Healthcare_Surgeon_Relationship__c.object-meta.xml
<CustomObject>
    <label>Account Relationship</label>
    <nameField>
        <displayFormat>{0000}</displayFormat>
        <label>Relationship Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Accounts Relationships</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Healthcare_Surgeon_Relationship__c/fields/Surgeon__c.field-meta.xml
<CustomField>
    <fullName>Surgeon__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Surgeon</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Healthcare Facility Relationship</relationshipLabel>
    <relationshipName>Healthcare_Facility_Surgeon</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Phy_Country_Codes__c/Phy_Country_Codes__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>Physician Country Codes</label>
</CustomObject>

force-app/main/default/objects/Phy_Country_Codes__c/fields/Condition_Code__c.field-meta.xml
<CustomField>
    <fullName>Condition_Code__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Condition Code</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Practice_Surgeon_Link__c/Practice_Surgeon_Link__c.object-meta.xml
<CustomObject>
    <label>Practice &amp; Surgeon Relationship</label>
    <nameField>
        <displayFormat>{0000}</displayFormat>
        <label>Practice Link Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Practice &amp; Surgeon Relationships</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Practice_Surgeon_Link__c/fields/Practice__c.field-meta.xml
<CustomField>
    <fullName>Practice__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Practice</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Surgeon Relationships</relationshipLabel>
    <relationshipName>R00N80000002Up33EAC</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Practice_Surgeon_Link__c/fields/Surgeon__c.field-meta.xml
<CustomField>
    <fullName>Surgeon__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Surgeon</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Practice Relationships</relationshipLabel>
    <relationshipName>R00N80000002hQEjEAM</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/Services_Inventory.cls
global class Services_Inventory {

     global class Physician_Locator_Output{
         
        WebService String MedicalPracticeId;
        WebService String PhysicianId;
        WebService String FirstName;
        WebService String MiddleName;
        WebService String LastName;     
        WebService String Suffix;
        WebService String PracticeName;
        WebService String office_Street;
        WebService String office_City;
        WebService String office_StateOrProvince;
        WebService String office_ZipCodeOrPostalCode;
        WebService String office_Country;
        WebService String PhoneNumber;
        WebService String FaxNumber;
        WebService String WebsiteUrl;
    //  WebService String Undergraduate;    // not available
        WebService String Graduate;
        WebService String Residency;
        WebService String Fellowship;
        WebService String Hospital_Affiliations;  
    //  WebService String Joint_Procedure_Specialties;
        WebService String MIS_Flag;
     // WebService String ZipCode_PostalCodeDistance; 
        WebService String Physician_Special_Interest;
        WebService String Medical_degree; 
        WebService String Specialties;
        WebService String Medical_practice_Street;
        WebService String Medical_practice_City;
        WebService String Medical_practice_StateOrProvince;
        WebService String Medical_practice_PostalCode;
        WebService String Medical_practice_Country;
        
     } 
     //Services_Inventory.zipCodeMethod(zipCodeList, SpecialityCondition)
     //Services_Inventory.StateCountryMethod(state, country, SpecialityCondition)
     //Services_Inventory.MyPhysicianMethod(MedicalPracticeId, physicianId)
     Webservice static list<Physician_Locator_Output> zipCodeMethod(list<String> zipCodeList , integer SpecialityNumber){
        
           string SpecialityCondition = SpConditionCode(SpecialityNumber);
           
      list<Physician_Locator_Output> result = searchResults(zipCodeList, '','', '', '', SpecialityCondition, true, false, false); 
                                           
          
        return result;
     }
     
     Webservice static list<Physician_Locator_Output> StateCountryMethod(String state,String country ,integer SpecialityNumber){
 
        
        string SpecialityCondition = SpConditionCode(SpecialityNumber);
        list<String> zipCodeList = new list<String>();
        list<Physician_Locator_Output> result = searchResults(zipCodeList, state, Country, '','', SpecialityCondition, false, true, false);
         
        return result;  
             
     }
     Webservice static Physician_Locator_Output MyPhysicianMethod(String MedicalPracticeId , String physicianId){

        list<String> zipCodeList = new list<String>();
        list<Physician_Locator_Output> result = searchResults(zipCodeList, '', '', MedicalPracticeId,physicianId,'',false, false , true); 
                                                                               
        
     // Physician_Locator_Output result = new Physician_Locator_Output();
     if(!result.isEmpty())
        return result[0];
        else
        return null;         
     } 
     
  
  
  //mehod used to get the condition from condition Number
  
  public static String SpConditionCode(integer SpecialityNumber)
  {

    if(SpecialityNumber ==0)
    return 'ALL';
    string ss = string.valueof(SpecialityNumber);
    Phy_Country_Codes__c pcc = Phy_Country_Codes__c.getvalues(ss);
    if(pcc != null)
    return pcc.Condition_Code__c ;
    else
    return 'error';
  }
  
     // method used for other webservice to return result
     
     public static list<Physician_Locator_Output> searchResults(list<String> zipCodeList ,String state, String Country , 
                                                                String MedicalPracticeId, String physicianId , String SpecialityCondition,
                                                                 Boolean isZip,Boolean isStateorCountry,Boolean isMyPhy){
        
      //  String MedRecTypeId = RecordTypeHelper.getRecordTypeId('Account','Medical Practice');
      //String MedRecTypeId = [Select Id, sObjectType, Name From RecordType where sObjectType = 'Account' and Name ='Medical Practice'].Id;
      String MedRecTypeId = [Select Id, sObjectType, Name From RecordType where sObjectType = 'Account' and DeveloperName ='Practice'].Id;
                list<Physician_Locator_Output> result = new list<Physician_Locator_Output>();
                 map<id,Account> MatchAccount;
        if(isZip){
        MatchAccount = new map<id,Account>([select id,name,ShippingCity,ShippingCountry,ShippingPostalCode,ShippingState,ShippingStreet, 
                                          Website,Phone,Fax   from Account where RecordTypeId= :MedRecTypeId and 
                                           ShippingPostalCode IN :zipCodeList limit 9999]);
        
        }else if(isStateorCountry){
        MatchAccount = new map<id,Account>([select id,name,ShippingCity,ShippingCountry,ShippingPostalCode,ShippingState,ShippingStreet, 
                                          Website,Phone,Fax   from Account where RecordTypeId= :MedRecTypeId and 
                                           ShippingState =:state and ShippingCountry = :Country limit 300]);
        }else if (isMyPhy){
        MatchAccount = new map<id,Account>([select id,name,ShippingCity,ShippingCountry,ShippingPostalCode,ShippingState,ShippingStreet, 
                                          Website,Phone,Fax   from Account where id = :MedicalPracticeId]); 
                                                
        }
     //   System.debug('Result is------------------------------------>' + MatchAccount);
        
    if(!MatchAccount.isEmpty()){                                                               
     // map<String,map<String,String>> fullMap = new map<String,map<String,String>>();
        map<String,list<Practice_Surgeon_Link__c>> SuVsPr = new map<String,list<Practice_Surgeon_Link__c>>();
        Set<String> SarId = new Set<String>();
        list<Practice_Surgeon_Link__c> PSL;
        if(isMyPhy){
                       PSL = [select id,Practice__c,Surgeon__c,Surgeon__r.FirstName,Surgeon__r.Middle_Name__c, 
                                                    Surgeon__r.LastName,Surgeon__r.Suffix__c,Surgeon__r.Technique__c,
                                                    Surgeon__r.Expertise_integration_purpose__c,Surgeon__r.Medical_School__c,
                                                    Surgeon__r.Residency__c,Surgeon__r.Fellowship__c,Surgeon__r.Medical_Degree__c,
                                                    Surgeon__r.Physician_Specialty__c,Surgeon__r.PersonMailingCity,
                                                    Surgeon__r.PersonMailingCountry,Surgeon__r.PersonMailingPostalCode,
                                                    Surgeon__r.PersonMailingState,Surgeon__r.PersonMailingStreet,Surgeon__r.MDM_SAP_ID__c,
                                                    Surgeon__r.Physicians_Locator__c
                                                    from Practice_Surgeon_Link__c where Practice__c =:MedicalPracticeId 
                                                    and Surgeon__r.MDM_SAP_ID__c = :physicianId];
        System.debug('Size is--------------------->' +PSL.size());
        if(!PSL.isEmpty())
        SpecialityCondition = PSL[0].Surgeon__r.Physician_Specialty__c;
        }
        else{
        PSL = [select id,Practice__c,Surgeon__c,Surgeon__r.FirstName,Surgeon__r.Middle_Name__c, 
                                                    Surgeon__r.LastName,Surgeon__r.Suffix__c,Surgeon__r.Technique__c,
                                                    Surgeon__r.Expertise_integration_purpose__c,Surgeon__r.Medical_School__c,
                                                    Surgeon__r.Residency__c,Surgeon__r.Fellowship__c,Surgeon__r.Medical_Degree__c,
                                                    Surgeon__r.Physician_Specialty__c,Surgeon__r.PersonMailingCity,
                                                    Surgeon__r.PersonMailingCountry,Surgeon__r.PersonMailingPostalCode,
                                                    Surgeon__r.PersonMailingState,Surgeon__r.PersonMailingStreet,Surgeon__r.MDM_SAP_ID__c,
                                                    Surgeon__r.Physicians_Locator__c
                                                    from Practice_Surgeon_Link__c where Practice__c IN :MatchAccount.keySet()];       
                                                //    and (Practice_Surgeon_Link__c.Surgeon__r.Physician_Specialty__c.contains(SpecialityCondition))];
        }
    system.debug('inside else------------------------------');
    list<String> ValidPractice = new list<String>();
    
  if(!PSL.isEmpty()){
     //Add all the Medical practice with associated physican
  //   for(Account ma :MatchAccount.values())
   //  {
        
        
            for(Practice_Surgeon_Link__c pp :PSL)
            {
             list<Practice_Surgeon_Link__c> temp = new list<Practice_Surgeon_Link__c>();
             if(!SuVsPr.containsKey(pp.Practice__c))
             {
                temp.add(pp);
                SuVsPr.put(pp.Practice__c,temp);
                ValidPractice.add(pp.Practice__c);
        //        SarId.add(pp.Surgeon__c);
                
             }
             else 
             {
                temp = SuVsPr.get(pp.Practice__c);
                temp.add(pp);
                SuVsPr.put(pp.Practice__c,temp);
                
             }
            
            
             /*
                if(pp.Practice__c == ma.id)
                {
                    temp.add(pp);
                }
                */
            
   /*
        if(!temp.isEmpty())
        {
            SuVsPr.put(ma.id,temp);
            ValidPractice.add(ma.id);
        }
        }
        */
  //  
  }  
    }
   
    if(!ValidPractice.isEmpty())
        
    { 
     // Collect all physician Id
        for(Practice_Surgeon_Link__c pp :PSL)
        {
            SarId.add(pp.Surgeon__c);
            //SuVsPr.put(pp.Practice__c);
        }
       
        list<String> SarId1 = new list<String>();
        SarId1.addAll(SarId);
        
        
      map<String,String> HcVsPy = new map<String,String>();
      
     list<Healthcare_Surgeon_Relationship__c> HSR = [select id,Healthcare_Facility__c,Healthcare_Facility__r.Name,
                                                            Healthcare_Facility__r.ShippingCity,Healthcare_Facility__r.ShippingCountry,                                                           
                                                            Healthcare_Facility__r.ShippingState,Surgeon__c
                                                            from Healthcare_Surgeon_Relationship__c where Surgeon__c IN :SarId];
     
     // map for physiacn associated with Health care facility
  //   for(integer i=0 ;i<SarId1.size();i++)
  //   {
     //   String temp;
        for(Healthcare_Surgeon_Relationship__c hh :HSR)
        {
         //   if(SarId1[i]==hh.Surgeon__c)
          //  {
              String temp = '';
            if(!HcVsPy.containsKey(hh.Surgeon__c)){
              //  if(temp =='' || temp==null) 
              //  {
              //  temp='';
                temp = hh.Healthcare_Facility__r.Name + ',' + hh.Healthcare_Facility__r.ShippingCity;
                temp = temp + ',' + hh.Healthcare_Facility__r.ShippingState + ',';
                temp = temp + hh.Healthcare_Facility__r.ShippingCountry;
                HcVsPy.put(hh.Surgeon__c,temp);
                }
                else
                {
                temp = HcVsPy.get(hh.Surgeon__c);
                temp = temp + '>' + hh.Healthcare_Facility__r.Name + ',' + hh.Healthcare_Facility__r.ShippingCity;
                temp = temp + ',' + hh.Healthcare_Facility__r.ShippingState + ',';
                temp = temp + hh.Healthcare_Facility__r.ShippingCountry;                    
                }
            }
   //     }
        
     //   if(temp!='')
        
   //  } 
    Boolean isPass = false;
    Boolean isCheck = false;
    if(SpecialityCondition == 'ALL'){
        isPass = true ;
    }
   // else{
   //   if(ps.Surgeon__r.Physician_Specialty__c !=null){
  //        isPass = true ;
   //   }
  //  }
    
        System.debug('Valid practise size is--------------->' + ValidPractice.size());
         for(integer i=0 ; i<ValidPractice.size();i++)
         {
             for(Practice_Surgeon_Link__c ps :SuVsPr.get(ValidPractice[i]))
             {
              //  System.debug('CONDITION IS-------->' +ps.Surgeon__r.Physician_Specialty__c);
              //  System.debug('Surgen IS-------->' +SpecialityCondition);
               if(isPass)
               {
                 if(ps.Surgeon__r.Physicians_Locator__c == true)
                 isCheck = true;
                 else
                 isCheck = false;
               }
               else
               { 
                  system.debug('else condition phy spec ------------------' + ps.Surgeon__r.Physician_Specialty__c);
                  system.debug('else condition phy locator ------------------' + ps.Surgeon__r.Physicians_Locator__c);
                  if(ps.Surgeon__r.Physician_Specialty__c !=null){
                    
                if(ps.Surgeon__r.Physician_Specialty__c.contains(SpecialityCondition) && ps.Surgeon__r.Physicians_Locator__c == true)
                    isCheck = true;
                else
                    isCheck = false;
               }
               else
                   isCheck = false;
               }  
           System.debug('IsCheck value is------------------------>' +isCheck);
           if(isCheck){     
            Physician_Locator_Output po = new Physician_Locator_Output();
            po.MedicalPracticeId = ps.Practice__c;
            po.PhysicianId = ps.Surgeon__r.MDM_SAP_ID__c;
            po.FirstName= ps.Surgeon__r.FirstName;
            po.MiddleName= ps.Surgeon__r.Middle_Name__c;
            po.LastName= ps.Surgeon__r.LastName;
            po.Suffix= ps.Surgeon__r.Suffix__c;
            po.Medical_degree = ps.Surgeon__r.Medical_Degree__c;
            po.MIS_Flag = ps.Surgeon__r.Technique__c;           
            po.Physician_Special_Interest = ps.Surgeon__r.Expertise_integration_purpose__c;
            po.Graduate= ps.Surgeon__r.Medical_School__c;
            po.Residency = ps.Surgeon__r.Residency__c;
            po.Fellowship= ps.Surgeon__r.Fellowship__c;
            po.Specialties = ps.Surgeon__r.Physician_Specialty__c;
            po.office_Street= ps.Surgeon__r.PersonMailingStreet;            
            po.office_City = ps.Surgeon__r.PersonMailingCity;
            po.office_StateOrProvince = ps.Surgeon__r.PersonMailingState;
            po.office_ZipCodeOrPostalCode = ps.Surgeon__r.PersonMailingPostalCode;
            po.office_Country = ps.Surgeon__r.PersonMailingCountry;
            po.PracticeName = MatchAccount.get(ValidPractice[i]).name;
            po.PhoneNumber = MatchAccount.get(ValidPractice[i]).phone;
            po.FaxNumber=MatchAccount.get(ValidPractice[i]).Fax;
            po.WebsiteUrl=MatchAccount.get(ValidPractice[i]).Website;
            po.Medical_practice_Street = MatchAccount.get(ValidPractice[i]).ShippingStreet;
            po.Medical_practice_City = MatchAccount.get(ValidPractice[i]).ShippingCity;
            po.Medical_practice_PostalCode = MatchAccount.get(ValidPractice[i]).ShippingPostalCode;
            po.Medical_practice_StateOrProvince = MatchAccount.get(ValidPractice[i]).ShippingState;
            po.Medical_practice_Country = MatchAccount.get(ValidPractice[i]).ShippingCountry;
            if(HcVsPy.containsKey(ps.Surgeon__c)) 
            po.Hospital_Affiliations = HcVsPy.get(ps.Surgeon__c);

         // po.Joint_Procedure_Specialties = ta.Speciality_Type__c;

            result.add(po);
                } 
               
             }
         
         
         }

    }// End of valid practice  
  
  }// End of match Account loop
               return result;
        
     }
}