force-app/main/default/objects/Account/fields/Expertise_Integration_purpose__c.field-meta.xml
<CustomField>
    <fullName>Expertise_Integration_purpose__c</fullName>
    <label>Enterprise Integration purpose</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Anterior Supine</fullName>
            </value>
            <value>
                <fullName>Partial Knee</fullName>
            </value>
            <value>
                <fullName>Patient Specific Instruments</fullName>
            </value>
            <value>
                <fullName>Vanguard</fullName>
            </value>
            <value>
                <fullName>VitaminE</fullName>
            </value>
            <value>
                <fullName>Vivacit-E Hip Construct</fullName>
            </value>
            <value>
                <fullName>XP</fullName>
            </value>
            <value>
                <fullName>Chondrofix</fullName>
            </value>
            <value>
                <fullName>Early Intervention</fullName>
            </value>
            <value>
                <fullName>Gel-One</fullName>
            </value>
            <value>
                <fullName>Persona Knee System</fullName>
            </value>
            <value>
                <fullName>PFJ</fullName>
            </value>
            <value>
                <fullName>Trabecular Metal Total Ankle</fullName>
            </value>
            <value>
                <fullName>Zimmer Unicompartmental Knee</fullName>
            </value>
            <value>
                <fullName>Oxford Partial Knee</fullName>
            </value>
            <value>
                <fullName>Zimmer Biomet Signature Solutions</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/GPL_Profile__c.field-meta.xml
<CustomField>
    <fullName>GPL_Profile__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Zimmer.com Profile</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>$Source.Id</field>
            <operation>equals</operation>
            <valueField>$Source.Id</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>GPL_Profile__c</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/Languages__c.field-meta.xml
<CustomField>
    <fullName>Languages__c</fullName>
    <description>The languages a surgeon speaks</description>
    <inlineHelpText>Select the languages a surgeon speaks proficiently</inlineHelpText>
    <label>Languages</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>English</fullName>
                <default>true</default>
                <label>English</label>
            </value>
            <value>
                <fullName>French</fullName>
            </value>
            <value>
                <fullName>German</fullName>
            </value>
            <value>
                <fullName>Spanish</fullName>
            </value>
            <value>
                <fullName>Chinese</fullName>
            </value>
            <value>
                <fullName>Hebrew</fullName>
            </value>
            <value>
                <fullName>Russian</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/MDM_SAP_ID__c.field-meta.xml
<CustomField>
    <fullName>MDM_SAP_ID__c</fullName>
    <description>The identification number assigned from the DCS/SAP/DPS systems</description>
    <encryptionScheme>None</encryptionScheme>
    <externalId>true</externalId>
    <inlineHelpText>This field identifies the DCS/SAP/DPS ID</inlineHelpText>
    <label>Zimmer Account Number</label>
    <length>12</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Account/fields/Physicians_Locator__c.field-meta.xml
<CustomField>
    <fullName>Physicians_Locator__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Indicates where we recieved the list information</description>
    <inlineHelpText>Check this box if you want to select this list for your mailng</inlineHelpText>
    <label>Physicians Locator</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/fields/Specialty_integration__c.field-meta.xml
<CustomField>
    <fullName>Specialty_integration__c</fullName>
    <label>Specialty integration</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Dental</fullName>
            </value>
            <value>
                <fullName>Elbow</fullName>
            </value>
            <value>
                <fullName>Foot and Ankle</fullName>
            </value>
            <value>
                <fullName>Hand and Wrist</fullName>
            </value>
            <value>
                <fullName>Hip</fullName>
            </value>
            <value>
                <fullName>Knee</fullName>
            </value>
            <value>
                <fullName>Orthopedic</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
            <value>
                <fullName>Pain Medicine</fullName>
            </value>
            <value>
                <fullName>Plastics</fullName>
            </value>
            <value>
                <fullName>Podiatry</fullName>
            </value>
            <value>
                <fullName>Primary Care</fullName>
            </value>
            <value>
                <fullName>Rheumetology</fullName>
            </value>
            <value>
                <fullName>Shoulder</fullName>
            </value>
            <value>
                <fullName>Spine</fullName>
            </value>
            <value>
                <fullName>Sports Medicine</fullName>
            </value>
            <value>
                <fullName>Trauma</fullName>
            </value>
            <value>
                <fullName>Wound Care</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Technique__c.field-meta.xml
<CustomField>
    <fullName>Technique__c</fullName>
    <description>The techniques commonly used by this surgeon</description>
    <inlineHelpText>Enter the surgery techniques commonly used by this surgeon (max 255 characters)</inlineHelpText>
    <label>Technique</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>MIS</fullName>
            </value>
            <value>
                <fullName>MIS II</fullName>
            </value>
            <value>
                <fullName>MIS Mini</fullName>
            </value>
            <value>
                <fullName>Quad Sparing</fullName>
            </value>
            <value>
                <fullName>PSI</fullName>
            </value>
            <value>
                <fullName>PSI Uni Knee</fullName>
            </value>
            <value>
                <fullName>Anterior Supine Hip</fullName>
            </value>
            <value>
                <fullName>Smart Tools – Knee</fullName>
            </value>
            <value>
                <fullName>Smart Tools – Hip</fullName>
            </value>
            <value>
                <fullName>Mini Hip – Posteriolateral</fullName>
            </value>
            <value>
                <fullName>Mini Hip –Anteriorlateral</fullName>
            </value>
            <value>
                <fullName>Subchondroplasty</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/GPL_Profile__c/GPL_Profile__c.object-meta.xml
<CustomObject>
    <label>GPL Profile</label>
    <nameField>
        <displayFormat>GPL_P-{0000}</displayFormat>
        <label>GPL Profile ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>GPL Profiles</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/GPL_Profile__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>GPL Profiles</relationshipLabel>
    <relationshipName>GPL_Profiles</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/GPL_Profile__c/fields/Devices__c.field-meta.xml
<CustomField>
    <fullName>Devices__c</fullName>
    <label>Devices</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Adkins Strut</fullName>
            </value>
            <value>
                <fullName>Chondrofix</fullName>
            </value>
            <value>
                <fullName>Early Intervention</fullName>
            </value>
            <value>
                <fullName>Gel-One</fullName>
            </value>
            <value>
                <fullName>Oxford Partial Knee</fullName>
            </value>
            <value>
                <fullName>Patient Specific Instruments</fullName>
            </value>
            <value>
                <fullName>Pectus Bar</fullName>
            </value>
            <value>
                <fullName>Persona Knee System</fullName>
            </value>
            <value>
                <fullName>PFJ</fullName>
            </value>
            <value>
                <fullName>RibFix Blu</fullName>
            </value>
            <value>
                <fullName>SternaLock 360</fullName>
            </value>
            <value>
                <fullName>SternaLock Blu</fullName>
            </value>
            <value>
                <fullName>Trabecular Metal Total Ankle</fullName>
            </value>
            <value>
                <fullName>Vanguard</fullName>
            </value>
            <value>
                <fullName>VitaminE</fullName>
            </value>
            <value>
                <fullName>Vivacit-E-Hip Construct</fullName>
            </value>
            <value>
                <fullName>XP</fullName>
            </value>
            <value>
                <fullName>Zimmer Biomet Signature Solutions</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/GPL_Profile__c/fields/Groups__c.field-meta.xml
<CustomField>
    <fullName>Groups__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Groups</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/GPL_Profile__c/fields/Honors__c.field-meta.xml
<CustomField>
    <fullName>Honors__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Honors</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/GPL_Profile__c/fields/MasterId__c.field-meta.xml
<CustomField>
    <fullName>MasterId__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <externalId>true</externalId>
    <label>Master ID</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/GPL_Profile__c/fields/Procedures__c.field-meta.xml
<CustomField>
    <fullName>Procedures__c</fullName>
    <label>Procedures</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Anterior Hip Replacement</fullName>
            </value>
            <value>
                <fullName>Anterior Supine</fullName>
            </value>
            <value>
                <fullName>MIS</fullName>
            </value>
            <value>
                <fullName>Mobi-C Cervical Disc Replacement</fullName>
            </value>
            <value>
                <fullName>mymobility® Mobile App</fullName>
            </value>
            <value>
                <fullName>Partial Knee Replacement</fullName>
            </value>
            <value>
                <fullName>ROSA® Knee</fullName>
            </value>
            <value>
                <fullName>ROSA® Spine</fullName>
            </value>
            <value>
                <fullName>ROSA ONE® Brain</fullName>
            </value>
            <value>
                <fullName>Subchondroplasty</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/GPL_Profile__c/fields/Publications__c.field-meta.xml
<CustomField>
    <fullName>Publications__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Publications</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/GPL_Profile__c/fields/Specialties__c.field-meta.xml
<CustomField>
    <fullName>Specialties__c</fullName>
    <label>Specialties</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Cardiothoracic</fullName>
            </value>
            <value>
                <fullName>Dental</fullName>
            </value>
            <value>
                <fullName>Elbow</fullName>
            </value>
            <value>
                <fullName>Foot and Ankle</fullName>
            </value>
            <value>
                <fullName>General Surgery/Trauma</fullName>
            </value>
            <value>
                <fullName>Hand and Wrist</fullName>
            </value>
            <value>
                <fullName>Heart Surgery</fullName>
            </value>
            <value>
                <fullName>Hips</fullName>
            </value>
            <value>
                <fullName>Knee</fullName>
            </value>
            <value>
                <fullName>Knee Pain Injection</fullName>
            </value>
            <value>
                <fullName>Orthopedic Trauma</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
            <value>
                <fullName>Pectus Surgery</fullName>
            </value>
            <value>
                <fullName>Pediatric</fullName>
            </value>
            <value>
                <fullName>Plastic</fullName>
            </value>
            <value>
                <fullName>ROSA Knee Robotics</fullName>
            </value>
            <value>
                <fullName>Shoulder</fullName>
            </value>
            <value>
                <fullName>Spine</fullName>
            </value>
            <value>
                <fullName>Spine/Back</fullName>
            </value>
            <value>
                <fullName>Sports Medicine</fullName>
            </value>
            <value>
                <fullName>Thoracic</fullName>
            </value>
            <value>
                <fullName>Trauma</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/GPL_Profile__c/recordTypes/GPL_ClinicProfile.recordType-meta.xml
<RecordType>
    <fullName>GPL_ClinicProfile</fullName>
    <active>true</active>
    <label>GPL Clinic Profile</label>
</RecordType>

force-app/main/default/objects/GPL_Profile__c/recordTypes/GPL_PhysicianProfile.recordType-meta.xml
<RecordType>
    <fullName>GPL_PhysicianProfile</fullName>
    <active>true</active>
    <label>GPL Physician Profile</label>
</RecordType>

force-app/main/default/classes/GplManageProfilePhotoControllerTest.cls
@isTEst
public class GplManageProfilePhotoControllerTest {
    static PageReference pageRef;
   	 private static Id CLINIC_RECORD_TYPE_ID = RecordTypeHelper.getRecordTypeId('GPL_Profile__c','GPL_ClinicProfile');
  
    private static Id physicianRecordTypeId = RecordTypeHelper.getRecordTypeId('GPL_Profile__c','GPL_PhysicianProfile');
    
      static testmethod void testGplManageProfilePhotoController(){
        Id personAccountTypeId = RecordTypeHelper.getRecordTypeId('Account','Physician');                
        Id physicianRTypeId = RecordTypeHelper.getRecordTypeId('GPL_Profile__c','GPL_PhysicianProfile');
          
            Account personAccounts = new Account(
                RecordTypeId = personAccountTypeId,
                FirstName = 'Test',
                LastName = 'Doctor',
                PersonMailingStreet = 'TEST 789 Maple St',
                PersonMailingCity = 'Puerto Villamil',
                PersonMailingState = 'EC',
                PersonMailingPostalCode = 'EC012001',
                PersonMailingCountry = 'EC',
                MDM_SAP_ID__c = '9999999',
                Specialty_integration__c = 'Knee',
                Technique__c = 'MIS',
                Expertise_Integration_purpose__c = 'Gender Knee',
                Physicians_Locator__c = true
            );     
      
        insert personAccounts;
         
       
            GPL_Profile__c profiles = new GPL_Profile__c(
                Account__c = personAccounts.Id,
                MasterId__c = personAccounts.Id,
                RecordTypeId = physicianRTypeId,
                Devices__c = 'Kinectiv',
                Groups__c = 'AAOS',
                Honors__c = 'Man of the Year (2011)',
                Publications__c = 'How to replace a knee (Doctor Review - May 2011)',
                Specialties__c = 'Knee',
                Procedures__c = 'MIS',
                Languages__c = 'English',
                Facebook__c = 'http://www.facebook.com',
                Twitter__c = 'http://www.twitter.com',
                LinkedIn__c = 'http://www.linkedin.com',
                YouTube__c = 'http://www.youtube.com'
            );
           
        
        insert profiles;
          System.debug('%%%%%' + profiles.id);
           
        
		pageRef = new PageReference('/apex/GplManageProfilePhotoPageVF?id=profiles.Id');   
		Test.setCurrentPage(pageRef);  
		pageRef.getParameters().put('id', profiles.Id); 
        Attachment attach=new Attachment();       
        attach.Name='Unit Test Attachment';
        Blob bodyBlob=Blob.valueOf('Unit Test Attachment Body');
        attach.body=bodyBlob;
        attach.parentId=profiles.id;
        
       
        
        List<Attachment> attachments=[select id, name from Attachment where parent.id=:profiles.id];
        System.assertEquals(0, attachments.size());
        
       ApexPages.StandardController stdCtr = new ApexPages.StandardController(profiles);
        
         GplManageProfilePhotoController ctr = new GplManageProfilePhotoController(stdCtr);
          ctr.photo.parentId = profiles.id;
          ctr.photo= attach;
    
        ctr.savePhoto(); 
        
        pageRef = ctr.savePhoto(); 
    }
}