force-app/main/default/objects/Account/fields/GPL_Profile__c.field-meta.xml
<CustomField>
    <fullName>GPL_Profile__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Zimmer.com Profile</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>$Source.Id</field>
            <operation>equals</operation>
            <valueField>$Source.Id</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>GPL_Profile__c</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/Inactive__c.field-meta.xml
<CustomField>
    <fullName>Inactive__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Account Inactive</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/recordTypes/Practice.recordType-meta.xml
<RecordType>
    <fullName>Practice</fullName>
    <active>true</active>
    <description>A record to keep information about the medical practice(s) to which a surgeon is a member</description>
    <label>Medical Practice</label>
</RecordType>

force-app/main/default/objects/GPL_Location__c/GPL_Location__c.object-meta.xml
<CustomObject>
    <label>GPL Location</label>
    <nameField>
        <displayFormat>GPL_L-{0000}</displayFormat>
        <label>GPL Location ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>GPL Locations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/GPL_Location__c/fields/City__c.field-meta.xml
<CustomField>
    <fullName>City__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>City</label>
    <length>80</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/GPL_Location__c/fields/Country__c.field-meta.xml
<CustomField>
    <fullName>Country__c</fullName>
    <label>Country</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>AU</fullName>
            </value>
            <value>
                <fullName>CA</fullName>
            </value>
            <value>
                <fullName>GB</fullName>
            </value>
            <value>
                <fullName>US</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/GPL_Location__c/fields/GPL_Profile__c.field-meta.xml
<CustomField>
    <fullName>GPL_Profile__c</fullName>
    <label>GPL Profile</label>
    <referenceTo>GPL_Profile__c</referenceTo>
    <relationshipLabel>GPL Locations</relationshipLabel>
    <relationshipName>Locations</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/GPL_Location__c/fields/Name__c.field-meta.xml
<CustomField>
    <fullName>Name__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Name</label>
    <required>true</required>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/GPL_Location__c/fields/PostalCode__c.field-meta.xml
<CustomField>
    <fullName>PostalCode__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Postal Code</label>
    <length>10</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/GPL_Location__c/fields/State__c.field-meta.xml
<CustomField>
    <fullName>State__c</fullName>
    <label>State</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Country__c</controllingField>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>AB</fullName>
            </value>
            <value>
                <fullName>ACT</fullName>
            </value>
            <value>
                <fullName>AK</fullName>
            </value>
            <value>
                <fullName>AL</fullName>
            </value>
            <value>
                <fullName>AR</fullName>
            </value>
            <value>
                <fullName>AZ</fullName>
            </value>
            <value>
                <fullName>BC</fullName>
            </value>
            <value>
                <fullName>CA</fullName>
            </value>
            <value>
                <fullName>CO</fullName>
            </value>
            <value>
                <fullName>CT</fullName>
            </value>
            <value>
                <fullName>DC</fullName>
            </value>
            <value>
                <fullName>DE</fullName>
            </value>
            <value>
                <fullName>FL</fullName>
            </value>
            <value>
                <fullName>GA</fullName>
            </value>
            <value>
                <fullName>HI</fullName>
            </value>
            <value>
                <fullName>IA</fullName>
            </value>
            <value>
                <fullName>ID</fullName>
            </value>
            <value>
                <fullName>IL</fullName>
            </value>
            <value>
                <fullName>IN</fullName>
            </value>
            <value>
                <fullName>KS</fullName>
            </value>
            <value>
                <fullName>KY</fullName>
            </value>
            <value>
                <fullName>LA</fullName>
            </value>
            <value>
                <fullName>MA</fullName>
            </value>
            <value>
                <fullName>MB</fullName>
            </value>
            <value>
                <fullName>MD</fullName>
            </value>
            <value>
                <fullName>ME</fullName>
            </value>
            <value>
                <fullName>MI</fullName>
            </value>
            <value>
                <fullName>MN</fullName>
            </value>
            <value>
                <fullName>MO</fullName>
            </value>
            <value>
                <fullName>MS</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/GPL_Profile__c/GPL_Profile__c.object-meta.xml
<CustomObject>
    <label>GPL Profile</label>
    <nameField>
        <displayFormat>GPL_P-{0000}</displayFormat>
        <label>GPL Profile ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>GPL Profiles</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/GPL_Profile__c/fields/GPL_Physician_Locator__c.field-meta.xml
<CustomField>
    <fullName>GPL_Physician_Locator__c</fullName>
    <defaultValue>false</defaultValue>
    <label>GPL Physician Locator</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/GPL_Profile__c/fields/Location_Count__c.field-meta.xml
<CustomField>
    <fullName>Location_Count__c</fullName>
    <label>Location Count</label>
    <summaryForeignKey>GPL_Location__c.GPL_Profile__c</summaryForeignKey>
    <summaryOperation>count</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/GPL_Profile__c/fields/Name__c.field-meta.xml
<CustomField>
    <fullName>Name__c</fullName>
    <formula>IF (!ISBLANK(Account__c), 
IF (Account__r.IsPersonAccount, 
IF (!ISNULL(TEXT(Account__r.Salutation)),TEXT(Account__r.Salutation) &amp; &quot; &quot;,null) &amp; Account__r.FirstName &amp; &quot; &quot; &amp; Account__r.LastName, 
Account__r.Name), 
IF (!ISNULL(TEXT(Contact__r.Salutation)),TEXT(Contact__r.Salutation) &amp; &quot; &quot;,null) &amp; Contact__r.FirstName &amp; &quot; &quot; &amp; Contact__r.LastName)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/GPL_Profile__c/fields/ParentId__c.field-meta.xml
<CustomField>
    <fullName>ParentId__c</fullName>
    <formula>IF(Account__c!=null,Account__c,Contact__c)</formula>
    <label>Parent ID</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/GPL_Profile__c/fields/Picture_Id__c.field-meta.xml
<CustomField>
    <fullName>Picture_Id__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Picture Id</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/SurgeonPortalExtension.cls
public with sharing class SurgeonPortalExtension 
{           
    private final GPL_Profile__c request;    
    public List<GPL_Location__c> gplLocations{get{return gplLocations;} set;}
    public SurgeonPortalExtension(){}
    public SurgeonPortalExtension(ApexPages.StandardController controller)
    {                      
        request=(GPL_Profile__c)controller.getRecord();
        String surgeonId=Apexpages.currentPage().getParameters().get('surgeonId');
        if(surgeonId!=null)
            {
                GPLProfileId=loadSurgeonData(surgeonId);
                system.debug('GPL Profile Id='+GPLProfileId);
            }
            
        loadLocations();
        
    }
    
   private void loadLocations()
   {
       gplLocations = [Select Id, Name, Name__c, City__c, State__c, PostalCode__c, Country__c from GPL_Location__c where GPL_Profile__c =: request.id];   
   }
    public Id GPLProfileId 
    {       
        get;
        set;    
    }  

    public Id SelectedLocationId 
    {       
        get;
        set;    
    }
    
    public Id loadSurgeonData(String surgeonId)
    {
        Id gplId=null;
                        
        for(Account surgeonPersonAccount:[select Id,IsPersonAccount from Account where PersonContactId=:surgeonId limit 1])
        {
                if(surgeonPersonAccount.IsPersonAccount)
                {
                    surgeonId=surgeonPersonAccount.Id;                  
                }
        }
        
        system.debug('surgeonId='+surgeonId);
        if(surgeonId.length()==18)surgeonId=surgeonId.substring(0,15); 
            
        for(GPL_Profile__c gplProfile:[select Id from GPL_Profile__c where ParentId__c=:surgeonId limit 1])
        {
            gplId=gplProfile.Id;
        }           
        return gplId;       
                
    }
     
    public PageReference doAction()
    {
        if(GPLProfileId!=null)
        {
            PageReference pr = new PageReference('/apex/SurgeonPortalView?id='+GPLProfileId);
            pr.setRedirect(true);
            return pr;
        }
        else
        {
            PageReference pr = new PageReference('/apex/SurgeonPortalError');
            pr.setRedirect(true);
            return pr;
        }       
    }
    
    public PageReference UploadPhoto()
    {                
        //PageReference pr = new PageReference('/p/attach/NoteAttach?pid='+request.Id+'&retURL=%2Fservlet%2Fservlet.Integration%3Flid=01NL0000000CeQH%26eid='+request.Id+'%26ic=1%26autoMapValues=1');        
        PageReference pr = Page.Surgeon_portal_PhotoPage;
        pr.getParameters().put('id',request.Id);        
        pr.setRedirect(true);
        return pr;
                    
    }
    
    public string fileName{
        get;set;    
    }  
      
    public Blob fileBody{
        get;set;    
    } 
    public PageReference UploadFile()  
    {  
        PageReference pr;  
        if(fileBody != null && fileName != null)  
        {
          GPL_Profile__c gplRequest=[select Picture_Id__c,Id from GPL_Profile__c where Id=:request.Id];  
          Attachment myAttachment  = new Attachment();  
          myAttachment.Body = fileBody;  
          myAttachment.Name = fileName;  
          myAttachment.ParentId = gplRequest.Id;            
          insert myAttachment;
          
          gplRequest.Picture_Id__c = myAttachment.Id;
          update gplRequest;
          
          pr = new PageReference('/apex/SurgeonPortalView?id='+gplRequest.Id);
          pr.setRedirect(true);
          return pr;           
        }  
        return null;  
    }
    
   //Open record in edit mode.
    public PageReference edit()
    {
        /****************************************************************************************************
        Purpose: edit method is used on Edit button to return SurgeonPortalEdit visualforce page
        which is displayed on visualforce page                      
        Parameters: None
        Returns: This property returns a PageReference.
        ******************************************************************************************************/        
        String returnPage;
        returnPage=ApexPages.currentPage().getParameters().get('returnURL');        
        return new PageReference(returnPage);        
    }
      
    public PageReference save()
    {
        GPL_Profile__c gplRequest=[select Id,GPL_Physician_Locator__c,Inactive__c from GPL_Profile__c where Id=:request.Id limit 1];
        if(gplRequest.GPL_Physician_Locator__c == False){
        request.GPL_Physician_Locator__c = True;
        request.Inactive__c=False;
        }
        String returnPage;
        try{                
        update request;
        }
        catch(Exception e){
             ApexPages.addMessages(e);
             return null;
        } 
        returnPage=ApexPages.currentPage().getParameters().get('returnURL');
        return new PageReference(returnPage);                   
    }
        
    public PageReference newLocation()
    {          
      GPL_Profile__c gplRequest=[select Name from GPL_Profile__c where Id=:request.Id];
      //return new Pagereference('/apex/SurgeonPortalDetailEdit?CF00NL0000000KouT_lkid='+gplRequest.Id+'&CF00NL0000000KouT='+gplRequest.Name+'&sfdc.override=1');
      return new Pagereference('/apex/SurgeonPortalDetailEdit?CF00NC0000005FaHm_lkid='+gplRequest.Id+'&CF00NC0000005FaHm='+gplRequest.Name+'&sfdc.override=1');
    }
    
   public void deleteLocation()
   {
       
      if (SelectedLocationId == null) {
          return;
      }
      
      GPL_Location__c tobeDeleted = null;
      for(GPL_Location__c gpl : gplLocations)
       if (gpl.Id == SelectedLocationId) {
          tobeDeleted = gpl;
          break;
       }
      
      if (tobeDeleted != null) {
       Delete tobeDeleted;
     }
     loadLocations();
     /*
     String returnPage;
     returnPage='/apex/SurgeonPortalView?id='+request.id;
     PageReference pr = new PageReference(returnPage);
     return pr;*/
   } 
   
   /*
   public boolean checkRequiredFieldsSave(){
   
   String message='';      
        Boolean success=true;
        
        if(request.Location_Count__c==1)
        {
            message='You Cannot delete this Practice Locations, as atleast One Practice Location for a Surgeon Must Exist';
            success=false;
            ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.INFO, message));
            //return success;
        }
        return success;
   
   }*/  
    public String getLt(){
        return '<';
    }   
    public String getGt(){
        return '>';
    }     
}