force-app/main/default/objects/Account/fields/GPL_Profile__c.field-meta.xml
<CustomField>
    <fullName>GPL_Profile__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Zimmer.com Profile</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>$Source.Id</field>
            <operation>equals</operation>
            <valueField>$Source.Id</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>GPL_Profile__c</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/Inactive__c.field-meta.xml
<CustomField>
    <fullName>Inactive__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Account Inactive</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/fields/Physicians_Locator__c.field-meta.xml
<CustomField>
    <fullName>Physicians_Locator__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Indicates where we recieved the list information</description>
    <inlineHelpText>Check this box if you want to select this list for your mailng</inlineHelpText>
    <label>Physicians Locator</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contact/fields/GPL_Profile__c.field-meta.xml
<CustomField>
    <fullName>GPL_Profile__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Zimmer.com Profile</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>$Source.Id</field>
            <operation>equals</operation>
            <valueField>GPL_Profile__c.Contact__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>GPL_Profile__c</referenceTo>
    <relationshipLabel>Contacts</relationshipLabel>
    <relationshipName>Contacts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Inactive__c.field-meta.xml
<CustomField>
    <fullName>Inactive__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Indicates whether this contact is inactive</description>
    <inlineHelpText>Check the box to Indicate that this contact is no longer an active contact</inlineHelpText>
    <label>Inactive</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Physicians_Locator__c.field-meta.xml
<CustomField>
    <fullName>Physicians_Locator__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Indicates where we recieved the list information</description>
    <inlineHelpText>Check this box if you want to select this list for your mailng</inlineHelpText>
    <label>Physicians Locator</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Specialty_Type__c.field-meta.xml
<CustomField>
    <fullName>Specialty_Type__c</fullName>
    <label>Specialty Type</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Bone Grafting</fullName>
            </value>
            <value>
                <fullName>Cosmetic Dentistry</fullName>
            </value>
            <value>
                <fullName>Endodontics</fullName>
            </value>
            <value>
                <fullName>General Dentistry</fullName>
            </value>
            <value>
                <fullName>Implant Dentistry</fullName>
            </value>
            <value>
                <fullName>Oral Surgery</fullName>
            </value>
            <value>
                <fullName>Periodontics</fullName>
            </value>
            <value>
                <fullName>Prosthodontics</fullName>
            </value>
            <value>
                <fullName>Ridge Augmentation</fullName>
            </value>
            <value>
                <fullName>Sinus Lifts</fullName>
            </value>
            <value>
                <fullName>Site Preservation</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/Website__c.field-meta.xml
<CustomField>
    <fullName>Website__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Website</label>
    <length>48</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/GPL_Location__c/GPL_Location__c.object-meta.xml
<CustomObject>
    <label>GPL Location</label>
    <nameField>
        <displayFormat>GPL_L-{0000}</displayFormat>
        <label>GPL Location ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>GPL Locations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/GPL_Location__c/fields/GPL_Profile__c.field-meta.xml
<CustomField>
    <fullName>GPL_Profile__c</fullName>
    <label>GPL Profile</label>
    <referenceTo>GPL_Profile__c</referenceTo>
    <relationshipLabel>GPL Locations</relationshipLabel>
    <relationshipName>Locations</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/GPL_Location__c/fields/Name__c.field-meta.xml
<CustomField>
    <fullName>Name__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Name</label>
    <required>true</required>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/GPL_Profile__c/GPL_Profile__c.object-meta.xml
<CustomObject>
    <label>GPL Profile</label>
    <nameField>
        <displayFormat>GPL_P-{0000}</displayFormat>
        <label>GPL Profile ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>GPL Profiles</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/GPL_Profile__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>GPL Profiles</relationshipLabel>
    <relationshipName>GPL_Profiles</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/GPL_Profile__c/fields/FirstName__c.field-meta.xml
<CustomField>
    <fullName>FirstName__c</fullName>
    <formula>IF (Account__c != null, Account__r.FirstName,
    IF (Contact__c != null, Contact__r.FirstName,&apos;&apos;)
)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>First Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/GPL_Profile__c/fields/LastName__c.field-meta.xml
<CustomField>
    <fullName>LastName__c</fullName>
    <formula>IF (Account__c != null, Account__r.LastName,
    IF (Contact__c != null, Contact__r.LastName,&apos;&apos;)
)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Last Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/GPL_Profile__c/fields/Name__c.field-meta.xml
<CustomField>
    <fullName>Name__c</fullName>
    <formula>IF (!ISBLANK(Account__c), 
IF (Account__r.IsPersonAccount, 
IF (!ISNULL(TEXT(Account__r.Salutation)),TEXT(Account__r.Salutation) &amp; &quot; &quot;,null) &amp; Account__r.FirstName &amp; &quot; &quot; &amp; Account__r.LastName, 
Account__r.Name), 
IF (!ISNULL(TEXT(Contact__r.Salutation)),TEXT(Contact__r.Salutation) &amp; &quot; &quot;,null) &amp; Contact__r.FirstName &amp; &quot; &quot; &amp; Contact__r.LastName)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/GPL_Profile__c/fields/Specialty_Type__c.field-meta.xml
<CustomField>
    <fullName>Specialty_Type__c</fullName>
    <label>Specialty Type</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Bone Grafting</fullName>
            </value>
            <value>
                <fullName>Cosmetic Dentistry</fullName>
            </value>
            <value>
                <fullName>Endodontics</fullName>
            </value>
            <value>
                <fullName>General Dentistry</fullName>
            </value>
            <value>
                <fullName>Implant Dentistry</fullName>
            </value>
            <value>
                <fullName>Oral Surgery</fullName>
            </value>
            <value>
                <fullName>Periodontics</fullName>
            </value>
            <value>
                <fullName>Prosthodontics</fullName>
            </value>
            <value>
                <fullName>Ridge Augmentation</fullName>
            </value>
            <value>
                <fullName>Sinus Lifts</fullName>
            </value>
            <value>
                <fullName>Site Preservation</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/GplCreateProfileFromContactController.cls
public with sharing class GplCreateProfileFromContactController {
    private final Contact contact;
    public GPL_Profile__c profile { get; set; }
    public GPL_Location__c location { get; set; }

       public GplCreateProfileFromContactController(ApexPages.StandardController stdController)
       {
        contact = (Contact)stdController.getRecord();
        Id id = contact.Id;
        profile = null;
        list<GPL_Profile__c> profiles = [SELECT Id, Name__c, FirstName__c, Inactive__c, LastName__c, Contact__c, Specialty_Type__c FROM GPL_Profile__c WHERE Contact__c = :id LIMIT 1];
        if ((profiles != null) && (!profiles.isEmpty()))
        {
            profile = profiles.get(0);
        }
        System.debug('------------------ LEAVE Constructor---------------------');
      }
    
    public PageReference back()
    {
        return new ApexPages.Standardcontroller(contact).view();
    }
    
    public PageReference init()
    {
        System.debug('------------------ IN Init()---------------------');
        if (profile != null)
        {
            PageReference profilePage = new ApexPages.Standardcontroller(profile).view(); 
            profilePage.setRedirect(true);
            return profilePage;
        } else {
            return null;
        }
    }
    
    public PageReference create()
    {
        profile = null;
        Id id = contact.Id;
        
        Contact c = [SELECT Id, RecordTypeId, Salutation, FirstName, LastName, GPL_Profile__c, Physicians_Locator__c,
         MailingCity, MailingCountry, Fax, Name, Phone, MailingPostalCode, MailingStreet, MailingState, Website__c, Specialty_Type__c FROM Contact WHERE Id = :id];
         
        profile = GplProfileBuilder.buildProfile(c);
        try{
            insert profile;
        }
        catch(Exception e)
        {
                ApexPages.addMessages(e);
        }
         
        location= GplProfileBuilder.buildlocation(c);
        location.GPL_Profile__c=profile.Id;
        
        try{
            insert location;
        }
        catch(Exception e){
            ApexPages.addMessages(e);
        } 
        c.GPL_Profile__c=profile.Id;
        c.Physicians_Locator__c=true;
        
        try{
        update c;   
        }
        catch(Exception e)
        {
            ApexPages.addMessages(e);
        }
         
        PageReference profilePage = new ApexPages.StandardController(profile).view();
        profilePage.setRedirect(true);
        return profilePage;
    }
    /*
    static testMethod void testGplCreateProfileFromContactController()
    {
        Id hospitalAccountTypeId = RecordTypeHelper.getRecordTypeId('Account','Healthcare Facility');
        Account account = new Account(
            RecordTypeId = hospitalAccountTypeId,
            Name = 'Test Hospital',
            ShippingStreet = 'TEST 789 Maple St',
            ShippingCity = 'Puerto Villamil',
            ShippingState = 'EC',
            ShippingPostalCode = 'EC012001',
            ShippingCountry = 'EC'
        );
        insert(account);
        Contact contact = new Contact(
            FirstName = 'Test',
            LastName = 'Contact',
            Salutation = 'Dr.'
        );
        PageReference pageRef = Page.GplCreateProfileFromContactPage;
        insert(contact);
        Test.setCurrentPage(pageRef);
        ApexPages.StandardController sc = new ApexPages.StandardController(contact);
        GplCreateProfileFromContactController controller = new GplCreateProfileFromContactController(sc);
        System.assertEquals(null, controller.init());
        controller.create();
        System.assertNotEquals(null, controller.profile);
        System.assertNotEquals(null, controller.init());
    }
    
*/
}