force-app/main/default/objects/Account/fields/Item_Clash_Conversion__c.field-meta.xml
<CustomField>
    <fullName>Item_Clash_Conversion__c</fullName>
    <label>Item Clash Conversion</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/K_Bill_Cap_Kits__c.field-meta.xml
<CustomField>
    <fullName>K_Bill_Cap_Kits__c</fullName>
    <label>K-Bill (Cap Kits)</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Legal_Amendment__c.field-meta.xml
<CustomField>
    <fullName>Legal_Amendment__c</fullName>
    <label>Legal Amendment</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/MDM_SAP_ID__c.field-meta.xml
<CustomField>
    <fullName>MDM_SAP_ID__c</fullName>
    <description>The identification number assigned from the DCS/SAP/DPS systems</description>
    <encryptionScheme>None</encryptionScheme>
    <externalId>true</externalId>
    <inlineHelpText>This field identifies the DCS/SAP/DPS ID</inlineHelpText>
    <label>Zimmer Account Number</label>
    <length>12</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Account/recordTypes/Distributor.recordType-meta.xml
<RecordType>
    <fullName>Distributor</fullName>
    <active>true</active>
    <description>A record to keep information about Zimmer Distributors</description>
    <label>Distributor</label>
</RecordType>

force-app/main/default/objects/Contact/fields/Contract_Signatory__c.field-meta.xml
<CustomField>
    <fullName>Contract_Signatory__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>Person responsible for contract approval</inlineHelpText>
    <label>Contract Signatory</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Username__c.field-meta.xml
<CustomField>
    <fullName>Username__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>This field is used to tie the contact records in Salesforce.com to their respective user record.</description>
    <label>User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Contacts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/DocuSign_Credential__c/DocuSign_Credential__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>Used to Store DocuSign Credentials and Signer 2 Recipient/Terry Glogovsky</description>
    <label>DocuSign Credential</label>
</CustomObject>

force-app/main/default/objects/DocuSign_Credential__c/fields/Username__c.field-meta.xml
<CustomField>
    <fullName>Username__c</fullName>
    <description>This is the Username for DocuSign Credential</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>This is the Username for DocuSign Credential</inlineHelpText>
    <label>Username</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/DocuSign_Template__c/DocuSign_Template__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>This custom setting associates logic/criteria with a respective DocuSign Template</description>
    <label>DocuSign Template</label>
</CustomObject>

force-app/main/default/objects/DocuSign_Template__c/fields/Logic__c.field-meta.xml
<CustomField>
    <fullName>Logic__c</fullName>
    <description>This field contains logic/criteria to associate with a DocuSign Template</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>This field contains logic/criteria to associate with a DocuSign Template</inlineHelpText>
    <label>Logic</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/DocuSign_Template__c/fields/Template_Id__c.field-meta.xml
<CustomField>
    <fullName>Template_Id__c</fullName>
    <description>This field contains DocuSign Template Id</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>This field contains DocuSign Template Id</inlineHelpText>
    <label>Template Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/DocuSignAccountBatchTest.cls
/*********************************************************************************************
    Description: This class test the DocuSignAccountBatch functionality to create DocuSign 
    Status records with intended Recipients
    History:
    15/05/2017  Diane Enriquez/Appirio    Initial Development
 **********************************************************************************************/
@isTest
public with sharing class DocuSignAccountBatchTest {
    public static void createTestData(){
        List<Account> accountList = new List<Account>();
        for(Integer i = 0; i < 5; i++){
            accountList.add(new Account(Name = 'Test'+i, Legal_Amendment__c = 'Yes', K_Bill_Cap_Kits__c =((i/2) == 0?'Yes':'No'), Item_Clash_Conversion__c = ((i/2) == 0?'Yes':'No'), MDM_SAP_ID__c =  '100'+i));
        }
        
        insert accountList;
        List<Contact> contactList = new List<Contact>();
        List<AccountTeamMember> teamMemberList = new List<AccountTeamMember>();
        List<Attachment> attachmentList = new List<Attachment>();
        Integer i = 0;
        for(Account account: accountList){
            contactList.add(new Contact(LastName = account.Name, Contract_Signatory__c = true, AccountId = account.Id, Email='test@test.com'));
            teamMemberList.add(new AccountTeamMember(UserId = UserInfo.getUserId(), AccountAccessLevel='Edit', AccountId = account.Id, TeamMemberRole = 'Distributor'));
            attachmentList.add(new Attachment(ParentId = account.Id, Name = '100'+(i++)+'_'+((i/2) == 0?'Yes':'No'), body = Blob.valueOf('12123')));
        }
        insert contactList;
        insert teamMemberList;
        insert attachmentList;
        DocuSign_Credential__c setting = DocuSign_Credential__c.getOrgDefaults();
        setting.UserName__c = 'Some Value';
        insert setting;
        
        List<DocuSign_Template__c> templateList = new List<DocuSign_Template__c>();
        templateList.add(new DocuSign_Template__c(Name = '1', Template_Id__c = 'DocuSign Template Id', Logic__c = ' createddate = today '));
        templateList.add(new DocuSign_Template__c(Name = '2', Template_Id__c = 'DocuSign Template Id', Logic__c = ' createddate = today '));
        insert templateList;
    }
    
    public static TestMethod void testRedirectToRecepientView(){
        createTestData();
        Test.setMock(HttpCalloutMock.class, new DocuSignRESTAPITestMock());
        Test.startTest();
        Database.executeBatch(new DocuSignAccountBatch(), 5);
        Test.stopTest();
        system.AssertNotEquals(0, [select count() from dsfs__DocuSign_Status__c]);
    }
}