force-app/main/default/objects/Account/fields/Latitude__c.field-meta.xml
<CustomField>
    <fullName>Latitude__c</fullName>
    <label>Latitude</label>
    <precision>11</precision>
    <scale>8</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Account/fields/Longitude__c.field-meta.xml
<CustomField>
    <fullName>Longitude__c</fullName>
    <label>Longitude</label>
    <precision>11</precision>
    <scale>8</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Account/fields/Organization__c.field-meta.xml
<CustomField>
    <fullName>Organization__c</fullName>
    <label>Organization</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Parent</fullName>
            </value>
            <value>
                <fullName>Satellite</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/territory__c.field-meta.xml
<CustomField>
    <fullName>territory__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>territory</label>
    <referenceTo>territory__c</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/recordTypes/Distributor.recordType-meta.xml
<RecordType>
    <fullName>Distributor</fullName>
    <active>true</active>
    <description>A record to keep information about Zimmer Distributors</description>
    <label>Distributor</label>
</RecordType>

force-app/main/default/objects/GDL_DistributorEvent__c/GDL_DistributorEvent__c.object-meta.xml
<CustomObject>
    <label>Distributor Event</label>
    <nameField>
        <displayFormat>GDL_E-{0000}</displayFormat>
        <label>Distributor Event ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Distributor Events</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/GDL_DistributorEvent__c/fields/DistributorProfile__c.field-meta.xml
<CustomField>
    <fullName>DistributorProfile__c</fullName>
    <label>Distributor Profile</label>
    <referenceTo>GDL_Profile__c</referenceTo>
    <relationshipLabel>Distributor Events</relationshipLabel>
    <relationshipName>DistributorEvents</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/GDL_DistributorEvent__c/fields/EndDate__c.field-meta.xml
<CustomField>
    <fullName>EndDate__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>End Date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/GDL_DistributorEvent__c/fields/Title__c.field-meta.xml
<CustomField>
    <fullName>Title__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Title</label>
    <length>200</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/GDL_DistributorLink__c/GDL_DistributorLink__c.object-meta.xml
<CustomObject>
    <label>Distributor Link</label>
    <nameField>
        <displayFormat>GDL_L-{0000}</displayFormat>
        <label>Distributor Link ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Distributor Links</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/GDL_DistributorLink__c/fields/DistributorProfile__c.field-meta.xml
<CustomField>
    <fullName>DistributorProfile__c</fullName>
    <label>Distributor Profile</label>
    <referenceTo>GDL_Profile__c</referenceTo>
    <relationshipLabel>Distributor Links</relationshipLabel>
    <relationshipName>DistributorLinks</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/GDL_DistributorLink__c/fields/Target__c.field-meta.xml
<CustomField>
    <fullName>Target__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Target</label>
    <required>true</required>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/GDL_DistributorLink__c/fields/Title__c.field-meta.xml
<CustomField>
    <fullName>Title__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Title</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/GDL_Profile__c/GDL_Profile__c.object-meta.xml
<CustomObject>
    <label>Distributor Profile</label>
    <nameField>
        <displayFormat>GDL_P-{0000}</displayFormat>
        <label>Distributor Profile ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Distributor Profiles</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/GDL_Profile__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Account</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Distributor</value>
        </filterItems>
        <filterItems>
            <field>Account.Organization__c</field>
            <operation>equals</operation>
            <value>Parent</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Distributor Profiles</relationshipLabel>
    <relationshipName>Distributor_Profiles</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/GDL_Profile__c/fields/Content__c.field-meta.xml
<CustomField>
    <fullName>Content__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Content</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/GDL_Profile__c/fields/Image__c.field-meta.xml
<CustomField>
    <fullName>Image__c</fullName>
    <label>Image</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>distributor-1.jpg</fullName>
                <default>true</default>
                <label>distributor-1.jpg</label>
            </value>
            <value>
                <fullName>distributor-2.jpg</fullName>
            </value>
            <value>
                <fullName>distributor-3.jpg</fullName>
            </value>
            <value>
                <fullName>distributor-4.jpg</fullName>
            </value>
            <value>
                <fullName>distributor-5.jpg</fullName>
            </value>
            <value>
                <fullName>distributor-6.jpg</fullName>
            </value>
            <value>
                <fullName>distributor-7.jpg</fullName>
            </value>
            <value>
                <fullName>distributor-8.jpg</fullName>
            </value>
            <value>
                <fullName>distributor-9.jpg</fullName>
            </value>
            <value>
                <fullName>distributor-10.jpg</fullName>
            </value>
            <value>
                <fullName>distributor-11.jpg</fullName>
            </value>
            <value>
                <fullName>distributor-12.jpg</fullName>
            </value>
            <value>
                <fullName>distributor-13.jpg</fullName>
            </value>
            <value>
                <fullName>distributor-14.jpg</fullName>
            </value>
            <value>
                <fullName>distributor-15.jpg</fullName>
            </value>
            <value>
                <fullName>distributor-16.jpg</fullName>
            </value>
            <value>
                <fullName>distributor-17.jpg</fullName>
            </value>
            <value>
                <fullName>distributor-18.jpg</fullName>
            </value>
            <value>
                <fullName>distributor-19.jpg</fullName>
            </value>
            <value>
                <fullName>distributor-20.jpg</fullName>
            </value>
            <value>
                <fullName>distributor-21.jpg</fullName>
            </value>
            <value>
                <fullName>distributor-22.jpg</fullName>
            </value>
            <value>
                <fullName>distributor-23.jpg</fullName>
            </value>
            <value>
                <fullName>distributor-24.jpg</fullName>
            </value>
            <value>
                <fullName>distributor-25.jpg</fullName>
            </value>
            <value>
                <fullName>distributor-26.jpg</fullName>
            </value>
            <value>
                <fullName>distributor-27.jpg</fullName>
            </value>
            <value>
                <fullName>distributor-28.jpg</fullName>
            </value>
            <value>
                <fullName>distributor-29.jpg</fullName>
            </value>
            <value>
                <fullName>distributor-30.jpg</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/territory__c/territory__c.object-meta.xml
<CustomObject>
    <description>Integration</description>
    <label>Territory</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Territory Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Territories</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/GdlLocatorServiceTest.cls
@isTest
public class GdlLocatorServiceTest {

    private static Id RECORD_TYPE_ID = RecordTypeHelper.getRecordTypeId('Account','Distributor');    
    
    static testmethod void testSearchLocations() {
        Account main = new Account(
            RecordTypeID = RECORD_TYPE_ID,
            Name = 'Test Parent Distributor',
            BillingStreet = 'TEST 123 Main Street',
            BillingCity = 'Easter Island',
            BillingState = 'CL',
            BillingPostalCode = 'CL012001',
            BillingCountry = 'CL',
            Latitude__c = -27.128,
            Longitude__c = -109.341,
            Territory_Number__c = '0000',
            Organization__c = 'Parent'
            //Territory__c = '0000' 
        );        
        insert(main);
        Account s1 = new Account(
            RecordTypeId = RECORD_TYPE_ID,
            ParentId = main.Id,
            Name = 'Test Parent Distributor',
            BillingStreet = 'TEST 123 Main Street',
            BillingCity = 'Puerto Villamil',
            BillingState = 'EC',
            BillingPostalCode = 'EC012001',
            BillingCountry = 'EC',
            Latitude__c = -0.8292784,
            Longitude__c = -90.9820667999999,
            Territory_Number__c = '0000',
            Organization__c = 'Parent'
            //Territory__c = '0000'
        );
        insert(s1);
        GDL_Profile__c profile = new GDL_Profile__c(
            Account__c = main.Id,
            Content__c = '<h3>About Test Parent Distributor</h3><p>This is the content for this distributor</p>',
            Image__c = 'image1'
        );
        insert(profile);
        GDL_DistributorLink__c link = new GDL_DistributorLink__c(
            Target__c = 'http://www.google.com',
            Title__c = 'Google',
            DistributorProfile__c = profile.Id
        );
        insert(link);
        GDL_DistributorEvent__c event = new GDL_DistributorEvent__c(
            Title__c = 'A Test Event',
            StartDate__c = System.today(),
            EndDate__C = System.today(),
            DistributorProfile__c = profile.Id
        );
        insert(event);
        
        GdlDataModel.SearchCriteria criteria = new GdlDataModel.SearchCriteria();
        criteria.country = 'CL';
        criteria.state = 'CL';
        criteria.postalCode = 'CL012001';
        test.startTest();
            list<GdlDataModel.DistributorLocation> locations = GdlLocatorService.searchLocations(criteria);
            System.assertEquals(1, locations.size());
            GdlDataModel.DistributorProfile prof = GdlLocatorService.getDistributorProfile(locations.get(0).Id);
            System.assertNotEquals(null, prof);
        test.stopTest();
        
    }

}