force-app/main/default/objects/Account/fields/Organization__c.field-meta.xml
<CustomField>
    <fullName>Organization__c</fullName>
    <label>Organization</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Parent</fullName>
            </value>
            <value>
                <fullName>Satellite</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/territory__c.field-meta.xml
<CustomField>
    <fullName>territory__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>territory</label>
    <referenceTo>territory__c</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/recordTypes/Distributor.recordType-meta.xml
<RecordType>
    <fullName>Distributor</fullName>
    <active>true</active>
    <description>A record to keep information about Zimmer Distributors</description>
    <label>Distributor</label>
</RecordType>

force-app/main/default/objects/County_Distributor__c/County_Distributor__c.object-meta.xml
<CustomObject>
    <description>Integration</description>
    <label>Territory County</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>County  Distributor Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Territory Counties</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/County_to_Zip_codes__c/County_to_Zip_codes__c.object-meta.xml
<CustomObject>
    <description>Integration</description>
    <label>County to Zip codes</label>
    <nameField>
        <displayFormat>{0000}</displayFormat>
        <label>County Zip code Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>County to Zip Codes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/County_to_Zip_codes__c/fields/County_Distributor__c.field-meta.xml
<CustomField>
    <fullName>County_Distributor__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>County distributor</label>
    <referenceTo>County_Distributor__c</referenceTo>
    <relationshipLabel>County to Zip Codes</relationshipLabel>
    <relationshipName>County_to_Zip_Codes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/County_to_Zip_codes__c/fields/Zip_Codes_Distributor__c.field-meta.xml
<CustomField>
    <fullName>Zip_Codes_Distributor__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Zip Codes distributor</label>
    <referenceTo>Zip_codes_distributor__c</referenceTo>
    <relationshipLabel>County to Zip Codes</relationshipLabel>
    <relationshipName>County_to_Zip_Codes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/territory__c/territory__c.object-meta.xml
<CustomObject>
    <description>Integration</description>
    <label>Territory</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Territory Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Territories</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Territory_county__c/Territory_county__c.object-meta.xml
<CustomObject>
    <label>County</label>
    <nameField>
        <displayFormat>{0000}</displayFormat>
        <label>Territory county Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Counties</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Territory_county__c/fields/County_Distributor__c.field-meta.xml
<CustomField>
    <fullName>County_Distributor__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>County distributor</label>
    <referenceTo>County_Distributor__c</referenceTo>
    <relationshipName>Territory_counties2</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Territory_county__c/fields/territory__c.field-meta.xml
<CustomField>
    <fullName>territory__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>territory</label>
    <referenceTo>territory__c</referenceTo>
    <relationshipName>Territory_counties2</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Zip_codes_distributor__c/Zip_codes_distributor__c.object-meta.xml
<CustomObject>
    <description>Integration</description>
    <label>Zip Codes distributor</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Zip Codes Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Zip Codes distributor</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/Test_Distributor_Locater_Updated.cls
@isTest
Private class Test_Distributor_Locater_Updated 
{
    static testmethod void testwebservice()
    {
        
        Zip_codes_distributor__c zci= new Zip_codes_distributor__c();
        zci.name='123456';
        insert zci;
        
        territory__c t=new territory__c();
        t.Name='teritory';
        insert t;
        
        County_Distributor__c cdc=new County_Distributor__c();
        cdc.Name='xyz';
        //cdc.Zip_Codes_Distributor__c=zci.Id;
        insert cdc;
        
        Territory_county__c tc=new Territory_county__c();
        tc.County_Distributor__c=cdc.Id;
        tc.territory__c=t.Id;
        tc.County_Distributor__c=cdc.Id;
        insert tc;
        
        //RecordType rtype=[select Id from RecordType where Name=:'Distributor'];
        RecordType rtype=[select Id from RecordType where DeveloperName=:'Distributor'];
        Account a=new Account();
        a.Name='testacct';
        a.RecordTypeId=rtype.Id;
        a.BillingCity='NewArk';
        a.Website='www.google.com';
        a.BillingState='CA';
        a.BillingPostalCode='123456';
        a.BillingStreet='asdf';
        a.BillingCountry='CA';
        a.territory__c=t.Id;
        a.Organization__c = 'Parent';
        insert a;
        
       
        
    //  Territory_county__c
        County_to_Zip_codes__c czc=new County_to_Zip_codes__c();
        
        Distributor_Locater_Updated.Distributor_Locator_Output subclass=new Distributor_Locater_Updated.Distributor_Locator_Output();
        subclass.ZipCodeOrPostalCode='123456';
        Distributor_Locater_Updated.zipCodeMethod('123456');
        Distributor_Locater_Updated.countryMethod('china');
        Distributor_Locater_Updated.MySalesAssociate(a.Id);
        
    }
}