force-app/main/default/objects/Account/fields/Physician_Specialty__c.field-meta.xml
<CustomField>
    <fullName>Physician_Specialty__c</fullName>
    <description>The speciality(s) of this surgeon with regard to Zimmer products</description>
    <inlineHelpText>Select Zimmer specialty for this surgeon</inlineHelpText>
    <label>Specialty</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Knee</fullName>
            </value>
            <value>
                <fullName>Hip</fullName>
            </value>
            <value>
                <fullName>Elbow</fullName>
            </value>
            <value>
                <fullName>Shoulder</fullName>
            </value>
            <value>
                <fullName>Spine</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
            <value>
                <fullName>CAS</fullName>
            </value>
            <value>
                <fullName>Dental</fullName>
            </value>
            <value>
                <fullName>Foot &amp; Ankle</fullName>
            </value>
            <value>
                <fullName>Hand &amp; Wrist</fullName>
            </value>
            <value>
                <fullName>Orthobiologics</fullName>
            </value>
            <value>
                <fullName>OSP</fullName>
            </value>
            <value>
                <fullName>Patient Specific</fullName>
            </value>
            <value>
                <fullName>Sports Medicine</fullName>
            </value>
            <value>
                <fullName>Trauma</fullName>
            </value>
            <value>
                <fullName>Neurosurgical</fullName>
            </value>
            <value>
                <fullName>Arthroplasty</fullName>
            </value>
            <value>
                <fullName>Arthroscopy</fullName>
            </value>
            <value>
                <fullName>Paediatric</fullName>
            </value>
            <value>
                <fullName>Oncology</fullName>
            </value>
            <value>
                <fullName>PEDIATRIC ORTHOPEDICS</fullName>
            </value>
            <value>
                <fullName>ORTHOPEDIC SURGERY</fullName>
                <label>Orthopedic Surgery</label>
            </value>
            <value>
                <fullName>NEUROLOGICAL SURGERY</fullName>
            </value>
            <value>
                <fullName>ORTHOPEDIC SURGERY OF THE SPINE</fullName>
            </value>
            <value>
                <fullName>ADULT RECONSTRUCTIVE ORTHOPEDICS</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Physicians_Locator__c.field-meta.xml
<CustomField>
    <fullName>Physicians_Locator__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Indicates where we recieved the list information</description>
    <inlineHelpText>Check this box if you want to select this list for your mailng</inlineHelpText>
    <label>Physicians Locator</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/fields/Specialty_integration__c.field-meta.xml
<CustomField>
    <fullName>Specialty_integration__c</fullName>
    <label>Specialty integration</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Dental</fullName>
            </value>
            <value>
                <fullName>Elbow</fullName>
            </value>
            <value>
                <fullName>Foot and Ankle</fullName>
            </value>
            <value>
                <fullName>Hand and Wrist</fullName>
            </value>
            <value>
                <fullName>Hip</fullName>
            </value>
            <value>
                <fullName>Knee</fullName>
            </value>
            <value>
                <fullName>Orthopedic</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
            <value>
                <fullName>Pain Medicine</fullName>
            </value>
            <value>
                <fullName>Plastics</fullName>
            </value>
            <value>
                <fullName>Podiatry</fullName>
            </value>
            <value>
                <fullName>Primary Care</fullName>
            </value>
            <value>
                <fullName>Rheumetology</fullName>
            </value>
            <value>
                <fullName>Shoulder</fullName>
            </value>
            <value>
                <fullName>Spine</fullName>
            </value>
            <value>
                <fullName>Sports Medicine</fullName>
            </value>
            <value>
                <fullName>Trauma</fullName>
            </value>
            <value>
                <fullName>Wound Care</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/territory__c.field-meta.xml
<CustomField>
    <fullName>territory__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>territory</label>
    <referenceTo>territory__c</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/recordTypes/Practice.recordType-meta.xml
<RecordType>
    <fullName>Practice</fullName>
    <active>true</active>
    <description>A record to keep information about the medical practice(s) to which a surgeon is a member</description>
    <label>Medical Practice</label>
</RecordType>

force-app/main/default/objects/Phy_Country_Codes__c/Phy_Country_Codes__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>Physician Country Codes</label>
</CustomObject>

force-app/main/default/objects/Phy_Country_Codes__c/fields/Condition_Code__c.field-meta.xml
<CustomField>
    <fullName>Condition_Code__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Condition Code</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Practice_Surgeon_Link__c/Practice_Surgeon_Link__c.object-meta.xml
<CustomObject>
    <label>Practice &amp; Surgeon Relationship</label>
    <nameField>
        <displayFormat>{0000}</displayFormat>
        <label>Practice Link Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Practice &amp; Surgeon Relationships</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Practice_Surgeon_Link__c/fields/Practice__c.field-meta.xml
<CustomField>
    <fullName>Practice__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Practice</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Surgeon Relationships</relationshipLabel>
    <relationshipName>R00N80000002Up33EAC</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Practice_Surgeon_Link__c/fields/Surgeon__c.field-meta.xml
<CustomField>
    <fullName>Surgeon__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Surgeon</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Practice Relationships</relationshipLabel>
    <relationshipName>R00N80000002hQEjEAM</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/territory__c/territory__c.object-meta.xml
<CustomObject>
    <description>Integration</description>
    <label>Territory</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Territory Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Territories</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/test_Services_Inventory.cls
@isTest
Private class test_Services_Inventory {
    
    static testmethod void testwebservice()
    {
        Services_Inventory.Physician_Locator_Output subclass=new Services_Inventory.Physician_Locator_Output();
        List<string> ziplist=new list<string>();
        ziplist.add('12345');
        //ziplist.add('1234');
        
        //RecordType rtype=[select Id from RecordType where Name='Medical Practice'];
        RecordType rtype=[select Id from RecordType where DeveloperName='Practice'];
        Account a=new Account();
        a.Name='testacct';
        a.RecordTypeId=rtype.Id;
        a.BillingCity='NewArk';
        a.Website='www.google.com';
        a.BillingState='CA';
        a.BillingPostalCode='123456';
        a.BillingStreet='asdf';
        a.BillingCountry='CA';
        a.ShippingPostalCode='12345';
        a.ShippingCountry='CA';
        a.Specialty_integration__c='brain';
        a.Physicians_Locator__c=true;   
        
        //a.territory__c=t.Id;
        insert a;
        System.Debug(a);
        Account a1=new Account();
        a1.FirstName='FirstName';
        a1.LastName='testacct1';
        a1.RecordTypeId=RecordTypeHelper.getRecordTypeId('Account','Physician');
        a1.BillingCity='NewArk';
        a1.Website='www.google.com';
        a1.BillingState='AB';
        a1.BillingPostalCode='123456';
        a1.BillingStreet='asdf';
        a1.BillingCountry='CA';
        a1.ShippingPostalCode='12345';
        a1.ShippingCountry='CA';
        a1.ShippingState='AB';
        a1.Specialty_integration__c='brain';
        a1.Physicians_Locator__c=true;
        a1.PersonMailingCountry='CA';
        a1.Physician_Specialty__c='brain';  
        a1.PersonMailingState ='AB';   
        a1.PersonMailingCity ='AB';
        a1.PersonMailingPostalCode='12345';
        a1.PersonMailingStreet ='asdg';
        insert a1;
        System.Debug(a1);
        Practice_Surgeon_Link__c psl=new Practice_Surgeon_Link__c();
        psl.Practice__c=a.Id;
        psl.Surgeon__c=a1.Id;
        insert psl;
        
        
        
        Practice_Surgeon_Link__c psl1=new Practice_Surgeon_Link__c();
        psl1.Practice__c=a.Id;
        psl1.Surgeon__c=a1.Id;
        Insert psl1;
        
        Phy_Country_Codes__c pcc=new Phy_Country_Codes__c();
        pcc.Name='150';
        pcc.Condition_Code__c='brain';
        insert pcc;
        Services_Inventory.zipCodeMethod(ziplist, 150);
        Services_Inventory.StateCountryMethod('CA', 'CA', 150);
        Services_Inventory.MyPhysicianMethod(psl.Id, psl.Id);   
    }
}