force-app/main/default/objects/Account/fields/Refer_To_SFDC_Id__c.field-meta.xml
<CustomField>
    <fullName>Refer_To_SFDC_Id__c</fullName>
    <description>This field gives the uniqe SFDC ID of the Master account to which the Inactive account refers to</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Refer To SFDC Unique Id #</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/Business_Division__c.field-meta.xml
<CustomField>
    <fullName>Business_Division__c</fullName>
    <label>Business Division</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Bone Healing</fullName>
            </value>
            <value>
                <fullName>CMFT</fullName>
            </value>
            <value>
                <fullName>CMFT - Robotics</fullName>
            </value>
            <value>
                <fullName>Dental</fullName>
            </value>
            <value>
                <fullName>Ortho</fullName>
            </value>
            <value>
                <fullName>Ortho - Robotics</fullName>
            </value>
            <value>
                <fullName>Recon</fullName>
            </value>
            <value>
                <fullName>Spine</fullName>
            </value>
            <value>
                <fullName>Spine - Robotics</fullName>
            </value>
            <value>
                <fullName>Trauma</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/Region__c.field-meta.xml
<CustomField>
    <fullName>Region__c</fullName>
    <label>Region</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Product_Type__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>East</fullName>
            </value>
            <value>
                <fullName>West</fullName>
            </value>
            <value>
                <fullName>N/A</fullName>
            </value>
            <value>
                <fullName>Northeast</fullName>
            </value>
            <value>
                <fullName>Mid-Atlantic</fullName>
            </value>
            <value>
                <fullName>Midwest</fullName>
            </value>
            <value>
                <fullName>Northwest</fullName>
            </value>
            <value>
                <fullName>Southwest</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/Refer_To_SFDC_Id__c.field-meta.xml
<CustomField>
    <fullName>Refer_To_SFDC_Id__c</fullName>
    <description>This field gives the uniqe SFDC ID of the Master account to which the Inactive account refers to</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Refer To SFDC Unique Id #</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Region__c.field-meta.xml
<CustomField>
    <fullName>Region__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Region</label>
    <length>25</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/recordTypes/Zimmer_Standard_Contact.recordType-meta.xml
<RecordType>
    <fullName>Zimmer_Standard_Contact</fullName>
    <active>true</active>
    <description>This is a Healthcare Professional Contact assigned to a specific Business Account (Non-Physician)</description>
    <label>Zimmer Standard Contact</label>
</RecordType>

force-app/main/default/objects/Trigger_Settings__c/Trigger_Settings__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Activate/ De-activate SFDC triggers</description>
    <label>Trigger Settings</label>
</CustomObject>

force-app/main/default/objects/Trigger_Settings__c/fields/Active__c.field-meta.xml
<CustomField>
    <fullName>Active__c</fullName>
    <defaultValue>false</defaultValue>
    <description>If Checked, Trigger is Activated and Id Unchecked, trigger is De-Activated</description>
    <label>Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/User/fields/Business_Division__c.field-meta.xml
<CustomField>
    <fullName>Business_Division__c</fullName>
    <description>This field is required-There are workflow and validation rules that uses this field to determine processing path based on the Geography, Business Division and/or Region field(s) setting of the user.</description>
    <inlineHelpText>This field is required-There are workflow and validation rules that uses this field to determine processing path based on the Geography, Business Division and/or Region field(s) setting of the user.</inlineHelpText>
    <label>Business Division</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>BH</fullName>
            </value>
            <value>
                <fullName>CAS</fullName>
            </value>
            <value>
                <fullName>CO</fullName>
            </value>
            <value>
                <fullName>DN</fullName>
            </value>
            <value>
                <fullName>GE</fullName>
            </value>
            <value>
                <fullName>GO</fullName>
            </value>
            <value>
                <fullName>HL</fullName>
            </value>
            <value>
                <fullName>N/A</fullName>
            </value>
            <value>
                <fullName>RC</fullName>
            </value>
            <value>
                <fullName>SP</fullName>
            </value>
            <value>
                <fullName>TR</fullName>
            </value>
            <value>
                <fullName>ZSP</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/User/fields/Geography__c.field-meta.xml
<CustomField>
    <fullName>Geography__c</fullName>
    <description>This field is required-There are workflow and validation rules that uses this field to determine processing path based on the Geography, Business Division and/or Region field(s) setting of the user.</description>
    <inlineHelpText>This field is required-There are workflow and validation rules that uses this field to determine processing path based on the Geography, Business Division and/or Region field(s) setting of the user.</inlineHelpText>
    <label>Geography</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Argentina</fullName>
            </value>
            <value>
                <fullName>Australia</fullName>
            </value>
            <value>
                <fullName>Austria</fullName>
            </value>
            <value>
                <fullName>Belgium</fullName>
            </value>
            <value>
                <fullName>Bolivia (Plurinational State of)</fullName>
            </value>
            <value>
                <fullName>Brazil</fullName>
            </value>
            <value>
                <fullName>Canada</fullName>
            </value>
            <value>
                <fullName>Chile</fullName>
            </value>
            <value>
                <fullName>China</fullName>
            </value>
            <value>
                <fullName>Colombia</fullName>
            </value>
            <value>
                <fullName>Costa Rica</fullName>
            </value>
            <value>
                <fullName>Czech Republic</fullName>
            </value>
            <value>
                <fullName>Denmark</fullName>
            </value>
            <value>
                <fullName>Ecuador</fullName>
            </value>
            <value>
                <fullName>Finland</fullName>
            </value>
            <value>
                <fullName>France</fullName>
            </value>
            <value>
                <fullName>Germany</fullName>
            </value>
            <value>
                <fullName>Hong Kong</fullName>
            </value>
            <value>
                <fullName>Hungary</fullName>
            </value>
            <value>
                <fullName>India</fullName>
            </value>
            <value>
                <fullName>Ireland</fullName>
            </value>
            <value>
                <fullName>Italy</fullName>
            </value>
            <value>
                <fullName>Japan</fullName>
            </value>
            <value>
                <fullName>Korea (Republic of)</fullName>
            </value>
            <value>
                <fullName>Lebanon</fullName>
            </value>
            <value>
                <fullName>Malaysia</fullName>
            </value>
            <value>
                <fullName>Mexico</fullName>
            </value>
            <value>
                <fullName>N/A</fullName>
            </value>
            <value>
                <fullName>Netherlands</fullName>
            </value>
            <value>
                <fullName>New Zealand</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/User/fields/Region__c.field-meta.xml
<CustomField>
    <fullName>Region__c</fullName>
    <description>This field is required-There are workflow and validation rules that uses this field to determine processing path based on the Geography, Business Division and/or Region field(s) setting of the user.</description>
    <inlineHelpText>This field is required-There are workflow and validation rules that uses this field to determine processing path based on the Geography, Business Division and/or Region field(s) setting of the user.</inlineHelpText>
    <label>Region</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>AM</fullName>
            </value>
            <value>
                <fullName>AP</fullName>
            </value>
            <value>
                <fullName>EU</fullName>
            </value>
            <value>
                <fullName>GL</fullName>
            </value>
            <value>
                <fullName>LA</fullName>
            </value>
            <value>
                <fullName>N/A</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/ContactCustomMergeTest.cls
/*****************************************************************************/
/* Class name: ContactCustomMergeClass                                             */
/* Author: Naveen Chugh                                                      */
/* Last modified: 09/02/2011                                                 */
/* Purpose: Used to provide unit test coverage for ContactCustomMergeClass   */
/*****************************************************************************/

@istest
private class ContactCustomMergeTest{
    
    @testsetup
        public static void TestCustom(){
            
            Trigger_Settings__c cs = new Trigger_Settings__c();
            cs.Name = 'AddUsersToPSQueues Trigger';
            cs.Active__c = true;
            insert cs;
        } 

    public static testMethod void testContactMerge() 
    {   
        /************************************************************************************************
          Purpose: This method provides the test coverage for the Custom Merge Functionalty
                   designed fot Contacts 
          Parameters: None
          Returns: None
          ***********************************************************************************************/  
        
        //Creating the test user
        profile[] UserProfile1 = [Select Id, Name From Profile where name = 'Custom - Data Administrator' limit 1];
        User userx = new user (Username = 'testx@key.net', FirstName = 'FirstTestx', LastName ='LastTestx', alias = 'FLast', 
                            email='testx@key.net', communityNickname='test0101019', TimeZoneSidKey='America/Indiana/Indianapolis',
                            LocaleSidKey='en_US', EmailEncodingKey='ISO-8859-1', ProfileId=UserProfile1[0].Id ,
                            LanguageLocaleKey='en_US',Region__c='AM', Geography__c='US', Business_Division__c='DN');
        insert userx;
        
        
        System.debug('-----SurgeonMergeTest.testSurgeon-userx----- = ' + userx);
        //Logging into the System as User userx
        System.RunAs(userx) {
            //Creating Contact 1 that would be used in custom Contact Merge Functionality 
            Contact contact1 = new Contact();
            //String rtId = [select id from RecordType where SObjectType = 'Contact' and IsActive = true and Name = 'Zimmer Standard Contact'].Id;
            String rtId = [select id from RecordType where SObjectType = 'Contact' and IsActive = true and DeveloperName = 'Zimmer_Standard_Contact'].Id;
            contact1.RecordTypeId = rtId;
            contact1.LastName = 'TEST CONTACT1';
            //contact1.Name = 'TEST';
            contact1.Refer_To_SFDC_Id__c= '';
            insert contact1;
            
            //Creating Contact 2 that would be used in custom Contact Merge Functionality 
            Contact contact2 = new Contact();
            contact2.RecordTypeId = rtId;
            contact2.LastName = 'TEST CONTACT2';
            //contact1.Name = 'TEST';
            contact2.Refer_To_SFDC_Id__c= contact1.id;
            insert contact2;
            
            //Because the merging is asynchronous
            Test.startTest();     
                Merge contact1 contact2;
            Test.stopTest();
    
    Contact[] contactList =[select id from Contact where LastName = 'TEST CONTACT1' all rows];
    Contact[] unDeletedContact = [select Refer_To_SFDC_Id__c from Contact where LastName = 'TEST CONTACT2' all rows];
    
    //Test Case: The refer To SFDC Unique Id field of the undeleted account has been populated with the id of the master Contact
         System.debug('Contact 1 id = ' + contactList[0].id + ' Conatct 2 refer to id = '+unDeletedContact[0].Refer_To_SFDC_Id__c );
    system.assertequals(contactList[0].id,unDeletedContact[0].Refer_To_SFDC_Id__c);

    } //end of runAs(userx)
  }
}