force-app/main/default/objects/Account/fields/RVP__c.field-meta.xml
<CustomField>
    <fullName>RVP__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>AVP</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Accounts1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/Territory_Name__c.field-meta.xml
<CustomField>
    <fullName>Territory_Name__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Territory Name</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Annual_Sales_Data__c/Annual_Sales_Data__c.object-meta.xml
<CustomObject>
    <label>Annual Sales Data</label>
    <nameField>
        <displayFormat>ASD-{0000000}</displayFormat>
        <label>Annual Sales Data Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Annual Sales Data</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Annual_Sales_Data__c/fields/Product_Group__c.field-meta.xml
<CustomField>
    <fullName>Product_Group__c</fullName>
    <label>Product Group</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Hips</fullName>
            </value>
            <value>
                <fullName>Knees</fullName>
            </value>
            <value>
                <fullName>Extremities</fullName>
            </value>
            <value>
                <fullName>Cement</fullName>
            </value>
            <value>
                <fullName>Sports Medicine</fullName>
            </value>
            <value>
                <fullName>Trauma</fullName>
            </value>
            <value>
                <fullName>Foot &amp; Ankle</fullName>
            </value>
            <value>
                <fullName>Surgical</fullName>
            </value>
            <value>
                <fullName>Early Intervention</fullName>
            </value>
            <value>
                <fullName>Total</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Annual_Sales_Data__c/fields/Quarter__c.field-meta.xml
<CustomField>
    <fullName>Quarter__c</fullName>
    <label>Quarter</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>First</fullName>
            </value>
            <value>
                <fullName>Second</fullName>
            </value>
            <value>
                <fullName>Third</fullName>
            </value>
            <value>
                <fullName>Fourth</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Annual_Sales_Data__c/fields/Territory_Name__c.field-meta.xml
<CustomField>
    <fullName>Territory_Name__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Territory Name</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Annual Sales Data</relationshipLabel>
    <relationshipName>Annual_Sales_Data</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Annual_Sales_Data__c/fields/This_Year_YTD_Sales_Thru_Month__c.field-meta.xml
<CustomField>
    <fullName>This_Year_YTD_Sales_Thru_Month__c</fullName>
    <label>This Year YTD Sales Thru Month</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Business_Plan__c/Business_Plan__c.object-meta.xml
<CustomObject>
    <label>Business Plan</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Business Plan Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Business Plans</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Business_Plan__c/fields/Quarter__c.field-meta.xml
<CustomField>
    <fullName>Quarter__c</fullName>
    <label>Quarter</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>First</fullName>
            </value>
            <value>
                <fullName>Second</fullName>
            </value>
            <value>
                <fullName>Third</fullName>
            </value>
            <value>
                <fullName>Fourth</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Business_Plan__c/recordTypes/Active.recordType-meta.xml
<RecordType>
    <fullName>Active</fullName>
    <active>true</active>
    <label>Active</label>
</RecordType>

force-app/main/default/objects/Business_Plan_Settings__c/Business_Plan_Settings__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>Business Plan Settings</label>
</CustomObject>

force-app/main/default/objects/Business_Plan_Settings__c/fields/Pricing_Impact__c.field-meta.xml
<CustomField>
    <fullName>Pricing_Impact__c</fullName>
    <label>YTD Pricing Impact</label>
    <precision>7</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Product_Group__c.field-meta.xml
<CustomField>
    <fullName>Product_Group__c</fullName>
    <label>Product Group</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Hips</fullName>
            </value>
            <value>
                <fullName>Knees</fullName>
            </value>
            <value>
                <fullName>Cement</fullName>
            </value>
            <value>
                <fullName>Extremities</fullName>
            </value>
            <value>
                <fullName>Sports Medicine</fullName>
            </value>
            <value>
                <fullName>Trauma</fullName>
            </value>
            <value>
                <fullName>Foot &amp; Ankle</fullName>
            </value>
            <value>
                <fullName>Surgical</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Territory_Name__c.field-meta.xml
<CustomField>
    <fullName>Territory_Name__c</fullName>
    <label>Territory Name</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>ALASKA (BARTOW)</fullName>
                <isActive>false</isActive>
                <label>ALASKA (BARTOW)</label>
            </value>
            <value>
                <fullName>APEX SURGICAL(FOX-GATTEN)</fullName>
                <isActive>false</isActive>
                <label>APEX SURGICAL(FOX-GATTEN)</label>
            </value>
            <value>
                <fullName>BONEAFIDE ORTHO(ZERINGUE)</fullName>
                <isActive>false</isActive>
                <label>BONEAFIDE ORTHO(ZERINGUE)</label>
            </value>
            <value>
                <fullName>Boneafide Orthopaedics, Inc.</fullName>
            </value>
            <value>
                <fullName>CAPITAL (PATAK)</fullName>
                <isActive>false</isActive>
                <label>CAPITAL (PATAK)</label>
            </value>
            <value>
                <fullName>CASE MEDICAL (CASE)</fullName>
                <isActive>false</isActive>
                <label>CASE MEDICAL (CASE)</label>
            </value>
            <value>
                <fullName>DAVIS</fullName>
                <isActive>false</isActive>
                <label>DAVIS</label>
            </value>
            <value>
                <fullName>DOWNSTATE NY (LOSCHIAVO)</fullName>
                <isActive>false</isActive>
                <label>DOWNSTATE NY (LOSCHIAVO)</label>
            </value>
            <value>
                <fullName>FEGAN INC</fullName>
                <isActive>false</isActive>
                <label>FEGAN INC</label>
            </value>
            <value>
                <fullName>GR LKS (FUMEI-LOCRICCHIO)</fullName>
                <isActive>false</isActive>
                <label>GR LKS (FUMEI-LOCRICCHIO)</label>
            </value>
            <value>
                <fullName>HIBBARD</fullName>
                <isActive>false</isActive>
                <label>HIBBARD</label>
            </value>
            <value>
                <fullName>HOLZBACH</fullName>
                <isActive>false</isActive>
                <label>HOLZBACH</label>
            </value>
            <value>
                <fullName>JNT MED CONCEPTS (PARKER)</fullName>
                <isActive>false</isActive>
                <label>JNT MED CONCEPTS (PARKER)</label>
            </value>
            <value>
                <fullName>Joint Medical Concepts</fullName>
            </value>
            <value>
                <fullName>LEGACY ORTHO(COOK-PERHACS</fullName>
                <isActive>false</isActive>
                <label>LEGACY ORTHO(COOK-PERHACS</label>
            </value>
            <value>
                <fullName>Legacy Orthopedic, Inc.</fullName>
            </value>
            <value>
                <fullName>MIDAMERICA (HOLINKA)</fullName>
                <isActive>false</isActive>
                <label>MIDAMERICA (HOLINKA)</label>
            </value>
            <value>
                <fullName>MIDARK SURGICAL (NIPPS)</fullName>
                <isActive>false</isActive>
                <label>MIDARK SURGICAL (NIPPS)</label>
            </value>
            <value>
                <fullName>Midark Surgical Inc.</fullName>
            </value>
            <value>
                <fullName>MID-OHIO (GRAHAM)</fullName>
                <isActive>false</isActive>
                <label>MID-OHIO (GRAHAM)</label>
            </value>
            <value>
                <fullName>NORTHEAST (KILCOMMONS)</fullName>
                <isActive>false</isActive>
                <label>NORTHEAST (KILCOMMONS)</label>
            </value>
            <value>
                <fullName>OREGON (COUPENS)</fullName>
                <isActive>false</isActive>
                <label>OREGON (COUPENS)</label>
            </value>
            <value>
                <fullName>ORTHOSOLU(OLIVER-STANBERY</fullName>
                <isActive>false</isActive>
                <label>ORTHOSOLU(OLIVER-STANBERY</label>
            </value>
            <value>
                <fullName>Osteo1, Inc</fullName>
                <isActive>false</isActive>
                <label>Osteo1, Inc</label>
            </value>
            <value>
                <fullName>OSTEO1 INC (SCHMITT)</fullName>
                <isActive>false</isActive>
                <label>OSTEO1 INC (SCHMITT)</label>
            </value>
            <value>
                <fullName>PRECISION (ETHERIDGE)</fullName>
                <isActive>false</isActive>
                <label>PRECISION (ETHERIDGE)</label>
            </value>
            <value>
                <fullName>PREMIER ORTH (VON SAVOYE)</fullName>
                <isActive>false</isActive>
                <label>PREMIER ORTH (VON SAVOYE)</label>
            </value>
            <value>
                <fullName>Premier Orthopedics, Inc.</fullName>
            </value>
            <value>
                <fullName>RICCIONE</fullName>
                <isActive>false</isActive>
                <label>RICCIONE</label>
            </value>
            <value>
                <fullName>RXMEDICAL (ROUSE)</fullName>
                <isActive>false</isActive>
                <label>RXMEDICAL (ROUSE)</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/recordTypes/Standard.recordType-meta.xml
<RecordType>
    <fullName>Standard</fullName>
    <active>true</active>
    <businessProcess>EU-Standard</businessProcess>
    <description>Record Type for all Opportunities in EMEA</description>
    <label>EU-Standard</label>
</RecordType>

force-app/main/default/objects/Product_Sales_Summary__c/Product_Sales_Summary__c.object-meta.xml
<CustomObject>
    <label>Product Sales Summary</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Product Sales Summary Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Product Sales Summary</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Product_Sales_Summary__c/fields/Annual_Sales_Data__c.field-meta.xml
<CustomField>
    <fullName>Annual_Sales_Data__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Annual Sales Data</label>
    <referenceTo>Annual_Sales_Data__c</referenceTo>
    <relationshipLabel>Product Sales Summary</relationshipLabel>
    <relationshipName>Product_Sales_Summary</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Product_Sales_Summary__c/fields/Pricing_Impact__c.field-meta.xml
<CustomField>
    <fullName>Pricing_Impact__c</fullName>
    <label>Base Pricing % Impact</label>
    <precision>7</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Trigger_Settings__c/Trigger_Settings__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Activate/ De-activate SFDC triggers</description>
    <label>Trigger Settings</label>
</CustomObject>

force-app/main/default/objects/Trigger_Settings__c/fields/Active__c.field-meta.xml
<CustomField>
    <fullName>Active__c</fullName>
    <defaultValue>false</defaultValue>
    <description>If Checked, Trigger is Activated and Id Unchecked, trigger is De-Activated</description>
    <label>Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/BusinessPlanCreation_Test.cls
@isTest
public class BusinessPlanCreation_Test {
    
    public static Account acc;
    public static Opportunity newOpp1;
    public static Opportunity newOpp2;
    
    @testSetup static void setup() {
        
        list<Business_Plan_Settings__c> insert_BPSetting = new list<Business_Plan_Settings__c>();
        
        Business_Plan_Settings__c bpSetting = new Business_Plan_Settings__c();
        bpSetting.Name = 'Product Group - 01';
        bpSetting.Pricing_Impact__c = -2.9;
        bpSetting.Product_Group__c = 'Knees';
        insert_BPSetting.add(bpSetting);
        
        Business_Plan_Settings__c bpSetting01 = new Business_Plan_Settings__c();
        bpSetting01.Name = 'Headcount Summary - 01';
        bpSetting01.Product_Group__c = 'B.E.S.T';
        insert_BPSetting.add(bpSetting01);
        
        insert insert_BPSetting;
        
        Trigger_Settings__c cs = new Trigger_Settings__c();
        cs.Name = 'AddUsersToPSQueues Trigger';
        cs.Active__c = false;
        insert cs;
        
        Profile p = [SELECT Id FROM Profile WHERE Name='Standard User'];
        
        User u = new User(Alias = 'stand', Email='AVPuser@testorg.com',
                          EmailEncodingKey='UTF-8', LastName='Testing', LanguageLocaleKey='en_US',
                          LocaleSidKey='en_US', ProfileId = p.Id,
                          TimeZoneSidKey='America/Los_Angeles', UserName='AVPuser@testorg.com');
        insert u;
        
        acc = new Account();
        acc.RecordTypeId = '012800000002AW5AAM';//Healthcare Facility
        acc.Name = 'APEX SURGICAL(FOX-GATTEN)';
        acc.RVP__c = u.Id;
        insert acc;
        
        Annual_Sales_Data__c annualSales = new Annual_Sales_Data__c();
        annualSales.Territory_Name__c = acc.Id;
        annualSales.Year__c = 2019;
        annualSales.Quarter__c= 'First';
        annualSales.Product_Group__c = 'Knees';
        annualSales.This_Year_YTD_Sales_Thru_Month__c = 15000;
        insert annualSales;
        
    }
    
    static testMethod void validate_BusinessPlanCreation() {
        
        test.startTest();
        
        Account acct = [select Id,Name from Account where Name='APEX SURGICAL(FOX-GATTEN)'];
                
        Business_Plan__c plan = new Business_Plan__c();
        plan.Name = 'Test Plan';
        plan.Active__c = TRUE;
        plan.Status__c = 'Active';
        plan.Year__c = 2019;
        plan.Quarter__c = 'First';
        plan.Territory_Account_Name__c = acct.Id;
        insert plan;
        
        system.debug('-----plan---'+plan);
        
        Executive_Summary__c exe = [select Id, Name, Business_Plan__c, IsActive__c from Executive_Summary__c];
        system.assertEquals(plan.Id, exe.Business_Plan__c);
        
        Product_Sales_Summary__c prodSummary= [select Id, Name,Business_Plan__c,Product_Group__c from Product_Sales_Summary__c];
        system.assertEquals(plan.Id, prodSummary.Business_Plan__c);
        system.assertEquals('Knees', prodSummary.Product_Group__c);
        
        Headcount_Summary__c hcSummary = [select Id,Name,Business_Plan__c,Specialty__c from Headcount_Summary__c];
        system.assertEquals(plan.Id, hcSummary.Business_Plan__c);
        system.assertEquals('B.E.S.T', hcSummary.Specialty__c);
            
        test.stopTest();
        
    }

}