force-app/main/default/objects/Account/fields/RVP__c.field-meta.xml
<CustomField>
    <fullName>RVP__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>AVP</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Accounts1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Business_Plan__c/Business_Plan__c.object-meta.xml
<CustomObject>
    <label>Business Plan</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Business Plan Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Business Plans</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Business_Plan__c/fields/Territory_Account_Name__c.field-meta.xml
<CustomField>
    <fullName>Territory_Account_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Territory Account Name</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Business Plans</relationshipLabel>
    <relationshipName>Business_Plans</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Market_Segmentation__c/Market_Segmentation__c.object-meta.xml
<CustomObject>
    <label>Market Segmentation</label>
    <nameField>
        <displayFormat>MS-{00000}</displayFormat>
        <label>Market Segmentation Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Market Segmentation</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Market_Segmentation__c/fields/Aligned_Team__c.field-meta.xml
<CustomField>
    <fullName>Aligned_Team__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Aligned Team</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Market_Segmentation__c/fields/Market_Procedures__c.field-meta.xml
<CustomField>
    <fullName>Market_Procedures__c</fullName>
    <label>IMS Covid Adj. Procedures 2019</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Market_Segmentation__c/fields/Master_Territory__c.field-meta.xml
<CustomField>
    <fullName>Master_Territory__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Master Territory</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Market_Segmentation__c/fields/Master_Territory_ID__c.field-meta.xml
<CustomField>
    <fullName>Master_Territory_ID__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Master Territory ID</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Market Segmentation (Master Territory ID)</relationshipLabel>
    <relationshipName>Market_Segmentation</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Market_Segmentation__c/fields/Procedure_Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Procedure_Opportunity__c</fullName>
    <label>Procedure Opportunity</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Market_Segmentation__c/fields/Product_Group__c.field-meta.xml
<CustomField>
    <fullName>Product_Group__c</fullName>
    <label>Product Group</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Bone Cement</fullName>
            </value>
            <value>
                <fullName>Extremities</fullName>
            </value>
            <value>
                <fullName>Shoulder</fullName>
            </value>
            <value>
                <fullName>Foot &amp; Ankle</fullName>
            </value>
            <value>
                <fullName>Sports Medicine</fullName>
            </value>
            <value>
                <fullName>Trauma</fullName>
            </value>
            <value>
                <fullName>Surgical</fullName>
            </value>
            <value>
                <fullName>Hips</fullName>
            </value>
            <value>
                <fullName>Primary Hips</fullName>
            </value>
            <value>
                <fullName>Revision Hips</fullName>
            </value>
            <value>
                <fullName>Knees</fullName>
            </value>
            <value>
                <fullName>Primary Knees</fullName>
            </value>
            <value>
                <fullName>Partial Knees</fullName>
            </value>
            <value>
                <fullName>Revision Knees</fullName>
            </value>
            <value>
                <fullName>Total Knees</fullName>
            </value>
            <value>
                <fullName>Total Hips</fullName>
            </value>
            <value>
                <fullName>Total</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Market_Segmentation__c/fields/Segementation__c.field-meta.xml
<CustomField>
    <fullName>Segementation__c</fullName>
    <label>Segementation</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Bronze</fullName>
            </value>
            <value>
                <fullName>Gold</fullName>
            </value>
            <value>
                <fullName>Green</fullName>
            </value>
            <value>
                <fullName>Platinum</fullName>
            </value>
            <value>
                <fullName>Silver</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Market_Segmentation__c/fields/Surgeon_Name__c.field-meta.xml
<CustomField>
    <fullName>Surgeon_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Surgeon Name</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Physician</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Market Segmentation</relationshipLabel>
    <relationshipName>Market_Segmentations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Market_Segmentation__c/fields/Zimmer_Biomet_Procedures__c.field-meta.xml
<CustomField>
    <fullName>Zimmer_Biomet_Procedures__c</fullName>
    <label>ZB PROCEDURES 2020</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Avalanche_Segmentation__c.field-meta.xml
<CustomField>
    <fullName>Avalanche_Segmentation__c</fullName>
    <description>New field created for Canada Opportunity</description>
    <inlineHelpText>Avalanche Segmentation Rules 
Platinum (High volume, High share) 
Gold (High volume, Low share) 
Silver (Low volume, High share) 
Bronze (Low volume, Low share)</inlineHelpText>
    <label>Avalanche Segmentation</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Platinum</fullName>
            </value>
            <value>
                <fullName>Gold</fullName>
            </value>
            <value>
                <fullName>Silver</fullName>
            </value>
            <value>
                <fullName>Bronze</fullName>
            </value>
            <value>
                <fullName>Green</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/BP_Target__c.field-meta.xml
<CustomField>
    <fullName>BP_Target__c</fullName>
    <defaultValue>false</defaultValue>
    <label>BP Target</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Business_Plan__c.field-meta.xml
<CustomField>
    <fullName>Business_Plan__c</fullName>
    <formula>CASESAFEID(Product_Sales_Summary__r.Business_Plan__r.Id)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Business Plan</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Market_Procedures__c.field-meta.xml
<CustomField>
    <fullName>Market_Procedures__c</fullName>
    <label>Market Procedures</label>
    <precision>10</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Procedure_Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Procedure_Opportunity__c</fullName>
    <formula>Market_Procedures__c - ZB_Procedures__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Procedure Opportunity</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Product_Group__c.field-meta.xml
<CustomField>
    <fullName>Product_Group__c</fullName>
    <label>Product Group</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Hips</fullName>
            </value>
            <value>
                <fullName>Knees</fullName>
            </value>
            <value>
                <fullName>Cement</fullName>
            </value>
            <value>
                <fullName>Extremities</fullName>
            </value>
            <value>
                <fullName>Sports Medicine</fullName>
            </value>
            <value>
                <fullName>Trauma</fullName>
            </value>
            <value>
                <fullName>Foot &amp; Ankle</fullName>
            </value>
            <value>
                <fullName>Surgical</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Product_Sales_Summary__c.field-meta.xml
<CustomField>
    <fullName>Product_Sales_Summary__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product Sales Summary</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Product_Sales_Summary__c.Business_Plan__r.Active__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Product_Sales_Summary__c</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunity</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Surgeon_Name__c.field-meta.xml
<CustomField>
    <fullName>Surgeon_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>This field is used to lookup your Surgeon account.</inlineHelpText>
    <label>Surgeon Name</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Physician, Physician(Processing)</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Opportunities (Surgeon Name)</relationshipLabel>
    <relationshipName>Opportunities2</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Team_Name__c.field-meta.xml
<CustomField>
    <fullName>Team_Name__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Team Name</label>
    <length>150</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/recordTypes/ASC.recordType-meta.xml
<RecordType>
    <fullName>ASC</fullName>
    <active>true</active>
    <businessProcess>AM-US_ASC</businessProcess>
    <description>This opportunity types triggers a ASC opportunity</description>
    <label>ASC</label>
</RecordType>

force-app/main/default/objects/Product_Sales_Summary__c/Product_Sales_Summary__c.object-meta.xml
<CustomObject>
    <label>Product Sales Summary</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Product Sales Summary Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Product Sales Summary</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Product_Sales_Summary__c/fields/Business_Plan__c.field-meta.xml
<CustomField>
    <fullName>Business_Plan__c</fullName>
    <label>Business Plan</label>
    <referenceTo>Business_Plan__c</referenceTo>
    <relationshipLabel>Product Sales Summary</relationshipLabel>
    <relationshipName>Product_Sales_Summary</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/BPSurgeonSelectionController.cls
public with sharing class BPSurgeonSelectionController {
    public BPSurgeonSelectionController() {

    }
    @AuraEnabled 
    public static List<accountListWrapper> fetchAccountWrapper(ID businessplanID
                                                                , String productgroupName
                                                                ,String sortField
                                                                , boolean isAsc
                                                                , String filter
                                                                , String segment ){     
        List<accountListWrapper> lstaccountListWrapper = new List<accountListWrapper>();
        // query account records and create 'accountListWrapper' class instance for each record. 
        List < Market_Segmentation__c > lstMktSeg = new List<Market_Segmentation__c>();
        system.debug('Business Plan ID'+ businessplanID);
        system.debug('productgroupName'+ productgroupName);
        system.debug('sortField'+ sortField);
        system.debug('isAsc'+ isAsc);
        system.debug('filter'+ filter);
        system.debug('segment'+ segment);
        
        Business_plan__c bp = [select id,Territory_Account_Name__c,Territory_Account_Name__r.RVP__c,Territory_Account_Name__r.RVP__r.FirstName,
                               					Territory_Account_Name__r.RVP__r.LastName from Business_plan__c where id = :businessplanID Limit 1];
         
		system.debug('--------AVP----'+bp.Territory_Account_Name__r.RVP__c);
		system.debug('--------AVP-fstName---'+bp.Territory_Account_Name__r.RVP__r.FirstName);
		system.debug('--------AVP-fstName---'+bp.Territory_Account_Name__r.RVP__r.LastName);
                                                                    
		string strAvp = bp.Territory_Account_Name__r.RVP__r.FirstName + ' '+bp.Territory_Account_Name__r.RVP__r.LastName;

        Set<ID> BPExistingSurgeonIdSet = new Set<ID>();
        String  rectypeName;
        rectypeName = productgroupName == 'Hips' ? 'US Hip' 
                        : productgroupName == 'Knees'? 'US Knee' 
                        : productgroupName == 'Sports Medicine' ? 'US Sports Medicine'  
                        : productgroupName == 'Extremities' ? 'US Extremities'  
                        : productgroupName == 'Foot & Ankle' ? 'US Foot and Ankle' 
                        : productgroupName == 'Trauma' ? 'US Trauma' 
                        : productgroupName == 'Cement' ? 'US Cement' 
                        : ''; 
        if(rectypeName != null || rectypeName != ''){
            for(Opportunity Opp  : [SELECT id, Surgeon_Name__c, Product_Sales_Summary__r.Business_Plan__c, recordType.Name
                                    FROM Opportunity 
                                    WHERE   Product_Sales_Summary__r.Business_Plan__c = :bp.id
                                    AND    recordType.Name = :rectypeName ]){
                BPExistingSurgeonIdSet.add(Opp.Surgeon_Name__c);                            
            }
        }
        string territoryaccountId = bp.Territory_Account_Name__c ; 
        String sSoql = 'SELECT ID, Surgeon_Name__c , Surgeon_Name__r.name , Aligned_Team__c, Surgeon_Name__r.PersonMailingStreet, Surgeon_Name__r.PersonMailingCity, Surgeon_Name__r.PersonMailingState, Master_Territory__c, Master_Territory_ID__c , Segementation__c, Product_Group__c, Market_Procedures__c, Zimmer_Biomet_Procedures__c, Procedure_Opportunity__c';
        sSoql += ' From Market_Segmentation__c WHERE Master_Territory_ID__c = :territoryaccountId ';
        If(filter!= null && filter != ''){
            String tempInput ='\'%' + filter  + '%\'';
            sSoql += ' AND Surgeon_Name__r.name LIKE ' +tempInput;
        }
        If(segment!= null && segment != ''){          
            sSoql += ' AND Segementation__c = :segment ';
        }
        If(productgroupName != null ){
            sSoql += ' AND Product_Group__c = :productgroupName ';
        }  
        /*
        IF(BPExistingSurgeonIdSet.size() > 0 ){
             sSoql += ' AND Surgeon_Name__c NOT IN :BPExistingSurgeonIdSet ';
        }   */
        system.debug('Surgeon_Name__c BPExistingSurgeonIdSet ' + BPExistingSurgeonIdSet);       
        if (sortField != '') {
            sSoql += ' order by ' + sortField;
        
            // if isAsc is equal tp ture then set 'asc' order otherwise set 'desc' order.
                if (isAsc) {
                    sSoql += ' asc';
                } else {
                    sSoql += ' desc';
                }
        }       
        list <Market_Segmentation__c> lstResult;
        try {
            system.debug('The query is' + sSoql);
            lstResult = Database.query(sSoql);
    
            for (Market_Segmentation__c mkt: lstResult) {
                
                lstaccountListWrapper.add(new accountListWrapper(false,BPExistingSurgeonIdSet.contains(mkt.Surgeon_Name__c)? true : false,mkt.Surgeon_Name__r.name.toUpperCase(),mkt,strAvp));
            }
            return lstaccountListWrapper;
        } 
        catch (Exception ex) {
            // for handle Exception
            return null;
        }        
    }
    
    /* wrapper class */  
    public class accountListWrapper {
        @AuraEnabled public boolean isChecked {get;set;}
        @AuraEnabled public boolean bptarget {get;set;}
        @AuraEnabled public String SurgeonName {get;set;}
        @AuraEnabled public  Market_Segmentation__c objAccount{get;set;}
        @AuraEnabled public String avpName {get;set;}
        public accountListWrapper(boolean isChecked, boolean bptarget, String SurgeonName, Market_Segmentation__c objAccount, String avpName){
            this.isChecked = isChecked;
            this.bptarget = bptarget;
            this.SurgeonName = SurgeonName;
            this.objAccount = objAccount;
            this.avpName = avpName;
        }
    }


    @AuraEnabled
    public static List < String > createOpportunities(List < Market_Segmentation__c > lstRecord, String businessplanID) {
        // for store Error Messages  
        List < String > oErrorMsg = new List < String > ();
        system.debug('Market Segmentation recrods --- >>>>> '+lstRecord);
        // Query Records for delete where id in lstRecordId [which is pass from client side controller] 
        Map<String, String> MaprecTypeNameID = new Map<String, String>();
        for(RecordType rectype : [SELECT Id,DeveloperName,SobjectType,Name FROM RecordType WHERE SobjectType = 'Opportunity']){
            String  rectypeName;
            rectypeName = rectype.name == 'US Hip' ? 'Hips' 
                            : rectype.name == 'US Knee' ? 'Knees'
                            : rectype.name == 'US Sports Medicine' ? 'Sports Medicine'
                            : rectype.name == 'US Extremities' ? 'Extremities'
                            : rectype.name == 'US Foot and Ankle' ? 'Foot & Ankle'
                            : rectype.name == 'US Trauma' ? 'Trauma'
                            : rectype.name == 'US Cement' ? 'Cement'
                            : 'NA'; 
            
            MaprecTypeNameID.put(rectypeName, rectype.id);
        }
        Map<String,String> prodsalessumNameID = new Map<String,String>();
        for(Product_Sales_Summary__c prod : [SELECT id, Business_Plan__c, Product_Group__c from Product_Sales_Summary__c where Business_Plan__c =:businessplanID]){
                prodsalessumNameID.put(prod.Product_Group__c, prod.id);
        }
        List<Opportunity> CreateOpp = new List<Opportunity>(); 
        for(Market_Segmentation__c mkt : lstRecord){
            if(mkt.Surgeon_Name__c != null && MaprecTypeNameID.containsKey(mkt.Product_Group__c) && prodsalessumNameID.containsKey(mkt.Product_Group__c)){
                Opportunity tempOpp = new Opportunity ();
                    tempOpp.Name = mkt.Surgeon_Name__r.name; 
                    tempOpp.Surgeon_Name__c =  mkt.Surgeon_Name__c; 
                    tempOpp.CloseDate = Date.newInstance(System.Today().year(), 12, 31);
                    tempOpp.stageName = 'Discover'; 
                    tempOpp.recordTypeId = MaprecTypeNameID.get(mkt.Product_Group__c);
                    tempOpp.Product_Sales_Summary__c = prodsalessumNameID.get(mkt.Product_Group__c);
                    tempOpp.Team_Name__c = mkt.Aligned_Team__c ; 
                    tempOpp.Avalanche_Segmentation__c = mkt.Segementation__c ; 
                    tempOpp.BP_Target__c = TRUE; 
                CreateOpp.add(tempOpp);
            }        
        }

        Database.SaveResult[]  DR_svs = Database.insert(CreateOpp, false);
        // Iterate through each returned result
        for (Database.SaveResult dr: DR_svs) {
            if (dr.isSuccess()) {
                system.debug('successful added in the business plan');
                // Operation was successful
            } else {
                // Operation failed, so get all errors   
                oErrorMsg.add('');
                for (Database.Error err: dr.getErrors()) {
                    // add Error message to oErrorMsg list and return the list
                    oErrorMsg.add(err.getStatusCode() + ': ' + err.getMessage());
                }
            }
        }
        return oErrorMsg;

    }
}