force-app/main/default/objects/Account/fields/RVP__c.field-meta.xml
<CustomField>
    <fullName>RVP__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>AVP</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Accounts1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Opt In</fullName>
                <default>true</default>
                <label>Opt In</label>
            </value>
            <value>
                <fullName>Opt Out</fullName>
            </value>
            <value>
                <fullName>Re-Opt In</fullName>
            </value>
            <value>
                <fullName>I</fullName>
            </value>
            <value>
                <fullName>G</fullName>
            </value>
            <value>
                <fullName>A</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Territory_Name__c.field-meta.xml
<CustomField>
    <fullName>Territory_Name__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Territory Name</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Annual_Sales_Data__c/Annual_Sales_Data__c.object-meta.xml
<CustomObject>
    <label>Annual Sales Data</label>
    <nameField>
        <displayFormat>ASD-{0000000}</displayFormat>
        <label>Annual Sales Data Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Annual Sales Data</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Annual_Sales_Data__c/fields/Quarter__c.field-meta.xml
<CustomField>
    <fullName>Quarter__c</fullName>
    <label>Quarter</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>First</fullName>
            </value>
            <value>
                <fullName>Second</fullName>
            </value>
            <value>
                <fullName>Third</fullName>
            </value>
            <value>
                <fullName>Fourth</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Annual_Sales_Data__c/fields/Territory_Name__c.field-meta.xml
<CustomField>
    <fullName>Territory_Name__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Territory Name</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Annual Sales Data</relationshipLabel>
    <relationshipName>Annual_Sales_Data</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Annual_Sales_Data__c/fields/This_Year_YTD_Sales_Thru_Month__c.field-meta.xml
<CustomField>
    <fullName>This_Year_YTD_Sales_Thru_Month__c</fullName>
    <label>This Year YTD Sales Thru Month</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Business_Plan__c/Business_Plan__c.object-meta.xml
<CustomObject>
    <label>Business Plan</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Business Plan Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Business Plans</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Business_Plan__c/fields/Quarter__c.field-meta.xml
<CustomField>
    <fullName>Quarter__c</fullName>
    <label>Quarter</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>First</fullName>
            </value>
            <value>
                <fullName>Second</fullName>
            </value>
            <value>
                <fullName>Third</fullName>
            </value>
            <value>
                <fullName>Fourth</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Business_Plan__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <defaultValue>&quot;Active&quot;</defaultValue>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Pending AVP Approval</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Approval Not Required</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Business_Plan__c/fields/Territory_Account_Name__c.field-meta.xml
<CustomField>
    <fullName>Territory_Account_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Territory Account Name</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Business Plans</relationshipLabel>
    <relationshipName>Business_Plans</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Business_Plan__c/recordTypes/Active.recordType-meta.xml
<RecordType>
    <fullName>Active</fullName>
    <active>true</active>
    <label>Active</label>
</RecordType>

force-app/main/default/objects/Opportunity/fields/Business_Plan__c.field-meta.xml
<CustomField>
    <fullName>Business_Plan__c</fullName>
    <formula>CASESAFEID(Product_Sales_Summary__r.Business_Plan__r.Id)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Business Plan</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Forecast</fullName>
                <isActive>false</isActive>
                <label>Forecast</label>
            </value>
            <value>
                <fullName>Upside</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Territory_Name__c.field-meta.xml
<CustomField>
    <fullName>Territory_Name__c</fullName>
    <label>Territory Name</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>ALASKA (BARTOW)</fullName>
                <isActive>false</isActive>
                <label>ALASKA (BARTOW)</label>
            </value>
            <value>
                <fullName>APEX SURGICAL(FOX-GATTEN)</fullName>
                <isActive>false</isActive>
                <label>APEX SURGICAL(FOX-GATTEN)</label>
            </value>
            <value>
                <fullName>BONEAFIDE ORTHO(ZERINGUE)</fullName>
                <isActive>false</isActive>
                <label>BONEAFIDE ORTHO(ZERINGUE)</label>
            </value>
            <value>
                <fullName>Boneafide Orthopaedics, Inc.</fullName>
            </value>
            <value>
                <fullName>CAPITAL (PATAK)</fullName>
                <isActive>false</isActive>
                <label>CAPITAL (PATAK)</label>
            </value>
            <value>
                <fullName>CASE MEDICAL (CASE)</fullName>
                <isActive>false</isActive>
                <label>CASE MEDICAL (CASE)</label>
            </value>
            <value>
                <fullName>DAVIS</fullName>
                <isActive>false</isActive>
                <label>DAVIS</label>
            </value>
            <value>
                <fullName>DOWNSTATE NY (LOSCHIAVO)</fullName>
                <isActive>false</isActive>
                <label>DOWNSTATE NY (LOSCHIAVO)</label>
            </value>
            <value>
                <fullName>FEGAN INC</fullName>
                <isActive>false</isActive>
                <label>FEGAN INC</label>
            </value>
            <value>
                <fullName>GR LKS (FUMEI-LOCRICCHIO)</fullName>
                <isActive>false</isActive>
                <label>GR LKS (FUMEI-LOCRICCHIO)</label>
            </value>
            <value>
                <fullName>HIBBARD</fullName>
                <isActive>false</isActive>
                <label>HIBBARD</label>
            </value>
            <value>
                <fullName>HOLZBACH</fullName>
                <isActive>false</isActive>
                <label>HOLZBACH</label>
            </value>
            <value>
                <fullName>JNT MED CONCEPTS (PARKER)</fullName>
                <isActive>false</isActive>
                <label>JNT MED CONCEPTS (PARKER)</label>
            </value>
            <value>
                <fullName>Joint Medical Concepts</fullName>
            </value>
            <value>
                <fullName>LEGACY ORTHO(COOK-PERHACS</fullName>
                <isActive>false</isActive>
                <label>LEGACY ORTHO(COOK-PERHACS</label>
            </value>
            <value>
                <fullName>Legacy Orthopedic, Inc.</fullName>
            </value>
            <value>
                <fullName>MIDAMERICA (HOLINKA)</fullName>
                <isActive>false</isActive>
                <label>MIDAMERICA (HOLINKA)</label>
            </value>
            <value>
                <fullName>MIDARK SURGICAL (NIPPS)</fullName>
                <isActive>false</isActive>
                <label>MIDARK SURGICAL (NIPPS)</label>
            </value>
            <value>
                <fullName>Midark Surgical Inc.</fullName>
            </value>
            <value>
                <fullName>MID-OHIO (GRAHAM)</fullName>
                <isActive>false</isActive>
                <label>MID-OHIO (GRAHAM)</label>
            </value>
            <value>
                <fullName>NORTHEAST (KILCOMMONS)</fullName>
                <isActive>false</isActive>
                <label>NORTHEAST (KILCOMMONS)</label>
            </value>
            <value>
                <fullName>OREGON (COUPENS)</fullName>
                <isActive>false</isActive>
                <label>OREGON (COUPENS)</label>
            </value>
            <value>
                <fullName>ORTHOSOLU(OLIVER-STANBERY</fullName>
                <isActive>false</isActive>
                <label>ORTHOSOLU(OLIVER-STANBERY</label>
            </value>
            <value>
                <fullName>Osteo1, Inc</fullName>
                <isActive>false</isActive>
                <label>Osteo1, Inc</label>
            </value>
            <value>
                <fullName>OSTEO1 INC (SCHMITT)</fullName>
                <isActive>false</isActive>
                <label>OSTEO1 INC (SCHMITT)</label>
            </value>
            <value>
                <fullName>PRECISION (ETHERIDGE)</fullName>
                <isActive>false</isActive>
                <label>PRECISION (ETHERIDGE)</label>
            </value>
            <value>
                <fullName>PREMIER ORTH (VON SAVOYE)</fullName>
                <isActive>false</isActive>
                <label>PREMIER ORTH (VON SAVOYE)</label>
            </value>
            <value>
                <fullName>Premier Orthopedics, Inc.</fullName>
            </value>
            <value>
                <fullName>RICCIONE</fullName>
                <isActive>false</isActive>
                <label>RICCIONE</label>
            </value>
            <value>
                <fullName>RXMEDICAL (ROUSE)</fullName>
                <isActive>false</isActive>
                <label>RXMEDICAL (ROUSE)</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/recordTypes/Standard.recordType-meta.xml
<RecordType>
    <fullName>Standard</fullName>
    <active>true</active>
    <businessProcess>EU-Standard</businessProcess>
    <description>Record Type for all Opportunities in EMEA</description>
    <label>EU-Standard</label>
</RecordType>

force-app/main/default/objects/Product_Sales_Summary__c/Product_Sales_Summary__c.object-meta.xml
<CustomObject>
    <label>Product Sales Summary</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Product Sales Summary Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Product Sales Summary</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Product_Sales_Summary__c/fields/Annual_Sales_Data__c.field-meta.xml
<CustomField>
    <fullName>Annual_Sales_Data__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Annual Sales Data</label>
    <referenceTo>Annual_Sales_Data__c</referenceTo>
    <relationshipLabel>Product Sales Summary</relationshipLabel>
    <relationshipName>Product_Sales_Summary</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Product_Sales_Summary__c/fields/Business_Plan__c.field-meta.xml
<CustomField>
    <fullName>Business_Plan__c</fullName>
    <label>Business Plan</label>
    <referenceTo>Business_Plan__c</referenceTo>
    <relationshipLabel>Product Sales Summary</relationshipLabel>
    <relationshipName>Product_Sales_Summary</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Territory_Name__c/Territory_Name__c.object-meta.xml
<CustomObject>
    <label>Territory Target Refinement</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Territory Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Territory Target Refinements</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Territory_Name__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <defaultValue>&quot;Round 1&quot;</defaultValue>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Round 1</fullName>
                <default>true</default>
                <label>Round 1</label>
            </value>
            <value>
                <fullName>Round 2</fullName>
            </value>
            <value>
                <fullName>Pending AVP Approval</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Approval Not Required</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Trigger_Settings__c/Trigger_Settings__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Activate/ De-activate SFDC triggers</description>
    <label>Trigger Settings</label>
</CustomObject>

force-app/main/default/objects/Trigger_Settings__c/fields/Active__c.field-meta.xml
<CustomField>
    <fullName>Active__c</fullName>
    <defaultValue>false</defaultValue>
    <description>If Checked, Trigger is Activated and Id Unchecked, trigger is De-Activated</description>
    <label>Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/BusinessPlanSalesSummaryController_Test.cls
@isTest
public class BusinessPlanSalesSummaryController_Test {
    
    public static Account acc;
    public static Opportunity newOpp1;
    public static Opportunity newOpp2;
    public static User u;
    
    @testSetup static void setup() {
        
        Trigger_Settings__c cs = new Trigger_Settings__c();
        cs.Name = 'AddUsersToPSQueues Trigger';
        cs.Active__c = false;
        insert cs;
        
        Profile p = [SELECT Id FROM Profile WHERE Name='Standard User'];
        
        UserRole role = new UserRole(Name = 'AVP-User');
        //insert role;
        
        User u = new User(Alias = 'stand', Email='AVPuser@testorg.com',
                          EmailEncodingKey='UTF-8', LastName='Testing', LanguageLocaleKey='en_US',
                          LocaleSidKey='en_US', ProfileId = p.Id,UserRoleId=role.Id,
                          TimeZoneSidKey='America/Los_Angeles', UserName='AVPuser@testorg.com');
        //insert u;
        
        acc = new Account();
        acc.RecordTypeId = '012800000002AW5AAM';//Healthcare Facility
        acc.Name = 'APEX SURGICAL(FOX-GATTEN)';
        acc.RVP__c = u.Id;
        insert acc;
        
        Business_Plan__c plan = new Business_Plan__c();
        plan.Name = 'Test Plan';
        plan.Active__c = TRUE;
        plan.Status__c = 'Active';
        plan.Year__c = 2019;
        plan.Quarter__c = 'Second';
        plan.Territory_Account_Name__c = acc.Id;
        insert plan;
        
        Annual_Sales_Data__c annualSales = new Annual_Sales_Data__c();
        annualSales.Territory_Name__c = acc.Id;
        annualSales.Year__c = 2020;
        annualSales.This_Year_YTD_Sales_Thru_Month__c = 15000;
        insert annualSales;
        
        Product_Sales_Summary__c pSummary = new Product_Sales_Summary__c();
        pSummary.Name = 'Test Knees Sales Summary';
        pSummary.Business_Plan__c = plan.Id;
        pSummary.Product_Group__c = 'Knees';
        pSummary.This_Quarter_Projection__c = 10000;
        pSummary.Pricing_Impact__c = 10;
        pSummary.Opportunities__c = 7500;
        pSummary.Risks__c = 1000;
        insert pSummary;
        
        //Planned_Growth__c = Sales_Plan__c - Full_Year_Estimate__c
        //Sales_Plan__c = Full_Year_Estimate__c + (Full_Year_Estimate__c * Pricing_Impact__c ) + Opportunities__c + Risks__c
        //Full_Year_Estimate__c = Annual_Sales_Data__r.This_Year_YTD_Sales_Thru_Month__c + This_Quarter_Projection__c
        
        Product_Sales_Summary__c pSummary2 = new Product_Sales_Summary__c();
        pSummary2.Name = 'Test Hips Sales Summary';
        pSummary2.Business_Plan__c = plan.Id;
        pSummary2.Product_Group__c = 'Hips';
        pSummary.This_Quarter_Projection__c = 14000;
        pSummary.Pricing_Impact__c = 14;
        pSummary.Opportunities__c = 9500;
        pSummary.Risks__c = 3000;
        insert pSummary2;
        
    }    
    
    static testMethod void validate_ForAVPUser() {
        
        test.startTest();
        
        Business_Plan__c plan1 = [select Id,Name from Business_Plan__c where name='Test Plan'];
        
        Profile p = [SELECT Id FROM Profile WHERE Name='Standard User'];
        
        UserRole role = new UserRole(Name = 'AVP-User');
        insert role;
        
        User u = new User(Alias = 'stand', Email='AVPuser@testorg.com',
                          EmailEncodingKey='UTF-8', LastName='Testing', LanguageLocaleKey='en_US',
                          LocaleSidKey='en_US', ProfileId = p.Id,UserRoleId=role.Id,
                          TimeZoneSidKey='America/Los_Angeles', UserName='AVPuser@testorg.com');
        insert u;
                
        System.runAs(u) {
            
        	BusinessPlanSalesSummaryController.getSalesSummary(plan1.Id);
        }
        
        test.stopTest();
        
    }
    
    static testMethod void validate_ForNonAvpUsers() {
        
        test.startTest();
        
        Business_Plan__c plan2 = [select Id,Name from Business_Plan__c where name='Test Plan'];
       
        BusinessPlanSalesSummaryController.getSalesSummary(plan2.Id);
        
        test.stopTest();
        
    }
    
}