force-app/main/default/objects/Account/fields/RVP__c.field-meta.xml
<CustomField>
    <fullName>RVP__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>AVP</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Accounts1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Annual_Sales_Data__c/Annual_Sales_Data__c.object-meta.xml
<CustomObject>
    <label>Annual Sales Data</label>
    <nameField>
        <displayFormat>ASD-{0000000}</displayFormat>
        <label>Annual Sales Data Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Annual Sales Data</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Annual_Sales_Data__c/fields/Full_Year_Target__c.field-meta.xml
<CustomField>
    <fullName>Full_Year_Target__c</fullName>
    <label>Full Year Target</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Annual_Sales_Data__c/fields/Product_Group__c.field-meta.xml
<CustomField>
    <fullName>Product_Group__c</fullName>
    <label>Product Group</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Hips</fullName>
            </value>
            <value>
                <fullName>Knees</fullName>
            </value>
            <value>
                <fullName>Extremities</fullName>
            </value>
            <value>
                <fullName>Cement</fullName>
            </value>
            <value>
                <fullName>Sports Medicine</fullName>
            </value>
            <value>
                <fullName>Trauma</fullName>
            </value>
            <value>
                <fullName>Foot &amp; Ankle</fullName>
            </value>
            <value>
                <fullName>Surgical</fullName>
            </value>
            <value>
                <fullName>Early Intervention</fullName>
            </value>
            <value>
                <fullName>Total</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Annual_Sales_Data__c/fields/Product_Sales_Summary__c.field-meta.xml
<CustomField>
    <fullName>Product_Sales_Summary__c</fullName>
    <formula>TEXT( Year__c )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Product Sales Summary</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Annual_Sales_Data__c/fields/Territory_Name__c.field-meta.xml
<CustomField>
    <fullName>Territory_Name__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Territory Name</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Annual Sales Data</relationshipLabel>
    <relationshipName>Annual_Sales_Data</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Annual_Sales_Data__c/fields/This_Year_ADS_Growth__c.field-meta.xml
<CustomField>
    <fullName>This_Year_ADS_Growth__c</fullName>
    <label>CY ADS % Growth</label>
    <precision>7</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Annual_Sales_Data__c/fields/This_Year_YTD_Sales_Thru_Month__c.field-meta.xml
<CustomField>
    <fullName>This_Year_YTD_Sales_Thru_Month__c</fullName>
    <label>This Year YTD Sales Thru Month</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Annual_Sales_Data__c/fields/This_Year_YTD_Target_Thru_Month__c.field-meta.xml
<CustomField>
    <fullName>This_Year_YTD_Target_Thru_Month__c</fullName>
    <defaultValue>0</defaultValue>
    <label>This Year YTD Target Thru Month</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Annual_Sales_Data__c/fields/This_Year_YTD_to_Target__c.field-meta.xml
<CustomField>
    <fullName>This_Year_YTD_to_Target__c</fullName>
    <label>CY YTD % to Target</label>
    <precision>6</precision>
    <scale>1</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Annual_Sales_Data__c/fields/Y_1_Percentage_Growth__c.field-meta.xml
<CustomField>
    <fullName>Y_1_Percentage_Growth__c</fullName>
    <label>Y-1 ADS % Growth</label>
    <precision>12</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Annual_Sales_Data__c/fields/Y_1_Sales__c.field-meta.xml
<CustomField>
    <fullName>Y_1_Sales__c</fullName>
    <label>Y-1 Sales</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Annual_Sales_Data__c/fields/Y_1_YTD_Sales_Thru_Month__c.field-meta.xml
<CustomField>
    <fullName>Y_1_YTD_Sales_Thru_Month__c</fullName>
    <label>Y-1 YTD Sales Thru Month</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Annual_Sales_Data__c/fields/Y_2_Percentage_Growth__c.field-meta.xml
<CustomField>
    <fullName>Y_2_Percentage_Growth__c</fullName>
    <label>Y-2 ADS % Growth</label>
    <precision>12</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Annual_Sales_Data__c/fields/Y_2_Sales__c.field-meta.xml
<CustomField>
    <fullName>Y_2_Sales__c</fullName>
    <label>Y-2 Sales</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Business_Plan__c/Business_Plan__c.object-meta.xml
<CustomObject>
    <label>Business Plan</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Business Plan Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Business Plans</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Business_Plan__c/fields/ADS__c.field-meta.xml
<CustomField>
    <fullName>ADS__c</fullName>
    <formula>( BP_Full_Year_Estimate__c  *(1+  ADS_Growth__c  ))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>2022 Full Year Estimate</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Business_Plan__c/fields/ADS_Dollar_Growth__c.field-meta.xml
<CustomField>
    <fullName>ADS_Dollar_Growth__c</fullName>
    <formula>( ( BP_Sales_Plan__c  /  BP_Y_BD__c  ) - ( BP_Full_Year_Estimate__c  /  BP_Y_1_BD__c  ))*  BP_Y_BD__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>2022 Full Year ADS $ Growth</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Business_Plan__c/fields/ADS_Growth__c.field-meta.xml
<CustomField>
    <fullName>ADS_Growth__c</fullName>
    <formula>( ( BP_Sales_Plan__c  /  BP_Y_BD__c  ) - ( BP_Full_Year_Estimate__c  /  BP_Y_1_BD__c  ))/ ( BP_Full_Year_Estimate__c  /  BP_Y_1_BD__c  )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>2022 Full Year ADS % Growth</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Business_Plan__c/fields/Territory_Account_Name__c.field-meta.xml
<CustomField>
    <fullName>Territory_Account_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Territory Account Name</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Business Plans</relationshipLabel>
    <relationshipName>Business_Plans</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Product_Sales_Summary__c/Product_Sales_Summary__c.object-meta.xml
<CustomObject>
    <label>Product Sales Summary</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Product Sales Summary Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Product Sales Summary</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Product_Sales_Summary__c/fields/ADS__c.field-meta.xml
<CustomField>
    <fullName>ADS__c</fullName>
    <formula>(Full_Year_Estimate__c *(1+ ADS_Growth__c ))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Next Year ADS $</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Product_Sales_Summary__c/fields/ADS_Dollar_Growth__c.field-meta.xml
<CustomField>
    <fullName>ADS_Dollar_Growth__c</fullName>
    <formula>( (Sales_Plan__c / BD_Y__c ) - (Full_Year_Estimate__c / BD_Y_1__c ))* BD_Y__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Next Year ADS $ Growth</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Product_Sales_Summary__c/fields/ADS_Growth__c.field-meta.xml
<CustomField>
    <fullName>ADS_Growth__c</fullName>
    <formula>( (Sales_Plan__c / BD_Y__c ) -  (Full_Year_Estimate__c / BD_Y_1__c ))/ (Full_Year_Estimate__c / BD_Y_1__c )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Next Year ADS Growth</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Product_Sales_Summary__c/fields/Annual_Sales_Data__c.field-meta.xml
<CustomField>
    <fullName>Annual_Sales_Data__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Annual Sales Data</label>
    <referenceTo>Annual_Sales_Data__c</referenceTo>
    <relationshipLabel>Product Sales Summary</relationshipLabel>
    <relationshipName>Product_Sales_Summary</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Product_Sales_Summary__c/fields/Business_Plan__c.field-meta.xml
<CustomField>
    <fullName>Business_Plan__c</fullName>
    <label>Business Plan</label>
    <referenceTo>Business_Plan__c</referenceTo>
    <relationshipLabel>Product Sales Summary</relationshipLabel>
    <relationshipName>Product_Sales_Summary</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Product_Sales_Summary__c/fields/Full_Year_Estimate__c.field-meta.xml
<CustomField>
    <fullName>Full_Year_Estimate__c</fullName>
    <formula>IF( Product_Group__c &lt;&gt; &apos;Total&apos;, 
Annual_Sales_Data__r.This_Year_YTD_Sales_Thru_Month__c +  This_Quarter_Projection__c, 
Business_Plan__r.BP_Sales_Plan__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Full Year Estimate</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Product_Sales_Summary__c/fields/Full_Year_Target_Attainment__c.field-meta.xml
<CustomField>
    <fullName>Full_Year_Target_Attainment__c</fullName>
    <formula>Annual_Sales_Data__r.Full_Year_Target__c /  Full_Year_Estimate__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Full Year Target Attainment</label>
    <precision>18</precision>
    <scale>1</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Product_Sales_Summary__c/fields/Planned_Growth__c.field-meta.xml
<CustomField>
    <fullName>Planned_Growth__c</fullName>
    <formula>Sales_Plan__c -  Full_Year_Estimate__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Planned $ Growth</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Product_Sales_Summary__c/fields/Planned_Growth_Percent__c.field-meta.xml
<CustomField>
    <fullName>Planned_Growth_Percent__c</fullName>
    <formula>IF( Full_Year_Estimate__c  &lt;&gt; 0,  (Sales_Plan__c /Full_Year_Estimate__c) -1  , 0)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Planned % Growth</label>
    <precision>18</precision>
    <scale>1</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Product_Sales_Summary__c/fields/Sales_Plan__c.field-meta.xml
<CustomField>
    <fullName>Sales_Plan__c</fullName>
    <formula>Full_Year_Estimate__c + (Full_Year_Estimate__c *  Pricing_Impact__c ) + (Full_Year_Estimate__c *   Vol_Mix_Impact__c  ) +Opportunities__c  +  Risks__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Sales Plan</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Product_Sales_Summary__c/fields/This_year_Growth_Percent__c.field-meta.xml
<CustomField>
    <fullName>This_year_Growth_Percent__c</fullName>
    <formula>( Full_Year_Estimate__c -  Annual_Sales_Data__r.Y_1_Sales__c )/ Annual_Sales_Data__r.Y_1_Sales__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>This year % Growth</label>
    <precision>18</precision>
    <scale>1</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Product_Sales_Summary__c/fields/Y_1_sales__c.field-meta.xml
<CustomField>
    <fullName>Y_1_sales__c</fullName>
    <formula>Annual_Sales_Data__r.Y_1_Sales__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Y-1 Sales</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Product_Sales_Summary__c/fields/Y_2_Sales__c.field-meta.xml
<CustomField>
    <fullName>Y_2_Sales__c</fullName>
    <formula>Annual_Sales_Data__r.Y_2_Sales__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Y-2 Sales</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/classes/BusinessPlanSalesSummaryController.cls
public with sharing class BusinessPlanSalesSummaryController {

    @AuraEnabled(cacheable=true)
    public static List<Product_Sales_Summary__c> getSalesSummaryForBP(String recordId) {
        List<Product_Sales_Summary__c> lstPrdSales =  [SELECT Id 
                                , NAME
                                , Business_Plan__c
                                , Business_Plan__r.Territory_Account_Name__r.RVP__c
                                , Product_Group__c
                                , Annual_Sales_Data__r.Y_2_Sales__c
                                , Y_2_Sales__c
                                , Annual_Sales_Data__r.Y_2_Percentage_Growth__c
                                , Annual_Sales_Data__r.Y_1_Sales__c
                                , Y_1_Sales__c
                                , Annual_Sales_Data__r.Y_1_Percentage_Growth__c
                                , Annual_Sales_Data__r.Y_1_YTD_Sales_Thru_Month__c
                                , Annual_Sales_Data__r.This_Year_YTD_Target_Thru_Month__c
                                , Annual_Sales_Data__r.This_Year_YTD_Sales_Thru_Month__c
                                , Annual_Sales_Data__r.This_Year_YTD_to_Target__c
                                , Annual_Sales_Data__r.This_Year_ADS_Growth__c
                                , Annual_Sales_Data__r.Full_Year_Target__c
                                , Full_Year_Estimate__c
                                , Full_Year_Target_Attainment__c
                                , This_year_Growth_Percent__c
                                , Sales_Plan__c
                                , Planned_Growth__c
                                , Planned_Growth_Percent__c
                                , ADS__c
                                , ADS_Dollar_Growth__c
                                , ADS_Growth__c
                    FROM        Product_Sales_Summary__c
                    WHERE       Business_Plan__c = :recordId
                    AND         Product_Group__c != 'ROSA'
                    AND         Product_Group__c != 'My Mobility'
                    ORDER by    Full_Year_Estimate__c desc
                    ];

        if (lstPrdSales != null) {
        System.debug('Returning Product Sales Summary Records ... '+lstPrdSales.size());
        System.debug(lstPrdSales);
        }
        return lstPrdSales;
    }

    @AuraEnabled(cacheable=true)
    public Static List<Product_Sales_Summary__c> getSalesSummary(string recordId) {
        system.debug('check recordID--> '+recordId);
        String RoleName = [Select u.Name, u.Id From UserRole u where u.Id=:UserInfo.getUserRoleId()].Name;
        if(RoleName.contains('AVP')){
            return [ SELECT     Id 
                            , NAME
                            , Business_Plan__c
                            , Business_Plan__r.Territory_Account_Name__r.RVP__c
                            , Product_Group__c
                            , Annual_Sales_Data__r.Y_2_Sales__c
                            , Y_2_Sales__c
                            , Annual_Sales_Data__r.Y_2_Percentage_Growth__c
                            , Annual_Sales_Data__r.Y_1_Sales__c
                            , Y_1_Sales__c
                            , Annual_Sales_Data__r.Y_1_Percentage_Growth__c
                            , Annual_Sales_Data__r.Y_1_YTD_Sales_Thru_Month__c
                            , Annual_Sales_Data__r.This_Year_YTD_Target_Thru_Month__c
                            , Annual_Sales_Data__r.This_Year_YTD_Sales_Thru_Month__c
                            , Annual_Sales_Data__r.This_Year_YTD_to_Target__c
                            , Annual_Sales_Data__r.This_Year_ADS_Growth__c
                            , Annual_Sales_Data__r.Full_Year_Target__c
                            , Full_Year_Estimate__c
                            , Full_Year_Target_Attainment__c
                            , This_year_Growth_Percent__c
                            , Sales_Plan__c
                            , Planned_Growth__c
                            , Planned_Growth_Percent__c
                            , ADS__c
                            , ADS_Dollar_Growth__c
                            , ADS_Growth__c
                FROM        Product_Sales_Summary__c
                WHERE       Business_Plan__c = :recordId
                AND         Business_Plan__r.Territory_Account_Name__r.RVP__c = :UserInfo.getUserId()
                AND         Product_Group__c != 'ROSA'
                AND         Product_Group__c != 'My Mobility'
                ORDER by    Full_Year_Estimate__c desc
                ];        
        }
        else{
            return [ SELECT     Id 
                                , NAME
                                , Business_Plan__c
                                , Business_Plan__r.Territory_Account_Name__r.RVP__c
                                , Product_Group__c
                                , Annual_Sales_Data__r.Y_2_Sales__c
                                , Y_2_Sales__c
                                , Annual_Sales_Data__r.Y_2_Percentage_Growth__c
                                , Annual_Sales_Data__r.Y_1_Sales__c
                                , Y_1_Sales__c
                                , Annual_Sales_Data__r.Y_1_Percentage_Growth__c
                                , Annual_Sales_Data__r.Y_1_YTD_Sales_Thru_Month__c
                                , Annual_Sales_Data__r.This_Year_YTD_Target_Thru_Month__c
                                , Annual_Sales_Data__r.This_Year_YTD_Sales_Thru_Month__c
                                , Annual_Sales_Data__r.This_Year_YTD_to_Target__c
                                , Annual_Sales_Data__r.This_Year_ADS_Growth__c
                                , Annual_Sales_Data__r.Full_Year_Target__c
                                , Full_Year_Estimate__c
                                , Full_Year_Target_Attainment__c
                                , This_year_Growth_Percent__c
                                , Sales_Plan__c
                                , Planned_Growth__c
                                , Planned_Growth_Percent__c
                                , ADS__c
                                , ADS_Dollar_Growth__c
                                , ADS_Growth__c
                    FROM        Product_Sales_Summary__c
                    WHERE       Business_Plan__c = :recordId
                    AND         Product_Group__c != 'ROSA'
                    AND         Product_Group__c != 'My Mobility'
                    ORDER by    Full_Year_Estimate__c desc
                    ];   
        }
    }
}