force-app/main/default/objects/Account/fields/RVP__c.field-meta.xml
<CustomField>
    <fullName>RVP__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>AVP</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Accounts1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Opt In</fullName>
                <default>true</default>
                <label>Opt In</label>
            </value>
            <value>
                <fullName>Opt Out</fullName>
            </value>
            <value>
                <fullName>Re-Opt In</fullName>
            </value>
            <value>
                <fullName>I</fullName>
            </value>
            <value>
                <fullName>G</fullName>
            </value>
            <value>
                <fullName>A</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/territory__c.field-meta.xml
<CustomField>
    <fullName>territory__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>territory</label>
    <referenceTo>territory__c</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Business_Plan__c/Business_Plan__c.object-meta.xml
<CustomObject>
    <label>Business Plan</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Business Plan Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Business Plans</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Business_Plan__c/fields/AVP_Name__c.field-meta.xml
<CustomField>
    <fullName>AVP_Name__c</fullName>
    <formula>Territory_Account_Name__r.RVP__r.FirstName  + &apos; &apos; +  Territory_Account_Name__r.RVP__r.LastName</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>AVP</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Business_Plan__c/fields/Quarter__c.field-meta.xml
<CustomField>
    <fullName>Quarter__c</fullName>
    <label>Quarter</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>First</fullName>
            </value>
            <value>
                <fullName>Second</fullName>
            </value>
            <value>
                <fullName>Third</fullName>
            </value>
            <value>
                <fullName>Fourth</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Business_Plan__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <defaultValue>&quot;Active&quot;</defaultValue>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Pending AVP Approval</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Approval Not Required</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Business_Plan__c/fields/Territory_Account_Name__c.field-meta.xml
<CustomField>
    <fullName>Territory_Account_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Territory Account Name</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Business Plans</relationshipLabel>
    <relationshipName>Business_Plans</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Product_Sales_Summary__c/Product_Sales_Summary__c.object-meta.xml
<CustomObject>
    <label>Product Sales Summary</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Product Sales Summary Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Product Sales Summary</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Product_Sales_Summary__c/fields/Business_Plan__c.field-meta.xml
<CustomField>
    <fullName>Business_Plan__c</fullName>
    <label>Business Plan</label>
    <referenceTo>Business_Plan__c</referenceTo>
    <relationshipLabel>Product Sales Summary</relationshipLabel>
    <relationshipName>Product_Sales_Summary</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Product_Sales_Summary__c/fields/Planned_Growth__c.field-meta.xml
<CustomField>
    <fullName>Planned_Growth__c</fullName>
    <formula>Sales_Plan__c -  Full_Year_Estimate__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Planned $ Growth</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/territory__c/territory__c.object-meta.xml
<CustomObject>
    <description>Integration</description>
    <label>Territory</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Territory Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Territories</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Territory_Name__c/Territory_Name__c.object-meta.xml
<CustomObject>
    <label>Territory Target Refinement</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Territory Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Territory Target Refinements</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Territory_Name__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <defaultValue>&quot;Round 1&quot;</defaultValue>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Round 1</fullName>
                <default>true</default>
                <label>Round 1</label>
            </value>
            <value>
                <fullName>Round 2</fullName>
            </value>
            <value>
                <fullName>Pending AVP Approval</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Approval Not Required</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Territory_Name__c/fields/Territory_Account__c.field-meta.xml
<CustomField>
    <fullName>Territory_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Territory Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Territory</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/BusinessPlanAVPViewController.cls
global with sharing class BusinessPlanAVPViewController {

    @AuraEnabled(cacheable=true)
    public static List<Business_Plan__c> getBusinessPlans() {
        String RoleName = [Select u.Name, u.Id From UserRole u where u.Id=:UserInfo.getUserRoleId()].Name;
        if(RoleName.contains('AVP')){
            return [SELECT Id, Name, AVP_Name__c, Territory_Account_Name__c, Status__c, Year__c, Quarter__c FROM Business_Plan__c WHERE Territory_Account_Name__r.RVP__c = :UserInfo.getUserId() ];
        }else{
            return [SELECT Id, Name, AVP_Name__c, Territory_Account_Name__c, Status__c, Year__c, Quarter__c FROM Business_Plan__c];
        }
    }

    /*public static Map<String, Map<String, List<Product_Sales_Summary__c>>> getAllBusinessPlansByYear(Integer yr) {
        List<Product_Sales_Summary__c> lstPSS = [Select Id, Name, Business_Plan__r.Name, Business_Plan__r.Territory_Account_Name__r.territory__r.Name, Product_Group__c,Business_Plan__r.Year__c from Product_Sales_Summary__c where Business_Plan__r.Active__c = true and Business_Plan__r.Year__c = :yr order by Business_Plan__r.Year__c desc, Product_Group__c asc];
        Map<String,Map<String, List<Product_Sales_Summary__c>>> terrPrdMap = new Map<String,Map<String, List<Product_Sales_Summary__c>>>();

        if (lstPSS != null && lstPSS.size() > 0) {
            for(Product_Sales_Summary__c obj : lstPSS){

                if (obj.Business_Plan__c != null 
                    && obj.Business_Plan__r.Territory_Account_Name__c != null 
                    && obj.Business_Plan__r.Territory_Account_Name__r.territory__c != null
                    && obj.Business_Plan__r.Territory_Account_Name__r.territory__r.Name != null)
                {
                    if(!terrPrdMap.containsKey(obj.Business_Plan__r.Territory_Account_Name__r.territory__r.Name)){
                        terrPrdMap.put(obj.Business_Plan__r.Territory_Account_Name__r.territory__r.Name, new Map<String, List<Product_Sales_Summary__c>>());
                    }

                    if (!terrPrdMap.get(obj.Business_Plan__r.Territory_Account_Name__r.territory__r.Name).containsKey(obj.Product_group__c))
                    {
                        terrPrdMap.get(obj.Business_Plan__r.Territory_Account_Name__r.territory__r.Name).put(obj.Product_group__c, new List<Product_Sales_Summary__c>());
                    }

                    terrPrdMap.get(obj.Business_Plan__r.Territory_Account_Name__r.territory__r.Name).get(obj.Product_group__c).add(obj);
                }
                //terrPrdMap.get(obj.Business_Plan__r.Territory_Account_Name__r.territory__r.Name).add(
                    //new UserTerritoryAssociation(uta2.UserId, uta2.Territory2Id, uta2.RoleInTerritory2));
            }
    
        }

        return terrPrdMap;

    }*/

    public static Map<String, Map<String, List<Product_Sales_Summary__c>>> getAllBusinessPlans() {
        List<Product_Sales_Summary__c> lstPSS = [Select Id, Name, Business_Plan__r.Name, Business_Plan__r.Territory_Account_Name__r.territory__r.Name, Product_Group__c,Business_Plan__r.Year__c from Product_Sales_Summary__c where Business_Plan__r.Active__c = true order by Business_Plan__r.Year__c desc, Product_Group__c asc];
        Map<String,Map<String, List<Product_Sales_Summary__c>>> terrPrdMap = new Map<String,Map<String, List<Product_Sales_Summary__c>>>();

        if (lstPSS != null && lstPSS.size() > 0) {
            for(Product_Sales_Summary__c obj : lstPSS){

                if (obj.Business_Plan__c != null 
                    && obj.Business_Plan__r.Territory_Account_Name__c != null 
                    && obj.Business_Plan__r.Territory_Account_Name__r.territory__c != null
                    && obj.Business_Plan__r.Territory_Account_Name__r.territory__r.Name != null)
                {
                    if(!terrPrdMap.containsKey(obj.Business_Plan__r.Territory_Account_Name__r.territory__r.Name)){
                        terrPrdMap.put(obj.Business_Plan__r.Territory_Account_Name__r.territory__r.Name, new Map<String, List<Product_Sales_Summary__c>>());
                    }

                    if (!terrPrdMap.get(obj.Business_Plan__r.Territory_Account_Name__r.territory__r.Name).containsKey(obj.Product_group__c))
                    {
                        terrPrdMap.get(obj.Business_Plan__r.Territory_Account_Name__r.territory__r.Name).put(obj.Product_group__c, new List<Product_Sales_Summary__c>());
                    }

                    terrPrdMap.get(obj.Business_Plan__r.Territory_Account_Name__r.territory__r.Name).get(obj.Product_group__c).add(obj);
                }
                /*terrPrdMap.get(obj.Business_Plan__r.Territory_Account_Name__r.territory__r.Name).add(
                    new UserTerritoryAssociation(uta2.UserId, uta2.Territory2Id, uta2.RoleInTerritory2));*/
            }
    
        }

        return terrPrdMap;

    }

    public static List<string> bgColorCodesForChart = new List<string>{'#FF6384','#36A2EB','#bed2ce','#0abc70','#f5b022','#e85e7f','#e85e7f','#e85e7f','#e85e7f','#e85e7f','#e85e7f','#e85e7f','#e85e7f'};
    
    @AuraEnabled
    public static ChartDataWrapper findDataSetForChart(String recordId){
        ChartDataWrapper cdataSet = new ChartDataWrapper();
        System.debug('recordId:' + recordId);
        string queryString = 'SELECT Product_Group__c, SUM(Planned_Growth__c) FROM Product_Sales_Summary__c GROUP BY Product_Group__c';
        AggregateResult[] groupedResults =  database.query(queryString);
        
        integer count =0;
        for (AggregateResult ar : groupedResults)  
        {
            
            string clabel = string.valueof(ar.get('Product_Group__c'));
            string categorylabel = string.valueof(ar.get('Product_Group__c'));
            decimal amount = (decimal)ar.get('expr0');
            //amount = amount != null ? (amount/1000000).setScale(2) : 0;
            cdataSet.labels.add(clabel + '('+string.valueof(amount)+')');
            cdataSet.dataValues.add(string.valueof(amount));
            if(bgColorCodesForChart[count] != null){
                cdataSet.bgColorValues.add(bgColorCodesForChart[count]);
                count++;
            }
            System.debug('Product_Group__c:' + clabel);
            System.debug('Sum amount' + string.valueof(amount));
        }
        return cdataSet;
    }
    
    public class ChartDataWrapper{
        @AuraEnabled
        public list<string> labels{get;set;}
        @AuraEnabled
        public list<string> dataValues{get;set;}
        @AuraEnabled
        public list<string> bgColorValues{get;set;}
        public ChartDataWrapper(){
            labels =new list<string> ();
            dataValues = new list<string> ();
            bgColorValues = new list<string> ();
        }
    }
}