force-app/main/default/objects/Account/fields/Sales_Plan_Owner__c.field-meta.xml
<CustomField>
    <fullName>Sales_Plan_Owner__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Field used to trigger sales plan owner for distributor.</description>
    <label>Sales Plan Owner</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Accounts2</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/recordTypes/Distributor.recordType-meta.xml
<RecordType>
    <fullName>Distributor</fullName>
    <active>true</active>
    <description>A record to keep information about Zimmer Distributors</description>
    <label>Distributor</label>
</RecordType>

force-app/main/default/objects/Competitor__c/Competitor__c.object-meta.xml
<CustomObject>
    <label>Competitor-Global</label>
    <nameField>
        <displayFormat>CM-{YYYY}{MM}-{000000}</displayFormat>
        <label>Competitor ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Competitors-Global</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Competitor__c/fields/Competitor__c.field-meta.xml
<CustomField>
    <fullName>Competitor__c</fullName>
    <label>Competitor</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>AAP</fullName>
            </value>
            <value>
                <fullName>Acumed</fullName>
            </value>
            <value>
                <fullName>Aecuaos</fullName>
            </value>
            <value>
                <fullName>Aesculap</fullName>
            </value>
            <value>
                <fullName>Ai-medic</fullName>
            </value>
            <value>
                <fullName>Alpha Consulting Group</fullName>
            </value>
            <value>
                <fullName>Arthrex</fullName>
            </value>
            <value>
                <fullName>Ascension</fullName>
            </value>
            <value>
                <fullName>ASDM</fullName>
            </value>
            <value>
                <fullName>AustoFix</fullName>
            </value>
            <value>
                <fullName>Axomed</fullName>
            </value>
            <value>
                <fullName>B.Braun</fullName>
            </value>
            <value>
                <fullName>Biomet</fullName>
            </value>
            <value>
                <fullName>Brehm</fullName>
            </value>
            <value>
                <fullName>Conformis</fullName>
            </value>
            <value>
                <fullName>Corin</fullName>
            </value>
            <value>
                <fullName>DePuy</fullName>
            </value>
            <value>
                <fullName>DeSoutter</fullName>
            </value>
            <value>
                <fullName>DJO/Encore</fullName>
            </value>
            <value>
                <fullName>Emergo Asia Pacific Pty Ltd</fullName>
            </value>
            <value>
                <fullName>Eska</fullName>
            </value>
            <value>
                <fullName>Exactech</fullName>
            </value>
            <value>
                <fullName>GE Healthcare Performance Solutions</fullName>
            </value>
            <value>
                <fullName>Global</fullName>
            </value>
            <value>
                <fullName>Globus Medical</fullName>
            </value>
            <value>
                <fullName>Health Care Surgical</fullName>
            </value>
            <value>
                <fullName>Hunter &amp; Associates</fullName>
            </value>
            <value>
                <fullName>Implantcast</fullName>
            </value>
            <value>
                <fullName>Implantindustries</fullName>
            </value>
            <value>
                <fullName>JMM</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Competitor__c/recordTypes/Sales.recordType-meta.xml
<RecordType>
    <fullName>Sales</fullName>
    <active>true</active>
    <description>US Recon SPMT used for sales prospects entered in the Distributor Channel</description>
    <label>Sales</label>
</RecordType>

force-app/main/default/objects/Contact/fields/Region__c.field-meta.xml
<CustomField>
    <fullName>Region__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Region</label>
    <length>25</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Competitor__c.field-meta.xml
<CustomField>
    <fullName>Competitor__c</fullName>
    <inlineHelpText>This is the competitor you are going up against for this sales plan.</inlineHelpText>
    <label>Primary Competitor</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>3di</fullName>
            </value>
            <value>
                <fullName>AAP</fullName>
            </value>
            <value>
                <fullName>Acumed</fullName>
            </value>
            <value>
                <fullName>Aecuaos</fullName>
            </value>
            <value>
                <fullName>Aesculap</fullName>
            </value>
            <value>
                <fullName>Ai-medic</fullName>
            </value>
            <value>
                <fullName>Alpha Consulting Group</fullName>
            </value>
            <value>
                <fullName>AMPLITUDE SAS</fullName>
            </value>
            <value>
                <fullName>AQ Implants</fullName>
            </value>
            <value>
                <fullName>Arthrex</fullName>
            </value>
            <value>
                <fullName>Arthrosurface</fullName>
            </value>
            <value>
                <fullName>ARTIQO</fullName>
            </value>
            <value>
                <fullName>Ascension</fullName>
            </value>
            <value>
                <fullName>Axomed</fullName>
            </value>
            <value>
                <fullName>B.Braun</fullName>
            </value>
            <value>
                <fullName>Brehm</fullName>
            </value>
            <value>
                <fullName>Conformis</fullName>
            </value>
            <value>
                <fullName>ConMed</fullName>
            </value>
            <value>
                <fullName>Corentec</fullName>
            </value>
            <value>
                <fullName>Corin</fullName>
            </value>
            <value>
                <fullName>Crossroads</fullName>
            </value>
            <value>
                <fullName>CrossRoads Medical</fullName>
            </value>
            <value>
                <fullName>DePuy</fullName>
            </value>
            <value>
                <fullName>DePuy Mitek</fullName>
            </value>
            <value>
                <fullName>DePuy Synthes</fullName>
            </value>
            <value>
                <fullName>DeSoutter</fullName>
            </value>
            <value>
                <fullName>DIZG</fullName>
            </value>
            <value>
                <fullName>DJO</fullName>
            </value>
            <value>
                <fullName>DJO Surgical</fullName>
            </value>
            <value>
                <fullName>Encore</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Primary_Sales_Associate__c.field-meta.xml
<CustomField>
    <fullName>Primary_Sales_Associate__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Please select your primary sales contact for this account.</inlineHelpText>
    <label>Primary Sales Associate</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>(1 AND 4) OR (1 AND 5) OR (2 AND 3)</booleanFilter>
        <filterItems>
            <field>Contact.RecordTypeId</field>
            <operation>equals</operation>
            <value>Zimmer Sales Contact</value>
        </filterItems>
        <filterItems>
            <field>$Source.RecordTypeId</field>
            <operation>equals</operation>
            <value>AP-AU-Sales</value>
        </filterItems>
        <filterItems>
            <field>Contact.RecordTypeId</field>
            <operation>equals</operation>
            <value>Zimmer Corporate Employees</value>
        </filterItems>
        <filterItems>
            <field>$Source.RecordTypeId</field>
            <operation>equals</operation>
            <value>Sales</value>
        </filterItems>
        <filterItems>
            <field>$Source.RecordTypeId</field>
            <operation>equals</operation>
            <value>AM-CA-RC Sales</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Associate Sales Plans</relationshipLabel>
    <relationshipName>Sales_Plans</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Sales_Plan_Owner__c.field-meta.xml
<CustomField>
    <fullName>Sales_Plan_Owner__c</fullName>
    <formula>Primary_Sales_Associate__r.Account.Sales_Plan_Owner__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Sales Plan Owner</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/User/fields/Business_Division__c.field-meta.xml
<CustomField>
    <fullName>Business_Division__c</fullName>
    <description>This field is required-There are workflow and validation rules that uses this field to determine processing path based on the Geography, Business Division and/or Region field(s) setting of the user.</description>
    <inlineHelpText>This field is required-There are workflow and validation rules that uses this field to determine processing path based on the Geography, Business Division and/or Region field(s) setting of the user.</inlineHelpText>
    <label>Business Division</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>BH</fullName>
            </value>
            <value>
                <fullName>CAS</fullName>
            </value>
            <value>
                <fullName>CO</fullName>
            </value>
            <value>
                <fullName>DN</fullName>
            </value>
            <value>
                <fullName>GE</fullName>
            </value>
            <value>
                <fullName>GO</fullName>
            </value>
            <value>
                <fullName>HL</fullName>
            </value>
            <value>
                <fullName>N/A</fullName>
            </value>
            <value>
                <fullName>RC</fullName>
            </value>
            <value>
                <fullName>SP</fullName>
            </value>
            <value>
                <fullName>TR</fullName>
            </value>
            <value>
                <fullName>ZSP</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/User/fields/Geography__c.field-meta.xml
<CustomField>
    <fullName>Geography__c</fullName>
    <description>This field is required-There are workflow and validation rules that uses this field to determine processing path based on the Geography, Business Division and/or Region field(s) setting of the user.</description>
    <inlineHelpText>This field is required-There are workflow and validation rules that uses this field to determine processing path based on the Geography, Business Division and/or Region field(s) setting of the user.</inlineHelpText>
    <label>Geography</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Argentina</fullName>
            </value>
            <value>
                <fullName>Australia</fullName>
            </value>
            <value>
                <fullName>Austria</fullName>
            </value>
            <value>
                <fullName>Belgium</fullName>
            </value>
            <value>
                <fullName>Bolivia (Plurinational State of)</fullName>
            </value>
            <value>
                <fullName>Brazil</fullName>
            </value>
            <value>
                <fullName>Canada</fullName>
            </value>
            <value>
                <fullName>Chile</fullName>
            </value>
            <value>
                <fullName>China</fullName>
            </value>
            <value>
                <fullName>Colombia</fullName>
            </value>
            <value>
                <fullName>Costa Rica</fullName>
            </value>
            <value>
                <fullName>Czech Republic</fullName>
            </value>
            <value>
                <fullName>Denmark</fullName>
            </value>
            <value>
                <fullName>Ecuador</fullName>
            </value>
            <value>
                <fullName>Finland</fullName>
            </value>
            <value>
                <fullName>France</fullName>
            </value>
            <value>
                <fullName>Germany</fullName>
            </value>
            <value>
                <fullName>Hong Kong</fullName>
            </value>
            <value>
                <fullName>Hungary</fullName>
            </value>
            <value>
                <fullName>India</fullName>
            </value>
            <value>
                <fullName>Ireland</fullName>
            </value>
            <value>
                <fullName>Italy</fullName>
            </value>
            <value>
                <fullName>Japan</fullName>
            </value>
            <value>
                <fullName>Korea (Republic of)</fullName>
            </value>
            <value>
                <fullName>Lebanon</fullName>
            </value>
            <value>
                <fullName>Malaysia</fullName>
            </value>
            <value>
                <fullName>Mexico</fullName>
            </value>
            <value>
                <fullName>N/A</fullName>
            </value>
            <value>
                <fullName>Netherlands</fullName>
            </value>
            <value>
                <fullName>New Zealand</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/User/fields/Region__c.field-meta.xml
<CustomField>
    <fullName>Region__c</fullName>
    <description>This field is required-There are workflow and validation rules that uses this field to determine processing path based on the Geography, Business Division and/or Region field(s) setting of the user.</description>
    <inlineHelpText>This field is required-There are workflow and validation rules that uses this field to determine processing path based on the Geography, Business Division and/or Region field(s) setting of the user.</inlineHelpText>
    <label>Region</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>AM</fullName>
            </value>
            <value>
                <fullName>AP</fullName>
            </value>
            <value>
                <fullName>EU</fullName>
            </value>
            <value>
                <fullName>GL</fullName>
            </value>
            <value>
                <fullName>LA</fullName>
            </value>
            <value>
                <fullName>N/A</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/SalesplanOwnerTestClass.cls
/*****************************************************************************/
/* Trigger name: SalesPlanOwnerUpdate                                        */
/* Author: Saikishore Aengareddy                                             */
/* Last modified: 08/29/2010                                                 */
/* Purpose: Used to provide unit test coverage for SalesPlanOwnerUpdate      */
/*****************************************************************************/

@isTest
private class SalesplanOwnerTestClass {
    static testMethod void validateSalesPlanOwner() {
        //User
        Profile p = [select id from profile where name='Custom-Zimmer Sales'];
        User u = new User(alias = 'standt', email='standarduser@testorg.com',
                          emailencodingkey='UTF-8', lastname='Testing', languagelocalekey='en_US',
                          localesidkey='en_US', profileid = p.Id,timezonesidkey='America/Los_Angeles',
                          username='zimmeruser@testorg.com',Region__c='AM', Geography__c='US', Business_Division__c='DN');
        insert u;
        System.debug('-----SalesplanOwnerTestClass.validateSalesPlanOwner-u----- = ' + u);
        System.runAs(u){
        // Insert account
        Account acct = new Account();
        
        // get a record type
        //String rtId = [select id from RecordType where SObjectType = 'Account' and IsActive = true and Name = 'Distributor'].Id;
        String rtId = [select id from RecordType where SObjectType = 'Account' and IsActive = true and DeveloperName = 'Distributor'].Id;
        
        // populate the required fields
        acct.RecordTypeId = rtId;
        acct.Name = 'TEST ACCOUNT1';
        acct.BillingCountry = 'US';   
       
        acct.ShippingCountry = 'US';  
       
        acct.BillingState='AL'; 
          
        acct.ShippingState ='AL';
       
        acct.BillingStreet ='Test street123 dr';
        acct.Sales_Plan_Owner__c = u.id;
        insert acct;
        
        // Insert account
        Account acct1 = new Account();
        
        // get a record type
        //String rtId1 = [select id from RecordType where SObjectType = 'Account' and IsActive = true and Name = 'Physician'].Id;
        String rtId1 = [select id from RecordType where SObjectType = 'Account' and IsActive = true and DeveloperName = 'Physician'].Id;
        
        // populate the required fields
        acct.RecordTypeId = rtId1;
        acct1.FirstName = 'TEST FIRST';
        acct1.LastName = 'TEST ACCOUNT2';
        acct1.BillingCountry = 'US';   
        acct1.PersonOtherCountry= 'US';   
        acct1.ShippingCountry = 'US';   
        acct1.PersonMailingCountry = 'US';   
        acct1.BillingState='AL'; 
        acct1.PersonMailingState='AK';
        acct1.PersonOtherState='AK';
        acct1.ShippingState ='AL';
        acct1.PersonOtherState='AL';
        acct1.BillingStreet ='Test street dr';
        acct1.PersonMailingStreet ='Test street two dr';
        acct1.PersonMailingStreet ='Sample street dr';
        acct1.PersonMailingCity='LA';        
        acct1.PersonMailingPostalCode='10106';
        insert acct1;

        //Insert Contact
        Contact c = new Contact();
        c.FirstName = 'John';
        c.LastName = 'Doe';
        c.Email = 'test@zimmer.com';
        c.AccountId = acct.Id;
        c.RecordTypeId = '012800000002DoB';
        
        insert c;
        
        //Insert Opportunity
        Opportunity oppty = new opportunity();
        oppty.Amount = 1000.0;
        oppty.StageName = 'Commitment';
        oppty.Name = 'TEST POA OPPTY';
        oppty.Type = 'Opportunity';
        oppty.Competitor__c = 'TEST COMPETITOR22';
        oppty.CloseDate = Date.Today().addDays(60);
       // oppty.AccountId = acct1.Id;
        oppty.Primary_sales_associate__c = c.id;
        // insert the opportunity
        insert oppty;
        Id spOwner = [select sales_plan_owner__c from Account where 
        Name = 'TEST ACCOUNT1' and BillingStreet ='Test street123 dr' limit 1].sales_plan_owner__c;
        Id opOwner = [select ownerId from opportunity where competitor__c = 'TEST COMPETITOR22' limit 1].OwnerId;
        system.assertEquals(spOwner, opOwner);
        }         
    }
}