force-app/main/default/objects/Account/fields/Sales_History__c.field-meta.xml
<CustomField>
    <fullName>Sales_History__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>DN-Sales History</label>
    <referenceTo>Sales_History__c</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Sales_History__c/Sales_History__c.object-meta.xml
<CustomObject>
    <label>DN-Sales History</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Invoice Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sales History</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Sales_History__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Sales History</relationshipLabel>
    <relationshipName>Sales</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/User/fields/Business_Division__c.field-meta.xml
<CustomField>
    <fullName>Business_Division__c</fullName>
    <description>This field is required-There are workflow and validation rules that uses this field to determine processing path based on the Geography, Business Division and/or Region field(s) setting of the user.</description>
    <inlineHelpText>This field is required-There are workflow and validation rules that uses this field to determine processing path based on the Geography, Business Division and/or Region field(s) setting of the user.</inlineHelpText>
    <label>Business Division</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>BH</fullName>
            </value>
            <value>
                <fullName>CAS</fullName>
            </value>
            <value>
                <fullName>CO</fullName>
            </value>
            <value>
                <fullName>DN</fullName>
            </value>
            <value>
                <fullName>GE</fullName>
            </value>
            <value>
                <fullName>GO</fullName>
            </value>
            <value>
                <fullName>HL</fullName>
            </value>
            <value>
                <fullName>N/A</fullName>
            </value>
            <value>
                <fullName>RC</fullName>
            </value>
            <value>
                <fullName>SP</fullName>
            </value>
            <value>
                <fullName>TR</fullName>
            </value>
            <value>
                <fullName>ZSP</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/User/fields/Geography__c.field-meta.xml
<CustomField>
    <fullName>Geography__c</fullName>
    <description>This field is required-There are workflow and validation rules that uses this field to determine processing path based on the Geography, Business Division and/or Region field(s) setting of the user.</description>
    <inlineHelpText>This field is required-There are workflow and validation rules that uses this field to determine processing path based on the Geography, Business Division and/or Region field(s) setting of the user.</inlineHelpText>
    <label>Geography</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Argentina</fullName>
            </value>
            <value>
                <fullName>Australia</fullName>
            </value>
            <value>
                <fullName>Austria</fullName>
            </value>
            <value>
                <fullName>Belgium</fullName>
            </value>
            <value>
                <fullName>Bolivia (Plurinational State of)</fullName>
            </value>
            <value>
                <fullName>Brazil</fullName>
            </value>
            <value>
                <fullName>Canada</fullName>
            </value>
            <value>
                <fullName>Chile</fullName>
            </value>
            <value>
                <fullName>China</fullName>
            </value>
            <value>
                <fullName>Colombia</fullName>
            </value>
            <value>
                <fullName>Costa Rica</fullName>
            </value>
            <value>
                <fullName>Czech Republic</fullName>
            </value>
            <value>
                <fullName>Denmark</fullName>
            </value>
            <value>
                <fullName>Ecuador</fullName>
            </value>
            <value>
                <fullName>Finland</fullName>
            </value>
            <value>
                <fullName>France</fullName>
            </value>
            <value>
                <fullName>Germany</fullName>
            </value>
            <value>
                <fullName>Hong Kong</fullName>
            </value>
            <value>
                <fullName>Hungary</fullName>
            </value>
            <value>
                <fullName>India</fullName>
            </value>
            <value>
                <fullName>Ireland</fullName>
            </value>
            <value>
                <fullName>Italy</fullName>
            </value>
            <value>
                <fullName>Japan</fullName>
            </value>
            <value>
                <fullName>Korea (Republic of)</fullName>
            </value>
            <value>
                <fullName>Lebanon</fullName>
            </value>
            <value>
                <fullName>Malaysia</fullName>
            </value>
            <value>
                <fullName>Mexico</fullName>
            </value>
            <value>
                <fullName>N/A</fullName>
            </value>
            <value>
                <fullName>Netherlands</fullName>
            </value>
            <value>
                <fullName>New Zealand</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/User/fields/Region__c.field-meta.xml
<CustomField>
    <fullName>Region__c</fullName>
    <description>This field is required-There are workflow and validation rules that uses this field to determine processing path based on the Geography, Business Division and/or Region field(s) setting of the user.</description>
    <inlineHelpText>This field is required-There are workflow and validation rules that uses this field to determine processing path based on the Geography, Business Division and/or Region field(s) setting of the user.</inlineHelpText>
    <label>Region</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>AM</fullName>
            </value>
            <value>
                <fullName>AP</fullName>
            </value>
            <value>
                <fullName>EU</fullName>
            </value>
            <value>
                <fullName>GL</fullName>
            </value>
            <value>
                <fullName>LA</fullName>
            </value>
            <value>
                <fullName>N/A</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/updSalesHistoryOwnTEST.cls
// ** Test Script for Sales History Owner Change Trigger.
@isTest
private class updSalesHistoryOwnTEST  {
	
    static User testUser; 
    static Id testRecordTypeId;

    private static void setupData(){
        Profile profile = [select Id from Profile where name = 'System Administrator' limit 1];
        
        User userObj = new User(alias = 'dentalca', email='dentalca@testorg.com',
        emailencodingkey='UTF-8', lastname='TestUser1', languagelocalekey='en_US',
        localesidkey='en_US', profileid = profile.Id,
        timezonesidkey='America/Los_Angeles', username='dentalca@testorg.com', isActive=true, 
        Region__c='AM', Geography__c='US', Business_Division__c='DN');
        insert userObj;

        System.assert(userObj.Id != null);       
        testUser = userObj;

        System.debug('-----updSalesHistoryOwnTEST.setupData-testUser----- = ' + testUser);

        String dentalCanadaRecordType = null;
        List<RecordType> recordTypeList = [Select Id From RecordType Where SobjectType = 'Account' and DeveloperName = 'DN_CA_Account_Record_Type' LIMIT 1];
        for (RecordType recordType : recordTypeList) {
            dentalCanadaRecordType = recordType.Id;
        }
        
        System.assert(dentalCanadaRecordType != null);       
        testRecordTypeId = dentalCanadaRecordType;

        System.debug('-----updSalesHistoryOwnTEST.setupData-testRecordTypeId----- = ' + testRecordTypeId);      
    }

    static testMethod void BulkUpdateTriggerTest() {
        setupData(); 
        System.runAs(testUser){
            // TEST BATCH UPDATES
            // This test will cover Sales History Updates that exceed
            // the the DML record limit on triggers 
            // ** NOTE ** TEST ups the limit to 500, so it's impossible
            // to test using the trigger. And if we try to exceed the 500
            // DML limit we hit another issue - max. batch in test is also 500
            // So the only way to test is to force the routine to run by passing in 
            // the account

            // Create Test Account
            Account a = new Account();
            a.Name = 'TESTAPEX';
            a.OwnerId = Userinfo.getUserId() ;
            a.RecordTypeId = testRecordTypeId;
            insert a;
            system.debug(' ---> [BulkUpdateTriggerTest] Owner Id ' + a.OwnerId );
            system.debug(' ---> [BulkUpdateTriggerTest] Created By ' + a.CreatedById );
            system.debug(' ---> [BulkUpdateTriggerTest] Account Name ' + a.Name );
        
            // Insert 200 Test Sales History Records(Invoices)
            List<Sales_History__c> salesHistory = new list<sales_history__C>{};

            for (integer i = 0; i < 200; i++) {
                Sales_History__c SalesHist = new Sales_History__c();
                SalesHist.Name = 'TEST' + i; 
                //SalesHist.OwnerId = a.OwnerID;
                SalesHist.Account__c = a.ID;
                // Insert test record to list bulk update outside of loop
                salesHistory.add(SalesHist);
            }
            // Bulk Insert records
            insert salesHistory;

            // Fire update trigger by changing ownership on Account record
            a.OwnerID = testUser.Id;
            update a;
        
            // Force call to batch processing
            Set<ID> AccountIDs = new Set<ID>();
            AccountIDs.add(a.ID);
            updSalesHistOwner.OwnerUpdate(AccountIDs);  
            
            // Added to get code coverage for updSalesHistOwnerNow. remove if required to Activate the class in production.
            updSalesHistOwnerNow.OwnerUpdate(AccountIDs);
        }
    }
    
    static testMethod void SyncUpdateTriggerTest() {
        setupData(); 
        System.runAs(testUser){
            // TEST SYNCHRONOUS UPDATES
            // This test will cover Sales History Updates that are
            // within the 100 DML record limit on triggers. This
            // will cause the update to occur as part of the triggers
            // stream

            // Create Test Account
            Account a = new Account();
            a.Name = 'TESTAPEX';
            a.OwnerId = Userinfo.getUserId() ;
            a.RecordTypeId = testRecordTypeId;
            insert a;
            system.debug(' ---> [SyncUpdateTriggerTest] Owner Id ' + a.OwnerId );
            system.debug(' ---> [SyncUpdateTriggerTest] Created By ' + a.CreatedById );
            system.debug(' ---> [SyncUpdateTriggerTest] Account Name ' + a.Name );
        
        
            // Insert 99 Test Sales History Records
            List<Sales_History__c> salesHistory = new list<sales_history__C>{};
        
            for (integer i = 0; i < 99; i++) {
                Sales_History__c SalesHist = new Sales_History__c();
                SalesHist.Name = 'TEST' + i; 
                //SalesHist.OwnerId = a.OwnerID;
                SalesHist.Account__c = a.ID;
                // Insert test record to list bulk update outside of loop
                salesHistory.add(SalesHist);
            }
            // Bulk Insert records
            insert salesHistory;

            // Fire update trigger by changing ownership on Account record
            a.OwnerID = testUser.Id;
            update a;           
        }
    }
    
    static testMethod void NoUpdatesTriggerTest() {
        setupData();
        System.runAs(testUser){
            // NO ACCOUNTS TO UPDATE
            // This test will cover the scenario where the trigger
            // is fired but the account owner has not changed, therefore
            // there is nothing to do.

            // Create Test Account
            Account a = new Account();
            a.Name = 'TESTAPEX';
            a.OwnerId = Userinfo.getUserId() ;
            a.RecordTypeId = testRecordTypeId;
            a.Site = 'TEST SITE';
            insert a;
            system.debug(' ---> [NoUpdatesTriggerTest] Owner Id ' + a.OwnerId );
            system.debug(' ---> [NoUpdatesTriggerTest] Created By ' + a.CreatedById );
            system.debug(' ---> [NoUpdatesTriggerTest] Account Name ' + a.Name );
        
            // Fire update trigger by changing site on Account record
            a.Site = 'ANOTHER SITE';
            update a;           
        } 
    }
    
    static testMethod void NoSalesHistoryToUpdateTest() {
        setupData(); 
        System.runAs(testUser){
            // NO SALES HISTORY TO UPDATE
            // This test will cover the trigger firing with an Account Owner
            // Change and not Sales History records to update.

            // Create Test Account
            Account a = new Account();
            a.Name = 'TESTAPEX';
            a.OwnerId = Userinfo.getUserId() ;
            a.RecordTypeId = testRecordTypeId;
            insert a;
            system.debug(' ---> [NoSalesHistoryToUpdateTest] Owner Id ' + a.OwnerId );
            system.debug(' ---> [NoSalesHistoryToUpdateTest] Created By ' + a.CreatedById );
            system.debug(' ---> [NoSalesHistoryToUpdateTest] Account Name ' + a.Name );
        
            // Fire update trigger by changing ownership on Account record
            a.OwnerID = testUser.Id;
            update a;           
        }
    }
    
}