force-app/main/default/objects/Account/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Opt In</fullName>
                <default>true</default>
                <label>Opt In</label>
            </value>
            <value>
                <fullName>Opt Out</fullName>
            </value>
            <value>
                <fullName>Re-Opt In</fullName>
            </value>
            <value>
                <fullName>I</fullName>
            </value>
            <value>
                <fullName>G</fullName>
            </value>
            <value>
                <fullName>A</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/territory__c.field-meta.xml
<CustomField>
    <fullName>territory__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>territory</label>
    <referenceTo>territory__c</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Instrument_Request__c/Instrument_Request__c.object-meta.xml
<CustomObject>
    <description>This object is being used for Instrument Tracking/Request Integration.</description>
    <label>Instrument Request</label>
    <nameField>
        <displayFormat>Inst-{00000}</displayFormat>
        <label>Instrument Request Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Instrument Requests</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Instrument_Request__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Instrument Requests</relationshipLabel>
    <relationshipName>Instrument_Requests</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Instrument_Request__c/fields/Record_Number__c.field-meta.xml
<CustomField>
    <fullName>Record_Number__c</fullName>
    <defaultValue>1</defaultValue>
    <label>Record Number</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Instrument_Request__c/fields/Requested_Qty__c.field-meta.xml
<CustomField>
    <fullName>Requested_Qty__c</fullName>
    <label>Requested_Qty</label>
    <precision>5</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Instrument_Request__c/fields/SNAP_KIT_ID__c.field-meta.xml
<CustomField>
    <fullName>SNAP_KIT_ID__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <externalId>true</externalId>
    <label>SNAP KIT ID</label>
    <length>50</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Instrument_Request__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Open</fullName>
            </value>
            <value>
                <fullName>Submitted</fullName>
            </value>
            <value>
                <fullName>Sent To Committee</fullName>
            </value>
            <value>
                <fullName>Review</fullName>
            </value>
            <value>
                <fullName>Unsubmitted</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Approved w/Edits</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Denied</fullName>
            </value>
            <value>
                <fullName>New</fullName>
            </value>
            <value>
                <fullName>Returned</fullName>
            </value>
            <value>
                <fullName>Ordered</fullName>
            </value>
            <value>
                <fullName>Partially Ordered</fullName>
            </value>
            <value>
                <fullName>Shipped</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Ortho_Team__c.field-meta.xml
<CustomField>
    <fullName>Ortho_Team__c</fullName>
    <description>This field represent the territory of Opportunity, this field mimic the standard territory is created for different label for ortho users.</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Assigned Team</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Forecast</fullName>
                <isActive>false</isActive>
                <label>Forecast</label>
            </value>
            <value>
                <fullName>Upside</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Surgeon_Name__c.field-meta.xml
<CustomField>
    <fullName>Surgeon_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>This field is used to lookup your Surgeon account.</inlineHelpText>
    <label>Surgeon Name</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Physician, Physician(Processing)</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Opportunities (Surgeon Name)</relationshipLabel>
    <relationshipName>Opportunities2</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/territory__c/territory__c.object-meta.xml
<CustomObject>
    <description>Integration</description>
    <label>Territory</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Territory Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Territories</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/User_Territory_Association__c/User_Territory_Association__c.object-meta.xml
<CustomObject>
    <label>User Territory Association</label>
    <nameField>
        <displayFormat>UT-{0000}</displayFormat>
        <label>User Territory Association Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>User Territory Associations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/User_Territory_Association__c/fields/Role__c.field-meta.xml
<CustomField>
    <fullName>Role__c</fullName>
    <label>Role</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Biologics</fullName>
            </value>
            <value>
                <fullName>Extremities</fullName>
            </value>
            <value>
                <fullName>Foot &amp; Ankle</fullName>
            </value>
            <value>
                <fullName>Hips</fullName>
            </value>
            <value>
                <fullName>Knees</fullName>
            </value>
            <value>
                <fullName>Sports Medicine</fullName>
            </value>
            <value>
                <fullName>Trauma</fullName>
            </value>
            <value>
                <fullName>Cement</fullName>
            </value>
            <value>
                <fullName>Early Intervention</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/User_Territory_Association__c/fields/Territory__c.field-meta.xml
<CustomField>
    <fullName>Territory__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Territory</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/User_Territory_Association__c/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>User_Territory_Associations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/Ortho_OpportunitiesTest.cls
/****************************************************/
// @Author: Ayush Goyal
// @Date: 24/02/2020
/****************************************************/

@isTest
public class Ortho_OpportunitiesTest { 
    
    @testSetup
    public static void createTestData(){
        
        TestUtilsLocal.createCustomSetting('BPTrigger_OpportunityAmountRollUp', true);
        List<Opportunity> oppList = new List<Opportunity>();
        List<User_Territory_Association__c> utaList = new List<User_Territory_Association__c>();
        
        User oppUser = TestUtilsLocal.createTestUser('oppTerrUser',true);
        User ZimmerSalesUser = TestUtilsLocal.createTestUser('ZimmerUser',false);
        User oppParentTerrUser = TestUtilsLocal.createTestUser('oppTerrUserParent',true);
        
        System.runAs(oppUser){
            Profile customZimmerSales = [SELECT Id FROM Profile WHERE Name='Custom-Zimmer Sales']; 
            ZimmerSalesUser.ProfileId = customZimmerSales.Id;
            insert ZimmerSalesUser;
        }
        
        Account acc = TestUtilsLocal.createAccount('Test',true);
        Account surgeon = TestUtilsLocal.createPhysicianAccount('Test','Surgeon',true);
        
        Opportunity opp = TestUtilsLocal.createOpportunity(acc,'TestOppValidate',false);
        opp.RecordTypeId=[Select Id From RecordType where sobjectType = 'Opportunity' and Name='US Knee'].Id;
        opp.Surgeon_Name__c = surgeon.Id;
        
        Opportunity opp1 = TestUtilsLocal.createOpportunity(acc,'TestOppValidateNegative',false);
        opp1.RecordTypeId=[Select Id From RecordType where sobjectType = 'Opportunity' and Name='US Knee'].Id;
        opp1.Surgeon_Name__c = surgeon.Id;
        opp1.OwnerId = ZimmerSalesUser.Id;
        
        System.runAs(oppUser){
            Territory2Model newTerritoryModel = [Select Id from territory2Model where DeveloperName =: System.Label.Ortho_Territory_Model];
            Territory2Type t2t = [Select Id,DeveloperName from Territory2Type where MasterLabel ='US Ortho'];
            Territory2 testTerr = TestUtilsLocal.createTerritory2('Test Knee','TestTerr',newTerritoryModel,t2t,true);
            Territory2 testTerr1 = TestUtilsLocal.createTerritory2('Test Territory1','TestTerr1',newTerritoryModel,t2t,true);
            Territory2 testTerr2 = TestUtilsLocal.createTerritory2('Test Territory2','TestTerr2',newTerritoryModel,t2t,true);
            ObjectTerritory2Association ota = TestUtilsLocal.createObjectTerritory2Association(acc,testTerr,true);
            ObjectTerritory2Association ota2 = TestUtilsLocal.createObjectTerritory2Association(surgeon,testTerr,true);
            //ObjectTerritory2Association ota3 = TestUtilsLocal.createObjectTerritory2Association(acc,testTerr1,true);
            //ObjectTerritory2Association ota4 = TestUtilsLocal.createObjectTerritory2Association(surgeon,testTerr1,true);
            //UserTerritory2Association uta = new UserTerritory2Association(UserId=ZimmerSalesUser.Id,Territory2Id=testTerr.Id);
            //UserTerritory2Association uta1 = new UserTerritory2Association(UserId=oppUser.Id,Territory2Id=testTerr.Id);
            //insert uta;
            //insert uta1;
        }
        
        oppList.add(opp);
        oppList.add(opp1);
        
        Territory2 testTerr = [Select Id,Name from Territory2 where Name='Test Knee'];
        Territory2 testTerr1 = [Select Id,Name from Territory2 where Name='Test Territory1'];
        User_Territory_Association__c utaCustom= new User_Territory_Association__c(Role__c='Knees',Territory__c=testTerr.Id,User__c=oppUser.Id);
        User_Territory_Association__c utaCustom1= new User_Territory_Association__c(Role__c='Knees',Territory__c=testTerr1.Id,User__c=ZimmerSalesUser.Id);
        User_Territory_Association__c utaCustom2= new User_Territory_Association__c(Role__c='Knees',Territory__c=testTerr.Id,User__c=ZimmerSalesUser.Id);
        utaList.add(utaCustom);
        utaList.add(utaCustom1);
        utaList.add(utaCustom2);
        insert utaList;        
        
        System.runAs(oppUser){
            insert oppList;
            
        }
        
        utaCustom2.Role__c = 'Hips';
        update utaCustom2;
    }
    
    @isTest
    static void testOnValidatePositive(){
        
        
        User u=[Select Id from User where name='oppTerrUser'];
        Territory2 t = [Select Id,Name from Territory2 where Name='Test Knee'];
        String terrName = t.Name;
        
        System.runAs(u){
            
            Test.startTest();
            
            Opportunity opp = [Select Id,Territory2Id from Opportunity where Name='TestOppValidate'];
            opp.Territory2Id = t.Id;
            update opp;
            Test.stopTest();
        }
        
        Opportunity oppty = [Select Id,Ortho_Team__c from Opportunity where Name='TestOppValidate'];
        System.assertEquals(oppty.Ortho_Team__c, terrName);
    }
    
    @isTest
    static void testOnValidateNegative(){
        
        User u=[Select Id from User where name='ZimmerUser'];
        Test.startTest();
        Opportunity opp = [Select Id,Territory2Id from Opportunity where Name='TestOppValidateNegative'];
        system.debug('already existing territory2ID'+opp.Territory2Id);
        Territory2 t = [Select Id,Name from Territory2 where Name='Test Territory2'];
        system.debug('new territory2ID'+t.Id);
        String tName = t.Name;
        System.runAs(u){
            try{
                opp.Territory2Id = t.Id;
                update opp;
            }catch(Exception ex){
                system.debug('catch message->'+ex.getMessage());
                Boolean expectedExceptionThrown =  ex.getMessage().contains('The Opportunity can\'t be assigned to selected Territory. Please select a relevant Territory.') ? true : false;
                //System.assertEquals(true, expectedExceptionThrown);
            }
        }
        Test.stopTest();
        Opportunity oppty = [Select Id,Ortho_Team__c from Opportunity where Name='TestOppValidate'];
        System.assertEquals('Test Knee',oppty.Ortho_Team__c);
    }
    
    @isTest
    static void testAssignTerritories(){
        Territory2 t = [Select Id,Name from Territory2 where Name='Test Knee'];
        Opportunity opp = [Select Id,Territory2Id from Opportunity where Name='TestOppValidate'];
        system.assertEquals(t.Id, opp.Territory2Id);
        
        //Update Territory Id to diff value
        Territory2 t1 = [Select Id,Name from Territory2 where Name='Test Territory1'];
        opp.Territory2Id = t1.Id;
        update opp;
    }

    @isTest
    static void testMobileOpptyFilter() {
        List<User> u=[Select Id from User where name='ZimmerUser'];
        Test.startTest();

        List<Account> accList = MobileOpptyFilterController.findRecords('Test', 'Account', '');
        System.debug(accList);

        List<Account> srgnList = MobileOpptyFilterController.findRecords('Test', 'Surgeon', '');
        System.debug(srgnList);

        List<User> uList = MobileOpptyFilterController.findRecords('Zimm', 'User', '');
        System.debug(uList);

        List<Territory2> tList = MobileOpptyFilterController.findRecords('T2', 'Territory2ForOpportunity', '');
        System.debug(tList);

        List<String> orthoRecIds = MobileOpptyFilterController.getUSOrthoRecordTypeIds();
        if (orthoRecIds != null) {
            System.debug('There are '+orthoRecIds.size()+ ' US Ortho record types');
        }
        System.assert(orthoRecIds.size() > 0, 'Ortho Record Types were fetched');
        Opportunity opp = [Select Id,Territory2Id from Opportunity where Name='TestOppValidateNegative'];
        List<Account> a = [Select Id,Name from Account where Name='Test' and RecordTypeId = '012800000002AW5AAM'];
        List<Account> s = [Select Id,Name from Account where Name='Test Surgeon' and RecordTypeId = '012800000002C4gAAE'];
        Territory2 testTerr = [Select Id,Name from Territory2 where Name='Test Knee'];

        
        List<Opportunity> lst = MobileOpptyFilterController.searchOpportunities((String)a[0].Id,(String)s[0].Id, '"'+orthoRecIds[0]+'"', testTerr.Id, '', (String)u[0].Id, true, true);

        System.debug(lst.size());
        System.assertEquals(lst.size(), 0);

        //Test Instrument Request
        Instrument_Request__c IR = new Instrument_Request__c();

        IR.Opportunity__c = opp.Id;
        IR.SNAP_KIT_ID__c = opp.Id + '-' + '123456';
        IR.Requested_Qty__c = 2;
        IR.Status__c = 'Shipped';

        insert IR;

        Instrument_Request__c IR1 = [Select Id, Record_Number__c, Name from Instrument_Request__c where Opportunity__c = :opp.Id];

        if (IR1 != null) {
            IR1.Status__c = 'New';

            update IR1;
        }

        System.assertEquals(IR1.Record_Number__c, 1);
        Test.stopTest();
        
    }


}