force-app/main/default/objects/Account/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Opt In</fullName>
                <default>true</default>
                <label>Opt In</label>
            </value>
            <value>
                <fullName>Opt Out</fullName>
            </value>
            <value>
                <fullName>Re-Opt In</fullName>
            </value>
            <value>
                <fullName>I</fullName>
            </value>
            <value>
                <fullName>G</fullName>
            </value>
            <value>
                <fullName>A</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Territory_Name__c.field-meta.xml
<CustomField>
    <fullName>Territory_Name__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Territory Name</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/recordTypes/Distributor.recordType-meta.xml
<RecordType>
    <fullName>Distributor</fullName>
    <active>true</active>
    <description>A record to keep information about Zimmer Distributors</description>
    <label>Distributor</label>
</RecordType>

force-app/main/default/objects/Opportunity/fields/At_Risk__c.field-meta.xml
<CustomField>
    <fullName>At_Risk__c</fullName>
    <defaultValue>false</defaultValue>
    <label>At Risk</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/BP_Target__c.field-meta.xml
<CustomField>
    <fullName>BP_Target__c</fullName>
    <defaultValue>false</defaultValue>
    <label>BP Target</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Product_Sales_Summary__c.field-meta.xml
<CustomField>
    <fullName>Product_Sales_Summary__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product Sales Summary</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Product_Sales_Summary__c.Business_Plan__r.Active__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Product_Sales_Summary__c</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunity</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Product_Segment__c.field-meta.xml
<CustomField>
    <fullName>Product_Segment__c</fullName>
    <label>Product Segment #</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>3+</fullName>
            </value>
            <value>
                <fullName>2+</fullName>
            </value>
            <value>
                <fullName>1 only</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Forecast</fullName>
                <isActive>false</isActive>
                <label>Forecast</label>
            </value>
            <value>
                <fullName>Upside</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Surgeon_Name__c.field-meta.xml
<CustomField>
    <fullName>Surgeon_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>This field is used to lookup your Surgeon account.</inlineHelpText>
    <label>Surgeon Name</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Physician, Physician(Processing)</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Opportunities (Surgeon Name)</relationshipLabel>
    <relationshipName>Opportunities2</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Territory_Name__c.field-meta.xml
<CustomField>
    <fullName>Territory_Name__c</fullName>
    <label>Territory Name</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>ALASKA (BARTOW)</fullName>
                <isActive>false</isActive>
                <label>ALASKA (BARTOW)</label>
            </value>
            <value>
                <fullName>APEX SURGICAL(FOX-GATTEN)</fullName>
                <isActive>false</isActive>
                <label>APEX SURGICAL(FOX-GATTEN)</label>
            </value>
            <value>
                <fullName>BONEAFIDE ORTHO(ZERINGUE)</fullName>
                <isActive>false</isActive>
                <label>BONEAFIDE ORTHO(ZERINGUE)</label>
            </value>
            <value>
                <fullName>Boneafide Orthopaedics, Inc.</fullName>
            </value>
            <value>
                <fullName>CAPITAL (PATAK)</fullName>
                <isActive>false</isActive>
                <label>CAPITAL (PATAK)</label>
            </value>
            <value>
                <fullName>CASE MEDICAL (CASE)</fullName>
                <isActive>false</isActive>
                <label>CASE MEDICAL (CASE)</label>
            </value>
            <value>
                <fullName>DAVIS</fullName>
                <isActive>false</isActive>
                <label>DAVIS</label>
            </value>
            <value>
                <fullName>DOWNSTATE NY (LOSCHIAVO)</fullName>
                <isActive>false</isActive>
                <label>DOWNSTATE NY (LOSCHIAVO)</label>
            </value>
            <value>
                <fullName>FEGAN INC</fullName>
                <isActive>false</isActive>
                <label>FEGAN INC</label>
            </value>
            <value>
                <fullName>GR LKS (FUMEI-LOCRICCHIO)</fullName>
                <isActive>false</isActive>
                <label>GR LKS (FUMEI-LOCRICCHIO)</label>
            </value>
            <value>
                <fullName>HIBBARD</fullName>
                <isActive>false</isActive>
                <label>HIBBARD</label>
            </value>
            <value>
                <fullName>HOLZBACH</fullName>
                <isActive>false</isActive>
                <label>HOLZBACH</label>
            </value>
            <value>
                <fullName>JNT MED CONCEPTS (PARKER)</fullName>
                <isActive>false</isActive>
                <label>JNT MED CONCEPTS (PARKER)</label>
            </value>
            <value>
                <fullName>Joint Medical Concepts</fullName>
            </value>
            <value>
                <fullName>LEGACY ORTHO(COOK-PERHACS</fullName>
                <isActive>false</isActive>
                <label>LEGACY ORTHO(COOK-PERHACS</label>
            </value>
            <value>
                <fullName>Legacy Orthopedic, Inc.</fullName>
            </value>
            <value>
                <fullName>MIDAMERICA (HOLINKA)</fullName>
                <isActive>false</isActive>
                <label>MIDAMERICA (HOLINKA)</label>
            </value>
            <value>
                <fullName>MIDARK SURGICAL (NIPPS)</fullName>
                <isActive>false</isActive>
                <label>MIDARK SURGICAL (NIPPS)</label>
            </value>
            <value>
                <fullName>Midark Surgical Inc.</fullName>
            </value>
            <value>
                <fullName>MID-OHIO (GRAHAM)</fullName>
                <isActive>false</isActive>
                <label>MID-OHIO (GRAHAM)</label>
            </value>
            <value>
                <fullName>NORTHEAST (KILCOMMONS)</fullName>
                <isActive>false</isActive>
                <label>NORTHEAST (KILCOMMONS)</label>
            </value>
            <value>
                <fullName>OREGON (COUPENS)</fullName>
                <isActive>false</isActive>
                <label>OREGON (COUPENS)</label>
            </value>
            <value>
                <fullName>ORTHOSOLU(OLIVER-STANBERY</fullName>
                <isActive>false</isActive>
                <label>ORTHOSOLU(OLIVER-STANBERY</label>
            </value>
            <value>
                <fullName>Osteo1, Inc</fullName>
                <isActive>false</isActive>
                <label>Osteo1, Inc</label>
            </value>
            <value>
                <fullName>OSTEO1 INC (SCHMITT)</fullName>
                <isActive>false</isActive>
                <label>OSTEO1 INC (SCHMITT)</label>
            </value>
            <value>
                <fullName>PRECISION (ETHERIDGE)</fullName>
                <isActive>false</isActive>
                <label>PRECISION (ETHERIDGE)</label>
            </value>
            <value>
                <fullName>PREMIER ORTH (VON SAVOYE)</fullName>
                <isActive>false</isActive>
                <label>PREMIER ORTH (VON SAVOYE)</label>
            </value>
            <value>
                <fullName>Premier Orthopedics, Inc.</fullName>
            </value>
            <value>
                <fullName>RICCIONE</fullName>
                <isActive>false</isActive>
                <label>RICCIONE</label>
            </value>
            <value>
                <fullName>RXMEDICAL (ROUSE)</fullName>
                <isActive>false</isActive>
                <label>RXMEDICAL (ROUSE)</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/recordTypes/ROSA.recordType-meta.xml
<RecordType>
    <fullName>ROSA</fullName>
    <active>true</active>
    <businessProcess>AM-US-SU-Sales</businessProcess>
    <label>ROSA Knee</label>
</RecordType>

force-app/main/default/objects/Segmentation_Breakout__c/Segmentation_Breakout__c.object-meta.xml
<CustomObject>
    <label>Segmentation Breakout</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Segmentation Breakout  Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Segmentation Breakouts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Segmentation_Breakout__c/fields/Case_Quantity__c.field-meta.xml
<CustomField>
    <fullName>Case_Quantity__c</fullName>
    <label>Case Quantity</label>
    <precision>12</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Segmentation_Breakout__c/fields/Price_Point__c.field-meta.xml
<CustomField>
    <fullName>Price_Point__c</fullName>
    <label>Price Point</label>
    <precision>12</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Segmentation_Breakout__c/fields/Segmentation_Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Segmentation_Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Segmentation Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Segmentation Breakouts</relationshipLabel>
    <relationshipName>Segmentation_Breakout_Opps</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Segmentation_Breakout__c/fields/Surgeon__c.field-meta.xml
<CustomField>
    <fullName>Surgeon__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Surgeon</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Segmentation Breakouts</relationshipLabel>
    <relationshipName>Segmentation_Breakouts_Surgeon</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Segmentation_Breakout__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Growth</fullName>
            </value>
            <value>
                <fullName>ZB Transfer</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Territory_Name__c/Territory_Name__c.object-meta.xml
<CustomObject>
    <label>Territory Target Refinement</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Territory Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Territory Target Refinements</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Territory_Name__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <defaultValue>&quot;Round 1&quot;</defaultValue>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Round 1</fullName>
                <default>true</default>
                <label>Round 1</label>
            </value>
            <value>
                <fullName>Round 2</fullName>
            </value>
            <value>
                <fullName>Pending AVP Approval</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Approval Not Required</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Trigger_Settings__c/Trigger_Settings__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Activate/ De-activate SFDC triggers</description>
    <label>Trigger Settings</label>
</CustomObject>

force-app/main/default/objects/Trigger_Settings__c/fields/Active__c.field-meta.xml
<CustomField>
    <fullName>Active__c</fullName>
    <defaultValue>false</defaultValue>
    <description>If Checked, Trigger is Activated and Id Unchecked, trigger is De-Activated</description>
    <label>Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/SegBreakoutSummaryTest.cls
@isTest
private class SegBreakoutSummaryTest {
    
    //Create Opportunity
    //
    //Create Segmentation Breakout
    //
    //Check Total
    //
    @isTest static void checkSegBreakoutSummary() {
        Trigger_Settings__c cs = new Trigger_Settings__c();
        cs.Name = 'BPTrigger_OpportunityAmountRollUp';
        cs.Active__c = true;
        insert cs;
        
        Account acc = new Account();
        acc.RecordTypeId = '012800000002AW5AAM';//Distributor
        acc.Name = 'Test Healthcare Facility';
        acc.Status__c = 'A';
        insert acc;

        /*
       
        acc2 = new Account();
        acc2.RecordTypeId = '012800000002C4gAAE';//person account
        acc2.LastName = 'Alex';
        acc2.FirstName = 'Test';
        acc2.PersonMailingCountry = 'US'; 
        acc2.PersonMailingCity = 'Warsaw';
        acc2.PersonMailingState = 'IN'; 
        acc2.PersonMailingStreet =' E Main St'; 
        acc2.PersonMailingPostalCode = '46582'; 
        insert acc2;

        */
       list<Opportunity> oppList = new list<Opportunity>();
        
        //for (integer i=0;i<1;i++){
            Opportunity newOpp = new Opportunity();
            newOpp.Name = 'Test Oppty - Rosa SB';
            newOpp.Amount = 5000; 
            newOpp.AccountId = acc.Id;
            newOpp.StageName = 'Target';
            newOpp.CloseDate = date.today().addDays(30);
            newOpp.RecordTypeId = '012C0000000YQqaIAG';
            //newOpp.Surgeon_Name__c = acct2.Id;
            //newOpp.BP_Target__c = TRUE;
            //newOpp.Territory_Name__c = 'APEX SURGICAL(FOX-GATTEN)';
            //newOpp.Product_Sales_Summary__c = pKneesSales.Id;  //ref Product_Sales_Summary__c
            
            //oppList.add(newOpp);
            newOpp.At_Risk__c = TRUE;
        	insert newOpp;
            
            //Create Segmentation Breakout Record
            //
            List<Segmentation_Breakout__c> sbList = new List<Segmentation_Breakout__c>();
            
            for (integer j=1;j<=5;j++) {
              Segmentation_Breakout__c sb = new Segmentation_Breakout__c();
                
                sb.Segmentation_Opportunity__c	= newOpp.id;
                sb.Case_Quantity__c	= j*2;
                sb.Name	= 'SB for Oppty -> '+j;
                sb.Price_Point__c	= j*1000;
                sb.Surgeon__c	= acc.id;
                
                if (j==1 || j == 5) {
                    sb.Type__c = 'Growth';
                    sb.Product_Segment__c	= 'Knees';
            	}
                else {
                    sb.Type__c = 'ZB Transfer';
                    sb.Product_Segment__c	= 'Hips';
                }
                
                sbList.add(sb);
            }
            insert sbList;      
        
			// Verify Count of SB for Oppty
			List<Segmentation_Breakout__c> lstSB = [Select Id, Case_Quantity__c, Price_Point__c, Total_Revenue__c, Product_Segment__c from Segmentation_Breakout__c where Segmentation_Opportunity__c = :newOpp.Id];
        
        	System.assert(lstSB.size() ==5);
        	/*PageReference pageRef = Page.OpptySegmentationBreakout;
        	Test.setCurrentPageReference (pageRef);
        	ApexPages.currentPage().getParameters().put('id', newOpp.Id);
        	SegBreakoutSummary controller = new SegBreakoutSummary(new ApexPages.StandardController( newOpp));*/
        
        	SegBreakoutSummary sc = new SegBreakoutSummary(new ApexPages.StandardController( newOpp));
        	System.debug('Total Amt should be '+sc.totalRevenue);
        	System.assertEquals(sc.totalRevenue, null);
    }
    
   
}