force-app/main/default/objects/Account/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Opt In</fullName>
                <default>true</default>
                <label>Opt In</label>
            </value>
            <value>
                <fullName>Opt Out</fullName>
            </value>
            <value>
                <fullName>Re-Opt In</fullName>
            </value>
            <value>
                <fullName>I</fullName>
            </value>
            <value>
                <fullName>G</fullName>
            </value>
            <value>
                <fullName>A</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Territory_Name__c.field-meta.xml
<CustomField>
    <fullName>Territory_Name__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Territory Name</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/recordTypes/Distributor.recordType-meta.xml
<RecordType>
    <fullName>Distributor</fullName>
    <active>true</active>
    <description>A record to keep information about Zimmer Distributors</description>
    <label>Distributor</label>
</RecordType>

force-app/main/default/objects/Business_Plan__c/Business_Plan__c.object-meta.xml
<CustomObject>
    <label>Business Plan</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Business Plan Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Business Plans</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Business_Plan__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <defaultValue>&quot;Active&quot;</defaultValue>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Pending AVP Approval</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Approval Not Required</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Business_Plan__c/fields/Territory_Account_Name__c.field-meta.xml
<CustomField>
    <fullName>Territory_Account_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Territory Account Name</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Business Plans</relationshipLabel>
    <relationshipName>Business_Plans</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Business_Plan__c/recordTypes/Active.recordType-meta.xml
<RecordType>
    <fullName>Active</fullName>
    <active>true</active>
    <label>Active</label>
</RecordType>

force-app/main/default/objects/Market_Segmentation__c/Market_Segmentation__c.object-meta.xml
<CustomObject>
    <label>Market Segmentation</label>
    <nameField>
        <displayFormat>MS-{00000}</displayFormat>
        <label>Market Segmentation Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Market Segmentation</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Market_Segmentation__c/fields/Market_Procedures__c.field-meta.xml
<CustomField>
    <fullName>Market_Procedures__c</fullName>
    <label>IMS Covid Adj. Procedures 2019</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Market_Segmentation__c/fields/Master_Territory_ID__c.field-meta.xml
<CustomField>
    <fullName>Master_Territory_ID__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Master Territory ID</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Market Segmentation (Master Territory ID)</relationshipLabel>
    <relationshipName>Market_Segmentation</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Market_Segmentation__c/fields/Product_Group__c.field-meta.xml
<CustomField>
    <fullName>Product_Group__c</fullName>
    <label>Product Group</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Bone Cement</fullName>
            </value>
            <value>
                <fullName>Extremities</fullName>
            </value>
            <value>
                <fullName>Shoulder</fullName>
            </value>
            <value>
                <fullName>Foot &amp; Ankle</fullName>
            </value>
            <value>
                <fullName>Sports Medicine</fullName>
            </value>
            <value>
                <fullName>Trauma</fullName>
            </value>
            <value>
                <fullName>Surgical</fullName>
            </value>
            <value>
                <fullName>Hips</fullName>
            </value>
            <value>
                <fullName>Primary Hips</fullName>
            </value>
            <value>
                <fullName>Revision Hips</fullName>
            </value>
            <value>
                <fullName>Knees</fullName>
            </value>
            <value>
                <fullName>Primary Knees</fullName>
            </value>
            <value>
                <fullName>Partial Knees</fullName>
            </value>
            <value>
                <fullName>Revision Knees</fullName>
            </value>
            <value>
                <fullName>Total Knees</fullName>
            </value>
            <value>
                <fullName>Total Hips</fullName>
            </value>
            <value>
                <fullName>Total</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Market_Segmentation__c/fields/Segementation__c.field-meta.xml
<CustomField>
    <fullName>Segementation__c</fullName>
    <label>Segementation</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Bronze</fullName>
            </value>
            <value>
                <fullName>Gold</fullName>
            </value>
            <value>
                <fullName>Green</fullName>
            </value>
            <value>
                <fullName>Platinum</fullName>
            </value>
            <value>
                <fullName>Silver</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Market_Segmentation__c/fields/Surgeon_Name__c.field-meta.xml
<CustomField>
    <fullName>Surgeon_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Surgeon Name</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Physician</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Market Segmentation</relationshipLabel>
    <relationshipName>Market_Segmentations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Market_Segmentation__c/fields/Zimmer_Biomet_Procedures__c.field-meta.xml
<CustomField>
    <fullName>Zimmer_Biomet_Procedures__c</fullName>
    <label>ZB PROCEDURES 2020</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/At_Risk__c.field-meta.xml
<CustomField>
    <fullName>At_Risk__c</fullName>
    <defaultValue>false</defaultValue>
    <label>At Risk</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/BP_Target__c.field-meta.xml
<CustomField>
    <fullName>BP_Target__c</fullName>
    <defaultValue>false</defaultValue>
    <label>BP Target</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Business_Plan__c.field-meta.xml
<CustomField>
    <fullName>Business_Plan__c</fullName>
    <formula>CASESAFEID(Product_Sales_Summary__r.Business_Plan__r.Id)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Business Plan</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Market_Procedures__c.field-meta.xml
<CustomField>
    <fullName>Market_Procedures__c</fullName>
    <label>Market Procedures</label>
    <precision>10</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Product_Group__c.field-meta.xml
<CustomField>
    <fullName>Product_Group__c</fullName>
    <label>Product Group</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Hips</fullName>
            </value>
            <value>
                <fullName>Knees</fullName>
            </value>
            <value>
                <fullName>Cement</fullName>
            </value>
            <value>
                <fullName>Extremities</fullName>
            </value>
            <value>
                <fullName>Sports Medicine</fullName>
            </value>
            <value>
                <fullName>Trauma</fullName>
            </value>
            <value>
                <fullName>Foot &amp; Ankle</fullName>
            </value>
            <value>
                <fullName>Surgical</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Product_Sales_Summary__c.field-meta.xml
<CustomField>
    <fullName>Product_Sales_Summary__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product Sales Summary</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Product_Sales_Summary__c.Business_Plan__r.Active__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Product_Sales_Summary__c</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunity</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Forecast</fullName>
                <isActive>false</isActive>
                <label>Forecast</label>
            </value>
            <value>
                <fullName>Upside</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Surgeon_Name__c.field-meta.xml
<CustomField>
    <fullName>Surgeon_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>This field is used to lookup your Surgeon account.</inlineHelpText>
    <label>Surgeon Name</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Physician, Physician(Processing)</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Opportunities (Surgeon Name)</relationshipLabel>
    <relationshipName>Opportunities2</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Product_Sales_Summary__c/Product_Sales_Summary__c.object-meta.xml
<CustomObject>
    <label>Product Sales Summary</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Product Sales Summary Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Product Sales Summary</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Product_Sales_Summary__c/fields/Business_Plan__c.field-meta.xml
<CustomField>
    <fullName>Business_Plan__c</fullName>
    <label>Business Plan</label>
    <referenceTo>Business_Plan__c</referenceTo>
    <relationshipLabel>Product Sales Summary</relationshipLabel>
    <relationshipName>Product_Sales_Summary</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Territory_Name__c/Territory_Name__c.object-meta.xml
<CustomObject>
    <label>Territory Target Refinement</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Territory Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Territory Target Refinements</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Territory_Name__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <defaultValue>&quot;Round 1&quot;</defaultValue>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Round 1</fullName>
                <default>true</default>
                <label>Round 1</label>
            </value>
            <value>
                <fullName>Round 2</fullName>
            </value>
            <value>
                <fullName>Pending AVP Approval</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Approval Not Required</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Trigger_Settings__c/Trigger_Settings__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Activate/ De-activate SFDC triggers</description>
    <label>Trigger Settings</label>
</CustomObject>

force-app/main/default/objects/Trigger_Settings__c/fields/Active__c.field-meta.xml
<CustomField>
    <fullName>Active__c</fullName>
    <defaultValue>false</defaultValue>
    <description>If Checked, Trigger is Activated and Id Unchecked, trigger is De-Activated</description>
    <label>Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/OpportunityAmountRollup_Test.cls
@isTest
public class OpportunityAmountRollup_Test {
    
    public static Account acc;
    public static Account acc2;
    public static Opportunity newOpp1;
    public static Opportunity newOpp2;
    
    @testSetup static void setup() {
        
        Trigger_Settings__c cs = new Trigger_Settings__c();
        cs.Name = 'BPTrigger_OpportunityAmountRollUp';
        cs.Active__c = true;
        insert cs;
        
        acc = new Account();
        acc.RecordTypeId = '012800000002ByTAAU';//Distributor
        acc.Name = 'Joint Medical Concepts';
        insert acc;

        acc = new Account();
        acc.RecordTypeId = '012800000002AW5AAM';//Distributor
        acc.Name = 'TEST ACCOUNT';
        insert acc;

        Business_Plan__c plan = new Business_Plan__c();
        plan.Name = 'Test Plan';
        plan.Active__c = TRUE;
        plan.Status__c = 'Active';
        plan.Year__c = 2019;
        plan.Territory_Account_Name__c = acc.Id;
        insert plan;
       
        acc2 = new Account();
        acc2.RecordTypeId = '012800000002C4gAAE';//person account
        acc2.LastName = 'Alex';
        acc2.FirstName = 'Test';
        acc2.PersonMailingCountry = 'US'; 
        acc2.PersonMailingCity = 'Warsaw';
        acc2.PersonMailingState = 'IN'; 
        acc2.PersonMailingStreet =' E Main St'; 
        acc2.PersonMailingPostalCode = '46582'; 
        insert acc2;

        
        Product_Sales_Summary__c pSummary = new Product_Sales_Summary__c();
        pSummary.Name = 'Test Knees Sales Summary';
        pSummary.Business_Plan__c = plan.Id;
        pSummary.Product_Group__c = 'Knees';
        insert pSummary;
        
        Product_Sales_Summary__c pSummary1 = new Product_Sales_Summary__c();
        pSummary1.Name = 'Test Hips Sales Summary';
        pSummary1.Business_Plan__c = plan.Id;
        pSummary1.Product_Group__c = 'Hips';
        insert pSummary1;

        Market_Segmentation__c marketseg = new Market_Segmentation__c ();
        marketseg.Surgeon_Name__c = acc2.id; 
        marketseg.Segementation__c = 'Gold';
        marketseg.Product_Group__c = 'Knees';
        marketseg.Master_Territory_ID__c = acc.id ; 
        marketseg.Zimmer_Biomet_Procedures__c = 100; 
        marketseg.Market_Procedures__c = 150;
        insert  marketseg ; 
    }
    
    static testMethod void validateOpportunitybeforeInsert() {
        
        
        
        Account acct = [select Id,Name from account where Name=:'TEST ACCOUNT'];
        Account acct2 = [select Id,Name,LastName, FirstName from account where LastName = 'Alex' and FirstName = 'Test'];
        Product_Sales_Summary__c pKneesSales = [Select Id, Name from Product_Sales_Summary__c where Name=:'Test Knees Sales Summary'];
        Product_Sales_Summary__c pHipsSales = [Select Id, Name from Product_Sales_Summary__c where Name=:'Test Hips Sales Summary'];
        
        /*
        list<Opportunity> oppList = new list<Opportunity>();
        
        for (integer i=0;i<5;i++){
            Opportunity newOpp = new Opportunity();
            newOpp.Name = 'Test Opp-'+i;
            newOpp.Amount = 5000; 
            newOpp.AccountId = acct.Id;
            newOpp.StageName = 'Target';
            newOpp.CloseDate = date.today().addDays(30);
            newOpp.RecordTypeId = '012800000002ReS';
            newOpp.Surgeon_Name__c = acct2.Id;
            if(i==3 || i==5 || i==7){ newOpp.At_Risk__c = FALSE;}
            else{ newOpp.At_Risk__c = TRUE; }
            newOpp.BP_Target__c = TRUE;
            newOpp.Territory_Name__c = 'APEX SURGICAL(FOX-GATTEN)';
            newOpp.Product_Sales_Summary__c = pKneesSales.Id;  //ref Product_Sales_Summary__c
            oppList.add(newOpp);
        }
        
        insert oppList; 
        
        newOpp1 = new Opportunity();
        newOpp1.Name = 'Test Opp';
        newOpp1.Amount = 5000;
        newOpp1.AccountId = acct.Id;
        newOpp1.StageName = 'Target';
        newOpp1.CloseDate = date.today().addDays(30);
        newOpp1.RecordTypeId = '012800000002ReS';
        newOpp1.Surgeon_Name__c = acct2.Id;
        newOpp1.At_Risk__c = FALSE;
        newOpp1.BP_Target__c = TRUE;
        newOpp1.Territory_Name__c = 'Joint Medical Concepts';
        newOpp1.Product_Sales_Summary__c = pKneesSales.Id;  //ref Product_Sales_Summary__c
        insert newOpp1;
        */
        newOpp2 = new Opportunity();
        newOpp2.Name = 'Test Opp';
        newOpp2.Amount = 5000;
        newOpp2.AccountId = acct.Id;
        newOpp2.StageName = 'Target';
        newOpp2.CloseDate = date.today().addDays(30);
        newOpp2.RecordTypeId = '012800000002ReS';
        newOpp2.Surgeon_Name__c = acct2.Id;
        newOpp2.At_Risk__c = TRUE;
        newOpp2.BP_Target__c = TRUE;
        newOpp2.Territory_Name__c = 'Joint Medical Concepts';
        newOpp2.Product_Sales_Summary__c = pHipsSales.Id;  //ref Product_Sales_Summary__c 
        insert newOpp2;
        
        test.startTest();
        
        Opportunity opp2 = [Select Id, Name, stageName from Opportunity where Id=:newOpp2.Id];
        opp2.StageName = 'Closed Lost';
        update opp2 ; 
        test.stopTest();
    }
    /*
    static testMethod void validateOpportunitybeforeUpdate() {
        
        test.startTest();
        
        Account acct = [select Id,Name from account where Name=:'APEX SURGICAL(FOX-GATTEN)'];
        Account acct2 = [select Id,Name,LastName, FirstName from account where LastName = 'Alex' and FirstName = 'Test'];
        
        Product_Sales_Summary__c pKneesSales = [Select Id, Name from Product_Sales_Summary__c where Name=:'Test Knees Sales Summary'];
        Product_Sales_Summary__c pHipsSales = [Select Id, Name from Product_Sales_Summary__c where Name=:'Test Hips Sales Summary'];
        newOpp1 = new Opportunity();
        newOpp1.Name = 'Test Opp';
        newOpp1.AccountId = acct.Id;
        newOpp1.StageName = 'Target';
        newOpp1.CloseDate = date.today().addDays(30);
        newOpp1.RecordTypeId = '012800000002ReS';
        newOpp1.Surgeon_Name__c = acct2.Id;
        newOpp1.At_Risk__c = TRUE;
        newOpp1.BP_Target__c = TRUE;
        newOpp1.Territory_Name__c = 'APEX SURGICAL(FOX-GATTEN)';
        newOpp1.Product_Sales_Summary__c = pKneesSales.Id;  //ref Product_Sales_Summary__c
        insert newOpp1;
        
        newOpp2 = new Opportunity();
        newOpp2.Name = 'Test Opp';
        newOpp2.AccountId = acct.Id;
        newOpp2.StageName = 'Target';
        newOpp2.CloseDate = date.today().addDays(30);
        newOpp2.RecordTypeId = '012800000002ReS';
        newOpp2.Surgeon_Name__c = acct2.Id;
        newOpp2.At_Risk__c = TRUE;
        //newOpp2.BP_Target__c = TRUE;
        newOpp2.Territory_Name__c = 'APEX SURGICAL(FOX-GATTEN)';
        newOpp2.Product_Sales_Summary__c = pHipsSales.Id;  //ref Product_Sales_Summary__c 
        insert newOpp2;
        Opportunity opp1 = [Select Id, Name from Opportunity where Id=:newOpp1.Id];
        opp1.StageName = 'Closed Lost';
        opp1.BP_Target__c = TRUE;
        opp1.At_Risk__c = TRUE;
        opp1.Product_Sales_Summary__c = pHipsSales.Id;  //ref Product_Sales_Summary__c
        update opp1;
        
        Opportunity opp2 = [Select Id, Name from Opportunity where Id=:newOpp2.Id];
        opp2.StageName = 'Closed Lost';
        opp2.BP_Target__c = TRUE;
        opp2.At_Risk__c = FALSE;
        opp2.Surgeon_Name__c = acct2.id ; 
        opp1.At_Risk__c = TRUE;
        Opp2.probability = 75 ; 
        Opp2.amount = 10000;
        //opp2.Product_Sales_Summary__c = pHipsSales.Id;  //ref Product_Sales_Summary__c
        update opp2;        
        test.stopTest();
        
    }*/
    
    
}