force-app/main/default/objects/Account/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Opt In</fullName>
                <default>true</default>
                <label>Opt In</label>
            </value>
            <value>
                <fullName>Opt Out</fullName>
            </value>
            <value>
                <fullName>Re-Opt In</fullName>
            </value>
            <value>
                <fullName>I</fullName>
            </value>
            <value>
                <fullName>G</fullName>
            </value>
            <value>
                <fullName>A</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Business_Plan__c/Business_Plan__c.object-meta.xml
<CustomObject>
    <label>Business Plan</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Business Plan Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Business Plans</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Business_Plan__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <defaultValue>&quot;Active&quot;</defaultValue>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Pending AVP Approval</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Approval Not Required</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Business_Plan__c/fields/Territory_Account_Name__c.field-meta.xml
<CustomField>
    <fullName>Territory_Account_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Territory Account Name</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Business Plans</relationshipLabel>
    <relationshipName>Business_Plans</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Business_Plan__c/recordTypes/Active.recordType-meta.xml
<RecordType>
    <fullName>Active</fullName>
    <active>true</active>
    <label>Active</label>
</RecordType>

force-app/main/default/objects/Executive_Summary__c/Executive_Summary__c.object-meta.xml
<CustomObject>
    <label>Executive Summary</label>
    <nameField>
        <displayFormat>ES-{00000}</displayFormat>
        <label>Executive Summary Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Executive Summary</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Executive_Summary__c/fields/Business_Plan__c.field-meta.xml
<CustomField>
    <fullName>Business_Plan__c</fullName>
    <label>Business Plan</label>
    <referenceTo>Business_Plan__c</referenceTo>
    <relationshipLabel>Executive Summary</relationshipLabel>
    <relationshipName>Executive_Summary</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Executive_Summary__c/fields/Executive_Summary_fld__c.field-meta.xml
<CustomField>
    <fullName>Executive_Summary_fld__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Executive Summary</label>
    <length>131072</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/Executive_Summary__c/fields/Question_Type__c.field-meta.xml
<CustomField>
    <fullName>Question_Type__c</fullName>
    <label>Question Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Market statistics</fullName>
            </value>
            <value>
                <fullName>Competitive landscape</fullName>
            </value>
            <value>
                <fullName>Account statistics and implications</fullName>
            </value>
            <value>
                <fullName>Surgeon / Hospital Alignment trends update</fullName>
            </value>
            <value>
                <fullName>Organization</fullName>
            </value>
            <value>
                <fullName>People</fullName>
            </value>
            <value>
                <fullName>Processes</fullName>
            </value>
            <value>
                <fullName>Overall Assessment</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/businessPlanExecutiveSummary_Test.cls
@isTest
public class businessPlanExecutiveSummary_Test {
    
    public static Account acc;
    
    @testSetup static void setup() {
        
        acc = new Account();
        acc.RecordTypeId = '012800000002AW5AAM';//Healthcare Facility
        acc.Name = 'APEX SURGICAL(FOX-GATTEN)';
        insert acc;
        
        Business_Plan__c plan = new Business_Plan__c();
        plan.Name = 'Test Plan';
        plan.Active__c = TRUE;
        plan.Status__c = 'Active';
        plan.Year__c = 2019;
        plan.Territory_Account_Name__c = acc.Id;
        insert plan;
       
        Executive_Summary__c exeSummary = new Executive_Summary__c();
        exeSummary.Question_Type__c = 'Processes';
        exeSummary.IsActive__c = TRUE;
        exeSummary.Executive_Summary_fld__c = 'This is the executive summary.';
        exeSummary.Business_Plan__c = plan.Id;
        insert exeSummary;
    }
    
    static testMethod void validate_getActiveExecutiveSummary_1() {
        
        test.startTest();
        
        Executive_Summary__c exsummary = [select id, Question_Type__c, IsActive__c , Executive_Summary_fld__c, Business_Plan__c
                                        from Executive_Summary__c where Business_Plan__c != null and IsActive__c = true LIMIT 1];
        
        system.debug('exsummary_1---'+exsummary);
        
        Business_Plan__c plan1 = [select Id,Name from Business_Plan__c where name='Test Plan'];
        system.debug('plan1_2---'+plan1);
        
        ApexPages.currentpage().getparameters().put('id' , plan1.Id);
        ApexPages.StandardController sc = new ApexPages.StandardController(exsummary);
        businessPlanExecutiveSummary testExeSummary = new businessPlanExecutiveSummary(sc);
        testExeSummary.ExeSum = exsummary;
        test.stopTest();
        
    }
    
    static testMethod void validate_getActiveExecutiveSummary_2() {
        
        test.startTest();
        
        Business_Plan__c plan1 = [select Id,Name from Business_Plan__c where name='Test Plan'];
        
        system.debug('plan1_2---'+plan1);
        
        businessPlanExecutiveSummary.getActiveExecutiveSummary(plan1.Id);
       
        test.stopTest();
        
    }
    
}