force-app/main/default/objects/Account/fields/territory__c.field-meta.xml
<CustomField>
    <fullName>territory__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>territory</label>
    <referenceTo>territory__c</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Surgeon_Name__c.field-meta.xml
<CustomField>
    <fullName>Surgeon_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>This field is used to lookup your Surgeon account.</inlineHelpText>
    <label>Surgeon Name</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Physician, Physician(Processing)</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Opportunities (Surgeon Name)</relationshipLabel>
    <relationshipName>Opportunities2</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/territory__c/territory__c.object-meta.xml
<CustomObject>
    <description>Integration</description>
    <label>Territory</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Territory Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Territories</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/User_Territory_Association__c/User_Territory_Association__c.object-meta.xml
<CustomObject>
    <label>User Territory Association</label>
    <nameField>
        <displayFormat>UT-{0000}</displayFormat>
        <label>User Territory Association Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>User Territory Associations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/User_Territory_Association__c/fields/Role__c.field-meta.xml
<CustomField>
    <fullName>Role__c</fullName>
    <label>Role</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Biologics</fullName>
            </value>
            <value>
                <fullName>Extremities</fullName>
            </value>
            <value>
                <fullName>Foot &amp; Ankle</fullName>
            </value>
            <value>
                <fullName>Hips</fullName>
            </value>
            <value>
                <fullName>Knees</fullName>
            </value>
            <value>
                <fullName>Sports Medicine</fullName>
            </value>
            <value>
                <fullName>Trauma</fullName>
            </value>
            <value>
                <fullName>Cement</fullName>
            </value>
            <value>
                <fullName>Early Intervention</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/User_Territory_Association__c/fields/Territory__c.field-meta.xml
<CustomField>
    <fullName>Territory__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Territory</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/User_Territory_Association__c/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>User_Territory_Associations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/Ortho_OpportunityTerritoryAssignJobTest.cls
@isTest
public class Ortho_OpportunityTerritoryAssignJobTest {
    @testSetup
    public static void createTestData(){
        TestUtilsLocal.createCustomSetting('BPTrigger_OpportunityAmountRollUp',true);
        User oppUser = TestUtilsLocal.createTestUser('oppTerrUser',true);
        Account acc = TestUtilsLocal.createAccount('Test',true);
        Account surgeon = TestUtilsLocal.createPhysicianAccount('Test','Surgeon',true);
       
        Opportunity opp = TestUtilsLocal.createOpportunity(acc,'TestOppValidate',false);
        opp.RecordTypeId=[Select Id From RecordType where sobjectType = 'Opportunity' and Name='US Knee'].Id;
        opp.Surgeon_Name__c = surgeon.Id;
        insert opp;
        Territory2 testTerr = new Territory2();
        //Territory2 testTerr = [Select Id from Territory2 where Name='ZB Mid Ohio Team Ace Opportunities'];
        System.runAs(oppUser){
            Territory2Model newTerritoryModel = [Select Id from territory2Model where DeveloperName =: System.Label.Ortho_Territory_Model];
            Territory2Type t2t = [Select Id,DeveloperName from Territory2Type where MasterLabel ='US Ortho'];
            testTerr = TestUtilsLocal.createTerritory2('TestTerr', 'TestTerr', newTerritoryModel, t2t, true);
        }
        User_Territory_Association__c  uta = new User_Territory_Association__c (User__c=oppUser.Id, Territory__c=testTerr.Id);
        uta.Role__c  ='Knees';
        insert uta;
       
        System.runAs(oppUser){
            UserTerritory2Association uta1 = new UserTerritory2Association(UserId=oppUser.Id, Territory2Id=testTerr.Id);
            insert uta1;
            ObjectTerritory2Association ota = TestUtilsLocal.createObjectTerritory2Association(acc,testTerr,true);
            ObjectTerritory2Association ota2 = TestUtilsLocal.createObjectTerritory2Association(surgeon,testTerr,true);
        }
       
    }
   
    @isTest
    static void testAssignTerritories(){
        
        User u = [Select Id,Name from User where LastName='oppTerrUser'];
        Territory2 t = [Select Id,Name from Territory2 where Name='TestTerr'];
        system.runAs(u){
            Test.startTest();
            Ortho_OpportunityTerritoryAssignJob batch = new Ortho_OpportunityTerritoryAssignJob();
            Database.executeBatch(batch);
            Test.stopTest();
        }
        
        Opportunity opp = [Select Id,Territory2Id from Opportunity where Name='TestOppValidate'];
        system.assertEquals(t.Id, opp.Territory2Id);
    }
}