force-app/main/default/objects/Account/fields/territory__c.field-meta.xml
<CustomField>
    <fullName>territory__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>territory</label>
    <referenceTo>territory__c</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/Territory_Name__c.field-meta.xml
<CustomField>
    <fullName>Territory_Name__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Territory Name</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Territory_Name__c.field-meta.xml
<CustomField>
    <fullName>Territory_Name__c</fullName>
    <label>Territory Name</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>ALASKA (BARTOW)</fullName>
                <isActive>false</isActive>
                <label>ALASKA (BARTOW)</label>
            </value>
            <value>
                <fullName>APEX SURGICAL(FOX-GATTEN)</fullName>
                <isActive>false</isActive>
                <label>APEX SURGICAL(FOX-GATTEN)</label>
            </value>
            <value>
                <fullName>BONEAFIDE ORTHO(ZERINGUE)</fullName>
                <isActive>false</isActive>
                <label>BONEAFIDE ORTHO(ZERINGUE)</label>
            </value>
            <value>
                <fullName>Boneafide Orthopaedics, Inc.</fullName>
            </value>
            <value>
                <fullName>CAPITAL (PATAK)</fullName>
                <isActive>false</isActive>
                <label>CAPITAL (PATAK)</label>
            </value>
            <value>
                <fullName>CASE MEDICAL (CASE)</fullName>
                <isActive>false</isActive>
                <label>CASE MEDICAL (CASE)</label>
            </value>
            <value>
                <fullName>DAVIS</fullName>
                <isActive>false</isActive>
                <label>DAVIS</label>
            </value>
            <value>
                <fullName>DOWNSTATE NY (LOSCHIAVO)</fullName>
                <isActive>false</isActive>
                <label>DOWNSTATE NY (LOSCHIAVO)</label>
            </value>
            <value>
                <fullName>FEGAN INC</fullName>
                <isActive>false</isActive>
                <label>FEGAN INC</label>
            </value>
            <value>
                <fullName>GR LKS (FUMEI-LOCRICCHIO)</fullName>
                <isActive>false</isActive>
                <label>GR LKS (FUMEI-LOCRICCHIO)</label>
            </value>
            <value>
                <fullName>HIBBARD</fullName>
                <isActive>false</isActive>
                <label>HIBBARD</label>
            </value>
            <value>
                <fullName>HOLZBACH</fullName>
                <isActive>false</isActive>
                <label>HOLZBACH</label>
            </value>
            <value>
                <fullName>JNT MED CONCEPTS (PARKER)</fullName>
                <isActive>false</isActive>
                <label>JNT MED CONCEPTS (PARKER)</label>
            </value>
            <value>
                <fullName>Joint Medical Concepts</fullName>
            </value>
            <value>
                <fullName>LEGACY ORTHO(COOK-PERHACS</fullName>
                <isActive>false</isActive>
                <label>LEGACY ORTHO(COOK-PERHACS</label>
            </value>
            <value>
                <fullName>Legacy Orthopedic, Inc.</fullName>
            </value>
            <value>
                <fullName>MIDAMERICA (HOLINKA)</fullName>
                <isActive>false</isActive>
                <label>MIDAMERICA (HOLINKA)</label>
            </value>
            <value>
                <fullName>MIDARK SURGICAL (NIPPS)</fullName>
                <isActive>false</isActive>
                <label>MIDARK SURGICAL (NIPPS)</label>
            </value>
            <value>
                <fullName>Midark Surgical Inc.</fullName>
            </value>
            <value>
                <fullName>MID-OHIO (GRAHAM)</fullName>
                <isActive>false</isActive>
                <label>MID-OHIO (GRAHAM)</label>
            </value>
            <value>
                <fullName>NORTHEAST (KILCOMMONS)</fullName>
                <isActive>false</isActive>
                <label>NORTHEAST (KILCOMMONS)</label>
            </value>
            <value>
                <fullName>OREGON (COUPENS)</fullName>
                <isActive>false</isActive>
                <label>OREGON (COUPENS)</label>
            </value>
            <value>
                <fullName>ORTHOSOLU(OLIVER-STANBERY</fullName>
                <isActive>false</isActive>
                <label>ORTHOSOLU(OLIVER-STANBERY</label>
            </value>
            <value>
                <fullName>Osteo1, Inc</fullName>
                <isActive>false</isActive>
                <label>Osteo1, Inc</label>
            </value>
            <value>
                <fullName>OSTEO1 INC (SCHMITT)</fullName>
                <isActive>false</isActive>
                <label>OSTEO1 INC (SCHMITT)</label>
            </value>
            <value>
                <fullName>PRECISION (ETHERIDGE)</fullName>
                <isActive>false</isActive>
                <label>PRECISION (ETHERIDGE)</label>
            </value>
            <value>
                <fullName>PREMIER ORTH (VON SAVOYE)</fullName>
                <isActive>false</isActive>
                <label>PREMIER ORTH (VON SAVOYE)</label>
            </value>
            <value>
                <fullName>Premier Orthopedics, Inc.</fullName>
            </value>
            <value>
                <fullName>RICCIONE</fullName>
                <isActive>false</isActive>
                <label>RICCIONE</label>
            </value>
            <value>
                <fullName>RXMEDICAL (ROUSE)</fullName>
                <isActive>false</isActive>
                <label>RXMEDICAL (ROUSE)</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/territory__c/territory__c.object-meta.xml
<CustomObject>
    <description>Integration</description>
    <label>Territory</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Territory Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Territories</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Territory_Name__c/Territory_Name__c.object-meta.xml
<CustomObject>
    <label>Territory Target Refinement</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Territory Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Territory Target Refinements</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/User_Territory_Association__c/User_Territory_Association__c.object-meta.xml
<CustomObject>
    <label>User Territory Association</label>
    <nameField>
        <displayFormat>UT-{0000}</displayFormat>
        <label>User Territory Association Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>User Territory Associations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/User_Territory_Association__c/fields/Role__c.field-meta.xml
<CustomField>
    <fullName>Role__c</fullName>
    <label>Role</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Biologics</fullName>
            </value>
            <value>
                <fullName>Extremities</fullName>
            </value>
            <value>
                <fullName>Foot &amp; Ankle</fullName>
            </value>
            <value>
                <fullName>Hips</fullName>
            </value>
            <value>
                <fullName>Knees</fullName>
            </value>
            <value>
                <fullName>Sports Medicine</fullName>
            </value>
            <value>
                <fullName>Trauma</fullName>
            </value>
            <value>
                <fullName>Cement</fullName>
            </value>
            <value>
                <fullName>Early Intervention</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/User_Territory_Association__c/fields/Territory__c.field-meta.xml
<CustomField>
    <fullName>Territory__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Territory</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/User_Territory_Association__c/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>User_Territory_Associations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/Ortho_UserTerritoryAssociationsTest.cls
/**
* @author Appirio Inc.
* @date March, 2020
*
* @group User_Territory_Association__c
*
* @description Encapsulates all behaviour logic relating to the User_Territory_Association__c object
*       For more guidelines and details see
*    https://developer.salesforce.com/page/Apex_Enterprise_Patterns_-_Domain_Layer
*/
@isTest
public class Ortho_UserTerritoryAssociationsTest {
    @testSetup
    public static void createCustomSetting(){
        
        TestUtilsLocal.createCustomSetting('AddUsersToPSQueues Trigger',true);
        
        User systemAdmin = TestUtilsLocal.createTestUser('systemAdmin', true);
    }
    public static User_Territory_Association__c createTestData(User usr){
        User testUser = [SELECT Id, Name FROM User WHERE Name = 'systemAdmin'];
        System.runAs(usr){
            
            Territory2Model newTerritoryModel = [Select Id from territory2Model where DeveloperName =: System.Label.Ortho_Territory_Model];
            Territory2Type t2t = [Select Id,DeveloperName from Territory2Type where MasterLabel ='US Ortho'];
            Territory2 testTerr = TestUtilsLocal.createTerritory2('TestTerr', 'TestTerr', newTerritoryModel, t2t, true);
            
            Account acc = TestUtilsLocal.createAccount('Test', false);
            acc.RecordTypeId = [SELECT Id, Name FROM RecordType WHERE Name = 'DN-Ghost Account'].Id;
            INSERT acc;
            
            TestUtilsLocal.createCustomSetting('BPTrigger_OpportunityAmountRollUp', true);
            Opportunity opp = TestUtilsLocal.createOpportunity(acc, 'TestOpp', false);
            opp.RecordTypeId = [SELECT Id, Name FROM RecordType WHERE Name = 'US OBT'].Id;
            opp.Territory2Id = testTerr.Id;
            INSERT opp;
            
            ObjectTerritory2Association ota = TestUtilsLocal.createObjectTerritory2Association(acc, testTerr, true);
            
            User_Territory_Association__c uta = new User_Territory_Association__c(Role__c = 'Extremities',
                                                                                  Territory__c = testTerr.Id,
                                                                                  Territory_Name__c = 'Test Terr',
                                                                                  User__c = testUser.Id);
            insert uta;
        }
        User_Territory_Association__c uta = [SELECT Role__c, Territory__c, Territory_Name__c, User__c FROM User_Territory_Association__c
                                             WHERE Role__c = 'Extremities'];
        return uta;
    }
    
    //Check when delete the user territory association
    @isTest
    public static void onAfterDelete(){        
        User usr = TestUtilsLocal.createTestSalesUser('oppTerrUser',true);
        User systemAdmin = [SELECT Id, Name FROM User WHERE Name = 'systemAdmin'];
        Test.startTest();
        System.runAs(systemAdmin){
            User_Territory_Association__c uta = createTestData(usr);
            DELETE uta;
        }
        Test.stopTest();
    }
}