force-app/main/default/objects/territory__c/territory__c.object-meta.xml
<CustomObject>
    <description>Integration</description>
    <label>Territory</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Territory Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Territories</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Territory_Name__c/Territory_Name__c.object-meta.xml
<CustomObject>
    <label>Territory Target Refinement</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Territory Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Territory Target Refinements</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/User_Territory_Association__c/User_Territory_Association__c.object-meta.xml
<CustomObject>
    <label>User Territory Association</label>
    <nameField>
        <displayFormat>UT-{0000}</displayFormat>
        <label>User Territory Association Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>User Territory Associations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/User_Territory_Association__c/fields/Role__c.field-meta.xml
<CustomField>
    <fullName>Role__c</fullName>
    <label>Role</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Biologics</fullName>
            </value>
            <value>
                <fullName>Extremities</fullName>
            </value>
            <value>
                <fullName>Foot &amp; Ankle</fullName>
            </value>
            <value>
                <fullName>Hips</fullName>
            </value>
            <value>
                <fullName>Knees</fullName>
            </value>
            <value>
                <fullName>Sports Medicine</fullName>
            </value>
            <value>
                <fullName>Trauma</fullName>
            </value>
            <value>
                <fullName>Cement</fullName>
            </value>
            <value>
                <fullName>Early Intervention</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/User_Territory_Association__c/fields/Territory__c.field-meta.xml
<CustomField>
    <fullName>Territory__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Territory</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/Ortho_UserTerritoryAssociations.cls
/**
* @author Appirio Inc.
* @date March, 2020
*
* @group User_Territory_Association__c
*
* @description Encapsulates all behaviour logic relating to the User_Territory_Association__c object
*       For more guidelines and details see
*    https://developer.salesforce.com/page/Apex_Enterprise_Patterns_-_Domain_Layer
*/
public class Ortho_UserTerritoryAssociations extends Ortho_AppModel{

    public static void onAfterInsert(List<User_Territory_Association__c> cObjUTAList){
        List<UserTerritoryAssociation> utaList = new List<UserTerritoryAssociation>();
        for(User_Territory_Association__c uta : cObjUTAList){
            utaList.add(new UserTerritoryAssociation((Object)uta));
        }
        Ortho_UTAService.alignOpportunityTeam(utaList, true, false);
    }

    public static void onAfterDelete(List<User_Territory_Association__c> cObjUTAList){

        List<UserTerritoryAssociation> utaList = new List<UserTerritoryAssociation>();
        for(User_Territory_Association__c uta : cObjUTAList){
            utaList.add(new UserTerritoryAssociation((Object)uta));
        }

        Ortho_UTAService.alignOpportunityTeam(utaList, false, false);
    }

    public static void setDefaults(List<User_Territory_Association__c> newList, Map<Id, User_Territory_Association__c> oldMap){
        List<User_Territory_Association__c> utaList = new List<User_Territory_Association__c>();
        Map<Id, Territory2> terrMap = new Map<Id, Territory2>();
        Set<Id> terrIdSet = new Set<Id>();
        for(User_Territory_Association__c uta : newList){
            if(oldMap == null || oldMap.get(uta.id).Territory__c != uta.Territory__c){
              utaList.add(uta);
              terrIdSet.add(uta.Territory__c);
            }
        }

        terrMap = new Map<Id, Territory2>(Ortho_TerritorySelector.selectAllTerritoriesByTerrId(terrIdSet));
        if(!utaList.isEmpty()){
            for(User_Territory_Association__c uta : utaList){
                if(terrMap != null && terrMap.containsKey(uta.Territory__c)){
                    uta.Territory_Name__c = terrMap.get(uta.Territory__c).Name;
                }
            }
        }
    }

    public static void onAfterUpdate(List<User_Territory_Association__c> newList, Map<Id, User_Territory_Association__c> oldMap){
        List<UserTerritoryAssociation> updatedUTAList = new List<UserTerritoryAssociation>();
        for(User_Territory_Association__c uta : newList){
            if(oldMap != NULL && oldMap.get(uta.id).Role__c != uta.Role__c){
                updatedUTAList.add(new UserTerritoryAssociation((Object)uta));
            }
        }
        if(!updatedUTAList.isEmpty()){
            Ortho_UTAService.alignOpportunityTeam(updatedUTAList, false, true);
        }
    }

}