force-app/main/default/objects/territory__c/territory__c.object-meta.xml
<CustomObject>
    <description>Integration</description>
    <label>Territory</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Territory Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Territories</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/WSE__c/WSE__c.object-meta.xml
<CustomObject>
    <label>WSE</label>
    <nameField>
        <displayFormat>WSE{0000000}</displayFormat>
        <label>WSE ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>WSEs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/WSE__c/fields/Prior_Mnth_WSE__c.field-meta.xml
<CustomField>
    <fullName>Prior_Mnth_WSE__c</fullName>
    <label>Prior WSE (M)</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/WSE__c/fields/Prior_Qtr_WSE__c.field-meta.xml
<CustomField>
    <fullName>Prior_Qtr_WSE__c</fullName>
    <label>Prior WSE (Q)</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/WSE__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <label>Product</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>KNEES</fullName>
            </value>
            <value>
                <fullName>HIPS</fullName>
            </value>
            <value>
                <fullName>CEMENT</fullName>
            </value>
            <value>
                <fullName>EXTREMITIES</fullName>
            </value>
            <value>
                <fullName>SPORTS MEDICINE</fullName>
            </value>
            <value>
                <fullName>EARLY INTERVENTION</fullName>
            </value>
            <value>
                <fullName>TRAUMA</fullName>
            </value>
            <value>
                <fullName>FOOT &amp; ANKLE</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/WSE__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pending</fullName>
                <default>true</default>
                <label>Pending</label>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Complete</fullName>
            </value>
            <value>
                <fullName>Submitted</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/WSE__c/fields/Target_Mnth__c.field-meta.xml
<CustomField>
    <fullName>Target_Mnth__c</fullName>
    <label>Target (M)</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/WSE__c/fields/Target_Qtr__c.field-meta.xml
<CustomField>
    <fullName>Target_Qtr__c</fullName>
    <label>Target (Q)</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/WSE__c/fields/Territory2Id__c.field-meta.xml
<CustomField>
    <fullName>Territory2Id__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Territory2Id</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/WSE__c/fields/Territory__c.field-meta.xml
<CustomField>
    <fullName>Territory__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Territory</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/WSE__c/fields/Vs_Prior_WSE_Amt_Mnth__c.field-meta.xml
<CustomField>
    <fullName>Vs_Prior_WSE_Amt_Mnth__c</fullName>
    <label>Vs Prior WSE $ (M)</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/WSE__c/fields/Vs_Prior_WSE_Amt_Qtr__c.field-meta.xml
<CustomField>
    <fullName>Vs_Prior_WSE_Amt_Qtr__c</fullName>
    <label>Vs Prior WSE $ (Q)</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/WSE__c/fields/Vs_Prior_WSE_Pct_Mnth__c.field-meta.xml
<CustomField>
    <fullName>Vs_Prior_WSE_Pct_Mnth__c</fullName>
    <label>Vs Prior WSE % (M)</label>
    <precision>18</precision>
    <scale>3</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/WSE__c/fields/Vs_Prior_WSE_Pct_Qtr__c.field-meta.xml
<CustomField>
    <fullName>Vs_Prior_WSE_Pct_Qtr__c</fullName>
    <label>Vs Prior WSE % (Q)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/WSE__c/fields/Vs_Target_Amt_Mnth__c.field-meta.xml
<CustomField>
    <fullName>Vs_Target_Amt_Mnth__c</fullName>
    <label>Vs Target $ (M)</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/WSE__c/fields/Vs_Target_Amt_Qtr__c.field-meta.xml
<CustomField>
    <fullName>Vs_Target_Amt_Qtr__c</fullName>
    <label>Vs Target $ (Q)</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/WSE__c/fields/Vs_Target_Pct_Mnth__c.field-meta.xml
<CustomField>
    <fullName>Vs_Target_Pct_Mnth__c</fullName>
    <label>Vs Target % (M)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/WSE__c/fields/Vs_Target_Pct_Qtr__c.field-meta.xml
<CustomField>
    <fullName>Vs_Target_Pct_Qtr__c</fullName>
    <label>Vs Target % (Q)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/WSE__c/fields/Week_Number__c.field-meta.xml
<CustomField>
    <fullName>Week_Number__c</fullName>
    <label>Week Number</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/WSE__c/fields/WSE_Mnth__c.field-meta.xml
<CustomField>
    <fullName>WSE_Mnth__c</fullName>
    <label>WSE (M)</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/WSE__c/fields/WSE_Qtr__c.field-meta.xml
<CustomField>
    <fullName>WSE_Qtr__c</fullName>
    <label>WSE (Q)</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/WSE__c/fields/WSE_Vs_PY_ADS_Mnth__c.field-meta.xml
<CustomField>
    <fullName>WSE_Vs_PY_ADS_Mnth__c</fullName>
    <label>WSE_Vs_PY_ADS % (M)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/WSE__c/fields/WSE_Vs_PY_ADS_Qtr__c.field-meta.xml
<CustomField>
    <fullName>WSE_Vs_PY_ADS_Qtr__c</fullName>
    <label>WSE_Vs_PY_ADS % (Q)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/WSE__c/fields/WSE_Vs_PY_Day_Adj_Mnth__c.field-meta.xml
<CustomField>
    <fullName>WSE_Vs_PY_Day_Adj_Mnth__c</fullName>
    <label>WSE Vs PY Day Adj (M)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/WSE__c/fields/WSE_Vs_PY_Day_Adj_Qtr__c.field-meta.xml
<CustomField>
    <fullName>WSE_Vs_PY_Day_Adj_Qtr__c</fullName>
    <label>WSE Vs PY Day Adj (Q)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/WSEController.cls
public with sharing class WSEController {
    public WSEController() {

    }

    @AuraEnabled
    public static List<WSE__c> getWSERecordsForWeek(Decimal weekNo, String TerrId){
        try {
            List<WSE__c> lstWSE = [Select Effective_Date__c,Id,Name,Owner.Name,Prior_Mnth_WSE__c,Prior_Qtr_WSE__c,WSE_Mnth__c,WSE_Qtr__c,Product__c,Status__c,Target_Mnth__c,Target_Qtr__c,Territory2Id__c,Territory__c,Vs_Prior_WSE_Amt_Mnth__c,Vs_Prior_WSE_Amt_Qtr__c,Vs_Prior_WSE_Pct_Mnth__c,Vs_Prior_WSE_Pct_Qtr__c,Vs_Target_Amt_Mnth__c,Vs_Target_Amt_Qtr__c,Vs_Target_Pct_Mnth__c,Vs_Target_Pct_Qtr__c,Week_Number__c,WSE_Vs_PY_ADS_Mnth__c,WSE_Vs_PY_ADS_Qtr__c,WSE_Vs_PY_Day_Adj_Mnth__c,WSE_Vs_PY_Day_Adj_Qtr__c from WSE__c where Week_Number__c = :weekNo and Territory2Id__c = :TerrId];

            return lstWSE;
        } catch (Exception e) {
            throw new AuraHandledException(e.getMessage());
        }
    }
    

    @AuraEnabled
    public static List<String> getWSEWeekNoList(){
        try {
            List<WSE__c> lstWSE = [Select Id, Effective_Date__c, Name, Week_Number__c from WSE__c order by Effective_Date__c desc];
            
            Set<String> s = new Set<String>();
            List<String> effDtList = new List<String>();
            
            System.debug('There are '+lstWSE.size() + ' records in WSE');

            for (WSE__c w : lstWSE) {
                Datetime dt = w.Effective_Date__c;                
                s.add(dt.format('MM-dd-yyyy'));
            }
            
            effDtList.addAll(s);
            System.debug('Effective Date List Array: '+effDtList);
            return effDtList;
        } catch (Exception e) {
            throw new AuraHandledException(e.getMessage());
        }
    }

    @AuraEnabled
    public static Map<Id,String> getWSETerrList(){
        try {
            List<WSE__c> lstWSE = [Select Id, Effective_Date__c, Name, Week_Number__c, Territory2Id__c, Territory__c from WSE__c order by Effective_Date__c desc];
            
            Map<Id, String> terr = new Map<Id,String>();

            for (WSE__c w : lstWSE) {
                if (!terr.containsKey(w.Territory2Id__c)) {
                    terr.put(w.Territory2Id__c, w.Territory__c);
                }
            }

            return terr;
        } catch (Exception e) {
            throw new AuraHandledException(e.getMessage());
        }
    }
    
}