force-app/main/default/objects/territory__c/territory__c.object-meta.xml
<CustomObject>
    <description>Integration</description>
    <label>Territory</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Territory Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Territories</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/User_Territory_Association__c/User_Territory_Association__c.object-meta.xml
<CustomObject>
    <label>User Territory Association</label>
    <nameField>
        <displayFormat>UT-{0000}</displayFormat>
        <label>User Territory Association Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>User Territory Associations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/User_Territory_Association__c/fields/Role__c.field-meta.xml
<CustomField>
    <fullName>Role__c</fullName>
    <label>Role</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Biologics</fullName>
            </value>
            <value>
                <fullName>Extremities</fullName>
            </value>
            <value>
                <fullName>Foot &amp; Ankle</fullName>
            </value>
            <value>
                <fullName>Hips</fullName>
            </value>
            <value>
                <fullName>Knees</fullName>
            </value>
            <value>
                <fullName>Sports Medicine</fullName>
            </value>
            <value>
                <fullName>Trauma</fullName>
            </value>
            <value>
                <fullName>Cement</fullName>
            </value>
            <value>
                <fullName>Early Intervention</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/User_Territory_Association__c/fields/Territory__c.field-meta.xml
<CustomField>
    <fullName>Territory__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Territory</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/User_Territory_Association__c/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>User_Territory_Associations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/Ortho_AppModel.cls
/**
* @author Appirio Inc.
* @date Feb, 2020
*
* @group AppModels for Ortho
**/
public virtual class Ortho_AppModel{
    public class UserTerritoryAssociation{
        public String userId;
        public String terrtoryId;
        public String role;
        public UserTerritoryAssociation(String userId, String terrtoryId, String role){
            this.userId = userId;
            this.terrtoryId = terrtoryId;
            this.role = role;
        }
        public UserTerritoryAssociation(Object obj){
            UserTerritory2Association sObj;
            User_Territory_Association__c cObj;
            if(obj instanceOf UserTerritory2Association){
                sObj = (UserTerritory2Association) obj;
                this.userId = sObj.UserId;
                this.terrtoryId = sObj.Territory2Id;
                this.role = sObj.RoleInTerritory2;
            }else if(obj instanceOf User_Territory_Association__c){
                cObj = (User_Territory_Association__c) obj;
                this.userId = cObj.User__c;
                this.terrtoryId = cObj.Territory__C;
                this.role = cObj.Role__C;
            }

        }
    }


}