force-app/main/default/objects/territory__c/territory__c.object-meta.xml
<CustomObject>
    <description>Integration</description>
    <label>Territory</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Territory Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Territories</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/User_Territory_Association__c/User_Territory_Association__c.object-meta.xml
<CustomObject>
    <label>User Territory Association</label>
    <nameField>
        <displayFormat>UT-{0000}</displayFormat>
        <label>User Territory Association Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>User Territory Associations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/User_Territory_Association__c/fields/Role__c.field-meta.xml
<CustomField>
    <fullName>Role__c</fullName>
    <label>Role</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Biologics</fullName>
            </value>
            <value>
                <fullName>Extremities</fullName>
            </value>
            <value>
                <fullName>Foot &amp; Ankle</fullName>
            </value>
            <value>
                <fullName>Hips</fullName>
            </value>
            <value>
                <fullName>Knees</fullName>
            </value>
            <value>
                <fullName>Sports Medicine</fullName>
            </value>
            <value>
                <fullName>Trauma</fullName>
            </value>
            <value>
                <fullName>Cement</fullName>
            </value>
            <value>
                <fullName>Early Intervention</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/User_Territory_Association__c/fields/Territory__c.field-meta.xml
<CustomField>
    <fullName>Territory__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Territory</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/User_Territory_Association__c/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>User_Territory_Associations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/Ortho_Util.cls
/**
 * @author Appirio
 * @date Feb, 2020
 *
 * @description Contains utility methods for generic use.
 */

public class Ortho_Util extends Ortho_AppModel{

    /**
    * @description Returns all the record types for Opportunity object.
    */
	public static Map<String,String> getUSOrthoOpptyRecordTypes(){
        Map<String, String> mapRecTypes = new Map<String,String>();

        List<String> recTypes = Ortho_SettingsService.getGeneralSettingValueByName('Opportunity_RecordTypes').split(',');
        for(RecordType rt: [SELECT Id, sObjectType, Name, DeveloperName
            FROM RecordType WHERE sobjectType = 'Opportunity' AND Name in : recTypes]){
            mapRecTypes.put(rt.Id, rt.Name);
        }
        return mapRecTypes;
    }

    /**
    * @description Returns all the leaf territories of given territiries
    */
    public static Set<Id> leafNodes(Id parentTerrId, Map<Id, Set<Id>> mapParentAndChildIds) {
        Set<Id> nodesToRet = new Set<Id>();
        if (mapParentAndChildIds.containsKey(parentTerrId)) {
            for (Id terrId : mapParentAndChildIds.get(parentTerrId)) {
                if (mapParentAndChildIds.containskey(terrId)) {
                    nodesToRet.addAll(leafNodes(terrId, mapParentAndChildIds));
                } else {
                    nodesToRet.add(terrId);
                }
            }
        } else {
            nodesToRet.add(parentTerrId);
        }
        return nodesToRet;

    }

    /**
    * @description Returns all the leaf territories of given territiries
    */
    public static Map<Id, List<UserTerritoryAssociation>> getUserTerritoryAssociations(Set<id> terrIdSet) {
        Map<Id, List<UserTerritoryAssociation>> terrUserMap = new Map<Id, List<UserTerritoryAssociation>>();

       List<UserTerritory2Association> utaList = Ortho_UserTerr2AssociationSelector.selectUtaByTerrId(terrIdSet);

        for(UserTerritory2Association uta2 : utaList){
            if(!terrUserMap.containsKey(uta2.Territory2Id)){
                terrUserMap.put(uta2.Territory2Id, new List<UserTerritoryAssociation>());
            }
            terrUserMap.get(uta2.Territory2Id).add(
                new UserTerritoryAssociation(uta2.UserId, uta2.Territory2Id, uta2.RoleInTerritory2));
        }

        List<User_Territory_Association__c> utaCustomList = Ortho_UserTerrAssociationSelector.selectUtaByTerrId(terrIdSet);

        for(User_Territory_Association__c uta : utaCustomList){
            if(!terrUserMap.containsKey(uta.Territory__C)){
                terrUserMap.put(uta.Territory__C, new List<UserTerritoryAssociation>());
            }
            terrUserMap.get(uta.Territory__C).add(
                new UserTerritoryAssociation(uta.User__c, uta.Territory__C, uta.Role__C));
        }

        return terrUserMap;
    }

    /**
    * @description Returns all the parent Child Territory Map
    */
    public static Map<Id, Set<Id>> getParentChildTerritoryMap(){
        Map<Id, Set<Id>> mapParentAndChildIds = new Map<Id, Set<Id>>();

        for (Territory2 terrObj : Ortho_TerritorySelector.selectAllTerritories()) {
            if (mapParentAndChildIds.containsKey(terrObj.ParentTerritory2Id) == false) {
                mapParentAndChildIds.put(terrObj.ParentTerritory2Id, new Set<Id>());
            }
            mapParentAndChildIds.get(terrObj.ParentTerritory2Id).add(terrObj.Id);
        }

        return mapParentAndChildIds;
    }
}