force-app/main/default/objects/GPL_Profile__c/GPL_Profile__c.object-meta.xml
<CustomObject>
    <label>GPL Profile</label>
    <nameField>
        <displayFormat>GPL_P-{0000}</displayFormat>
        <label>GPL Profile ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>GPL Profiles</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/GPL_Profile__c/fields/Picture_Id__c.field-meta.xml
<CustomField>
    <fullName>Picture_Id__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Picture Id</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/GplManageProfilePhotoController.cls
public class GplManageProfilePhotoController {
    private final GPL_Profile__c profile;
    private ApexPages.standardController sc;
    public Attachment photo {
        get {
            if (photo == null){
                photo = new Attachment();
            }
            return photo;
        }
        set;
    }
    
    public GplManageProfilePhotoController(ApexPages.StandardController stdController){
        this.sc = stdController;
        this.profile = (GPL_Profile__c)stdController.getRecord();
    } 
    
    public PageReference savePhoto(){
        photo.ParentId = profile.Id;
        try {
            blob body = photo.Body;
            if (body.size() > 100000){
                ApexPages.addMessage(new ApexPages.message(ApexPages.severity.Error,'Image size must be less than 100K'));
                return null;
            }
            insert photo;
            profile.Picture_Id__c = photo.Id;
            update profile;
        } catch (Exception e){
            ApexPages.addMessage(new ApexPages.message(ApexPages.severity.ERROR,'Error uploading attachment'));
            return null;
        } finally {
            photo = new Attachment();
        }
        return new PageReference('/' + profile.Id);
    }
}