force-app/main/default/objects/Instrument_Request__c/Instrument_Request__c.object-meta.xml
<CustomObject>
    <description>This object is being used for Instrument Tracking/Request Integration.</description>
    <label>Instrument Request</label>
    <nameField>
        <displayFormat>Inst-{00000}</displayFormat>
        <label>Instrument Request Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Instrument Requests</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Instrument_Request__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Instrument Requests</relationshipLabel>
    <relationshipName>Instrument_Requests</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Instrument_Request__c/fields/Record_Number__c.field-meta.xml
<CustomField>
    <fullName>Record_Number__c</fullName>
    <defaultValue>1</defaultValue>
    <label>Record Number</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Instrument_Request__c/fields/SNAP_KIT_ID__c.field-meta.xml
<CustomField>
    <fullName>SNAP_KIT_ID__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <externalId>true</externalId>
    <label>SNAP KIT ID</label>
    <length>50</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Instrument_Request__c/fields/SNAP_Kit_Nbr__c.field-meta.xml
<CustomField>
    <fullName>SNAP_Kit_Nbr__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>SNAP Kit Number</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Instrument_Request__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Open</fullName>
            </value>
            <value>
                <fullName>Submitted</fullName>
            </value>
            <value>
                <fullName>Sent To Committee</fullName>
            </value>
            <value>
                <fullName>Review</fullName>
            </value>
            <value>
                <fullName>Unsubmitted</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Approved w/Edits</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Denied</fullName>
            </value>
            <value>
                <fullName>New</fullName>
            </value>
            <value>
                <fullName>Returned</fullName>
            </value>
            <value>
                <fullName>Ordered</fullName>
            </value>
            <value>
                <fullName>Partially Ordered</fullName>
            </value>
            <value>
                <fullName>Shipped</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/IOM_Request_Status__c.field-meta.xml
<CustomField>
    <fullName>IOM_Request_Status__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>IOM Request Status</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Forecast</fullName>
                <isActive>false</isActive>
                <label>Forecast</label>
            </value>
            <value>
                <fullName>Upside</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/recordTypes/ASC.recordType-meta.xml
<RecordType>
    <fullName>ASC</fullName>
    <active>true</active>
    <businessProcess>AM-US_ASC</businessProcess>
    <description>This opportunity types triggers a ASC opportunity</description>
    <label>ASC</label>
</RecordType>

force-app/main/default/classes/InstRqstHandler.cls
public with sharing class InstRqstHandler {
    public static boolean isRunning = false;
    public InstRqstHandler() {

    }

    public static void onBeforeInsertUpdate(List<Instrument_Request__c> irList){
        List<Opportunity> updatedOppList = new List<Opportunity>();
        Set<Id> terrIds = new Set<Id>();
        Map<Id,Id> oppTerrMap = new Map<Id,String>();
        System.debug('In InstRqstHandler - onBeforeInsertUpdate : No of Instrument Records = '+irList.size());  

        for (Instrument_Request__c ir: irList){
            if((ir.SNAP_Kit_Nbr__c == null || String.isBlank(ir.SNAP_Kit_Nbr__c) 
                && ir.SNAP_KIT_ID__c != null && String.isNotBlank(ir.SNAP_KIT_ID__c))){
                ir.SNAP_Kit_Nbr__c = ir.SNAP_KIT_ID__c.right(ir.SNAP_KIT_ID__c.length()-19);
            }
        }        
    }   

    public static void onAfterInsertUpdate(List<Instrument_Request__c> irList, Map<Id,Instrument_Request__c> irMap){

        if (InstRqstHandler.isRunning)
        {
            return;
        }

        InstRqstHandler.isRunning = false;

        Set<Id> oppIds = new Set<Id>();       
        Set<String> kitIds = new Set<String>();
        Map<Id, Set<String>> oppStatusMap = new Map<Id, Set<String>>();
        /*
            oppStatusMap => Set <Status String>, Sent, Shipped etc.
        */
        System.debug('In InstRqstHandler - onAfterInsertUpdate : No of IRs = '+irList.size());
        for (Instrument_Request__c ir: irList){
            if (ir.Opportunity__c != null)
            {
                oppIds.add(ir.Opportunity__c);
            }
            if (ir.SNAP_Kit_Nbr__c != null)
            {
                kitIds.add(ir.SNAP_Kit_Nbr__c);
            }
        }

        // May Need to Fetch all Instrument Requests... for the Opportunity and then create Status list
        List<Opportunity> oppListToUpdate = [Select Id, Name, IOM_Request_Status__c from Opportunity where Id in :oppIds];

        List<Instrument_Request__c> lstIRs = [Select Id, Opportunity__c, Status__c, Record_Number__c,SNAP_Kit_Nbr__c from Instrument_Request__c where Opportunity__c IN :oppIds order by Opportunity__c asc, Status__c];
        List<Instrument_Request__c> lstIRsByKitIds = [Select Id, Opportunity__c, Status__c, Record_Number__c,SNAP_Kit_Nbr__c from Instrument_Request__c where SNAP_Kit_Nbr__c IN :kitIds order by SNAP_Kit_Nbr__c, Opportunity__c asc];

        System.debug('It found '+lstIRs.size()+' instrument requests for Oppty : '+oppIds);

        Integer i = 1;
        String prevIRSnapKitNbr = '';
        Set<Instrument_Request__c> lstIRToUpdateForOrder = new Set<Instrument_Request__c>();

        for (Instrument_Request__c ir: lstIRs){
            if (ir.Opportunity__c != null)
            {
                if (oppStatusMap.containsKey(ir.Opportunity__c)) {
                    oppStatusMap.get(ir.Opportunity__c).add(ir.Status__c);
                }
                else {   
                    Set<String> st = new Set<String>();
                    st.add(ir.Status__c);
                    oppStatusMap.put(ir.Opportunity__c, st);
                }
            }
        }
        for (Instrument_Request__c ir: lstIRsByKitIds){

            if (ir.SNAP_Kit_Nbr__c != prevIRSnapKitNbr)
            {
                i = 1;
            }
            else 
            {
                i++;
            }

            if (ir.Record_Number__c != i)
            {
                System.debug('IR '+ir.SNAP_Kit_Nbr__c + ' Oppty: '+ir.Opportunity__c+ ' order does not match : '+ ir.Record_Number__c + ' vs '+ i);
                ir.Record_Number__c = i;
                lstIRToUpdateForOrder.add(ir);
            }

            prevIRSnapKitNbr = ir.SNAP_Kit_Nbr__c;
        }

        //System.debug(oppStatusMap);
		List<Opportunity> finalListOfOppToUpdate = new List<Opportunity>();
        for (Opportunity o: oppListToUpdate) {            
            String strOppStatus = '';
            for (String s : oppStatusMap.get(o.Id))
            {
                strOppStatus += s + ';';
            }
            if (o.IOM_Request_Status__c != strOppStatus) {
                System.debug('IOM Status is not same... '+ o.IOM_Request_Status__c + ' vs '+ strOppStatus + '. It will be updated for Opp: '+o.Id);
            	o.IOM_Request_Status__c = strOppStatus;
                finalListOfOppToUpdate.add(o);
       		}
            else {
                System.debug('IOM Status is same... '+ o.IOM_Request_Status__c + ' vs '+ strOppStatus + '. It will NOT be updated for Opp: '+o.Id);
            }
           
        }
        
        if(!finalListOfOppToUpdate.isEmpty()){            
            update oppListToUpdate;
        }

        System.debug('Found IR Reordering needed for '+lstIRToUpdateForOrder.size() + ' records');
        if (!lstIRToUpdateForOrder.isEmpty()){  
            //InstRqstHandler.isRunning = true; 
            //List<Instrument_Request__c> lstIRs =  new List<Instrument_Request__c>(lstIRToUpdateForOrder); 
            update (new List<Instrument_Request__c>(lstIRToUpdateForOrder));
        }
    }
}