force-app/main/default/objects/CountryISO__c/CountryISO__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Store data for country name and ISO code</description>
    <label>CountryISO</label>
</CustomObject>

force-app/main/default/objects/CountryISO__c/fields/Geography__c.field-meta.xml
<CustomField>
    <fullName>Geography__c</fullName>
    <description>Country ISO code</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Geography</label>
    <length>3</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/CountryISO__c/fields/Region__c.field-meta.xml
<CustomField>
    <fullName>Region__c</fullName>
    <description>Region of country</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Region</label>
    <length>3</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/User/fields/Geography__c.field-meta.xml
<CustomField>
    <fullName>Geography__c</fullName>
    <description>This field is required-There are workflow and validation rules that uses this field to determine processing path based on the Geography, Business Division and/or Region field(s) setting of the user.</description>
    <inlineHelpText>This field is required-There are workflow and validation rules that uses this field to determine processing path based on the Geography, Business Division and/or Region field(s) setting of the user.</inlineHelpText>
    <label>Geography</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Argentina</fullName>
            </value>
            <value>
                <fullName>Australia</fullName>
            </value>
            <value>
                <fullName>Austria</fullName>
            </value>
            <value>
                <fullName>Belgium</fullName>
            </value>
            <value>
                <fullName>Bolivia (Plurinational State of)</fullName>
            </value>
            <value>
                <fullName>Brazil</fullName>
            </value>
            <value>
                <fullName>Canada</fullName>
            </value>
            <value>
                <fullName>Chile</fullName>
            </value>
            <value>
                <fullName>China</fullName>
            </value>
            <value>
                <fullName>Colombia</fullName>
            </value>
            <value>
                <fullName>Costa Rica</fullName>
            </value>
            <value>
                <fullName>Czech Republic</fullName>
            </value>
            <value>
                <fullName>Denmark</fullName>
            </value>
            <value>
                <fullName>Ecuador</fullName>
            </value>
            <value>
                <fullName>Finland</fullName>
            </value>
            <value>
                <fullName>France</fullName>
            </value>
            <value>
                <fullName>Germany</fullName>
            </value>
            <value>
                <fullName>Hong Kong</fullName>
            </value>
            <value>
                <fullName>Hungary</fullName>
            </value>
            <value>
                <fullName>India</fullName>
            </value>
            <value>
                <fullName>Ireland</fullName>
            </value>
            <value>
                <fullName>Italy</fullName>
            </value>
            <value>
                <fullName>Japan</fullName>
            </value>
            <value>
                <fullName>Korea (Republic of)</fullName>
            </value>
            <value>
                <fullName>Lebanon</fullName>
            </value>
            <value>
                <fullName>Malaysia</fullName>
            </value>
            <value>
                <fullName>Mexico</fullName>
            </value>
            <value>
                <fullName>N/A</fullName>
            </value>
            <value>
                <fullName>Netherlands</fullName>
            </value>
            <value>
                <fullName>New Zealand</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/User/fields/Region__c.field-meta.xml
<CustomField>
    <fullName>Region__c</fullName>
    <description>This field is required-There are workflow and validation rules that uses this field to determine processing path based on the Geography, Business Division and/or Region field(s) setting of the user.</description>
    <inlineHelpText>This field is required-There are workflow and validation rules that uses this field to determine processing path based on the Geography, Business Division and/or Region field(s) setting of the user.</inlineHelpText>
    <label>Region</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>AM</fullName>
            </value>
            <value>
                <fullName>AP</fullName>
            </value>
            <value>
                <fullName>EU</fullName>
            </value>
            <value>
                <fullName>GL</fullName>
            </value>
            <value>
                <fullName>LA</fullName>
            </value>
            <value>
                <fullName>N/A</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/RegionAdder.cls
public with sharing class RegionAdder {
    
    //pull data of user in list
    public static void regionUpdate (list<User> userList){
        
        //creating map , key and value as countryISO and will pull values related to key
        map<String,countryISO__c> csMap = new map<String,countryISO__c>();
        map<String,CountryISO__c> csiMap = new map<String,CountryISO__c>();
        //iterate values of custom settings, and pulling values from custom settings using getall() method
        for(CountryISO__c each : CountryISO__c.getAll().values()){
            
            //creating map putting all data related to CountryISO__c.name
            csMap.put(each.Geography__c,each);
            csiMap.put(each.name,each);
        }
        
        //itarating user list
        for(User eachUser : userList){
            
            if(eachUser.Geography__c != null || eachUser.Geography__c != 'N/A'){
         
                if(csMap.containsKey(eachUser.Geography__c)){
                        //add region
                        eachUser.Region__c = csMap.get(eachUser.Geography__c).Region__c;
                }
                
                else if(csiMap.containsKey(eachUser.Geography__c)){
                        //add region
                        eachUser.Region__c = csiMap.get(eachUser.Geography__c).Region__c;
                        //replace billing country with ISO
                        eachUser.Geography__c = csiMap.get(eachUser.Geography__c).Geography__c;
                }
                
                else{
                    //eachUser.Geography__c.addError('Please enter valid country');
                }
            }
            else{}
        }
    }
}