force-app/main/default/objects/Opportunity/recordTypes/AM_US_SM_Sales.recordType-meta.xml
<RecordType>
    <fullName>AM_US_SM_Sales</fullName>
    <active>true</active>
    <businessProcess>AM-US-RC Sales</businessProcess>
    <description>Sports Medicine for US Sales</description>
    <label>US Sports Medicine</label>
</RecordType>

force-app/main/default/objects/Opportunity/recordTypes/Revenue_Growth.recordType-meta.xml
<RecordType>
    <fullName>Revenue_Growth</fullName>
    <active>true</active>
    <businessProcess>AM-US-RC Sales</businessProcess>
    <description>Knee for US Sales</description>
    <label>US Knee</label>
</RecordType>

force-app/main/default/objects/Opportunity/recordTypes/US_Cement.recordType-meta.xml
<RecordType>
    <fullName>US_Cement</fullName>
    <active>true</active>
    <businessProcess>AM-US-RC Sales</businessProcess>
    <description>Cement for US Recon</description>
    <label>US Cement</label>
</RecordType>

force-app/main/default/objects/Opportunity/recordTypes/US_Early_Intervention.recordType-meta.xml
<RecordType>
    <fullName>US_Early_Intervention</fullName>
    <active>true</active>
    <businessProcess>AM-US-RC Sales</businessProcess>
    <label>US Early Intervention</label>
</RecordType>

force-app/main/default/objects/Opportunity/recordTypes/US_Extremities.recordType-meta.xml
<RecordType>
    <fullName>US_Extremities</fullName>
    <active>true</active>
    <businessProcess>AM-US-RC Sales</businessProcess>
    <description>Extremities for US Sales</description>
    <label>US Extremities</label>
</RecordType>

force-app/main/default/objects/Opportunity/recordTypes/US_Foot_and_Ankle_Sales.recordType-meta.xml
<RecordType>
    <fullName>US_Foot_and_Ankle_Sales</fullName>
    <active>true</active>
    <businessProcess>AM-US-RC Sales</businessProcess>
    <description>Foot and Ankle for US Sales</description>
    <label>US Foot and Ankle</label>
</RecordType>

force-app/main/default/objects/Opportunity/recordTypes/US_Hip.recordType-meta.xml
<RecordType>
    <fullName>US_Hip</fullName>
    <active>true</active>
    <businessProcess>AM-US-RC Sales</businessProcess>
    <description>Hip for US Sales</description>
    <label>US Hip</label>
</RecordType>

force-app/main/default/objects/Opportunity/recordTypes/US_Trauma.recordType-meta.xml
<RecordType>
    <fullName>US_Trauma</fullName>
    <active>true</active>
    <businessProcess>AM-US-RC Sales</businessProcess>
    <description>Trauma for US Sales</description>
    <label>US Trauma</label>
</RecordType>

force-app/main/default/objects/Ortho_App_Favorites__c/Ortho_App_Favorites__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>Ortho App Favorites</label>
</CustomObject>

force-app/main/default/objects/Ortho_App_Favorites__c/fields/Is_Favorite__c.field-meta.xml
<CustomField>
    <fullName>Is_Favorite__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is Favorite?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Ortho_App_Favorites__c/fields/User_ID__c.field-meta.xml
<CustomField>
    <fullName>User_ID__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>User_ID</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Ortho_Mobile_Setting__mdt/Ortho_Mobile_Setting__mdt.object-meta.xml
<CustomObject>
    <label>Ortho Mobile Setting</label>
    <pluralLabel>Ortho Mobile Settings</pluralLabel>
</CustomObject>

force-app/main/default/classes/Ortho_SettingsServiceTest.cls
@isTest
public class Ortho_SettingsServiceTest {
    
    @testSetup
    public static void createTestData(){
        User appUser = TestUtilsLocal.createTestUser('appUser',true);
        Ortho_App_Favorites__c appFav = new Ortho_App_Favorites__c(Name='Test',User_Id__c = appUser.Id, Is_Favorite__c=true);
        insert appFav;
    }
    
    @isTest
    static void getSettingByTypeTest(){
        Test.startTest();
        List<Ortho_Mobile_Setting__mdt> oms = Ortho_SettingsService.getSettingByType('Communication Group');
        Test.stopTest();
        System.assertEquals('Group: Communications Test', oms.get(0).MasterLabel);
    }
    
    @isTest
    static void getAppFavoritesByUserTest(){
        Id appUserId = [Select Id from User where name='appUser'].Id;
        Test.startTest();
        List<Ortho_App_Favorites__c> appFav = Ortho_SettingsService.getAppFavoritesByUser(appUserId);
        Test.stopTest();
        System.assertEquals(true, appFav.get(0).Is_Favorite__c);
    }
    
    @isTest
    static void getAppFavoritesByUserAndAppTest(){
        Test.startTest();
        Id appUserId = [Select Id from User where name='appUser'].Id;
        List<Ortho_App_Favorites__c> appFav = Ortho_SettingsService.getAppFavoritesByUserAndApp(appUserId,null);
        Test.stopTest();
        System.assertEquals(true, appFav.get(0).Is_Favorite__c);
    }
    
    @isTest
    static void getGeneralSettingValueByNameTest(){
        Test.startTest();
        String ogsValue= Ortho_SettingsService.getGeneralSettingValueByName('Opportunity RecordTypes');
        Test.stopTest();
        System.assertNotEquals(null, ogsValue);
    }
    
    @isTest
    static void getGeneralSettingValueByTypeTest(){
        Test.startTest();
        Map<String,String> mapRecTypeToProduct= Ortho_SettingsService.getGeneralSettingValueByType('Product Role Mapping');
        Test.stopTest();
        List<String> oppRecTypeIds = new List<String>();
        oppRecTypeIds.add(Schema.SObjectType.Opportunity.getRecordTypeInfosByDeveloperName().get('US_Extremities').getRecordTypeId());
        oppRecTypeIds.add(Schema.SObjectType.Opportunity.getRecordTypeInfosByDeveloperName().get('US_Foot_and_Ankle_Sales').getRecordTypeId());
        oppRecTypeIds.add(Schema.SObjectType.Opportunity.getRecordTypeInfosByDeveloperName().get('US_Hip').getRecordTypeId());
        oppRecTypeIds.add(Schema.SObjectType.Opportunity.getRecordTypeInfosByDeveloperName().get('US_Cement').getRecordTypeId());
        oppRecTypeIds.add(Schema.SObjectType.Opportunity.getRecordTypeInfosByDeveloperName().get('Revenue_Growth').getRecordTypeId());
        oppRecTypeIds.add(Schema.SObjectType.Opportunity.getRecordTypeInfosByDeveloperName().get('US_Early_Intervention').getRecordTypeId());
        oppRecTypeIds.add(Schema.SObjectType.Opportunity.getRecordTypeInfosByDeveloperName().get('AM_US_SM_Sales').getRecordTypeId());
        oppRecTypeIds.add(Schema.SObjectType.Opportunity.getRecordTypeInfosByDeveloperName().get('US_Trauma').getRecordTypeId());
        
       
        system.assertEquals('Extremities', mapRecTypeToProduct.get(oppRecTypeIds.get(0)));
        system.assertEquals('Foot & Ankle', mapRecTypeToProduct.get(oppRecTypeIds.get(1)));
        system.assertEquals('Hips', mapRecTypeToProduct.get(oppRecTypeIds.get(2)));
        system.assertEquals('Cement', mapRecTypeToProduct.get(oppRecTypeIds.get(3)));
        system.assertEquals('Knees', mapRecTypeToProduct.get(oppRecTypeIds.get(4)));
        system.assertEquals('Early Intervention', mapRecTypeToProduct.get(oppRecTypeIds.get(5)));
        system.assertEquals('Sports Medicine', mapRecTypeToProduct.get(oppRecTypeIds.get(6)));
        system.assertEquals('Trauma', mapRecTypeToProduct.get(oppRecTypeIds.get(7)));
    }
    
}