force-app/main/default/objects/Purchase_Order__c/Purchase_Order__c.object-meta.xml
<CustomObject>
    <label>Purchase Order</label>
    <nameField>
        <displayFormat>PO-{000000}</displayFormat>
        <label>Purchase Order Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Purchase Orders</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Purchase_Order__c/fields/Bill_ID__c.field-meta.xml
<CustomField>
    <fullName>Bill_ID__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Bill ID</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Purchase_Order__c/fields/ERP_Account_ID__c.field-meta.xml
<CustomField>
    <fullName>ERP_Account_ID__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>ERP Account ID</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Purchase_Order__c/fields/ERP_Account_Name__c.field-meta.xml
<CustomField>
    <fullName>ERP_Account_Name__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>ERP Account Name</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Purchase_Order__c/fields/ERP_Order__c.field-meta.xml
<CustomField>
    <fullName>ERP_Order__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>ERP Order</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Purchase_Order__c/fields/PO_Status__c.field-meta.xml
<CustomField>
    <fullName>PO_Status__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>PO Status</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Purchase_Order__c/fields/PO_Subtotal__c.field-meta.xml
<CustomField>
    <fullName>PO_Subtotal__c</fullName>
    <label>PO Subtotal</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Purchase_Order__c/fields/Territory2_ID__c.field-meta.xml
<CustomField>
    <fullName>Territory2_ID__c</fullName>
    <description>SFDC Territory2 Id</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Territory2 ID</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Purchase_Order__c/fields/Territory2_Name__c.field-meta.xml
<CustomField>
    <fullName>Territory2_Name__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Territory2 Name</label>
    <length>60</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Purchase_Order__c/fields/Territory_Name__c.field-meta.xml
<CustomField>
    <fullName>Territory_Name__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Territory Name</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Territory_Name__c/Territory_Name__c.object-meta.xml
<CustomObject>
    <label>Territory Target Refinement</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Territory Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Territory Target Refinements</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/User/fields/Region__c.field-meta.xml
<CustomField>
    <fullName>Region__c</fullName>
    <description>This field is required-There are workflow and validation rules that uses this field to determine processing path based on the Geography, Business Division and/or Region field(s) setting of the user.</description>
    <inlineHelpText>This field is required-There are workflow and validation rules that uses this field to determine processing path based on the Geography, Business Division and/or Region field(s) setting of the user.</inlineHelpText>
    <label>Region</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>AM</fullName>
            </value>
            <value>
                <fullName>AP</fullName>
            </value>
            <value>
                <fullName>EU</fullName>
            </value>
            <value>
                <fullName>GL</fullName>
            </value>
            <value>
                <fullName>LA</fullName>
            </value>
            <value>
                <fullName>N/A</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/POServiceTest.cls
@isTest
public inherited sharing class POServiceTest {
  
    @testSetup
    public static void createTestData(){
        
        User utausr = TestUtilsLocal.createTestUser('utaTest', True);    
        

        /*Territory2Model newTerritoryModel = TestUtilsLocal.createTerritory2Model('Zimmer', 'Zimmer', true);
        Territory2Type t2t = [Select Id,DeveloperName from Territory2Type where MasterLabel ='US Ortho'];
        Territory2 tr = TestUtilsLocal.createTerritory2('Test Terr','TestTerr',newTerritoryModel,t2t,true);

        // Add User to Territory
        UserTerritory2Association uta = new UserTerritory2Association(RoleInTerritory2 = 'Sales Manager',
                                                                          UserId = oppUser.Id,
                                                                          Territory2Id = tr.Id);*/

        
    }


    @isTest
    public static void afterDelete()
    { 
        User usr = [SELECT Id FROM User WHERE Name = 'utaTest'];
        Test.startTest();        
        System.runAs(usr){
            Territory2Model newTerritoryModel = TestUtilsLocal.createTerritory2Model('Zimmer', 'Zimmer', true);
            Territory2Type t2t = [Select Id,DeveloperName from Territory2Type where MasterLabel ='US Ortho'];
            Territory2 tr = TestUtilsLocal.createTerritory2('Test Terr','TestTerr',newTerritoryModel,t2t,true);
            
            UserTerritory2Association uta = new UserTerritory2Association(RoleInTerritory2 = 'Sales Manager',
                                                                          UserId = usr.Id,
                                                                          Territory2Id = tr.Id);
            INSERT uta;
            
            uta.RoleInTerritory2 = 'Sales Manager?';
            
            update uta;
            
            UserTerritory2Association uta1 = [SELECT Id, RoleInTerritory2 FROM UserTerritory2Association WHERE User.Name ='utaTest'];
            DELETE uta1;
        }
        Test.stopTest();
    }

    @isTest
    public static void createPurchaseOrder()
    {
        //User utausr = TestUtilsLocal.createTestUser('utaTest28', True); 
        User usr = [SELECT Id FROM User WHERE Name = 'utaTest'];   
        User usr1 = TestUtilsLocal.createTestSalesUser('utaTest1A', True);        
        User usr2 = TestUtilsLocal.createTestSalesUser('utaTest2A', True);
        Test.startTest();        
        System.runAs(usr){
            //Territory2Model newTerritoryModel = TestUtilsLocal.createTerritory2Model('Zimmer', 'Zimmer', true);
            Territory2Model newTerritoryModel = [Select Id from territory2Model where DeveloperName =: System.Label.Ortho_Territory_Model];
            
            Territory2Type t2t = [Select Id,DeveloperName from Territory2Type where MasterLabel ='US Ortho'];
            Territory2 tr = TestUtilsLocal.createTerritory2('Test Terr','TestTerr',newTerritoryModel,t2t,true);
            
            UserTerritory2Association uta = new UserTerritory2Association(RoleInTerritory2 = 'Sales Manager',
                                                                          UserId = usr1.Id,
                                                                          Territory2Id = tr.Id);
            UserTerritory2Association uta2 = new UserTerritory2Association(RoleInTerritory2 = 'Sales Manager',
                                                                          UserId = usr2.Id,
                                                                          Territory2Id = tr.Id);
            INSERT uta;
            Insert uta2;
            
            Purchase_Order__c po = new Purchase_Order__c();
            po.Bill_ID__c = '123456';
            po.ERP_Account_ID__c = '004910';
            po.ERP_Account_Name__c = 'BEAUFORT MEML HOSPITAL';
            po.ERP_Order__c = 'EE2283';
            po.PO_Status__c = '3';
            po.PO_Subtotal__c = 4000;
            po.Region__c = 'MIDWEST';
            po.Territory2_ID__c = tr.id;
            po.Territory2_Name__c = tr.Name;
        
            //Territory_Name__c
            //Territory_Name__c
            insert po;

            List<Purchase_Order__c> lstPOs = new List<Purchase_Order__c>();
            lstPOs.add(po);

            PO_Util.createPOSharesForPurchaseOrders(lstPOs);    

            po.Region__c = 'NORTHEAST';
            update po;

            List<Purchase_Order__c> ul = new List<Purchase_Order__c>();
            ul.add(po);
            PO_Util.createPOSharesForPurchaseOrders(ul);

            //Test.startTest();
            SchedulableContext sc = null;
			POCreateShareSchedulableJob testobj = new POCreateShareSchedulableJob();
            testObj.execute(sc);
            
            
            
            PODailyCreateShareJob obj = new PODailyCreateShareJob();
            DataBase.executeBatch(obj); 
            
            //DataBase.executeBatch(obj); 
            //Test.stopTest();
            
            //UserTerritory2Association uta1 = [SELECT Id, RoleInTerritory2 FROM UserTerritory2Association WHERE User.Name ='utaTest'];
            //DELETE uta1;
        }
        Test.stopTest();
    }
}