force-app/main/default/objects/Business_Plan__c/Business_Plan__c.object-meta.xml
<CustomObject>
    <label>Business Plan</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Business Plan Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Business Plans</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Market_Segmentation__c/Market_Segmentation__c.object-meta.xml
<CustomObject>
    <label>Market Segmentation</label>
    <nameField>
        <displayFormat>MS-{00000}</displayFormat>
        <label>Market Segmentation Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Market Segmentation</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Market_Segmentation__c/fields/Market_Procedures__c.field-meta.xml
<CustomField>
    <fullName>Market_Procedures__c</fullName>
    <label>IMS Covid Adj. Procedures 2019</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Market_Segmentation__c/fields/Product_Group__c.field-meta.xml
<CustomField>
    <fullName>Product_Group__c</fullName>
    <label>Product Group</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Bone Cement</fullName>
            </value>
            <value>
                <fullName>Extremities</fullName>
            </value>
            <value>
                <fullName>Shoulder</fullName>
            </value>
            <value>
                <fullName>Foot &amp; Ankle</fullName>
            </value>
            <value>
                <fullName>Sports Medicine</fullName>
            </value>
            <value>
                <fullName>Trauma</fullName>
            </value>
            <value>
                <fullName>Surgical</fullName>
            </value>
            <value>
                <fullName>Hips</fullName>
            </value>
            <value>
                <fullName>Primary Hips</fullName>
            </value>
            <value>
                <fullName>Revision Hips</fullName>
            </value>
            <value>
                <fullName>Knees</fullName>
            </value>
            <value>
                <fullName>Primary Knees</fullName>
            </value>
            <value>
                <fullName>Partial Knees</fullName>
            </value>
            <value>
                <fullName>Revision Knees</fullName>
            </value>
            <value>
                <fullName>Total Knees</fullName>
            </value>
            <value>
                <fullName>Total Hips</fullName>
            </value>
            <value>
                <fullName>Total</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Market_Segmentation__c/fields/Segementation__c.field-meta.xml
<CustomField>
    <fullName>Segementation__c</fullName>
    <label>Segementation</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Bronze</fullName>
            </value>
            <value>
                <fullName>Gold</fullName>
            </value>
            <value>
                <fullName>Green</fullName>
            </value>
            <value>
                <fullName>Platinum</fullName>
            </value>
            <value>
                <fullName>Silver</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Market_Segmentation__c/fields/Surgeon_Name__c.field-meta.xml
<CustomField>
    <fullName>Surgeon_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Surgeon Name</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Physician</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Market Segmentation</relationshipLabel>
    <relationshipName>Market_Segmentations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Market_Segmentation__c/fields/Zimmer_Biomet_Procedures__c.field-meta.xml
<CustomField>
    <fullName>Zimmer_Biomet_Procedures__c</fullName>
    <label>ZB PROCEDURES 2020</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Business_Plan__c.field-meta.xml
<CustomField>
    <fullName>Business_Plan__c</fullName>
    <formula>CASESAFEID(Product_Sales_Summary__r.Business_Plan__r.Id)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Business Plan</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Market_Procedures__c.field-meta.xml
<CustomField>
    <fullName>Market_Procedures__c</fullName>
    <label>Market Procedures</label>
    <precision>10</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Product_Group__c.field-meta.xml
<CustomField>
    <fullName>Product_Group__c</fullName>
    <label>Product Group</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Hips</fullName>
            </value>
            <value>
                <fullName>Knees</fullName>
            </value>
            <value>
                <fullName>Cement</fullName>
            </value>
            <value>
                <fullName>Extremities</fullName>
            </value>
            <value>
                <fullName>Sports Medicine</fullName>
            </value>
            <value>
                <fullName>Trauma</fullName>
            </value>
            <value>
                <fullName>Foot &amp; Ankle</fullName>
            </value>
            <value>
                <fullName>Surgical</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Product_Sales_Summary__c.field-meta.xml
<CustomField>
    <fullName>Product_Sales_Summary__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product Sales Summary</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Product_Sales_Summary__c.Business_Plan__r.Active__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Product_Sales_Summary__c</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunity</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Surgeon_Name__c.field-meta.xml
<CustomField>
    <fullName>Surgeon_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>This field is used to lookup your Surgeon account.</inlineHelpText>
    <label>Surgeon Name</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Physician, Physician(Processing)</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Opportunities (Surgeon Name)</relationshipLabel>
    <relationshipName>Opportunities2</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Product_Sales_Summary__c/Product_Sales_Summary__c.object-meta.xml
<CustomObject>
    <label>Product Sales Summary</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Product Sales Summary Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Product Sales Summary</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Product_Sales_Summary__c/fields/Business_Plan__c.field-meta.xml
<CustomField>
    <fullName>Business_Plan__c</fullName>
    <label>Business Plan</label>
    <referenceTo>Business_Plan__c</referenceTo>
    <relationshipLabel>Product Sales Summary</relationshipLabel>
    <relationshipName>Product_Sales_Summary</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Product_Sales_Summary__c/fields/Full_Year_Estimate__c.field-meta.xml
<CustomField>
    <fullName>Full_Year_Estimate__c</fullName>
    <formula>IF( Product_Group__c &lt;&gt; &apos;Total&apos;, 
Annual_Sales_Data__r.This_Year_YTD_Sales_Thru_Month__c +  This_Quarter_Projection__c, 
Business_Plan__r.BP_Sales_Plan__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Full Year Estimate</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Product_Sales_Summary__c/fields/Last_Year_Actual__c.field-meta.xml
<CustomField>
    <fullName>Last_Year_Actual__c</fullName>
    <formula>Annual_Sales_Data__r.Y_1_Sales__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Last Year Actual</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Product_Sales_Summary__c/fields/Sales_Plan__c.field-meta.xml
<CustomField>
    <fullName>Sales_Plan__c</fullName>
    <formula>Full_Year_Estimate__c + (Full_Year_Estimate__c *  Pricing_Impact__c ) + (Full_Year_Estimate__c *   Vol_Mix_Impact__c  ) +Opportunities__c  +  Risks__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Sales Plan</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Product_Sales_Summary__c/fields/This_Year_Target__c.field-meta.xml
<CustomField>
    <fullName>This_Year_Target__c</fullName>
    <formula>Annual_Sales_Data__r.Full_Year_Target__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>This Year Target</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Product_Sales_Summary__c/fields/Y_2_Sales__c.field-meta.xml
<CustomField>
    <fullName>Y_2_Sales__c</fullName>
    <formula>Annual_Sales_Data__r.Y_2_Sales__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Y-2 Sales</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Product_Sales_Summary__c/fields/Y_3_Sales__c.field-meta.xml
<CustomField>
    <fullName>Y_3_Sales__c</fullName>
    <formula>Annual_Sales_Data__r.Y_3_Sales__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Y-3 Sales</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/classes/ChartController.cls
public class ChartController {
   public Decimal min {get;set;}
   public Decimal SegMax { get; set; }
   public class Sale {
        public decimal amount {get; set;}       
        public String fieldNames {get; set; }
        sale(decimal amount, String fieldNames) {
            this.amount = amount;
            this.fieldNames = fieldNames;
        }
    }
  public class Data {
        public Integer MarketProcedure { get; set; }
        public Integer ZBProcedures { get; set; }
        public String Name { get; set; }
        public String SegmentName { get; set; }
        public Data(Integer MarketProcedure,Integer ZBProcedures, String Name, String SegmentName) {
            this.MarketProcedure = MarketProcedure;
            this.ZBProcedures = ZBProcedures;
            this.Name = Name;
            this.SegmentName = SegmentName;
        }
    }
    @AuraEnabled
    public Data[] getMktData(){
        String queryString ='';
        String businessPlanId = '';
        businessPlanId = ApexPages.currentPage().getParameters().get('bpid');
        queryString = ApexPages.currentPage().getParameters().get('productgroup');
        queryString = queryString == 'Foot Ankle'? 'Foot & Ankle' : queryString ; 
        Data[] MktData = new Data[]{};
        SegMax = 0;
        Set<ID> SurgeonID = new Set<ID>();
        for(Opportunity opps: [select Surgeon_Name__c from Opportunity where Product_Sales_Summary__r.Business_Plan__c = :businessPlanId
                               AND Product_Sales_Summary__r.Product_Group__c = :queryString]){
          SurgeonID.add(opps.Surgeon_Name__c);                               
        }
        
        for(Market_Segmentation__c segments : [SELECT Zimmer_Biomet_Procedures__c
                                                    , Market_Procedures__c
                                                   , Surgeon_Name__c
                                                   , Product_Group__c
                                                   , Surgeon_Name__r.name
                                                    , Segementation__c
                                             FROM  Market_Segmentation__c
                                             where  Surgeon_Name__c 
                                             IN    :SurgeonID
                                             AND  Product_Group__c = :queryString]){
            if(SegMax < segments.Market_Procedures__c) SegMax = segments.Market_Procedures__c + 100;
          MktData.add(new Data((Integer)segments.Market_Procedures__c
                                , (Integer)segments.Zimmer_Biomet_Procedures__c
                                , segments.Surgeon_Name__r.name
                                , segments.Segementation__c));                                                     
        }
        return MktData ;
    }
    public Sale[] getSales() {
        Sale[] Sales = new Sale[] {};
        String queryString ='';
        String businessPlanId = '';
        businessPlanId = ApexPages.currentPage().getParameters().get('bpid');
        queryString = ApexPages.currentPage().getParameters().get('productgroup');
        queryString = queryString == 'Foot Ankle'? 'Foot & Ankle' : queryString ; 
        for (Product_Sales_Summary__c pss : [
                select
                        Y_3_Sales__c,
                        Y_2_Sales__c, 
                        Last_Year_Actual__c ,
                        This_Year_Target__c  ,
                        Full_Year_Estimate__c , 
                        Sales_Plan__c ,
                        Business_Plan__c,
                        Product_Group__c
                from Product_Sales_Summary__c
                where  Business_Plan__c = :businessPlanId
                AND Product_Group__c = :queryString]) {
            IF(min == null || min <=0 ){
                min = pss.Last_Year_Actual__c - 1000000;
            }
            Sales.add(new Sale(
                    (decimal) pss.get('Y_3_Sales__c'),
                    '2017 Sales'
            ));
            Sales.add(new Sale(
                    (decimal) pss.get('Y_2_Sales__c'),
                    '2018 Sales'
            ));
            Sales.add(new Sale(
                    (decimal) pss.get('Last_Year_Actual__c'),
                    'Last Year Actual'
            ));
            Sales.add(new Sale(
                    (decimal) pss.get('This_Year_Target__c'),
                    'This Year Target'
            ));
            Sales.add(new Sale(
                    (decimal) pss.get('Full_Year_Estimate__c'),
                    'Full Year Estimate'
            ));
            Sales.add(new Sale(
                    (decimal) pss.get('Sales_Plan__c'),
                    'Sales Plan'
            ));
        }
        return Sales;
    }
}