force-app/main/default/objects/Business_Plan__c/Business_Plan__c.object-meta.xml
<CustomObject>
    <label>Business Plan</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Business Plan Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Business Plans</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Executive_Summary__c/Executive_Summary__c.object-meta.xml
<CustomObject>
    <label>Executive Summary</label>
    <nameField>
        <displayFormat>ES-{00000}</displayFormat>
        <label>Executive Summary Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Executive Summary</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Executive_Summary__c/fields/Business_Plan__c.field-meta.xml
<CustomField>
    <fullName>Business_Plan__c</fullName>
    <label>Business Plan</label>
    <referenceTo>Business_Plan__c</referenceTo>
    <relationshipLabel>Executive Summary</relationshipLabel>
    <relationshipName>Executive_Summary</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Executive_Summary__c/fields/Executive_Summary_fld__c.field-meta.xml
<CustomField>
    <fullName>Executive_Summary_fld__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Executive Summary</label>
    <length>131072</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/Executive_Summary__c/fields/Question_Type__c.field-meta.xml
<CustomField>
    <fullName>Question_Type__c</fullName>
    <label>Question Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Market statistics</fullName>
            </value>
            <value>
                <fullName>Competitive landscape</fullName>
            </value>
            <value>
                <fullName>Account statistics and implications</fullName>
            </value>
            <value>
                <fullName>Surgeon / Hospital Alignment trends update</fullName>
            </value>
            <value>
                <fullName>Organization</fullName>
            </value>
            <value>
                <fullName>People</fullName>
            </value>
            <value>
                <fullName>Processes</fullName>
            </value>
            <value>
                <fullName>Overall Assessment</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/businessPlanExecutiveSummary.cls
public with sharing class businessPlanExecutiveSummary {
    public Executive_Summary__c ExeSum {get;set;}
    @AuraEnabled (cacheable=true)
    public static Executive_Summary__c getActiveExecutiveSummary(string bpid){
        Executive_Summary__c exsummary = [select    id
                                                    , Question_Type__c
                                                    , IsActive__c 
                                                    , Executive_Summary_fld__c 
                                                    , Business_Plan__c
                                        from        Executive_Summary__c
                                        where       Business_Plan__c = :bpid
                                        and         IsActive__c = true 
                                        LIMIT 1];
        return exsummary; 
    } 
    public businessPlanExecutiveSummary(ApexPages.StandardController controller){
        string bpid ;
        bpid =  ApexPages.currentPage().getParameters().get('id');
        system.debug('BPid--->>'+bpid);
        ExeSum = [select    id
                                                    , Question_Type__c
                                                    , IsActive__c 
                                                    , Executive_Summary_fld__c 
                                                    , Business_Plan__c
                                        from        Executive_Summary__c
                                        where       Business_Plan__c = :bpid
                                        and         IsActive__c = true 
                                        LIMIT 1];
         system.debug('ExeSum--->>'+ExeSum);
    } 
}