force-app/main/default/objects/Business_Plan__c/Business_Plan__c.object-meta.xml
<CustomObject>
    <label>Business Plan</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Business Plan Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Business Plans</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Opportunity/fields/Business_Plan__c.field-meta.xml
<CustomField>
    <fullName>Business_Plan__c</fullName>
    <formula>CASESAFEID(Product_Sales_Summary__r.Business_Plan__r.Id)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Business Plan</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Product_Sales_Summary__c.field-meta.xml
<CustomField>
    <fullName>Product_Sales_Summary__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product Sales Summary</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Product_Sales_Summary__c.Business_Plan__r.Active__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Product_Sales_Summary__c</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunity</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Product_Sales_Summary__c/Product_Sales_Summary__c.object-meta.xml
<CustomObject>
    <label>Product Sales Summary</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Product Sales Summary Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Product Sales Summary</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Product_Sales_Summary__c/fields/Business_Plan__c.field-meta.xml
<CustomField>
    <fullName>Business_Plan__c</fullName>
    <label>Business Plan</label>
    <referenceTo>Business_Plan__c</referenceTo>
    <relationshipLabel>Product Sales Summary</relationshipLabel>
    <relationshipName>Product_Sales_Summary</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/BusinessPlanRemoveOpportunities.cls
public class BusinessPlanRemoveOpportunities {
    public BusinessPlanRemoveOpportunities() {

    }

    public PageReference upload() {
        ApexPages.getMessages().clear();
        
        try {
            List<String> parentIds = ApexPages.currentPage().getParameters().get('id').split(',');
            List<Opportunity> updateOpp = new List<Opportunity>();
            for (Opportunity Opp : [SELECT ID, Product_Sales_Summary__c from Opportunity WHERE ID in :parentIds]) {
                opp.Product_Sales_Summary__c = null ; 
                updateOpp.add(Opp);
            }       
            if (updateOpp.size()>0){
                update updateOpp ; 

            }

            Apexpages.addMessage(new ApexPages.Message(ApexPages.SEVERITY.CONFIRM, 'update successful.'));
            pagereference page = new PageReference ('/lightning/o/Business_Plan__c/list?filterName=Recent');
            return page ;
        } catch(Exception ex) {
            Apexpages.addMessage(new ApexPages.Message(ApexPages.SEVERITY.ERROR, 'There was an error while updating a record.'));
        }   

        return null;
    }
}