force-app/main/default/objects/Segmentation_Breakout__c/Segmentation_Breakout__c.object-meta.xml
<CustomObject>
    <label>Segmentation Breakout</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Segmentation Breakout  Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Segmentation Breakouts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Segmentation_Breakout__c/fields/Segmentation_Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Segmentation_Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Segmentation Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Segmentation Breakouts</relationshipLabel>
    <relationshipName>Segmentation_Breakout_Opps</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Segmentation_Breakout__c/fields/Total_Revenue__c.field-meta.xml
<CustomField>
    <fullName>Total_Revenue__c</fullName>
    <formula>IF(ISBLANK( Contracted_Growth_Amount__c), Case_Quantity__c  *  Price_Point__c, Contracted_Growth_Amount__c)</formula>
    <label>Total Revenue</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/classes/SegBreakoutSummary.cls
public with sharing class SegBreakoutSummary {
    public Decimal totalRevenue { get;  set;}
    
    public SegBreakoutSummary(ApexPages.StandardController controller) {
        
        String currentRecordId;
        currentRecordId  = ApexPages.CurrentPage().getparameters().get('id');
        //System.debug('Current Opportunity in SegBreakoutSummary :' + currentRecordId);
        AggregateResult[] groupedResults = [SELECT SUM(Total_Revenue__c)ttlRev FROM Segmentation_Breakout__c where Segmentation_Opportunity__c = :currentRecordId];
        
        if (!groupedResults.isEmpty()) this.totalRevenue = (Decimal)groupedResults.get(0).get('ttlRev');
        System.debug('Total Revenue for Oppoprtunity : '+ currentRecordId + ' is '+totalRevenue);
    }
}