force-app/main/default/objects/Competitor__c/Competitor__c.object-meta.xml
<CustomObject>
    <label>Competitor-Global</label>
    <nameField>
        <displayFormat>CM-{YYYY}{MM}-{000000}</displayFormat>
        <label>Competitor ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Competitors-Global</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Competitor__c/fields/Competitor__c.field-meta.xml
<CustomField>
    <fullName>Competitor__c</fullName>
    <label>Competitor</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>AAP</fullName>
            </value>
            <value>
                <fullName>Acumed</fullName>
            </value>
            <value>
                <fullName>Aecuaos</fullName>
            </value>
            <value>
                <fullName>Aesculap</fullName>
            </value>
            <value>
                <fullName>Ai-medic</fullName>
            </value>
            <value>
                <fullName>Alpha Consulting Group</fullName>
            </value>
            <value>
                <fullName>Arthrex</fullName>
            </value>
            <value>
                <fullName>Ascension</fullName>
            </value>
            <value>
                <fullName>ASDM</fullName>
            </value>
            <value>
                <fullName>AustoFix</fullName>
            </value>
            <value>
                <fullName>Axomed</fullName>
            </value>
            <value>
                <fullName>B.Braun</fullName>
            </value>
            <value>
                <fullName>Biomet</fullName>
            </value>
            <value>
                <fullName>Brehm</fullName>
            </value>
            <value>
                <fullName>Conformis</fullName>
            </value>
            <value>
                <fullName>Corin</fullName>
            </value>
            <value>
                <fullName>DePuy</fullName>
            </value>
            <value>
                <fullName>DeSoutter</fullName>
            </value>
            <value>
                <fullName>DJO/Encore</fullName>
            </value>
            <value>
                <fullName>Emergo Asia Pacific Pty Ltd</fullName>
            </value>
            <value>
                <fullName>Eska</fullName>
            </value>
            <value>
                <fullName>Exactech</fullName>
            </value>
            <value>
                <fullName>GE Healthcare Performance Solutions</fullName>
            </value>
            <value>
                <fullName>Global</fullName>
            </value>
            <value>
                <fullName>Globus Medical</fullName>
            </value>
            <value>
                <fullName>Health Care Surgical</fullName>
            </value>
            <value>
                <fullName>Hunter &amp; Associates</fullName>
            </value>
            <value>
                <fullName>Implantcast</fullName>
            </value>
            <value>
                <fullName>Implantindustries</fullName>
            </value>
            <value>
                <fullName>JMM</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/BP_Target__c.field-meta.xml
<CustomField>
    <fullName>BP_Target__c</fullName>
    <defaultValue>false</defaultValue>
    <label>BP Target</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Competitor__c.field-meta.xml
<CustomField>
    <fullName>Competitor__c</fullName>
    <inlineHelpText>This is the competitor you are going up against for this sales plan.</inlineHelpText>
    <label>Primary Competitor</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>3di</fullName>
            </value>
            <value>
                <fullName>AAP</fullName>
            </value>
            <value>
                <fullName>Acumed</fullName>
            </value>
            <value>
                <fullName>Aecuaos</fullName>
            </value>
            <value>
                <fullName>Aesculap</fullName>
            </value>
            <value>
                <fullName>Ai-medic</fullName>
            </value>
            <value>
                <fullName>Alpha Consulting Group</fullName>
            </value>
            <value>
                <fullName>AMPLITUDE SAS</fullName>
            </value>
            <value>
                <fullName>AQ Implants</fullName>
            </value>
            <value>
                <fullName>Arthrex</fullName>
            </value>
            <value>
                <fullName>Arthrosurface</fullName>
            </value>
            <value>
                <fullName>ARTIQO</fullName>
            </value>
            <value>
                <fullName>Ascension</fullName>
            </value>
            <value>
                <fullName>Axomed</fullName>
            </value>
            <value>
                <fullName>B.Braun</fullName>
            </value>
            <value>
                <fullName>Brehm</fullName>
            </value>
            <value>
                <fullName>Conformis</fullName>
            </value>
            <value>
                <fullName>ConMed</fullName>
            </value>
            <value>
                <fullName>Corentec</fullName>
            </value>
            <value>
                <fullName>Corin</fullName>
            </value>
            <value>
                <fullName>Crossroads</fullName>
            </value>
            <value>
                <fullName>CrossRoads Medical</fullName>
            </value>
            <value>
                <fullName>DePuy</fullName>
            </value>
            <value>
                <fullName>DePuy Mitek</fullName>
            </value>
            <value>
                <fullName>DePuy Synthes</fullName>
            </value>
            <value>
                <fullName>DeSoutter</fullName>
            </value>
            <value>
                <fullName>DIZG</fullName>
            </value>
            <value>
                <fullName>DJO</fullName>
            </value>
            <value>
                <fullName>DJO Surgical</fullName>
            </value>
            <value>
                <fullName>Encore</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Drive_Defend__c.field-meta.xml
<CustomField>
    <fullName>Drive_Defend__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Drive &amp; Defend</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Product_Group__c.field-meta.xml
<CustomField>
    <fullName>Product_Group__c</fullName>
    <label>Product Group</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Hips</fullName>
            </value>
            <value>
                <fullName>Knees</fullName>
            </value>
            <value>
                <fullName>Cement</fullName>
            </value>
            <value>
                <fullName>Extremities</fullName>
            </value>
            <value>
                <fullName>Sports Medicine</fullName>
            </value>
            <value>
                <fullName>Trauma</fullName>
            </value>
            <value>
                <fullName>Foot &amp; Ankle</fullName>
            </value>
            <value>
                <fullName>Surgical</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Surgeon_Name__c.field-meta.xml
<CustomField>
    <fullName>Surgeon_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>This field is used to lookup your Surgeon account.</inlineHelpText>
    <label>Surgeon Name</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Physician, Physician(Processing)</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Opportunities (Surgeon Name)</relationshipLabel>
    <relationshipName>Opportunities2</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/MobileOpptyFilterController.cls
public with sharing class MobileOpptyFilterController {

  @AuraEnabled(cacheable=false)  
  public static List<sobject> findRecords(String searchKey, String objectName, String recordTypeId) {  
    string searchText = '\'' + String.escapeSingleQuotes(searchKey) + '%\'';  
    string rText = '';
    string query = '';
    //System.debug('In find Records : '+searchKey+ ' Object: '+objectName);
    query = 'SELECT Id, Name FROM ' +objectName+ ' WHERE Name LIKE '+searchText+' LIMIT 6';
    
    if (objectName == 'account')
      query = 'SELECT Id, Name FROM Account WHERE Name LIKE '+'\'%' + String.escapeSingleQuotes(searchKey) + '%\'' +' and RecordTypeId = \'012800000002AW5AAM\' LIMIT 6';

    if (objectName == 'Surgeon')
      query = 'SELECT Id, Name FROM Account WHERE Name LIKE '+'\'%' + String.escapeSingleQuotes(searchKey) + '%\'' +' and RecordTypeId = \'012800000002C4gAAE\' LIMIT 6';

    if (objectName == 'Territory2ForOpportunity')
      query = 'SELECT Id, Name FROM Territory2 WHERE Name LIKE '+'\'%' + String.escapeSingleQuotes(searchKey) + '%\'' +' and Name like \'%OPPORTUNITY%\' LIMIT 6';

      if (objectName == 'User')
      query = 'SELECT Id, Name FROM User WHERE (FirstName LIKE '+'\'%' + String.escapeSingleQuotes(searchKey) + '%\' OR LastName LIKE '+'\'%' + String.escapeSingleQuotes(searchKey) + '%\') LIMIT 6';

    System.debug('The Query '+query);

    return Database.query(query);
  }  

  @AuraEnabled(cacheable=true)  
  public static List<String> getUSOrthoRecordTypeIds() {  
    
    Map<String, String> recordTypeMap = Ortho_Util.getUSOrthoOpptyRecordTypes();

    Set<String> orthoRecordTypeSet = recordTypeMap.keySet();
    
    return (new List<String>(orthoRecordTypeSet));
  }

  @AuraEnabled(cacheable=true)  
  public static List<Opportunity> searchOpportunities(String acctId, String srgnId, String prdGrpId,String teamId, String cmptrId, String ownerId, Boolean bpTrgt, Boolean drvDfnd) {  
    //string searchText = '\'' + String.escapeSingleQuotes(searchKey) + '%\'';
    
    System.debug('Finding Opportunities for Filters Account :'+acctId) ;
    
    Integer noOfFilters = 0;
    String recordTypeStr = '';

    /*Map<String, String> recordTypeMap = Ortho_Util.getUSOrthoOpptyRecordTypes();    
    Set<String> orthoRecordTypeSet = recordTypeMap.keySet();
    
    Integer i = 1;
    for (String s : orthoRecordTypeSet) 
    {
      recordTypeStr = recordTypeStr + '\''+s+'\'';
      if (i != orthoRecordTypeSet.size() ) {
      recordTypeStr = recordTypeStr + ',';
      }
      i++;
    }*/
    
    string query = 'SELECT Id, Name, Account.Name, StageName, Surgeon_Name__r.Name, Product_Group__c, Owner.Name, Territory2.Name, RecordType.Name, CloseDate FROM Opportunity WHERE ';

    /*if (String.isNotBlank(recordTypeStr)) {
      query = query + ' RecordTypeId in ('+recordTypeStr+ ')';
      noOfFilters++;
    }*/

    if (String.isNotBlank(acctId)) {
      if (noOfFilters > 0)
        query = query + ' and ';
        query = query + 'AccountId=\''+acctId+'\'';
        noOfFilters++;
    }

    if (String.isNotBlank(srgnId)){
      if (noOfFilters > 0)
        query = query + ' and ';
        query = query + 'Surgeon_Name__c =\''+srgnId+'\'';
    noOfFilters++;
    }

    if (String.isNotBlank(prdGrpId)){      
      String prd = prdGrpId.replace('[','').replace(']','').replace('"','\'');
      if (String.isNotBlank(prd))
      {
          if (noOfFilters > 0)
            query = query + ' and ';
        query = query + 'RecordTypeId in ('+prd+')';
        noOfFilters++;
      }
    }

    if (String.isNotBlank(teamId)){
      if (noOfFilters > 0)
        query = query + ' and ';
    query = query + 'Territory2Id=\''+teamId+'\'';
    noOfFilters++;
    }

    /*if (String.isNotBlank(cmptrId)){
      if (noOfFilters > 0)
        query = query + ' and ';
    query = query + 'Competitor__c=\''+cmptrId+'\'';
    noOfFilters++;
    }*/

    if (String.isNotBlank(cmptrId)){      
      String cmptr = cmptrId.replace('[','').replace(']','').replace('"','\'');
      if (String.isNotBlank(cmptr))
      {
          if (noOfFilters > 0)
            query = query + ' and ';
        query = query + 'Competitor__c in ('+cmptr+')';
        noOfFilters++;
      }
    }

    if (String.isNotBlank(ownerId)){
      if (noOfFilters > 0)
        query = query + ' and ';
    query = query + 'OwnerId=\''+ownerId+'\'';
    noOfFilters++;
    }

    //if (String.isNotBlank(bpTrgt)){
    if (bpTrgt==true) {
      if (noOfFilters > 0)
        query = query + ' and ';
    query = query + 'BP_Target__c='+bpTrgt;
    noOfFilters++;
    }

    //if (String.isNotBlank(drvDfnd)){
    if (drvDfnd==true) {
      if (noOfFilters > 0)
        query = query + ' and ';
    query = query + 'Drive_Defend__c='+drvDfnd;
    noOfFilters++;
    }

    query = query + ' Order by CloseDate desc NULLS FIRST LIMIT 500';
    System.debug('The Query '+query);

    /*query = 'SELECT Id, Name, StageName FROM Opportunity WHERE ';
    if (String.isNotBlank(acctId)) {
      query = query + 'AccountId=\''+acctId+'\'';
      noOfFilters++;
      }*/
    return Database.query(query);  
  }  
}