force-app/main/default/objects/Competitor__c/Competitor__c.object-meta.xml
<CustomObject>
    <label>Competitor-Global</label>
    <nameField>
        <displayFormat>CM-{YYYY}{MM}-{000000}</displayFormat>
        <label>Competitor ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Competitors-Global</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Competitor__c/fields/Competitor__c.field-meta.xml
<CustomField>
    <fullName>Competitor__c</fullName>
    <label>Competitor</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>AAP</fullName>
            </value>
            <value>
                <fullName>Acumed</fullName>
            </value>
            <value>
                <fullName>Aecuaos</fullName>
            </value>
            <value>
                <fullName>Aesculap</fullName>
            </value>
            <value>
                <fullName>Ai-medic</fullName>
            </value>
            <value>
                <fullName>Alpha Consulting Group</fullName>
            </value>
            <value>
                <fullName>Arthrex</fullName>
            </value>
            <value>
                <fullName>Ascension</fullName>
            </value>
            <value>
                <fullName>ASDM</fullName>
            </value>
            <value>
                <fullName>AustoFix</fullName>
            </value>
            <value>
                <fullName>Axomed</fullName>
            </value>
            <value>
                <fullName>B.Braun</fullName>
            </value>
            <value>
                <fullName>Biomet</fullName>
            </value>
            <value>
                <fullName>Brehm</fullName>
            </value>
            <value>
                <fullName>Conformis</fullName>
            </value>
            <value>
                <fullName>Corin</fullName>
            </value>
            <value>
                <fullName>DePuy</fullName>
            </value>
            <value>
                <fullName>DeSoutter</fullName>
            </value>
            <value>
                <fullName>DJO/Encore</fullName>
            </value>
            <value>
                <fullName>Emergo Asia Pacific Pty Ltd</fullName>
            </value>
            <value>
                <fullName>Eska</fullName>
            </value>
            <value>
                <fullName>Exactech</fullName>
            </value>
            <value>
                <fullName>GE Healthcare Performance Solutions</fullName>
            </value>
            <value>
                <fullName>Global</fullName>
            </value>
            <value>
                <fullName>Globus Medical</fullName>
            </value>
            <value>
                <fullName>Health Care Surgical</fullName>
            </value>
            <value>
                <fullName>Hunter &amp; Associates</fullName>
            </value>
            <value>
                <fullName>Implantcast</fullName>
            </value>
            <value>
                <fullName>Implantindustries</fullName>
            </value>
            <value>
                <fullName>JMM</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Competitor__c/fields/Sales_Plan__c.field-meta.xml
<CustomField>
    <fullName>Sales_Plan__c</fullName>
    <inlineHelpText>Associate the competitor with a sales plan</inlineHelpText>
    <label>Sales Plan</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipName>Competitors</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Competitor__c.field-meta.xml
<CustomField>
    <fullName>Competitor__c</fullName>
    <inlineHelpText>This is the competitor you are going up against for this sales plan.</inlineHelpText>
    <label>Primary Competitor</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>3di</fullName>
            </value>
            <value>
                <fullName>AAP</fullName>
            </value>
            <value>
                <fullName>Acumed</fullName>
            </value>
            <value>
                <fullName>Aecuaos</fullName>
            </value>
            <value>
                <fullName>Aesculap</fullName>
            </value>
            <value>
                <fullName>Ai-medic</fullName>
            </value>
            <value>
                <fullName>Alpha Consulting Group</fullName>
            </value>
            <value>
                <fullName>AMPLITUDE SAS</fullName>
            </value>
            <value>
                <fullName>AQ Implants</fullName>
            </value>
            <value>
                <fullName>Arthrex</fullName>
            </value>
            <value>
                <fullName>Arthrosurface</fullName>
            </value>
            <value>
                <fullName>ARTIQO</fullName>
            </value>
            <value>
                <fullName>Ascension</fullName>
            </value>
            <value>
                <fullName>Axomed</fullName>
            </value>
            <value>
                <fullName>B.Braun</fullName>
            </value>
            <value>
                <fullName>Brehm</fullName>
            </value>
            <value>
                <fullName>Conformis</fullName>
            </value>
            <value>
                <fullName>ConMed</fullName>
            </value>
            <value>
                <fullName>Corentec</fullName>
            </value>
            <value>
                <fullName>Corin</fullName>
            </value>
            <value>
                <fullName>Crossroads</fullName>
            </value>
            <value>
                <fullName>CrossRoads Medical</fullName>
            </value>
            <value>
                <fullName>DePuy</fullName>
            </value>
            <value>
                <fullName>DePuy Mitek</fullName>
            </value>
            <value>
                <fullName>DePuy Synthes</fullName>
            </value>
            <value>
                <fullName>DeSoutter</fullName>
            </value>
            <value>
                <fullName>DIZG</fullName>
            </value>
            <value>
                <fullName>DJO</fullName>
            </value>
            <value>
                <fullName>DJO Surgical</fullName>
            </value>
            <value>
                <fullName>Encore</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/PreventPrimaryDeletionTest.cls
//****************************************************************************************************
//    Name: PreventPrimaryDeletionTest
//==============================================================================================
//    Author: Prateekshit Malhotra
//==============================================================================================
//    Create Date: 23-May-2012     
//==============================================================================================
//    Purpose: This is Test Class for PreventPrimaryDeletion Trigger.
//==============================================================================================
  
//******************************************************************************************************/

@isTest
private class PreventPrimaryDeletionTest{
            
            Public Static Opportunity testOpportunity;
            Public Static Competitor__c testCompetitor;
            
            Public Static void createData(){
            
            testOpportunity= new Opportunity();
            testOpportunity.Name = 'a';
            testOpportunity.CloseDate = Date.today();
            testOpportunity.StageName = 'Prospecting';
            testOpportunity.Competitor__c = 'A';
            insert testOpportunity;
            
            testCompetitor= new Competitor__c();
            testCompetitor.Competitor__c = 'AAP';
            testCompetitor.Sales_Plan__c = testOpportunity.id;
            insert testCompetitor;
            }
            
            public Static testmethod void primaryDeletion(){
            test.startTest();
            createData();
            delete testCompetitor;
            test.stopTest();
            }
            }