force-app/main/default/objects/Ortho_App_Favorites__c/Ortho_App_Favorites__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>Ortho App Favorites</label>
</CustomObject>

force-app/main/default/objects/Ortho_App_Favorites__c/fields/App_ID__c.field-meta.xml
<CustomField>
    <fullName>App_ID__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>App ID</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Ortho_App_Favorites__c/fields/Is_Favorite__c.field-meta.xml
<CustomField>
    <fullName>Is_Favorite__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is Favorite?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Ortho_App_Favorites__c/fields/User_ID__c.field-meta.xml
<CustomField>
    <fullName>User_ID__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>User_ID</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/Ortho_MyAppsControllerTest.cls
/**
* @author Appirio Inc.
* @date March, 2020
*
* @group Opportunity
*
* @description Test Class for Ortho_ListviewSelector Controller
*/
@isTest
public class Ortho_MyAppsControllerTest {
    
    @testSetup
    public static void createTestData(){
        User appUser = TestUtilsLocal.createTestUser('appUser',true);
        system.assertNotEquals(null, appUser.id);
        
        //get App details
        AppMenuItem objAppMenuItem = [SELECT Id, Name, Label FROM AppMenuItem Limit 1];
        // Add custom setting
        Ortho_App_Favorites__c objApp= new Ortho_App_Favorites__c(Name ='CustomSetting',User_Id__c = appUser.id,Is_Favorite__c = true,App_Id__c = objAppMenuItem.id);
        insert objApp;
        
    }
    
    @istest
    static void testUserApp(){
        User appUser = [Select Id from User where name='appUser'];
        AppMenuItem objAppMenuItem = [SELECT Id, Name, Label FROM AppMenuItem Limit 1];
        Test.startTest();
        //Run as User
        System.runAs(appUser) {
            Ortho_MyAppsController.getApps();
            Ortho_MyAppsController.setFavorite(objAppMenuItem.id,objAppMenuItem.Name,true);
        }
        Ortho_MyAppsController.OrthoApps omac = new Ortho_MyAppsController.OrthoApps();
        omac.addFavorite(objAppMenuItem);
        Ortho_MyAppsController.setFavorite(objAppMenuItem.id,objAppMenuItem.Name,true);
        Test.stopTest();
    }
    
}