force-app/main/default/objects/Ortho_App_Favorites__c/Ortho_App_Favorites__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>Ortho App Favorites</label>
</CustomObject>

force-app/main/default/objects/Ortho_App_Favorites__c/fields/App_ID__c.field-meta.xml
<CustomField>
    <fullName>App_ID__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>App ID</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Ortho_App_Favorites__c/fields/Is_Favorite__c.field-meta.xml
<CustomField>
    <fullName>Is_Favorite__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is Favorite?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Ortho_App_Favorites__c/fields/User_ID__c.field-meta.xml
<CustomField>
    <fullName>User_ID__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>User_ID</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Ortho_Mobile_Setting__mdt/Ortho_Mobile_Setting__mdt.object-meta.xml
<CustomObject>
    <label>Ortho Mobile Setting</label>
    <pluralLabel>Ortho Mobile Settings</pluralLabel>
</CustomObject>

force-app/main/default/objects/Ortho_Mobile_Setting__mdt/fields/Setting_Type__c.field-meta.xml
<CustomField>
    <fullName>Setting_Type__c</fullName>
    <label>Setting Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Communication Group</fullName>
                <default>true</default>
                <label>Communication Group</label>
            </value>
            <value>
                <fullName>App</fullName>
            </value>
            <value>
                <fullName>Trigger</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Ortho_Mobile_Setting__mdt/fields/Test_Context__c.field-meta.xml
<CustomField>
    <fullName>Test_Context__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Test Context</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Ortho_Mobile_Setting__mdt/fields/Trigger_Context__c.field-meta.xml
<CustomField>
    <fullName>Trigger_Context__c</fullName>
    <description>Triggers only. Context for the Trigger Setting</description>
    <label>Trigger Context</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>User</fullName>
                <default>true</default>
                <label>User</label>
            </value>
            <value>
                <fullName>Profile</fullName>
            </value>
            <value>
                <fullName>All</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Ortho_Mobile_Setting__mdt/fields/Trigger_Disabled__c.field-meta.xml
<CustomField>
    <fullName>Trigger_Disabled__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Only used for trigger settings. Select to Disable Trigger for Context</description>
    <label>Trigger Disabled</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Ortho_Mobile_Setting__mdt/fields/Trigger_Name__c.field-meta.xml
<CustomField>
    <fullName>Trigger_Name__c</fullName>
    <description>Name of Trigger</description>
    <label>Trigger Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Ortho_Mobile_Setting__mdt/fields/Value__c.field-meta.xml
<CustomField>
    <fullName>Value__c</fullName>
    <description>Setting Value</description>
    <label>Value</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Ortho_Sales_General_Setting__mdt/Ortho_Sales_General_Setting__mdt.object-meta.xml
<CustomObject>
    <description>This custom metadata holds some generic settings value for ortho sales division for eg. Opportunity record types for Ortho</description>
    <label>Ortho Sales General Setting</label>
    <pluralLabel>Ortho Sales General Settings</pluralLabel>
</CustomObject>

force-app/main/default/objects/Ortho_Sales_General_Setting__mdt/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>General</fullName>
                <default>true</default>
                <label>General</label>
            </value>
            <value>
                <fullName>Product Role Mapping</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/Ortho_SettingsService.cls
/**
 * @author Appirio
 * @date Feb, 2020
 *
 * @description Contains methods to return records of Ortho Metadata Records based on requirement.
 */


public with sharing class Ortho_SettingsService {
    
    /**
    * @description Returns ortho mobile settings by type.
    */


    public static List<Ortho_Mobile_Setting__mdt> getSettingByType(String type){
        if(Test.isRunningTest()){
             Ortho_Mobile_Setting__mdt[] orthoMobileSettings = [SELECT MasterLabel, QualifiedApiName, Setting_Type__c ,Value__c, Trigger_Name__c, Trigger_Context__c, Trigger_Disabled__c FROM Ortho_Mobile_Setting__mdt where Setting_Type__c = :type
                                                          AND Test_Context__c = True];
        	return orthoMobileSettings;
        }
        
        Ortho_Mobile_Setting__mdt[] orthoMobileSettings = [SELECT MasterLabel, QualifiedApiName, Setting_Type__c ,Value__c, Trigger_Name__c, Trigger_Context__c, Trigger_Disabled__c FROM Ortho_Mobile_Setting__mdt where Setting_Type__c = :type
                                                          AND Test_Context__c = False];
        return orthoMobileSettings;
    }
    
    /**
    * @description Returns all the app favorites by user.
    */

    public static List<Ortho_App_Favorites__c> getAppFavoritesByUser(Id userId){
        List<Ortho_App_Favorites__c> appFavorites = [Select id, App_Id__c, User_Id__c,Is_Favorite__c from Ortho_App_Favorites__c where User_Id__c =: userId and Is_Favorite__c = true];
        return appFavorites;
    }
    
    /**
    * @description Returns all the app favorites by user and app.
    */
    
    public static List<Ortho_App_Favorites__c> getAppFavoritesByUserAndApp(Id userId, String appId){
        List<Ortho_App_Favorites__c> appFavorites = [Select id, App_Id__c, User_Id__c,Is_Favorite__c from Ortho_App_Favorites__c where User_Id__c =: userId and App_Id__c =: appId];
        return appFavorites;
    }
    
    
    /**
    * @description Returns all the general Settings metadata values by Name
    */
    public static String getGeneralSettingValueByName(String settingName){
        Ortho_Sales_General_Setting__mdt[] orthoSalesGeneralSettings = [SELECT MasterLabel, Value__c FROM
            Ortho_Sales_General_Setting__mdt WHERE DeveloperName = :settingName];
        String value = '';
        if(!orthoSalesGeneralSettings.isEmpty()){
            value = orthoSalesGeneralSettings[0].Value__c;
        }
        return value;
    }
    
     /**
    * @description Returns all the general Settings metadata values by Type
    */
    
    public static Map<String,String> getGeneralSettingValueByType(String typeName){
        Map<String,String> oppRecordTypeMapByProduct = new Map<String,String>();
        Ortho_Sales_General_Setting__mdt[] orthoSalesGeneralSettings = [SELECT MasterLabel, Value__c FROM
                                                                        Ortho_Sales_General_Setting__mdt WHERE Type__c = :typeName];


        String recTypeid;

        for(Ortho_Sales_General_Setting__mdt os: orthoSalesGeneralSettings){
            if(typeName == Ortho_Constants.PRODUCT_ROLE_MAPPING){
                recTypeid = Schema.SObjectType.Opportunity.getRecordTypeInfosByDeveloperName().get(os.MasterLabel).getRecordTypeId();
                oppRecordTypeMapByProduct.put(recTypeid, os.Value__c);
            }else{
                oppRecordTypeMapByProduct.put(os.MasterLabel, os.Value__c);
            }
        }


        return oppRecordTypeMapByProduct;
       
        
    }

}