force-app/main/default/objects/Ortho_App_Favorites__c/Ortho_App_Favorites__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>Ortho App Favorites</label>
</CustomObject>

force-app/main/default/objects/Ortho_App_Favorites__c/fields/App_ID__c.field-meta.xml
<CustomField>
    <fullName>App_ID__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>App ID</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Ortho_App_Favorites__c/fields/Is_Favorite__c.field-meta.xml
<CustomField>
    <fullName>Is_Favorite__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is Favorite?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Ortho_App_Favorites__c/fields/User_ID__c.field-meta.xml
<CustomField>
    <fullName>User_ID__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>User_ID</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Ortho_Mobile_Setting__mdt/Ortho_Mobile_Setting__mdt.object-meta.xml
<CustomObject>
    <label>Ortho Mobile Setting</label>
    <pluralLabel>Ortho Mobile Settings</pluralLabel>
</CustomObject>

force-app/main/default/objects/Ortho_Mobile_Setting__mdt/fields/Value__c.field-meta.xml
<CustomField>
    <fullName>Value__c</fullName>
    <description>Setting Value</description>
    <label>Value</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/Ortho_MyAppsController.cls
public with sharing class Ortho_MyAppsController {
    
    public class OrthoApps {
        @AuraEnabled
        public List<AppMenuItem> apps {get;set;}

        @AuraEnabled
        public List<AppMenuItem> favorites {get;set;}

        public OrthoApps(){
            apps = new List<AppMenuItem>();
            favorites = new List<AppMenuItem>();
        }

        public void addApp(AppMenuItem ami){
            apps.add(ami);
        }
        public void addFavorite(AppMenuItem ami){
            favorites.add(ami);
        }
        
    }
    @AuraEnabled(cacheable=true)
    public static OrthoApps getApps(){
        List<Ortho_Mobile_Setting__mdt> appSettings = Ortho_SettingsService.getSettingByType('App');

        Set<String> appNames = new Set<String>();
        for(Ortho_Mobile_Setting__mdt appSetting : appSettings){
            appNames.add(appSetting.Value__c);
        }

        Set<String> appFavoritesMap = new Set<String>();


        for(Ortho_App_Favorites__c appFavorite : Ortho_SettingsService.getAppFavoritesByUser(UserInfo.getUserId())){
            appFavoritesMap.add(appFavorite.App_Id__c);
        }

        OrthoApps apps = new OrthoApps();
        for(AppMenuItem ami : Ortho_AppMenuItemSelector.selectAppMenuItemsByName(appNames)){
            if(appFavoritesMap.contains(ami.Id)){
                apps.addFavorite(ami);
            }
            else{
                apps.addApp(ami);
            }
        }

        return apps;        
    }

    @AuraEnabled
    public static void setFavorite(String appId, String appName, Boolean isFavorite){
        List<Ortho_App_Favorites__c> appFavorites = Ortho_SettingsService.getAppFavoritesByUserAndApp(UserInfo.getUserId(), appId);
        Id userId = UserInfo.getUserId();
        if(appFavorites.size() > 0){
            for(Ortho_App_Favorites__c appFavorite : appFavorites){
                appFavorite.Is_Favorite__c = isFavorite;
            }
        }
        else{
            appFavorites.add(new Ortho_App_Favorites__c(
                Name = userId+appId,
                App_Id__c = appId, 
                User_Id__c = userId,
                Is_Favorite__c = isFavorite
            ));
        }

        try{
            upsert appFavorites;
        }
        catch(Exception ex){
            throw new MyAppsException(ex.getMessage());
        }

        

    }

    public class MyAppsException extends Exception {}




}